### ISSUE TITLE
Add filter option to aws eks list-clusters

### ISSUE THREAD

**Issue by Pobek** [aws/aws-sdk#100]
**Is your feature request related to a problem? Please describe.**
You currently cannot add filters (like for `aws ec2 describe-instances`) for when running `aws eks list-clusters`. 

**Describe the solution you'd like**
Adding the option `--filters` to `aws eks list-clusters` command to filter returned values.

**Describe alternatives you've considered**
Using `awk` / `jq` to filter the returned result. Adds more syntax and code that can be finished with adding the filters option

**Additional context**
None needed

**Comment by Pobek** [comment]
@stobrien89 Thanks for the response! 
I did not know about client-side filtering but it doesn't help in this case. When running `aws eks list-clusters` you don't get any other information (such as tags) besides the name of the clusters. In my use case, I want to list all the clusters with a certain tag, similar to what you can do with `aws ec2 describe-instances` with the `--filters` parameter.

**Comment by stobrien89** [comment]
Thanks for the clarification @Pobek,

I haven't heard back from the EKS team yet, but I'll let you know as soon as I do!

**Comment by stobrien89** [comment]
Hi @Pobek,

I heard back from the EKS team and they let me know that they're currently researching this and have added the request to their backlog.  I don't have a timeline for implementation, but it can take several months to plan and release a service team feature request.  I'll let you know as soon as I have more information.
