### ISSUE TITLE
WEB_APP Tests in CLI throwing errors/Documentation Bug

### ISSUE THREAD

**Issue by Technologeek** [aws/aws-sdk#101]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/devicefarm/latest/developerguide/how-to-create-test-run.html#how-to-create-test-run-cli) and the [API reference](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/devicefarm/create-upload.html/)

Issue is about usage on:
- [ ] CLI : passing arguments or cli configurations.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Mac -CLI Version 2

**Describe the question**
How to use create-upload command when you have a web-app and there isn't any application file? The documentation is either incorrect or confusing because it says this

```
--type (string)
The upload’s upload type.
Must be one of the following values:
ANDROID_APP
IOS_APP
WEB_APP
```

```
If you call CreateUpload with WEB_APP specified, AWS Device Farm throws an ArgumentException error.
Possible values:
ANDROID_APP
IOS_APP
WEB_APP
```
According to that, "WEB_APP" is a possible value but it will throw an error? How should I create-upload for my WEB_APP? The step 3 of this [documentation](https://docs.aws.amazon.com/devicefarm/latest/developerguide/how-to-create-test-run.html#how-to-create-test-run-cli) states upload your application file but there isn't any since it's a web app? Need some guidance here as in the UI console you don't need to choose any app to upload if you select your upload type as a WEB_APP

**Logs/output**
Nothing relevant

**Comment by kdaily** [comment]
V273392987
