### ISSUE TITLE
Error: No provisioned throughput specified for the global secondary index

### ISSUE THREAD

**Issue by okarmusk** [aws/aws-sdk#108]
Hello,
I'm trying to create table with global secondary index. I followed an example from: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GCICli.html#GCICli.CreateTableWithIndex

Based on documentation, I created script what should create table with global secondary index:
```
aws dynamodb create-table \
    --table-name ServiceConfiguration \
    --attribute-definitions \
        AttributeName=Version,AttributeType=S \
        AttributeName=ServiceName,AttributeType=S \
        AttributeName=LaunchDate,AttributeType=S \
        AttributeName=Tag,AttributeType=S \
        AttributeName=Checksum,AttributeType=S \
    --key-schema \
        AttributeName=Version,KeyType=HASH \
        AttributeName=ServiceName,KeyType=RANGE \
    --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 \
    --global-secondary-indexes \
        "[
            {
                \"IndexName\": \"LaunchDateIndex\",
                \"KeySchema\": [{\"AttributeName\":\"LaunchDate\",\"KeyType\":\"HASH\"},
                                {\"AttributeName\":\"Tag\",\"KeyType\":\"RANGE\"}],
                \"Projection\":{
                    \"ProjectionType\":\"INCLUDE\",
                    \"NonKeyAttributes\":[\"Version\", \"ServiceName\", \"Checksum\"]
                }
            }
        ]" \
    --endpoint-url http://localhost:8000
```
Example from dynamo-db developer guide doesn't work too, returns the same error.

The aws-cli return `An error occurred (ValidationException) when calling the CreateTable operation: No provisioned throughput specified for the global secondary index`.

I added line with `--provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 \`.

aws-cli version `aws-cli/2.2.1 Python/3.8.8 Linux/5.4.0-72-generic exe/x86_64.ubuntu.20 prompt/off`
Localhost dynamo-db docker image `amazon/dynamodb-local:1.15.0`

**Comment by kdaily** [comment]
V416963781

**Comment by kdaily** [comment]
Hi @okarmusk and @supercoinman,

I heard back from the DynamoDB team, who confirmed that the example in the documentation is not correct. This is a working example of how to add provisioned throughput to a GSI, which would replace the example from the Amazon DynamoDB Developer Guide here:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GCICli.html#GCICli.CreateTableWithIndex

```
aws dynamodb create-table \
    --table-name GameScores \
    --attribute-definitions AttributeName=UserId,AttributeType=S \
                            AttributeName=GameTitle,AttributeType=S \
                            AttributeName=TopScore,AttributeType=N  \
    --key-schema AttributeName=UserId,KeyType=HASH \
                 AttributeName=GameTitle,KeyType=RANGE \
    --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 \
    --global-secondary-indexes \
        "[
            {
                \"IndexName\": \"GameTitleIndex\",
                \"KeySchema\": [{\"AttributeName\":\"GameTitle\",\"KeyType\":\"HASH\"},
                                {\"AttributeName\":\"TopScore\",\"KeyType\":\"RANGE\"}],
                \"Projection\":{
                    \"ProjectionType\":\"INCLUDE\",
                    \"NonKeyAttributes\":[\"UserId\"]
                },
                \"ProvisionedThroughput\": {
                    \"ReadCapacityUnits\": 10,
                    \"WriteCapacityUnits\": 5
                }
            }
        ]"
```

Of note, the API documentation IS correct for this, which shows the use of the `ProvisionedThroughput` property of the `GlobalSecondaryIndexes` parameter:

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-GlobalSecondaryIndexes

I will leave this open as a documentation issue to be corrected. Thanks again!
