### ISSUE TITLE
listObjects, sort by descending is needed

### ISSUE THREAD

**Issue by diamond122** [aws/aws-sdk#11]
Let's assume that we need to get 5 last objects.
According to the docs, there's no way to get results sorted in descending.
So we should fetch all objects even there's the `MaxKeys` param to get limited objects.
In that case, `MaxKeys` is helpless.
It could be better to add new param to determine ascending/descending for sort algorithm.
Thanks in advance.

**Comment by tim-finnigan** [comment]
The [ListObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html) and [ListObjectsV2](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) API return objects in alphabetical/ascending order by default. I'll reach out to the S3 team and see if they would consider adding an option to return results in reverse alphabetical order. Linking related issue: https://github.com/boto/boto3/issues/2248.

**Comment by tim-finnigan** [comment]
P62107993

**Comment by tim-finnigan** [comment]
The contact I reached out to requested more information on use cases regarding this feature request. Can anyone provide more info on how this feature would help accomplish what you are trying to do?

**Comment by tim-finnigan** [comment]
Closing this as no response for one week. Once we gather more use cases on how this feature would help improve your workflow then we can bring that to the S3 team. As mentioned [here](https://github.com/boto/boto3/issues/2248#issuecomment-570659675) there are workarounds but we acknowledge the 1000 object limitation.

**Comment by rodrick10** [comment]
> Closing this as no response for one week. Once we gather more use cases on how this feature would help improve your workflow then we can bring that to the S3 team. As mentioned [here](https://github.com/boto/boto3/issues/2248#issuecomment-570659675) there are workarounds but we acknowledge the 1000 object limitation.

@tim-finnigan I  have a bucket with more than 1000 files and each file has a timestamp (all timestamp have the same format). I need to extract the most recent file and I can't use the last modified attribute. With the files organized bydescending order, this task would be a matter of extracting the first file on the 'Contents' list.

**Comment by alex067** [comment]
> Apologies for missing your response @rodrick10. Just to clarify - the [ListObjectsV2 API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) returns a maximum of 1000 results per request. But you can use the [paginator](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/paginator/ListObjectsV2.html) to get the full results and then sort by last modified time. (For more info on boto3 paginators please see [this documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/paginators.html)).
> 
> Here is an example which I think addresses your use case:
> 
> ```python
> import boto3
> 
> s3 = boto3.client('s3')
> paginator = s3.get_paginator('list_objects_v2')
> response_iterator = paginator.paginate(Bucket='bucket-name')
> 
> objects = []
> 
> for response in response_iterator:
>     if 'Contents' in response:
>         for obj in response['Contents']:
>             objects.append(obj)
>             
> sorted_objects = sorted(objects, key=lambda x: x['LastModified'], reverse=True)
> ```

This definitely works but it's grossly inefficient. 

It's requiring us to store the entire bucket prefix content in memory, then sort it at the very end. 

If we have a bucket containing more than 1000 objects, then this becomes an expensive operation.

**Comment by tim-finnigan** [comment]
@alex067 yes it's not ideal considering the memory usage — I did out to the S3 team again with all of the feedback here after seeing this related issue opened: https://github.com/aws/aws-sdk/issues/539. (The best way to escalate issues like these is for folks to reach out directly through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.) I'm still not sure if they can or will optimize for the use cases shared here but I can see the need for supporting these use cases.
