### ISSUE TITLE
aws identitystore list-users support for AttributePath 'UserID' filter

### ISSUE THREAD

**Issue by uname223** [aws/aws-sdk#112]
**Is your feature request related to a problem? Please describe.**
Currently only AttributePath 'UserName' is supported as per documentation and there is still no [list-all](https://github.com/aws/aws-cli/issues/5930) switch available

**Describe the solution you'd like**
A simple filter lookup by AttributePath 'UserID' filter would be beneficial

**Describe alternatives you've considered**
Manual lookup

**Additional context**
Feature is rather self explanatory

**Comment by stobrien89** [comment]
P51528088

**Comment by stobrien89** [comment]
Hi @uname223,

Thanks for your patience.  I heard back from the SSO/IdentityStore team and they've confirmed that your request is in their backlog and is in consideration for a future release.  I'll keep this open for tracking purposes and provide any additional updates I receive!

**Comment by tim-finnigan** [comment]
Per the [announcement](https://aws.amazon.com/about-aws/whats-new/2022/09/aws-iam-identity-center-apis-manage-users-groups-scale/) of new Identity Store APIs on September 1, 2022. The ListUsers API [documentation](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListUsers.html) notes:
> Filtering for a `User` by the `UserName` attribute is deprecated. Instead, use the `GetUserId` API action.

[Here](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_GetUserId.html) is the documentation for the GetUserId API. You may also be interested in using related APIs such as [IsMemberInGroups](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_IsMemberInGroups.html) or [ListGroupMemberships](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListGroupMemberships.html). I hope that helps - I'm going to close this issue but please let us know if you have any further feedback or questions that we can forward to the Identity Store team. Thanks!
