### ISSUE TITLE
get_cost_and_usage MatchOptions for filter does not reflect documentation

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#113]
(transferred from boto3: https://github.com/boto/boto3/issues/2969)

Transferring to shared aws-sdk as this is an issue with Service API/documentation. Relevant doc links:

* https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html
* https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_TagValues.html

**Comment by tim-finnigan** [comment]
P51597803

**Comment by tim-finnigan** [comment]
The following note has been added to the documentation for GetCostAndUsage:

> Valid values for `MatchOptions` for `CostCategories` and `Tags` are `EQUALS` , `ABSENT` , and `CASE_SENSITIVE`.

**Comment by gcrumpler** [comment]
@tim-finnigan This didn't actually solve the confusion as the json blobs still reference a list of options that includes 
```
"CostCategories": {
        "Key": "string",
        "Values": ["string", ...],
        "MatchOptions": ["EQUALS"|"ABSENT"|"STARTS_WITH"|"ENDS_WITH"|"CONTAINS"|"CASE_SENSITIVE"|"CASE_INSENSITIVE"|"GREATER_THAN_OR_EQUAL", ...]
``` 

I had to come find a related closed ticket referencing this issue to know what is the correct usage. Net-net it looks like the documentation is still contradictory at best.
