### ISSUE TITLE
elbv2 wait commands

### ISSUE THREAD

**Issue by carlnordenfelt** [aws/aws-sdk#114]
Hi,

I am wondering if there are plans to add elbv2 wait commands for registering and de-registering Targets in Target Groups?

/ Carl

**Comment by kdaily** [comment]
The ELB v2 is aware of this and will take your feedback into consideration.

**Comment by tim-finnigan** [comment]
We haven't received any updates on this but as mentioned above the ELBv2 team has noted the feedback. The current available waiters can be found here: https://docs.aws.amazon.com/cli/latest/reference/elbv2/wait/index.html. Please feel free to check back in here for an update in the future or reach out to [AWS Support](https://aws.amazon.com/contact-us/) for further assistance. Thanks!
