### ISSUE TITLE
Missing paginator definition for IAM `ListPolicyTags`

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#115]
Original issue: https://github.com/boto/botocore/issues/2467

> According to the API spec, the IAM method ListPolicyTags supports pagination via the "Marker" field in the request and response. However, the client reports that can_paginate("list_policy_tags") is False.
> 
> It appears that the problem is due to ListPolicyTags not being listed in https://github.com/boto/botocore/blob/develop/botocore/data/iam/2010-05-08/paginators-1.json. I see the similar ListUserTags in there as expected.

**Comment by mrry** [comment]
This issue also seems to affect the other tag-related IAM methods:

* `ListInstanceProfileTags`
* `ListMFADeviceTags`
* `ListOpenIDConnectProviderTags`
* `ListRoleTags`
* `ListSAMLProviderTags`
* `ListServerCertificateTags`

All define pagination-related fields as part of their request and response, but they are absent from the paginators document (in botocore, at least).

**Comment by tim-finnigan** [comment]
Thanks @mrry for noting that, I have passed your comment along to the IAM team. I do see `ListUserTags` in the paginators file but none of the ones mentioned here.

**Comment by tim-finnigan** [comment]
We received an update that the IAM team has added the necessary changes to implement these paginator definitions. However, there is still some work required to integrate these models into the AWS SDKs. We should get another update on this soon.

**Comment by tim-finnigan** [comment]
It looks like all of the requested paginators are now available: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#paginators. Thanks for your patience!
