### ISSUE TITLE
Cannot configure CreateTrainingJob to usage image from private repository

### ISSUE THREAD

**Issue by kdaily** [aws/aws-sdk#117]
Transferred from https://github.com/boto/boto3/issues/2906

**Is your feature request related to a problem? Please describe.**
I am attempting to launch a training job by specifying a `TrainingImage` from a private artifactory as my organization does not use ECR. However, when launching the job I receive the following error message:

> ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: TrainingImageConfig with TrainingRepositoryAccessMode set to VPC must be provided when using a training image from a private Docker registry. Please provideTrainingImageConfig and TrainingRepositoryAccessMode set to VPC when using a training image from a private Docker registry.

The issue herein is that I cannot find a way to provide the requested authentication configuration for the training job using container from our private repository to succeed.

**Describe the solution you'd like**
The `CreateTrainingJob` API can use images from private container repositories for training.

**Comment by Askill** [comment]
Hej guys, any update on this issue?

**Comment by kdaily** [comment]
Hi @Askill,

I requested an update from the SageMaker team and will post here if I hear anything. Thanks!

**Comment by RyanFitzSimmonsAK** [comment]
This feature [appears to have been implemented](https://docs.aws.amazon.com/sagemaker/latest/dg/docker-containers-adapt-your-own-private-registry.html) by the Sagemaker team as of [February 2023](https://aws.amazon.com/about-aws/whats-new/2023/02/training-image-private-docker-registry-amazon-sagemaker/).  Closing as complete.
