### ISSUE TITLE
Declare environment variables for CreateHyperParameterTuningJob

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#122]
Origin: https://github.com/boto/boto3/issues/2987

> **Description of problem**
When using boto3 client [client = boto3.client('sagemaker')] to create training jobs in sagemaker, we are able to declare environment variables when creating a single Training Job using client.create_training_job().

> However, when we try to create hyperparameter tuning jobs in sagemaker using client.create_hyper_parameter_tuning_job() we noticed that declaration of environment variables are not possible. boto3 docs

>**Solution**
Currently we found a sort of workaround for the problem by passing the environment variable through the hyperparameters Link however, it does not seem like a desirable solution.

>We were hoping that client.create_hyper_parameter_tuning_job() is able to take in environment variables under TrainingJobDefinition and TrainingJobDefinitions, similar to what is done for client.create_training_job(), so that environment variables can be set.

>Since hyperparameter tuning jobs in essence is multiple individual Training Jobs, we believe that this should be possible.

**Comment by stobrien89** [comment]
P52099353

**Comment by tim-finnigan** [comment]
Closing as it is now possible to pass environment variables via the [Enviornment](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_HyperParameterTrainingJobDefinition.html#sagemaker-Type-HyperParameterTrainingJobDefinition-Environment) parameter when using the [CreateHyperParameterTuningJob](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateHyperParameterTuningJob.html) API.
