### ISSUE TITLE
lake-formation lf-delete-tags does not prevent deleting the tags assigned to resources

### ISSUE THREAD

**Issue by aminsindi** [aws/aws-sdk#123]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
We are getting an issue with aws cli, when we try to delete and lf-tag. The [docs](https://docs.aws.amazon.com/cli/latest/reference/lakeformation/delete-lf-tag.html) says if tag is assigned to any resource, then it would not let us delete the tag. 

**SDK version number**
aws --version 
aws-cli/2.2.25 Python/3.9.6 Darwin/20.6.0 source/x86_64 prompt/off

**Platform/OS/Hardware/Device**
MacOS Darwin FVFYR0CGHV2G 20.6.0 Darwin Kernel Version 20.6.0

**To Reproduce (observed behavior)**
1. create lf-tags
``` 
aws lakeformation create-lf-tag --tag-key classification --tag-values '["public","private"]'
```
2. add glue resource(table,database etc)
``` 
aws glue create-database --database-input '{"Name":"test_db"}'
```
3. assign the tag to created resource 
```
aws lakeformation add-lf-tags-to-resource --resource '{"Database":{"Name":"test_db"}}' --lf-tags '{"TagKey":"classification", "TagValues":["private"]}'
aws lakeformation get-resource-lf-tags --resource '{"Database":{"Name":"test_db"}}'
```
4. drop the tags 
```
aws lakeformation delete-lf-tag --tag-key classification
```

**Expected behavior**
Expected to be not allowed to delete the tag and instead throw an error.

**Logs/output**

**Additional context**

**Comment by stobrien89** [comment]
P52367089

**Comment by tim-finnigan** [comment]
The [documentation](https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_DeleteLFTag.html) for the DeleteLFTag API has since been updated for clarification and now says the following:

> Deletes the specified LF-tag given a key name. If the input parameter tag key was not found, then the operation will throw an exception. When you delete an LF-tag, the <code>LFTagPolicy</code> attached to the LF-tag becomes invalid. If the deleted LF-tag was still assigned to any resource, the tag policy attach to the deleted LF-tag will no longer be applied to the resource.

I'll go ahead and close this issue, if there are any further questions or feedback related to us please let us know. Thanks!
