### ISSUE TITLE
Add support for specifying source identity when assuming roles with config files

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#124]
Origin: https://github.com/boto/botocore/issues/2486

**Is your feature request related to a problem? Please describe.**
When assuming roles with profiles specified in config file (~/.aws/config), source identity cannot be specified.

**Describe the solution you'd like**
Source idenity is the new feature that added to STS in April, which allows you to easily identitfy who assumed IAM roles.
Unlike role session names, it's preserved even after assuming other roles with role chaining.

https://aws.amazon.com/about-aws/whats-new/2021/04/aws-identity-and-access-management-now-makes-it-easier-to-relate-a-users-iam-role-activity-to-their-corporate-identity/

Most of time I use aws-vault. I already created a pull request for adding the feature, as aws-vault use their own config parser, not botocore's parser or AWS SDK for Go's parser.

99designs/aws-vault#807

I still sometimes need to rely on AWS CLI for assuming roles, so it would be great if AWS CLI support it as well.
I created the issue in this repo because configuration parser is implemented in botocore.

**Comment by stekern** [comment]
Any updates to this?
