### ISSUE TITLE
[feature request] waiter for Firehose DeliveryStream in ACTIVE state

### ISSUE THREAD

**Issue by kdaily** [aws/aws-sdk#126]
Original request: https://github.com/boto/botocore/issues/2483#issuecomment-922964059

**Comment by kdaily** [comment]
V435706550

**Comment by RyanFitzSimmonsAK** [comment]
Hi, thank you for your patience. The service team has made a backlog item for adding this waiter, but I cannot provide a specific timeline for implementation. Please refer to an [SDK or AWS CLI changelog](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst) for updates about this going forward.
