### ISSUE TITLE
UnknownoperationException throw for transactWrite api

### ISSUE THREAD

**Issue by nickyang07** [aws/aws-sdk#13]
I use local dynamodb for testing my project, and it throws this exception. According to this thread https://github.com/aws/aws-sdk-php/issues/1687 It looks like the docker image that I use for dynamodb-local may not support transactWrite api at all.

Any update from AWS team? When we can have an update for the javascript dynamodb-local

**Comment by stobrien89** [comment]
Appears this has been resolved by an update.  Resolving.
