### ISSUE TITLE
Unable to read Environment Variables from GetCanary

### ISSUE THREAD

**Issue by davegallant** [aws/aws-sdk#131]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
It is not possible to obtain the environment variables of a Canary (Synthetics) using this sdk. The [Canary struct](https://github.com/aws/aws-sdk-go/blob/99a46dbc1de902b9ee946e67591cd19d6ab70900/service/synthetics/api.go#L1433) does not contain information about the environment variables. 

It does not seem like the API itself is returning this information.
https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_GetCanary.html

**Version of AWS SDK for Go?**
v1.38.69

**Version of Go (`go version`)?**
1.16.5

**To Reproduce (observed behavior)**

```go
import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/synthetics"
)

input := &synthetics.GetCanaryInput{
 	Name: aws.String("my-canary"),
}

output, err := conn.GetCanary(input)
if err != nil {
 	return nil, err
}
```

**Expected behavior**
It should be possible to obtain the environment variables from the Canary struct.

**Additional context**
Without the ability to obtain the environment variables, it will be difficult to implement https://github.com/hashicorp/terraform-provider-aws/issues/17948.

**Comment by vudh1** [comment]
V694652014
