### ISSUE TITLE
Workdocs describe-users documentation needs love

### ISSUE THREAD

**Issue by jbruett** [aws/aws-sdk#132]
**Is your feature request related to a problem? Please describe.**
not related to a problem, just a suggestion for better documentation

**Describe the solution you'd like**
The user documentation for the workdocs describe-users command is lacking any kind of logical explanation on how to use the --user-query parameter.  (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/workdocs/describe-users.html) 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by stobrien89** [comment]
P53603225

**Comment by tim-finnigan** [comment]
Thanks for your patience - we've heard back from the team and `--user-query` documentation has since been updated to provide more context.
