### ISSUE TITLE
Provide values for `CreateNotificationRule` -> `Targets` -> `TargetType`

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#133]
Origin: https://github.com/boto/boto3/issues/3037

From @kornicameister,

> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/codestar-notifications.html#CodeStarNotifications.Client.create_notification_rule does not mention that it is possible to create notification rule using TargetType: AWSChatbotSlack although it seems to be perfectly possible using web console.

**Comment by stobrien89** [comment]
P53788239

**Comment by tim-finnigan** [comment]
Checking in – the options for `TargetType` now appear to be present in the documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/codestar-notifications/client/create_notification_rule.html#

>**TargetType** (string) –
>The target type. Can be an Chatbot topic or Chatbot client.
>
>   * Chatbot topics are specified as `SNS`.
>   * Chatbot clients are specified as `AWSChatbotSlack`.
