### ISSUE TITLE
Provide Created/Updated/Last active information in QuickSight ListUsers/DescribeUser API responses

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#134]
Originally requested here: https://github.com/boto/boto3/issues/3040

> There seems to be no way of retrieving when a QuickSight user was either created, updated, or last active (available via the Manager users section of QuickSight).

**Comment by tim-finnigan** [comment]
P53853169

**Comment by tim-finnigan** [comment]
Hi @mlevit, just wanted to follow up on your request here.  I heard from the Quicksight team that this request is not under consideration right now, but could potentially be on the roadmap for next year. But they would like to better understand your use case. Could you tell us more about your potential use cases for this data?

**Comment by mlevit** [comment]
Thanks for the update @tim-finnigan. I maintain https://github.com/servian/aws-auto-cleanup and was looking to add QuickSight to the list of supported services and resources. In order for me to clean up users (which cost $9 per month if not more) I need to understand when the users were either created or last accessed.

**Comment by tim-finnigan** [comment]
Thanks @mlevit for sharing that use case, I will pass that along to the Quicksight team.

**Comment by awssteph** [comment]
I would like to support this item as well, need to review for cleanups as overspending.

**Comment by AkashJay** [comment]
@tim-finnigan @mlevit Any update on the above request?

**Comment by tim-finnigan** [comment]
@AkashJay I don't have any update but just pinged the QuickSight team on this and can post here after hearing back.
