### ISSUE TITLE
QuickSight ARN and UserName is N/A non-federated users

### ISSUE THREAD

**Issue by mlevit** [aws/aws-sdk#135]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
ARN and user names returned via `quicksight list-users` has a value of `N/A` for non-federated users.

**SDK version number**

`aws-cli/2.2.45 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off`

**Platform/OS/Hardware/Device**
What are you running the cli on?

macOS

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

-- Run `aws quicksight list-users --aws-account-id <account_id> --namespace default`

**Expected behavior**

`ARN` and `UserName` should have valid entries.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

[debug.log](https://github.com/aws/aws-cli/files/7342045/debug.log)
[output.log](https://github.com/aws/aws-cli/files/7342035/output.log)

**Additional context**

**Comment by kdaily** [comment]
V450472834

**Comment by kdaily** [comment]
Hi @mlevit,

I heard back from the Quicksight team. They noted:

"In the output, UserName field could be 'N/A' when IdentityType is IAM and the corresponding IAM user is deleted."

This is a known issue and the documentation will be improved with this information. Thanks again for letting us know!

**Comment by mlevit** [comment]
@kdaily thanks for getting back so quickly.

This then leads to another defect. As you can see in the below screen, the three IAM users are still accessible via the QuickSight console but there is no way of deleting them via the SDK as the SDK requires the username for this action, however the returned username from `list-users` or `describe-user` is `N/A`.

![Screen Shot 2021-10-15 at 10 41 09 am](https://user-images.githubusercontent.com/233717/137410058-eab8057e-3d81-4262-bead-a84ca0789bf4.png)

**Comment by kdaily** [comment]
Thanks @mlevit - I'll let the Quicksight team know.

**Comment by kdaily** [comment]
Hi @mlevit,

Unfortunately there is not a way using the SDK to delete a user in this scenario.

As noted above, changes to to the documentation are pending, but the Quicksight team doesn't have any plans to implement this feature at this time. I've given them your feedback on this use case and why it would be important to you.

**Comment by kdaily** [comment]
@mlevit, thanks again for raising this. I'm closing this out as the Quicksight team has no plans to change this at this time.
