### ISSUE TITLE
Missing paginator definition for KMS `ListResourceTags`

### ISSUE THREAD

**Issue by mrry** [aws/aws-sdk#136]
(This is a similar issue to https://github.com/aws/aws-sdk/issues/115.)

The KMS API `ListResourceTags` includes `NextMarker` and `Truncated` attributes in its output shape: https://github.com/boto/botocore/blob/23c65ffcf6934955bc018ebaabaeb8ca26c8f452/botocore/data/kms/2014-11-01/service-2.json#L2574-L2581

However, the corresponding [paginators-1.json](https://github.com/boto/botocore/blob/23c65ffcf6934955bc018ebaabaeb8ca26c8f452/botocore/data/kms/2014-11-01/paginators-1.json) file for the service does not define a paginator for `ListResourceTags`.

As a result, generated SDK clients do not treat this method as supporting pagination.

**Comment by tim-finnigan** [comment]
Thanks @mrry, just raised this with the KMS team and will update this issue when we get a response.

**Comment by tim-finnigan** [comment]
P54138882

**Comment by tim-finnigan** [comment]
Closing this as the KMS team has added a paginator model for ListResourceTags. Please update to the latest version of your SDK for access.
