### ISSUE TITLE
[codecommit] return url pull request

### ISSUE THREAD

**Issue by renatoassis01** [aws/aws-sdk#138]
Hi,
In the output of the  `aws codecommit create-pull-request`  command, it could have a property with a pull request url 

```json
"pullRequest": {
url: "https://console.aws.amazon.com/codesuite/codecommit/repositories/REPO/pull-requests/xxxxxx"
}
```

**Comment by tim-finnigan** [comment]
Hi @renatoassis01, thanks for your patience. I heard back from the CodeCommit team regarding this request. They do not plan to put this feature request on their roadmap for now. Providing console URLs in a response would require a new contract between the console endpoint and service which may change in the future.
