### ISSUE TITLE
Return error when parallel `Scan` `SegmentSize` is too large

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#141]
Origin: https://github.com/boto/boto3/issues/3020

Summary: 

Per DynamoDB, one must experiment with TotalSegment values to determine the optimal number for `TotalSegments`, but a parallel scan will not work (returns an empty array) if the TotalSegment value is too large for a given table.  Requesting that DynamoDB provide an error/error message in this case.

**Comment by stobrien89** [comment]
P53423433

**Comment by tim-finnigan** [comment]
I think the documentation has been updated since this was originally opened: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.ParallelScan. Please follow up here or create a new issue if you still have questions related to this.
