### ISSUE TITLE
Missing automatic pagination for additional Quicksight list commands

### ISSUE THREAD

**Issue by vergenzt** [aws/aws-sdk#142]
Following up to aws/aws-cli#5713, there are still a number of resources that appear to be missing paginators. In my case, I noticed that `list-users` doesn't paginate, however I was able to fetch a longer list based on which API responses may include a `NextToken` according to `botocore/data/quicksight/2018-04-01/service-2.json`.

## Missing paginators:
```json
[
  "ListFolderMembers",
  "ListFolders",
  "ListGroupMemberships",
  "ListGroups",
  "ListIAMPolicyAssignments",
  "ListIAMPolicyAssignmentsForUser",
  "ListThemeAliases",
  "ListUserGroups",
  "ListUsers",
  "SearchFolders"
]
```

I generated the above by running the following with `botocore-1.21.61` installed in a Python 3.8 virtualenv at `.venv`:
```bash
$ jq -n '[
    (input | [paths(..) | select(try (.[1] | test(".*Response$")) and .[-1] == "NextToken") | .[1] | sub("Response$"; "")] | unique),
    (input.pagination | keys)
  ] | .[0] - .[1]' \
  .venv/lib/python3.8/site-packages/botocore/data/quicksight/2018-04-01/{service-2,paginators-1}.json
```

**Comment by tim-finnigan** [comment]
P72311108

**Comment by tim-finnigan** [comment]
We've heard back from the QuickSight team regarding this issue and they have updated their paginators. To access these please use the latest version of the CLI/SDK, and if you have additional feedback related to this please let us know.
