### ISSUE TITLE
aws lambda create-function: add parameter for log file retention days

### ISSUE THREAD

**Issue by nCubed** [aws/aws-sdk#143]
**Is your feature request related to a problem? Please describe.**
When creating a Lambda with the CLI, there is no way to provide a log file retention policy since the logs are not created until after the first run of the Lambda. And when the log group is automatically created, the retention policy is set to never-ever-ever-ever-ever-delete.

**Describe the solution you'd like**
Add an optional parameter to `create-function` with the log retention policy days.

**Describe alternatives you've considered**
1. Run the lambda once, programmatically, and then add the log retention policy 🤮
2. Manually add the policy after running the lambda 🤮 
3. Add common code in all lambdas to set the log retention policy 🤮 

**Additional context**
The v2 CLI and documentation are great! Keep it up!!!

**Comment by stobrien89** [comment]
P55040321

**Comment by tim-finnigan** [comment]
Checking in - here is the current documentation for changing log retention in the CloudWatch User Guide: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention

Others have also requested the ability to set the retention using the CreateFunction API. The service team is still tracking this feature request internally but it is not currently planned on their roadmap. For more information going forward we recommend directly reaching out to [AWS Support](https://aws.amazon.com/contact-us/) but feel free to check back in here in the future for updates. Thanks!
