### ISSUE TITLE
AWS identitystore "ListMembersInGroup" operation support

### ISSUE THREAD

**Issue by dejan-lokar** [aws/aws-sdk#144]
**Is your feature request related to a problem? Please describe.**
I'm not able to list members of a group using the `identitystore` APIs. AWS console uses the `ListMembersInGroup` operation but that is not exposed in the public SDK.

**Describe the solution you'd like**
SDK method for listing users that are members of a group.

**Describe alternatives you've considered**
Manual check using the AWS console.

**Additional context**
/

**Comment by Project0** [comment]
sounds very similar to #25, overall there is a huge lack in API operations with users and groups.

I have a similar use case where i need to retrieve the group membership of a specific user (Already raised a feature request via our TAM). We currently workaround this issue with calling a API from our IdP (Okta).

**Comment by tim-finnigan** [comment]
P65634571

**Comment by tim-finnigan** [comment]
I reached out to the SSO team for an update and they responded:

> We are currently working on launching an updated version of the AWS SSO User and Group Management APIs...Please reach out to AWS Support or your account team to track the AWS SSO Product Feature Request for more details on timelines.

As mentioned in an earlier comment this overlaps with https://github.com/aws/aws-sdk/issues/25 (and perhaps more closely with https://github.com/aws/aws-sdk/issues/109). For the sake of consolidating issues I'm going to close this one. But please refer to those issues for updates on the new APIs going forward.
