### ISSUE TITLE
suite test run does not work.

### ISSUE THREAD

**Issue by AldoCF96** [aws/aws-sdk#145]
**Describe the issue with documentation**
When running a test suite it seems to have a problem determining the test.
**To Reproduce (observed behavior)**
![image](https://user-images.githubusercontent.com/50414883/131028714-34c9da65-795e-426b-97ba-4898779a1146.png)

**Expected behavior**
it seems for https://docs.aws.amazon.com/sdk-for-go/api/service/iotdeviceadvisor/#SuiteRunConfiguration ask for a list of test but for some reason it does not specify if it needs the id or the name, and there is not documentation about it   Where do we find the selectedtestlist what is the format ?  

**Screenshots**
response from console:
![image](https://user-images.githubusercontent.com/50414883/131029210-350e0067-28ab-4f81-87a6-870bda90b1b5.png)

Please provide valid test ids. The following test ids are invalid: MQTT_Connect

**Additional context**

**Comment by vudh1** [comment]
This ticket has been fixed, therefore closing now.
