### ISSUE TITLE
FilterLogEventsRequest should provide option to sort on descending order of timestamp

### ISSUE THREAD

**Issue by pradeepagrawal8184** [aws/aws-sdk#146]
### Describe the feature

Currently by default returned response is based on ascending order of timestamp. If there are too many logs then getting the last log takes lot of time due to unnecessary traversal (using token). if most recent logs can be obtained in single calls then it will be helpful.

### Is your Feature Request related to a problem?

Currently by default returned response is based on ascending order of timestamp. If there are too many logs then getting the last log takes lot of time due to unnecessary traversal (using token). 

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

1.12.125

### JDK version used

1.8.0_291

### Operating System and version

centos7

**Comment by saedyousef** [comment]
Hi , @debora-ito ,
Any updates on this?

**Comment by tim-finnigan** [comment]
Thanks for your patience here. We heard back from a member of the CloudWatch Logs team who noted that they are still tracking this feature request in their backlog. We cannot provide guarantees for if or when a new feature like this gets implemented, but please track the AWS [blog](https://aws.amazon.com/blogs/mt/tag/amazon-cloudwatch-logs/) and SDK changelogs for related updates.
