### ISSUE TITLE
Identity store action describe-user should return more user fields 

### ISSUE THREAD

**Issue by hhamalai** [aws/aws-sdk#156]
**Is your feature request related to a problem? Please describe.**

Currently, identity store action describe-user returns UserId and UserName fields. In addition to this, users are having e.g, first, last, and display names. Automating user account provisioning on third-party, SSO/SAML-linked applications would be more straightforward if we could use the user information already present in the identity store. However, there exists no API action to retrieve anything user-related data except the userid and username fields.

**Describe the solution you'd like**

I would like to have the additional user fields (at least first and last names and the display name) to be present in the describe-user output.

**Describe alternatives you've considered**
This data is available via AWS web console, but not in any machine-accessible API.

**Comment by KaibaLopez** [comment]
Ticket opened: [P58185304](https://t.corp.amazon.com/P58185304/overview)

**Comment by tim-finnigan** [comment]
The Identity Store team acknowledged this issue are tracking this as a product feature request. We can't provide an ETA on if or when they might implement this but please feel free to check back in for updates.
