### ISSUE TITLE
DescribeSavingsPlans: Add support for listing child account savings plans

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#157]
Origin: https://github.com/boto/boto3/issues/2835, requester: @cris1133

> When you call describe_savings_plans in boto3 while assuming a role via STS into a master payer account, it only gets the master payer's savings plans and doesn't return info about the child account's savings plans. This behavior is different from describe_reserved_instances.

Request sent to Savingsplans team: P46834501

**Comment by tim-finnigan** [comment]
The service team acknowledged this feature request and added it to their backlog for further review. Although it seems like this use case could be met by assuming a role on the account of which you want to view the savings plan. API documentation for reference: https://docs.aws.amazon.com/savingsplans/latest/APIReference/API_DescribeSavingsPlans.html.
