### ISSUE TITLE
Boto3/botocore lakeformation `grant_permissions attribute` valid value documentation error.

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#160]
Origin: https://github.com/boto/botocore/issues/2406, requester: @stthoom 

> Issue with Boto3 Lakeformation documentation. grant_permissions "Permissions" parameter valid values are DESCRIBE and ASSOCIATE, which are documented as "DESCRIBE_TAG" and ASSOCIATE_TAG", upon usage is causing an error.

Service team request: P49159160

**Comment by tim-finnigan** [comment]
This appears to now be fixed in the API documentation (and corresponding SDK documenation):https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_GrantPermissions.html
