### ISSUE TITLE
`PutRule` accepts invalid cron expressions

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#161]
Origin: https://github.com/boto/boto3/issues/2876, requester: @HCharlie 

> For example this invalid cron expression, cron(0/5, 9-18, ?, *, MON-FRI, *)

```
import boto3

client = boto3.client("events")
rule_name = "test"
cron_expression = "cron(0/5, 9-18, ?, *, MON-FRI, *)"
client.put_rule(
    Name=rule_name,
    ScheduleExpression=cron_expression,
    State='ENABLED',
)
```

>if you run the code, there's no exception reported about invalid cron expression, is this a new feature or a bug?
if this is not a bug, then there's a bug in the aws console, if I put this cronexpression, I would not get any samples.

Service team request: P52102614

**Comment by tim-finnigan** [comment]
This issue must have been addressed in the console because that cron expression appears to be valid:

<img width="862" alt="image" src="https://github.com/aws/aws-sdk/assets/87778557/d985aad9-4235-4222-b50b-1225533fb413">
