### ISSUE TITLE
DuplicateRequest exception for `TransferDomainToAnotherAwsAccount` does not return RequestId

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#164]
Origin: https://github.com/boto/boto3/issues/2841, Requester: @BastianZim 

> When calling boto3.client("route53domains").transfer_domain_to_another_aws_account() on a domain that has already been prepared for transfer, the following exception is raised:

```
response = domains_client.transfer_domain_to_another_aws_account(
        DomainName="example.com", AccountId="account_id")
Traceback (most recent call last):

  File "<ipython-input-22-5de0b5a2322a>", line 1, in <module>
    response = domains_client.transfer_domain_to_another_aws_account(

  File "/Users/user/opt/anaconda3/envs/manage_domains/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)

  File "/Users/user/opt/anaconda3/envs/manage_domains/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)

DuplicateRequest: An error occurred (DuplicateRequest) when calling the TransferDomainToAnotherAwsAccount operation: A request already pending for the operation. Please use the RequestId from the exception to track the request status.
```
> The way I understand the error message, a request ID should be provided, this is not the case.

Service team request: P73920457

**Comment by tim-finnigan** [comment]
New ref: P73920457

**Comment by tim-finnigan** [comment]
Checking in — we heard back from the service team that they have merged in a fix for this. It is planned for release in the near future, so you will need to update to the latest version of your SDK. Feel free to check back in for any questions related to this.
