### ISSUE TITLE
Update SDK reference guide examples with `FilterExpression` values

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#166]
**Origin: https://github.com/boto/boto3/issues/2868** , **Requester: @butlerbt**

>Working in with the python sdk and ran into this yesterday when I decided to not use resource.Table and use client instead due to simplifying unit tests. Seems like the dynamodb.client docs are lacking and not up to date with the current api. One specific example is the .scan() documentation. For example it lists ComparisonOperator as being a required argument to pass.

>Another point in case is the expression statement docs are non-existent which is tough since this is the argument that all of the depreciated arguments are shifting responsibility onto.

**Service team request:** P47815594

**Comment by tim-finnigan** [comment]
We heard back from the DynamoDB team that their documentation was updated. There is a Scan example [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/example_dynamodb_Scan_section.html) and also in context of a tutorial [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/example_dynamodb_Scenario_GettingStartedMovies_section.html).
