### ISSUE TITLE
Central location for API models?

### ISSUE THREAD

**Issue by dacut** [aws/aws-sdk#171]
It seems like the model files are checked in to each language-specific SDK, e.g.:
https://github.com/aws/aws-sdk-go-v2/tree/main/codegen/sdk-codegen/aws-models
https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models
https://github.com/boto/botocore/tree/develop/botocore/data
https://github.com/aws/aws-sdk-ruby/tree/version-3/apis

Is there a central location for the Smithy models? There are times when I'd like to do something programmatic (e.g. custom codegen) whenever a new model file is released, but would like to get it from the central authority rather than from a language-specific repo.

Thanks!

**Comment by jmklix** [comment]
Sorry, but there is no public location for this.
