### ISSUE TITLE
Include PreferredMfaSetting in UserType class

### ISSUE THREAD

**Issue by Shedelok** [aws/aws-sdk#176]
### Describe the feature

It would be great if `UserType` class (which is used in response of `listUsers`) contained `PreferredMfaSetting` as well as `adminGetUser` response does.

### Is your Feature Request related to a problem?

I want to write a code that checks whether a user has MFA enabled or not. My solution is to call `adminGetUser` method and return `adminGetUserResult.getPreferredMfaSetting() != null`.
I also want to be able to list all users along with this MFA information. Here, I can call `adminGetUser` for each user, but it works slow and makes a lot of requests. I see that `listUsers` method returns `UserType` class for each user and it contains `MFAOptions` field. But according to documentation, it is deprecated and only contains information about SMS MFA.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

1.11.740

### JDK version used

1.8

### Operating System and version

Ubuntu 20.04

**Comment by debora-ito** [comment]
Hi @Shedelok thank you for reaching out.

This would be a service feature request, I will pass it on to the Cognito team.

Transferring to the `aws-sdk` repo, so people can upvote this if they want to see it supported.

**Comment by JuanGQCadavid** [comment]
👍 Here in my company we are doing a lot of calls that could be simplified by this feature.

**Comment by debora-ito** [comment]
P58758536

**Comment by debora-ito** [comment]
The service team acknowledged the feature request and added to their backlog. We don't have a timeline to share for when the feature will be implemented.

Will go ahead and close this, as there's no action pending on the SDK team. Feel free to reach out if you have any other questions.
