### ISSUE TITLE
Aws::CloudWatch::Metric#put_data always results in InvalidParameterCombination

### ISSUE THREAD

**Issue by adibsaad** [aws/aws-sdk#179]
Related to https://github.com/aws/aws-sdk-ruby/issues/2378

Problematic code is [here](https://github.com/aws/aws-sdk-ruby/blob/bc3b4a52402ce9a0c2bf847b3ccaa7da7cb42b4e/gems/aws-sdk-cloudwatch/lib/aws-sdk-cloudwatch/metric.rb#L647)

The deep merge always adds a `{ metric_name: @name }` element to the `metric_data` option, resulting in `InvalidParameterCombination` error. Simply removing that line should fix it.

**Comment by yenfryherrerafeliz** [comment]
V613999914

**Comment by tim-finnigan** [comment]
Checking in - it looks like the Python team added this warning to their documentation: https://github.com/boto/boto3/pull/3673. I think other SDKs would similarly need to add notes directly to their pages. But yes the recommendation here is to use the client method.
