### ISSUE TITLE
waitFor service method for ElasticBeanstalk 

### ISSUE THREAD

**Issue by yairkukielka** [aws/aws-sdk#18]
It would be great to have waitFor in ElasticBeanstalk service.

My current use case is calling ElasticBeanstalk.createApplicationVersion and when that process finishes I'd like to get notified via callback to make a subsequent call to ElasticBeanstalk.updateEnvironment.

Right now the only approach that I see for this is to poll (calling ElasticBeanstalk.describeApplicationVersions) the status of the application version until it's "Processed" .

Thank you!

**Comment by ajredniwja** [comment]
V423616331 for internal use, will update the ticket once I hear back from ElasticBeanstalk team.

**Comment by ashishdhingra** [comment]
Created https://github.com/aws/elastic-beanstalk-roadmap/issues/325 as proposed in issue opened with the service team.

**Comment by ashishdhingra** [comment]
Closing this in favor of https://github.com/aws/elastic-beanstalk-roadmap/issues/325. Please follow it for any updates.
