### ISSUE TITLE
 OpenZFS ThroughputCapacity Documentation error

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#182]
Original issue: https://github.com/boto/boto3/issues/3127

Minimum value is documented as 2^3 (8), but should be 2^6 (64)

**Comment by tim-finnigan** [comment]
P59243320

**Comment by tim-finnigan** [comment]
I received an update from the FSx team. They said Amazon FSx is a family of services, including FSx for Windows, FSx for ONTAP, FSx for OpenZFS, and FSx for Lustre, that all share a common API. Those minimum and maximum values are global across the file systems that offer a ThroughputCapacity setting, leading to the inconsistency mentioned for the minimum value for FSx for OpenZFS. But the feedback has been noted and they may add some clarifying text regarding this in the documentation.

**Comment by hossimo** [comment]
Thanks for the update. I do sometimes use FSx for windows at 8MB/S when a system is idle for some time but I need to keep the file system up.

So I totally understand.
