### ISSUE TITLE
AWS FSX CLI and SDK doesnt support ONTAP FSX Backup Operations

### ISSUE THREAD

**Issue by jacobjohnanda** [aws/aws-sdk#183]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The FSX documentation states that FSX ONTAP  operations like "backups" are supported using Amazon FSX console, API, or CLI.  Please find the details here "https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/using-backups.html"

But while using the  AWS FSX CLI or SDK , I get the error that its unsupported.

(py36-venv) [root@ip-172-31-76-32 pydev]# /usr/local/bin/aws fsx create-backup --file-system-id fs-0720a6df76120ca84

**An error occurred (UnsupportedOperation) when calling the CreateBackup operation: ONTAP file system backup is unsupported.**

------

py36-venv) [root@ip-172-31-76-32 pydev]# python3 create_backup.py
Traceback (most recent call last):
  File "create_backup.py", line 4, in <module>
    FileSystemId='fs-0720a6df76120ca84'
  File "/home/ec2-user/pydev/py36-venv/lib64/python3.6/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/pydev/py36-venv/lib64/python3.6/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
**botocore.errorfactory.UnsupportedOperation: An error occurred (UnsupportedOperation) when calling the CreateBackup operation: ONTAP file system backup is unsupported.**

**SDK version number**
Python boto3 SDK
**Platform/OS/Hardware/Device**
RHEL 7.5
What are you running the cli on?
FSX ONTAP backup commands 

**To Reproduce (observed behavior)**
Please run the command aws fsx create-backup --file-system-id fs-0720a6df76120ca84

**Expected behavior**
Fails stating that its unsupported.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
py36-venv) [root@ip-172-31-76-32 pydev]# /usr/local/bin/aws fsx create-backup --file-system-id fs-0720a6df76120ca84

**An error occurred (UnsupportedOperation) when calling the CreateBackup operation: ONTAP file system backup is unsupported.**

------

py36-venv) [root@ip-172-31-76-32 pydev]# python3 create_backup.py
Traceback (most recent call last):
  File "create_backup.py", line 4, in <module>
    FileSystemId='fs-0720a6df76120ca84'
  File "/home/ec2-user/pydev/py36-venv/lib64/python3.6/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/pydev/py36-venv/lib64/python3.6/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
**botocore.errorfactory.UnsupportedOperation: An error occurred (UnsupportedOperation) when calling the CreateBackup operation: ONTAP file system backup is unsupported.**

**Additional context**

**Comment by tim-finnigan** [comment]
P59384141

**Comment by tim-finnigan** [comment]
I heard back from the FSx team regarding this issue. They explained that ONTAP backups are taken at the volume-level, not at the filesystem-level. If you run the command and provide the volume ID instead of the file system ID you will be able to create a volume backup.

They are also planning to improve the error message "ONTAP file system backup is unsupported" by providing more clarification in the message.
