### ISSUE TITLE
can't get tags for a given codedeploy application + group

### ISSUE THREAD

**Issue by francisferrell** [aws/aws-sdk#188]
**Is your feature request related to a problem? Please describe.**
Given a CodeDeploy application name and deployment group name, I can't find any combination of CLI commands that will give me the tags

**Describe the solution you'd like**

`aws deploy get-deployment-group --application-name foo --deployment-group-name bar` should output either the tags for the deployment group or the ARN of the deployment group which could then be used with `aws deploy list-tags-for-resource`.

**Describe alternatives you've considered**

**Additional context**
```
 ~ $ aws --version
aws-cli/2.4.18 Python/3.9.10 Darwin/21.3.0 source/arm64 prompt/off
```

**Comment by tim-finnigan** [comment]
P59994659

**Comment by tim-finnigan** [comment]
Checking in - based on [this documentation](https://docs.aws.amazon.com/codedeploy/latest/userguide/instances-tagging.html#instances-tagging-example-1) it seems like `ec2TagSet` is what tagging  for deployment groups involves. I forwarded this issue to the CodeDeploy team for further consideration but I think it would help to have more details regarding the use case and why the current behavior isn't sufficient in addressing that.
