### ISSUE TITLE
list-command-invocations should return 404 if nothing is found

### ISSUE THREAD

**Issue by iloveicedgreentea** [aws/aws-sdk#190]
I had an issue where I was sending an SSM command and then calling list-command-invocations too quickly. This ends up returning a 200 and an empty list because the commandID was not found yet.

If I sleep for a second it works as intended. This is counter intuitive since a 200 de facto means the request was successful.

A successful request means the commandID was accepted and in this case, it was clearly not. This doesn't meet the criteria for a successful request, ergo it should return a 404.

**Comment by tim-finnigan** [comment]
The Systems Manager team has added this waiter request to their backlog. I can't give an update on if or when they will implement this but please feel free to check back in here for updates.
