### ISSUE TITLE
AWS ACM able to download certificate, certificate chain and public key 

### ISSUE THREAD

**Issue by kderck** [aws/aws-sdk#195]
Dear AWS, 

I would like be able to download certificate, a certificate chain, and public key from AWS Certificate Manager from the Public Certificate Authority. I understand that you can download the certificate with `aws acm --get-certificate arn` and than you can extract from stdout. However, I find this solution is prone to mistakes, and to get the public key I also need to extract from the certificate.

**Comment by tim-finnigan** [comment]
A member of the ACM team said there is an internal tracking item for this feature request. I'm going to go ahead and close this issue, but if you want an update on this request please let me know and I can reach back out to that team.
