### ISSUE TITLE
c6a instances are missing from InstanceType

### ISSUE THREAD

**Issue by Nezz** [aws/aws-sdk#198]
### Describe the issue

The c6a instances are now available in several regions. Could you please add them to the InstanceType enum?

### Links

https://github.com/aws/aws-sdk-java/blob/b112cf9fea9d2e3ab4af57c9eda14f6016b71d57/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/InstanceType.java#L82

**Comment by Nezz** [comment]
Any news on this one @debora-ito? We'd love to use those instances but we cannot until this is resolved.

**Comment by debora-ito** [comment]
The EC2 team is aware and is working on it.

In the meantime, in the Java SDK you have the option to use the instance type String setter.

**Comment by Nezz** [comment]
The Jenkins plugin relies on the enum sadly. I cannot specify instance type from a string.

**Comment by debora-ito** [comment]
C6a instance types added, Java SDK release `1.12.198`.
