### ISSUE TITLE
RDS log message was truncated by downloadDBLogFilePortion

### ISSUE THREAD

**Issue by beyondbill** [aws/aws-sdk#20]
When I use `rds.downloadDBLogFilePortion` to download a large log file (200MB ~ 3GB), I can almost always see ` [Your log message was truncated]` several (5 ~ 40) times in the downloaded file.

According to AWS doc, `rds.downloadDBLogFilePortion` will
`Downloads all or a portion of the specified log file, up to 1 MB in size.`

My guess is that 1MB limit could cut in the middle of a log line. 

I tried to set `NumberOfLines` option to a small number (200). Most of the time it works without truncating logs. However, under rare circumstance, a extremely long log line could still possibly get truncated. Another problem of limiting `NumberOfLines` is that it will slow down the download.

Is there a way that I can avoid truncated log messages (ideally without compromising download speed)? Thank you!

My code is as follows:

```javascript
function downloadLogFile(databaseId, logFileName, outputStream) {
    return new Promise(function(resolve, reject) {
        outputStream.on('error', function(err) {
            reject(err)
        })

        // bound w/ AWS#Response
        // recurses itself if more pages
        // ends the outputStream when done
        function pageCb(err, data) {
            if (err) {
                return reject(err)
            }

            const logData = data.LogFileData
            if (!logData) {
                outputStream.end('\n')
                return resolve()
            }
            
            outputStream.write(logData)

            if (this.hasNextPage()) {
                return this.nextPage(pageCb)
            }

            // otherwise we've completed this file
            outputStream.end('\n')
            return resolve()
        }

        rds.downloadDBLogFilePortion({
            DBInstanceIdentifier: databaseId,
            LogFileName: logFileName,
            Marker: '0'
        }, pageCb)
    })
}
```

**Comment by arangyupgrade** [comment]
Is there any update on this issue? we are facing the same problem

**Comment by thom-vend** [comment]
Facing the same issue in 2021! 😊

**Comment by aitorres** [comment]
Bumping for visibility, facing this issue in 2022!

**Comment by tim-finnigan** [comment]
In the [API documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DownloadDBLogFilePortion.html) it notes:

>**NumberOfLines**
>The number of lines to download. If the number of lines specified results in a file over 1 MB in size, the file is truncated at 1 MB in size

I found a number of workarounds were mentioned in [this issue](https://github.com/aws/aws-cli/issues/2268) (for example in comments [here](https://github.com/aws/aws-cli/issues/2268#issuecomment-373803942) and [here](https://github.com/aws/aws-cli/issues/2268#issuecomment-389714721)).

We could reach out to the RDS team but I think we need more clarity on what the ask is. For example is the request to:

* Increase the 1 MB limit
* Avoid truncating logs in the middle of the line
* Release a separate API for downloading entire log files

I’m closing this as the 1 MB limitation is called out in the documentation. But if anyone can clarify the ask and provide use cases then please create a new issue or post here and we can reopen this one.

**Comment by thom-vend** [comment]
> Avoid truncating logs in the middle of the line
Doesn't that sound an issue to you? 😊  it's terrible for us.

The current api is useless, everyone hack a way via the console endpoint to download the logs with script like that: https://gist.github.com/thom-vend/4bf9ed94bf34bbd44100328960c101a7

Where should this issue need to be raise to have a proper api to download and ingest our db logs?
Can you open yourself the issue? this issue have been open in 2017, nothing have changed since then.

**Comment by tim-finnigan** [comment]
Thanks @thom-vend for the feedback! This is an old issue and that’s why I asked for clarification on the request so that I could forward it to the appropriate team. 

I think what you are asking for is a DownloadDBLogFile API as opposed to the DownloadDBLogFilePortion API. That way you could download whole log files without running into the 1 MB limit. Is that correct?

**Comment by thom-vend** [comment]
If we need to make multiple call that's a small inconvenience but having them truncated make this unusable, you are potentially loosing the most important message 😬
Thanks!

**Comment by tim-finnigan** [comment]
Thanks @thom-vend for following up! I can see why this is a pain point for you and others. I just reached out to the RDS team regarding this and will post an update here when I hear back.

**Comment by tim-finnigan** [comment]
P62112246

**Comment by thom-vend** [comment]
_@tim-finnigan is that your password or a reference to a ticket or a mistake?_

**Comment by tim-finnigan** [comment]
It's a reference to a ticket, we generally post those in a separate comment so it's easier to identify which issues have a corresponding ticket.

**Comment by tim-finnigan** [comment]
I heard back from the RDS team and they do not have plans to change the API or increase the 1 MB limit. Instead they recommended publishing your database logs to CloudWatch as documented here in the RDS User Guide: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Procedural.UploadtoCloudWatch.html

That probably wasn’t the answer you were hoping for, but I think CloudWatch integration is something that more services would want to support for all of [the features](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html#cloudwatch-logs-features) it provides. Here is a list of services that currently publish to CloudWatch Logs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/aws-services-sending-logs.html

**Comment by whalesalad** [comment]
Some of my PostgreSQL log files are 400+mb

It takes an eternity to request them in batches.
