### ISSUE TITLE
'cloudfront list-distributions-by-web-acl-id' only works for wafv1 acls

### ISSUE THREAD

**Issue by slushysnowman** [aws/aws-sdk#207]
**Is your feature request related to a problem? Please describe.**
Cloudfront list-distributions-by-web-acl-id only returns results when the id if a waf web-acl id is specified, it doesn't work for wafv2 ids

Current workaround is to get this information via list-distributions instead

**Describe the solution you'd like**

- Documentation should be updated to reflect that list-distributions-by-web-acl-id only works for waf, not for wafv2
- Ideally, support for wafv2 IDs would be added

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by tim-finnigan** [comment]
A fix for this was recently rolled out per the service team. Please update to the latest version of your CLI/SDKs in order to do this. If you have any further questions or feedback please let us know here or contact [AWS Support](https://aws.amazon.com/contact-us/). Thanks!
