### ISSUE TITLE
service/timestreamquery: Timestream Run Query Function: Passing Query Arguments?

### ISSUE THREAD

**Issue by kmart88** [aws/aws-sdk#209]
**Is your feature request related to a problem? Please describe.**
The current implementation of the Timestream runQuery function is vulnerable to SQL injection.

**Describe the solution you'd like**
The current implementation of the Timestream runQuery function does not allow for passing query args into the function.  What I have been doing instead is interpolating the query string beforehand, then passing it to the function.  It would be much safer & easier to have query args as a function parameter.  Using string interpolation is vulnerable to SQL injection and can’t be deployed in production.

**Describe alternatives you've considered**
Writing custom query validation logic for the string interpolation is one solution we've considered, as well as resorting to some other SQL query builder go packages.  However, we feel these are not the best options and being able to pass query args as a parameter would be much better.

**Comment by vudh1** [comment]
V694656713
