### ISSUE TITLE
logs filter-log-events & get-log-events: Add the option to use ingestionTime instead of timestamp for start- & end-time

### ISSUE THREAD

**Issue by FlyWieEinAirplane** [aws/aws-sdk#213]
**Is your feature request related to a problem? Please describe.**
In a project we are using aws logs filter-log-events to fetch the latest logs and push them to somewhere else. To define the timerange we use the parameters
[--start-time <value>]
[--end-time <value>]
which use the timestamp field of each event for filtering.

The problem is, that some of our events are ingested an arbitrary amount of time lated, than they are written. This means once they are ingested, the timestamp of these events could be far in the past.
We wanted to use the ingestionTime for our timerange definition but that doesn't seem to work

**Describe the solution you'd like**
We would like to be able to request the logs ingested within the last 30 seconds.

**Describe alternatives you've considered**
We tried to change the timerange selection to a custom filter like this: --filter-pattern "{$.ingestionTime > 1234567890}" but that didn't lead to anything.

**Additional context**
If this is a problem of the AWS http API, which cannot be solved within the aws-cli, we can close this issue.
Of course there are other solutions than the pulling-based approach, but I'm curious whether there is a solution to this
Any help is appreciated.

**Comment by aaoswal** [comment]
P61792300

**Comment by tim-finnigan** [comment]
We heard back from the service team and they captured this ask in their backlog. We can't provide an ETA on if or when this would be implemented but we can confirm that they are tracking the request on their end. Please feel free to check in for updates down the line but I am going to close this issue.
