### ISSUE TITLE
Clarify Kendra SpellCorrectedQueries behavior for FAQs

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#214]
Raised by customer here: https://github.com/boto/boto3/issues/3196

**Comment by tim-finnigan** [comment]
P61791711

**Comment by SandeepPasula898** [comment]
Hello, Any update on this issue?

**Comment by tim-finnigan** [comment]
Hello, I don't have any updates yet on this issue.

**Comment by tim-finnigan** [comment]
Hi @SandeepPasula898 I heard back from the Kendra team. They said if the index does not have any documents and only FAQs then you need to provide `QueryResultTypeFilter='QUESTION_ANSWER'` in the query, for example:

```
response = kendra.query(IndexId=KENDRA_INDEX, QueryText='calendare',
                        QueryResultTypeFilter='QUESTION_ANSWER',
                        SpellCorrectionConfiguration={'IncludeQuerySpellCheckSuggestions': True})
```

After doing that, I did get `SpellCorrectedQueries` returned in the response. 

They plan to update their documentation to make this more clear. Thanks again for reporting. I'm going to close this as resolved but please let me know if you have any other questions.

**Comment by SandeepPasula898** [comment]
Thank you @tim-finnigan , It resolved the issue.
