### ISSUE TITLE
Add Support for Snowball Edge devices in AWS CLI version 2

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-sdk#216]
**Is your feature request related to a problem? Please describe.**

Per documentation (https://docs.aws.amazon.com/snowball/latest/developer-guide/using-adapter-cli.html), only one specific version (1.16.14) of the AWS CLI tool works with Snowball Edge devices. The problem is one of user-experience.

**Describe the solution you'd like**

I would like all versions of the AWS CLI tool to work with Snowball Edge devices.

**Describe alternatives you've considered**

The alternative is to use AWS CLI 1.16.14 for Snowball Edge operations and AWS CLI version 2.0 for all other operations.

**Additional context**

The support for only a specific version of the AWS CLI creates the appearance of an unfinished or unsupported offering (which this could be) but results in a frustrating end-user experience.

**Comment by tim-finnigan** [comment]
P65631513

**Comment by tim-finnigan** [comment]
I just checked in with the Snowball team for an update and was informed that this request is not being prioritized at this time. However, it is still in their backlog for consideration. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for updates in the future or feel free to check back here as well.

**Comment by colinbjohnson** [comment]
If/when AWS decides to drop support for AWS CLI version 1 can I reopen this? It seems highly likely that the AWS team is headed for a situation where an unsupported AWS CLI version (version 1) will be the only supported mechanism for connecting to a Snowball device.

**Comment by tim-finnigan** [comment]
@colinbjohnson thanks for following up. Yes we can revisit this issue - in the meantime we're going to try getting more details from the Snowball team regarding their plans for supporting v2.
