### ISSUE TITLE
Allow for custom "now" date / truncated dates when generating a S3 presigned URL

### ISSUE THREAD

**Issue by kdaily** [aws/aws-sdk#218]
Original issue: https://github.com/boto/botocore/issues/2647

> **Is your feature request related to a problem? Please describe.**
> 
> `generate_presigned_url` generates signatures using the current date, which works most of the time. However, it is sometimes required to use a "truncated date" in order to not blow up caches with new urls every time. For instance, one would like to create signed urls with a 10 minute truncated date, so all urls for the same object within a 10 minute window end up with the same signature and parameters.
> 
> **Describe the solution you'd like**
> 
> I think the implementation should be fairly easy, just allow receiving a "current utc time" parameter to customize what the current date is when creating the signature.
> 
> Better implementations would be to add new methods with this kind of truncated datetime feature, but may require more work and documentation.
> 
> Some ideas grabbed from here: https://advancedweb.hu/cacheable-s3-signed-urls/
> 
> Thoughts?

**Comment by tim-finnigan** [comment]
We heard back from the S3 team that they are adding this as a PFR (Product Feature Request) to their queue and will consider it against other items in the request stack for roadmap. They are not able to provide a roadmap commitment but are happy to take any additional feedback as required.
