### ISSUE TITLE
password_last_changed missing api

### ISSUE THREAD

**Issue by karikarshivani** [aws/aws-sdk#22]
### **Request:**
I am unable to access the "password_last_changed" value in the [credential report](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html#id_credentials_understanding_the_report_format) directly (without needing to download the CSV and parsing it) and there doesn't seem to be a way to get it using the SDK or CLI.

### **Recommended solution:**
It would be very helpful if the [list_users](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/IAM/Client.html#list_users-instance_method) method returned all the values that we see in the credential report CSV file.

### **Alternate solution:**
As the last resort, I am considering a temporary approach of using [max_password_age](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/IAM/AccountPasswordPolicy.html#max_password_age-instance_method) to ensure that the password is changed.

### **Context:**
We are currently using AWS Ruby SDK v2 for a CMS project in collaboration with MITRE to create InSpec profiles.
Here is how we are utilizing the SDK to automate AWS CIS foundations benchmark (1.2): [inspec-aws aws_iam_users](https://github.com/inspec/inspec-aws/blob/master/libraries/aws_iam_users.rb)
Here is the control requirement that has triggered this request: [AWS control#1.3](https://github.com/mitre/cis-aws-foundations-baseline/blob/sk-1.2update/controls/cis-aws-foundations-1.3.rb#L32)

Thank you!

**Comment by karikarshivani** [comment]
Checking in to see if there's any progress on this @kellertk @ajredniwja @mullermp

**Comment by mullermp** [comment]
@kellertk's team owns the service team outreach for this.

**Comment by mullermp** [comment]
Don't auto close this.

**Comment by Amndeep7** [comment]
Hello, has there been any progress on this yet?

**Comment by tim-finnigan** [comment]
Checking in, thanks all for your patience. We do not have any updates on this other than that the feature request is still being tracked internally in the service team's backlog. We cannot provide any guarantees as to if or when something like this would be implemented, but please refer to the AWS blog or SDK CHANGELOG for updates.
