### ISSUE TITLE
Creating a Query with the Dialog Code Hook is not working with KendraSearchIntent

### ISSUE THREAD

**Issue by SandeepPasula898** [aws/aws-sdk#220]
Hello, I am trying to add **kendraQueryFilterString** and **kendraQueryRequestPayload** parameters to my delegate function. None of them are getting applied when testing.

- I am using **LexV2** bot with **KendraSearchIntent** in it.
- In associated lambda function of dialogcodehook, I am returning delegate response as below
```
response = {
        'sessionState': {
            'sessionAttributes': session_attributes,
            'dialogAction': {
                'type': 'Delegate',
                'kendraQueryRequestPayload': kendraQueryRequestPayload,
                'kendraQueryFilterString': kendraQueryFilterString
            },
            'intent': intent
        }
    }
```
Reference doc - https://docs.aws.amazon.com/lex/latest/dg/built-in-intent-kendra-search.html

**Comment by tim-finnigan** [comment]
Hi @SandeepPasula898 thanks for reaching out. Could you please provide the full steps to reproduce this?

**Comment by SandeepPasula898** [comment]
Hi @tim-finnigan, For reproducing this behavior, I will provide sample configuration of LexV2, Kendra FAQ sample and lambda function in couple of days by creating them since I am working on client's data. Thanks.

**Comment by tim-finnigan** [comment]
Hi @SandeepPasula898 since we haven't heard back in over a month I'm going to close this but please let us know if you're still encountering this issue.
