### ISSUE TITLE
Possibility to only scale upwards when using rds modify-current-db-cluster-capacity

### ISSUE THREAD

**Issue by ViktorCollin** [aws/aws-sdk#221]
### Describe the feature

I would like a way to set the desired capacity but make sure that if it is already scaled to a higher capacity it should not scale down. This would make it possible to ensure that the database is ready for a sharp spike in traffic taht we know it's coming. 

### Use Case

This would be useful in situation when to have a sharp spike of traffic on a predictable time. eg. our service is used in classrooms and the school day starts at 08:00. This means that we go from almost no traffic at all to peek in less then 5 minutes time. 

### Proposed Solution

Add a flag `--at-least-capacity=<number>` flag to the `aws rds modify-current-db-cluster-capacity` i should work as the `--capacity` flag except setting the desired capacity to the maximum of given value and the current capacity. 

 `aws rds modify-current-db-cluster-capacity --at-least-capacity=8` when current capacity is 4 should set the desired capacity to 8 
 `aws rds modify-current-db-cluster-capacity --at-least-capacity=8` when current capacity is 16 should leave the desired capacity at 16

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.3.4

### Environment details (OS name and version, etc.)

linux

**Comment by tim-finnigan** [comment]
@ViktorCollin have you tried the approach mentioned in the comment above? Please let us know if that helps your use case. We can still follow up with the RDS team to get their thoughts on your proposed feature request. But it would help to have more information from your side as far as what you’ve tried and what blockers you are running into. I’m going to close this but can reopen later if you get back to us regarding this. Thanks!

**Comment by ViktorCollin** [comment]
Thanks so very much for the help! I missed the response earlier, sorry for that. Yes I figured it out in a similar way that you described above. Hopefully we can remove the need for this type of actions when migrating to Aurora Serverless v2
