### ISSUE TITLE
aws cloudwatch logs filter pattern include lines before and/or after matching pattern

### ISSUE THREAD

**Issue by HaithamMaya** [aws/aws-sdk#225]
Is there a way to include N lines before and/or after a matching pattern in AWS CloudWatch Logs?

Let's say I have this query and would like 3 lines before and after each match.

```
aws logs filter-log-events --log-group-name my-group --filter-pattern "mypattern"
```
The only work around I have at the moment is to remove the filter pattern and use grep:

```
aws logs filter-log-events --log-group-name my-group | grep -A 3 -B 3 mypattern
```

However, I would like to only stream the log events I need and do it as part of the aws log events query.

Ref:
https://stackoverflow.com/questions/59217130/aws-cloudwatch-logs-filter-pattern-include-lines-before-and-or-after-matching-pa

**Comment by ACronje** [comment]
+1

**Comment by ArthV** [comment]
+1

**Comment by webocs** [comment]
+1

**Comment by ewerkhoven** [comment]
cloudwatch cannot be considered a minimally viable product without this functionality

**Comment by morenobonaventura** [comment]
+1

**Comment by ronanj2** [comment]
+1

**Comment by cemysf** [comment]
+1

**Comment by mahmoudawny** [comment]
+1

**Comment by Von-Starck** [comment]
+1

**Comment by jamesmacwilliam** [comment]
how has this not made it in yet +1

**Comment by brgibson** [comment]
+1 please 🙇

**Comment by aerlaut** [comment]
+1

**Comment by wdougoveto** [comment]
+1

**Comment by karumugasundaram** [comment]
+1

**Comment by hmcmanus** [comment]
+1

**Comment by webocs** [comment]
Al most 3 years and still no news of this feature.. :(

**Comment by nick-myers-dt** [comment]
I find myself needing this on a daily basis. +1

**Comment by ridwannizam** [comment]
This is very important feature, Elastic Search and Grafana have support for this issue.

**Comment by thiagosantosleite** [comment]
+1

**Comment by williancolognesitrimble** [comment]
+1

**Comment by wiwichips** [comment]
+1

**Comment by jnguyen1098** [comment]
+1

**Comment by ga-142** [comment]
+1

**Comment by jcoffa** [comment]
+1 how has this not been implemented yet, grep has had this feature for longer than most people in this thread have been alive

**Comment by jnguyen1098** [comment]
My team and I get burned by this every week and have to use raw timestamp ranges to get the context I need, completely wasting my team's annual spend for Lambdas that emit way too many logs at-scale. Would love to combime what `grep` has already been giving us for decades with CloudWatch's beautifully fluent query language 🥲

**Comment by oguz-al** [comment]
+1

**Comment by andrey-berenda** [comment]
+1

**Comment by shinnawy** [comment]
This will help tremendously for quick insights and queries 🙏

**Comment by cn00** [comment]
+1

**Comment by joaoagaccenture** [comment]
+1

**Comment by chrizee** [comment]
+1

**Comment by KartikShrivastava** [comment]
+1

**Comment by stephenc-dg** [comment]
How is this not already implemented? Please give us two examples of higher priorities for the CloudWatch team than this.

**Comment by Dsujan** [comment]
Hi @kdaily, not sure if you are the right person but does the team have a timeline on this? This is a much-needed feature and is causing people whom I know to bail on Cloudwatch and have a full-blown ELK because they just cannot see the damn logs before the filter.

**Comment by javierwilson** [comment]
+1

**Comment by tim-finnigan** [comment]
Thanks all for your continued patience here. We have heard back from the CloudWatch team and were informed that this feature request was deprioritized for bandwidth on other higher priority features. The CloudWatch team is continuing to track this feature request in their backlog.

I have passed along all of the feedback in this issue to the CloudWatch team and they will reevaluate this for implementation in the future. I don't have any other news to share for now, so I will be closing this issue. Please keep an eye on our [changelogs](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) and [blogs](https://aws.amazon.com/blogs/aws/category/management-tools/amazon-cloudwatch/) for updates.

**Comment by justinlawrence** [comment]
> Thanks all for your continued patience here. We have heard back from the CloudWatch team and were informed that this feature request was deprioritized for bandwidth on other higher priority features. The CloudWatch team is continuing to track this feature request in their backlog.
> 
> I have passed along all of the feedback in this issue to the CloudWatch team and they will reevaluate this for implementation in the future. I don't have any other news to share for now, so I will be closing this issue. Please keep an eye on our [changelogs](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) and [blogs](https://aws.amazon.com/blogs/aws/category/management-tools/amazon-cloudwatch/) for updates.

Completed?!? Hardly.

**Comment by blchilders** [comment]
> > Thanks all for your continued patience here. We have heard back from the CloudWatch team and were informed that this feature request was deprioritized for bandwidth on other higher priority features. The CloudWatch team is continuing to track this feature request in their backlog.
> > I have passed along all of the feedback in this issue to the CloudWatch team and they will reevaluate this for implementation in the future. I don't have any other news to share for now, so I will be closing this issue. Please keep an eye on our [changelogs](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) and [blogs](https://aws.amazon.com/blogs/aws/category/management-tools/amazon-cloudwatch/) for updates.
> 
> Completed?!? Hardly.

There wasn't a .. our management is not liking the statistics from open issues status.

**Comment by rwelch-dynata** [comment]
coming from graphana and GCP, cloudwatch is painful and I hate it.  Hilarious to see this opened in 2020 then closed 3 years later.

**Comment by manibatra** [comment]
Tedious to work without this feature. Coming from Loki lack of this feature seems like such a downgrade.
