### ISSUE TITLE
apprunner UpdateService does not return OperationId

### ISSUE THREAD

**Issue by kdaily** [aws/aws-sdk#226]
Original issue: https://github.com/aws/aws-cli/pull/6871

`OperationId` is not returned in the response from the operation `UpdateService`. The docs and model claim that there is one and that it is a required value in the response.

**Comment by kdaily** [comment]
P63213303

**Comment by tim-finnigan** [comment]
We heard back from a member of the service team who noted that a fix has gone out for this. If anyone is still running into this issue after updating to a recent version please let us know. Thanks!
