### ISSUE TITLE
Default IMDS to IPv6 endpoint if no IPv4 interface address

### ISSUE THREAD

**Issue by johngmyers** [aws/aws-sdk#227]
The IMDS client should default to using the IPv6 endpoint when running in an IPv6-only environment. It should not be incumbent on the admin to set an environment variable to tell the SDK something that the SDK could figure out for itself.

I have submitted aws/aws-sdk-go#4234 to implement this for the Go SDK.

**Comment by vudh1** [comment]
I have discussed this with the team and we are not considering this feature to be implemented.
