### ISSUE TITLE
Start DLQ redrive functionality for AWS CLI

### ISSUE THREAD

**Issue by adzeeman** [aws/aws-sdk#228]
### Describe the feature

The added `Start DLQ redrive` functionality on AWS Console for SQS is superb ([ref](https://aws.amazon.com/blogs/compute/introducing-amazon-simple-queue-service-dead-letter-queue-redrive-to-source-queues/)).

The feature request is to add this functionality to the AWS CLI.

### Use Case

Exposing the `Start DLQ redrive` functionality to the AWS CLI and other AWS client SDKs would allow consumers to automate this process of moving messages back to the source queue or another queue.

An example of this automation is a scheduled worker to start the redrive.

### Synopsis
```bash
dlq-redrive
--queue-url <value>
[--message-destination <value>]
[--velocity <value>]
[--messages-per-second <value>]
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/1.19.112 Python/3.9.7 Darwin/21.4.0 botocore/1.20.112

### Environment details (OS name and version, etc.)

macOS Monterey

**Comment by adzeeman** [comment]
Hi @tim-finnigan. What did the SQS team have to say? Do you have an idea when/if this feature will be released?

**Comment by niebloomj** [comment]
Do we have a tracking ticket for the feature? Thank you.

**Comment by niebloomj** [comment]
@tim-finnigan

**Comment by aj-dev-smith** [comment]
Hi @tim-finnigan, any updates on this?  My team really loves the Redrive feature in the Console, but in real production usecases we need a programmatic solution to trigger a redrive.  We can't assign production console access to click this button.

**Comment by tim-finnigan** [comment]
Hello, there is an internal tracking ticket for this feature request. We can't guarantee any timelines but the SQS team member that I communicated with said that this would likely be on their 2023 roadmap. If you want to provide more feedback or try getting more information then I recommend contacting [AWS Support](https://aws.amazon.com/contact-us/).

**Comment by sanattaori** [comment]
Hi Team, what is alternative solution, AWS suggests till this solution is implemented.

**Comment by fgm** [comment]
Is it correct to assume the "automated" way would be to write code doing this ?

1. receive from the DLQ, probably requesting more than 1 in the ReceiveMessageInput
2. batch-produce the messages to retry to the source queue
3. delete the produced messages using the ReceiptHandle obtained at step 1.

It seems the DLQ redrive provided in the console implements basically this, with just a couple parameters regarding the rate of production (velocity settings).

**Comment by dltacube** [comment]
Anyone have any idea if this is something that's been worked on elsewhere as part of another ticket/initiative? I find it hard to believe there isn't a programmatic way of moving messages from one queue to another.

**Comment by mfabricanti** [comment]
This feature on CLI would be super useful for us too!

**Comment by FL-K** [comment]
Hi, we also need this feature on the cli.
Subscribed for updates

**Comment by arnautg** [comment]
Also need this feature on our company

**Comment by joematune** [comment]
Woohoo! Available in SDK and CLI.

- Announcement: [https://aws.amazon.com/whats-new/2023/06/amazon-sqs-dead-letter-queue-redrive-aws-sdk-cli/](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-sqs-dead-letter-queue-redrive-aws-sdk-cli/)
- CLI start-message-move-task docs: [aws.com/documentation/sqs/start-message-move-task](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/start-message-move-task.html)

```bash
aws sqs start-message-move-task \
  --source-arn https://sqs.us-east-2.amazonaws.com/123.../my-queue \
  --destination-arn https://sqs.us-east-2.amazonaws.com/123.../my-queue-dlq
```

**Comment by tim-finnigan** [comment]
Thanks @joematune for noting this! [Here](https://github.com/aws/aws-cli/blob/4ba3b4e5ac9fc95b2ed61e85e4a801848b5639d5/CHANGELOG.rst?plain=1#L34) is the CHANGELOG entry for v2 (2.11.26) and [v1](https://github.com/aws/aws-cli/blob/cd83e5ee3013931a7af9a27ea3a6ad5a9d000c56/CHANGELOG.rst?plain=1#L46) (1.27.148).

**Comment by adzeeman** [comment]
@joematune, thank you 🚀 Looking forward to start using this feature!
