### ISSUE TITLE
sendEmail() function doesn't allow the setting of the List-Unsubscribe header

### ISSUE THREAD

**Issue by 17100113** [aws/aws-sdk#23]
Hi. The List-Unsubscribe header could be made into a param in the args list for sendEmail. Right now, if we're to add the List-Unsubscribe header, we'll have to have the sendRawEmail function instead. Current solutions are like so: https://stackoverflow.com/questions/35278372/how-to-implement-list-unsubscribe-header-in-emails-sent-by-aws-ses-with-the-php/38684545#38684545
Code readability is heavily compromised.

**Comment by tim-finnigan** [comment]
Based on this article it looks like it is now available: https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-ses-now-offers-list-and-subscription-management-capabilities/

> ...customers can configure Amazon SES to add an email footer unsubscribe link and/or a list-unsubscribe header to enable end users to unsubscribe from a list or from all customer emails. 

Please reopen or create a new issue if we missed something. Thanks!
