### ISSUE TITLE
AWS API structured action/datatype data dictionary

### ISSUE THREAD

**Issue by darianmiller** [aws/aws-sdk#231]
I started writing some AWS routines for Delphi and wrote an API document parser to extract the defined Actions and Data Types for a given AWS API based on your online developer guide pages (such as https://docs.aws.amazon.com/lambda/latest/dg/API_Reference.html)  

In conjunction with this web scraping tool, I have a simple code generator in the works to produce the Delphi source code units needed to support the particular webservice. This can also generate a JSON based outline of the webservice (sample attached.) 
[Lambda.json.txt](https://github.com/aws/aws-sdk/files/8646100/Lambda.json.txt)

Since the developer guides vary in format and webscraping isn't the greatest solution to building a library, it would be much easier if Amazon offered a structured view of your APIs that could be more easily parsed. So my main question is this: is there a published spec of each your APIs in a structured format rather than HTML page or Markdown document?  I assume it's available, but there is so much content on AWS online, it's simply hard for me to locate.  (I apologize if I missed the forest amongst the trees if there's an obvious solution.)

I'm an Embarcadero MVP for Delphi and would like to see more AWS functionality available to Delphi developers. There isn't an official Delphi SDK Delphi and there are only a few Delphi libraries available covering just a few of Amazon web services.  Delphi is also not a supported language for Lambda, but it's fairly straightforward to use Delphi code in a serverless manner leveraging Lambda but few seem to know about this.  There are still a bunch of Delphi developers out there and I believe they would benefit from easier interoperability with AWS.

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Which AWS SDK or tool are you using? Please open an issue for this directly in the GitHub repository for that SDK or Tool. And please provide more details on your use case.

AWS API documentation for services can be find in the User Guides like S3 here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations_Amazon_Simple_Storage_Service.html. And at the bottom on an API documentation page you can find links to SDK/Tool-specific documentation: https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html#API_AbortMultipartUpload_SeeAlso

**Comment by darianmiller** [comment]
@tim-finnigan I don't use a current AWS SDK which is the problem.  I program in Delphi and you don't currently offer a SDK for Delphi programmers.  However, I have recently discovered what I need was hiding in plain sight.  I was specifically after the files that you internally use for codegen for your various SDKs.  I now see that they are available in a few repos, such as in the SDK for Net here: 
https://github.com/aws/aws-sdk-net/tree/3eca86cb8c585ff490f216d29c354deec8d2a33a/generator/ServiceModels

I can use these service model files to build my own SDK for Delphi which I am now doing.  I would hope that AWS would provide native support for Delphi as there are quite a few of us Delphi developers out there, but in the meantime, I'll use these.  

Thanks!
