### ISSUE TITLE
Add `update-function-code` for Cloudfront functions

### ISSUE THREAD

**Issue by lcswillems** [aws/aws-sdk#234]
### Describe the feature

For a Lambda function, it possible to update its code and publish with one command:

```
aws lambda update-function-code --publish ...
```

There is no similar command for Cloudfront functions.

### Use Case

I would like to update the code of my Cloudfront function without having to update the whole function and also to publish with one command. Something like:

```
aws cloudfront update-function-code --publish ...
```

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by tim-finnigan** [comment]
P64367397

**Comment by lcswillems** [comment]
Thanks! It is not only about combining "update" and "publish". It is also about updating only the code.

**Comment by lcswillems** [comment]
I want the same thing than the `update-function-code` available for Lambda functions.

**Comment by tim-finnigan** [comment]
Thanks I will note that to the Cloudfront team.

**Comment by tim-finnigan** [comment]
I heard back from a member of the CloudFront team and they added this feature request to their backlog for consideration. I can’t guarantee a timeline of when they might implement this but feel free to check back in for updates.

**Comment by lcswillems** [comment]
Thanks!

**Comment by rashidul0405** [comment]
@tim-finnigan it's marked as completed, but I can't see anything like this in doc!!
