### ISSUE TITLE
Add a waiter for the EfsClient

### ISSUE THREAD

**Issue by rupert-madden-abbott** [aws/aws-sdk#236]
It would be helpful if the `EfsClient` had a `Waiter` like many other clients.

I want to create a file system, and then create a mount target. If the second call happens before the file system is ready, I get an error `IncorrectFileSystemLifeCycleStateException`. At the moment, I need to poll for the file system to move to the correct state before creating the mount target.

**Comment by debora-ito** [comment]
P45713050

**Comment by debora-ito** [comment]
@rupert-madden-abbott the EFS team acknowledged your request, and seems like there are some internal teams interested in seeing waiters supported too.

I'll go ahead and close this issue as there's nothing pending from the SDK team. Once the EFS team releases support for waiters, it will probably be mentioned in the SDK CHANGELOG.
