### ISSUE TITLE
ElasticBeanstalk ApplicationVersionDescription UNKNOWN_TO_SDK_VERSION 

### ISSUE THREAD

**Issue by count-emmolgus** [aws/aws-sdk#237]
The ApplicationVersionDescription.status() will always return UNKNOWN_TO_SDK_VERSION irregardles of the actual status.
Since the status field of the object is in all upper-case (e.g. UNPROCESSED), but fromValue uses the toString method which will compare with the.

## Expected Behavior
The API response should match the sdk's specification. (Which would be the correct enum value in this case)

## Your Environment
Java 11
aws sdk for java 2.16.92

I'd assume it's related to the same/similiar core issue as: aws/aws-sdk#238

![image](https://user-images.githubusercontent.com/51096443/123970822-c4de1d00-d9b9-11eb-9b30-6134bc2b5aa4.png)

**Comment by tim-finnigan** [comment]
@debora-ito do you know if Elastic Beanstalk fixed this? I couldn't find any related updates or reports.
