### ISSUE TITLE
UNKNOWN_TO_SDK_VERSION

### ISSUE THREAD

**Issue by kedbirhan** [aws/aws-sdk#238]
there is a problem with RecorderStatus class of AWS config package. API call response capitalizes the RecorderStatus. unfortunately, the SDK matches it to the enum if it's not capitalized. hence returning "UNKNOWN_TO_SDK_VERSION". 
## Expected Behavior
the API response should match the sdk's specification.

```
RecorderStatus recorderStatus=configurationRecorderStatus.lastStatus();         System.out.println(configurationRecorderStatus.lastStatus().name().equalsIgnoreCase(RecorderStatus.SUCCESS.name()));
    log.info("{} {}", configurationRecorderStatus.recording().equals(True),
configurationRecorderStatus.lastStatus().equals(RecorderStatus.SUCCESS)**); // if configurationRecorderStatus.lastStatus() is success it should be true but the response is Capitalized so the sdk is unabel to resolve to the defined enum, hence retuns false
           return  configurationRecorderStatus.recording() && configurationRecorderStatus.lastStatus().equals(RecorderStatus.SUCCESS);
```

## Your Environment
: 
java 11
aws sdk for java v2.15.7
mac

**Comment by debora-ito** [comment]
@kedbirhan got an update from the service team: they are aware of the issue, but they don't have short term plans to fix it. They are concerned that the change is backwards incompatible.

As a workaround, Java SDK provides a [lastStatusAsString](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/config/model/ConfigurationRecorderStatus.html#lastStatusAsString())() to obtain the raw enum value.

Will go ahead and close this issue, as there's nothing pending from the SDK team. Feel free to reach out if you have questions, about this or any other issue.
