### ISSUE TITLE
list-mfa-devices sometimes attempts to retrieve MFA devices for all users

### ISSUE THREAD

**Issue by tobynorth** [aws/aws-sdk#239]
### Describe the bug

Running `aws iam list-mfa-devices` can result in an attempt to retrieve _all_ MFA devices, which is incorrect according to the docs.

### Expected Behavior

[The docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-mfa-devices.html) suggest that `list-mfa-devices` should only ever return MFA devices for a single user at a time:

> If the request includes a IAM user name, then this operation lists all the MFA devices associated with the specified user. If you do not specify a user name, IAM determines the user name implicitly based on the Amazon Web Services access key ID signing the request for this operation.

Based on this, I'd expect `aws iam list-mfa-devices` without the `--user-name` flag to attempt to retrieve only MFA devices for the user with the current access key ID in `~/.aws/credentials`.

### Current Behavior

The command apparently attempts to retrieve all MFA devices (`resource: *`):

![image](https://user-images.githubusercontent.com/19778351/168383561-8da040ea-b598-4d7c-a8b7-9646e996cff7.png)

Look at the [debug.log](https://github.com/aws/aws-cli/files/8691196/debug.log) from running this command for more details.

The user `trn_test` in the above screenshot has permission to run `iam:ListMFADevices` only for its own MFA devices. After adding `--user-name trn_test`, the command works as intended and only retrieves MFA devices for `trn_test`:

![image](https://user-images.githubusercontent.com/19778351/168384815-d5fa7508-0f2f-4f77-95bf-7ec0283df3d0.png)

### Reproduction Steps

Simply run `aws iam list-mfa-devices` when using an access key generated for a user that only has permission to list its own MFA devices. Here's how to setup such a user:

1. In IAM > Users, create a user that is allowed to perform `iam:ListMFADevices` for only its own devices by attaching a policy that includes something like this: 
```
{
    "Version": "2012-10-17",
    "Statement": [
        ...
        {
            "Sid": "AllowManageOwnUserMFA",
            "Effect": "Allow",
            "Action": [
                "iam:ListMFADevices"
            ],
            "Resource": "arn:aws:iam::*:user/*${aws:username}"
        },
        ...
    ]
}
```
2. Enable MFA for this user and create an access key.
3. In `~/.aws/credentials`, backup your `[default]` profile and paste the following, filling in the access key ID and secret access key from step 2:
```
[default]
aws_access_key_id = <fill in>
aws_secret_access_key = <fill in>
```
4. Launch a new terminal window and run the command above.

### CLI version used

2.6.0

### Environment details (OS name and version, etc.)

OS X 12.3.1

**Comment by tim-finnigan** [comment]
P64416265

**Comment by tim-finnigan** [comment]
I received an update from a member of the IAM team. They said that the API and AuthZ logic are working as designed. If no user name is supplied in the request then the authorized resource is `"*"`, and therefore the policy should include resource `"*"` for the request to be allowed. Please note that `"*"` is not referring to as all MFA devices but rather the subject for this API is users. For more information please see the AuthZ reference here: https://docs.aws.amazon.com/service-authorization/latest/reference/list_identityandaccessmanagement.html. 

AuthZ-ing resource `"*"` (vs "Resource": "arn:aws:iam:::user/*${aws:username}" - as you had suggested) is for historical reasons, and they are not considering to change this behavior at the moment. But the API behaves as expected - if no user name is provided in the request then only MFA devices for the caller are returned.

**Comment by tobynorth** [comment]
@tim-finnigan Thanks for the clarification! Do you think it would make sense to reopen this as a documentation issue, though? [The doc page I linked to in the issue description](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-mfa-devices.html) is technically correct, but I definitely didn't expect based on reading it that `list-mfa-devices` will AuthZ resource `"*"` if you don't include `--user-name`. I think adding a note to that effect would be helpful.

**Comment by tim-finnigan** [comment]
Thanks @tobynorth, I passed that feedback along to the IAM team and waiting to hear back. If they agree then I can reopen this and track the documentation change. I also think that adding a note could help clarify the behavior here.
