### ISSUE TITLE
IAM ListRoles doesn't return proper data

### ISSUE THREAD

**Issue by Bensign** [aws/aws-sdk#24]
The IAM method of ListRoles states in the documentation that each role will have a RoleLastUsed struct returned. However, RoleLastUsed always returns null even with IAM Roles that have activity associated with them.

I am attempting to access this data through the Ruby SDK - which after hours of opening issues and wasting my time I've been told this is a service team issue. Can you please resolve this? It seems like IAM 101 type data.

**Comment by mullermp** [comment]
Related issues

https://github.com/aws/aws-sdk-ruby/issues/2360
https://github.com/aws/aws-sdk-ruby/issues/2433

**Comment by luckielordie** [comment]
I'm seeing the same issue in the Go API

**Comment by mullermp** [comment]
Yes. This is an issue with the service API, so all SDKs will have the same behavior here.

**Comment by stobrien89** [comment]
Ticketed the Cloudformation team to remove from the SDK docs: P51484521

**Comment by tim-finnigan** [comment]
P62164673

**Comment by mullermp** [comment]
I recall inquiring about this and it boiled down to technical limitations.

**Comment by tim-finnigan** [comment]
Here is a relevant comment on this behavior: https://github.com/awsdocs/iam-user-guide/issues/81#issuecomment-1205810659

> Unfortunately, the list operation and the get operation both return the same data type. This was an early API model decision and one that we're stuck with today. The only way to fix it is to rewrite the API model to ensure that each operation returns a different data type and release a new version of the API. The API, CLI, and SDK documentation sets all come from the API model.
>
>The IAM team is aware of this issue and is investigating a path forward. You can contact AWS Premium Support at any time to request an update for this issue.

**Comment by tim-finnigan** [comment]
>The IAM team is aware of this issue and is investigating a path forward. You can contact AWS Premium Support at any time to request an update for this issue.

We don't have any updates since this post. As mentioned there you can reach out through [AWS Support](https://aws.amazon.com/contact-us/) for updates or check in here as well. But since the IAM team is aware of this issue and tracking it in their backlog we are going to close this issue.
