### ISSUE TITLE
Missing RDS waiter: db instance stopped

### ISSUE THREAD

**Issue by lbruun** [aws/aws-sdk#240]
## Describe the Feature
I cannot find a waiter for RDS instance 'stopped' state.

## Is your Feature Request related to a problem?
Use case:  Execute action _StopDBInstance_ and wait for the instance to be in `stopped` state.

## Proposed Solution
Implement method `waitUntilDBInstanceStopped(..)` on `RdsWaiter`.

## Describe alternatives you've considered
It is possible - although somewhat complex - for the user himself to create functionality for this, but it means the user has to know all the details about how waiters work (for example Acceptors).

## Your Environment

* AWS Java SDK version used: latest
* JDK version used: v11
* Operating System and version: Windows and Linux

**Comment by debora-ito** [comment]
The RDS team acknowledged the feature request and added to their backlog. We don't have a timeline to share for when the waiter will be available.

V295337676

Closing this, as there's no action pending on the SDK team. Feel free to reach out if anyone have further questions.
