### ISSUE TITLE
API to list valid instance types for EMR

### ISSUE THREAD

**Issue by achals** [aws/aws-sdk#241]
The EC2 client has an API, `describeInstanceTypeOfferings`, to list available instance types in a region. EMR's instance type offering is a subset of these instances, as described in https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-supported-instance-types.html.

It would be great if the API/SDK exposed a method to list all instance types that EMR supports in a region.

## Is your Feature Request related to a problem?
We allow users to specify instance types for their spark jobs. Right now, there's no possible way to validate the instance type short of running a new Job Flow and failing and introspecting the result.

## Proposed Solution
A new API, `describeInstanceTypeOfferings` on the EMRClient.

## Describe alternatives you've considered
Parsing https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-supported-instance-types.html and attempting to do a string match. 🤮 

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:  `2.10.52`
* JDK version used:
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```
* Operating System and version: `amazon-eks-node-1.15-v20200312`

**Comment by praetp** [comment]
Any update on this ?

**Comment by steven-aerts** [comment]
A workaround is using the pricing api.
From the command line it looks like this:
```
aws --region us-east-1 pricing get-products --service-code ElasticMapReduce --filters 'Type=TERM_MATCH,Field=RegionCode,Value=eu-west-3' 'Type=TERM_MATCH,Field=softwareType,Value=EMR' | jq -r '.PriceList[] | fromjson | .product.attributes.instanceType' | sort -u 
```
Not nice, and it might even be out of sync sometimes.  But the best we could come up with.

**Comment by debora-ito** [comment]
The EMR team acknowledged the feature request. We don't have a timeline for when it would be available.

V228592666

Will go ahead and close this, as there's no action pending on the SDK team.  Feel free to reach out if you have any other question.
