### ISSUE TITLE
[S3 Client] Skip upload when uploaded object will overwrite identical object

### ISSUE THREAD

**Issue by psantus** [aws/aws-sdk#243]
Since PUT requests are more expensive than GET, before uploading an object it'd be great to check a fully identical object doesn't already exist.

## Describe the Feature

For some workloads to be repeatable/idempotent, we sometimes need to be able to try object upload without the pain of checking the object already exists.

## Is your Feature Request related to a problem?

Currently, API users who want to do that 
- need to have their own implementation
- need to either GET the object (may incur transfer charges) or LIST bucket objects (same price as PUT)
so it ends up being a quite expensive operation.

## Proposed Solution

- Would require AWS implement a get-object-metadata / get-object-summary service in the S3 API (with a veeery cheap pricing).
- Then AmazonS3Client.putObject implementations should compare object properties (including MD5 eTag), and if identical, make an early return without trying the PUT API request.

## Describe alternatives you've considered

None :) 

## Additional Context

We use S3 to archive request/response with external 3rd parties for audit purposes

## Your Environment

* AWS Java SDK version used:
* JDK version used: 2.15.33
* Operating System and version: irrelevant

**Comment by steve-o** [comment]
The main issue here is that AWS S3 service does not support _conditional requests_ per RFC-7232 for `PUT` or `POST` requests, only for `GET`.  One should be able to `PUT` with a `if-none-match` and the MD5 digest of the object to prevent the re-upload.  This may need a `Expect: 100-continue` to defer the body transfer, otherwise the payload is still sent, just ignored.

https://datatracker.ietf.org/doc/html/rfc7232#section-3.2

**Comment by kellertk** [comment]
P126357928

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The S3 team is continuing to track this in their backlog. For updates please refer to the [S3 blog](https://aws.amazon.com/blogs/aws/category/storage/amazon-simple-storage-services-s3/) or SDK changelog.
