### ISSUE TITLE
MediaConvert- No way to retrieve job output group output location

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk#247]
There seems to be no provision to retrieve the final url of the output asset file (like for HLS - main index.m3u8 file location). It can be predicated in the client side but it has limitations, as the output location could be configured to use variable expression in destination url like s3://x-vod-output-bucket/processedpoutputs/$dt$/ . In such cases , finally the playable asset would be in a dynamic location. How would the client code know until the same is returned in the job response?

**Comment by debora-ito** [comment]
V109397033.

**Comment by ramkeshsehara** [comment]
+1 we also needing this functionality

Any progress?

**Comment by tim-finnigan** [comment]
Thanks all for your patience here. We just heard back from the MediaConvert team who noted that they don't have any plans to change the GetJob API, because the information can be retrieved via a CloudWatch Event which is the preferred method for receiving progress data.

**Comment by lmanerich** [comment]
> Thanks all for your patience here. We just heard back from the MediaConvert team who noted that they don't have any plans to change the GetJob API, because the information can be retrieved via a CloudWatch Event which is the preferred method for receiving progress data.

I don't think that receiving the final file path is a "progress data".
I really think this should be planned and implemented as is just an attribute in the already existing output group array.

**Comment by lmanerich** [comment]
> Thanks all for your patience here. We just heard back from the MediaConvert team who noted that they don't have any plans to change the GetJob API, because the information can be retrieved via a CloudWatch Event which is the preferred method for receiving progress data.

I don't think that receiving the final file path is a "progress data".
I really think this should be planned and implemented as is just an attribute in the already existing output group array.
