### ISSUE TITLE
CloudFormation events resource status values contains values from StackStatus enum

### ISSUE THREAD

**Issue by Discipe** [aws/aws-sdk#248]
Class com.amazonaws.services.cloudformation.model.StackEvent has method for retrieving resource status:
```Java
 /**
     * <p>
     * Current status of the resource.
     * </p>
     * 
     * @return Current status of the resource.
     * @see ResourceStatus
     */
    public String getResourceStatus() {
        return this.resourceStatus;
    }
```

But it actually can return values from StackStatus enum, e.g.: "ROLLBACK_IN_PROGRESS" and "ROLLBACK_COMPLETE". That causes exception "Cannot create enum from <...> value!" when trying to call function `ResourceStatus.fromValue(String)` with `getResourceStatus()` as function's argument.
If this is intentional, then method name and documentation are misleading - status values for resources with type "AWS::CloudFormation::Stack" is actually `StackStatus` enum, not `ResourceStatus`. 

Short example (in Scala):
```Scala

import scala.collection.JavaConverters._
import com.amazonaws.services.cloudformation.model._
import com.amazonaws.services.cloudformation.AmazonCloudFormationClientBuilder
object Test {

  def main(args: Array[String]): Unit = {
    val cfClient = AmazonCloudFormationClientBuilder.defaultClient()
    val name = ""  //stack name with "ROLLBACK_*" events
    val events = cfClient.describeStackEvents(new DescribeStackEventsRequest().withStackName(name)).getStackEvents.asScala

    //here we fail
    events.map(e => ResourceStatus.fromValue(e.getResourceStatus))
  }
}
```

**Comment by debora-ito** [comment]
P22716170

**Comment by debora-ito** [comment]
Quick update: I just checked the internal ticket with the CloudFormation team, but it has no recent updates.
I'll go ahead and close this issue, since there's no pending actions from the SDK side.
