### ISSUE TITLE
Unable to specify source launch template when creating a new launch template

### ISSUE THREAD

**Issue by paksv** [aws/aws-sdk#249]
In AWS console it is possible to specify a source template and version when creating a new launch template. However, when I try to create one using AWS java SDK it is only possible by specifying a LaunchTemplateData.

It might not have been a problem, but there are two different objects: RequestLaunchTemplateData and ResponseLaunchTemplateData and I wasn't able to find any way to map one to another.

Unfortunately, there's no reasonable workaround for that issue. Copying the fields (and constant maintenance of that code) is the last thing I would want to do.

**Comment by tim-finnigan** [comment]
Have you tried using the DescribeLaunchTemplates API (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeLaunchTemplates.html) and then using the results in [CreateLaunchTemplate](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateLaunchTemplate.html)? Or does it not provide all of the fields you need?

I do see in the [CreateLaunchTemplate](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateLaunchTemplate.html) documentation it notes:
>To clone an existing launch template as the basis for a new launch template, use the Amazon EC2 console. The API, SDKs, and CLI do not support cloning a template. For more information, see [Create a launch template from an existing launch template](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template-from-existing-launch-template) in the _Amazon EC2 User Guide_.
