### ISSUE TITLE
com.amazonaws.services.cloudformation.model.ValidateTemplateResult support for CAPABILITY_AUTO_EXPAND

### ISSUE THREAD

**Issue by dxciberaws** [aws/aws-sdk#250]
When validating cloudformation templates containing Fn::Transform, the obtained ValidateTemplateResult object does not report the CAPABILITY_AUTO_EXPAND capability.

This has a side effect in the Eclipse Tookit, which cannot create CFN stacks that use macros.

**Comment by debora-ito** [comment]
P31563606

**Comment by debora-ito** [comment]
According to the CloudFormation team, this was fixed some time ago.

Will go ahead and close this, as there's no action pending from the SDK team. Let us know if you have any other question or comment.
