### ISSUE TITLE
aws-java-sdk-dynamodb missing enum values for ReturnValuesOnConditionCheckFailure

### ISSUE THREAD

**Issue by RustedBones** [aws/aws-sdk#251]
The [`ReturnValuesOnConditionCheckFailure`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ReturnValuesOnConditionCheckFailure.html) enum provides the `ALL_OLD` and `NONE` values.

However, int [`Update.withReturnValuesOnConditionCheckFailure`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/Update.html#withReturnValuesOnConditionCheckFailure-com.amazonaws.services.dynamodbv2.model.ReturnValuesOnConditionCheckFailure-), it is stated that `NONE`, `ALL_OLD`, `UPDATED_OLD`, `ALL_NEW`, `UPDATED_NEW` are valid values.

`ReturnValuesOnConditionCheckFailure` must be extended with the missing enum values

**Comment by tim-finnigan** [comment]
It looks like the documentation has since been updated, closing as resolved.
