### ISSUE TITLE
AWS S3 SDK doesn't support file renaming. 

### ISSUE THREAD

**Issue by nazeer1100126** [aws/aws-sdk#252]
There is no method available to rename a particular file in AWS S3 SDK.
The suggested approach copying the file content to new file is time consuming.

**Comment by tim-finnigan** [comment]
Thanks for your patience. The S3 team is continuing to track this in their backlog. Please refer to the [blog](https://aws.amazon.com/blogs/aws/category/storage/amazon-simple-storage-services-s3/) or changelog for updates.
