### ISSUE TITLE
S3 Replication Status constant for complete should be defined as 'COMPLETED'

### ISSUE THREAD

**Issue by tsenovIvan** [aws/aws-sdk#254]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
S3 replication constant _ReplicationStatusComplete_ and its value should be COMPLETED instead of COMPLETE.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-status.html

**Version of AWS SDK for Go?**
aws.SDKVersion prints 1.6.0
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go-v2/aws"`

**Version of Go (`go version`)?**
1.16.2

**To Reproduce (observed behavior)**
Make a request for S3 Object with HeadObject() for an object that has Replication Enabled and the object has been replicated. The ReplicationStatus property of HeadObjectOutput returns COMPLETED.
The _ReplicationStatusComplete_ constant however is set to COMPLETE.
According to this [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-status.html
) it is supposed to be COMPLETED, so the constant should be changed accordingly.

**Expected behavior**
_ReplicationStatusComplete_ should have value COMPLETED. Maybe the constant itself should also be renamed to _ReplicationStatusCompleted_

**Additional context**
n/a

**Comment by debora-ito** [comment]
P49956507

**Comment by ashishdhingra** [comment]
@tsenovIvan Good afternoon. Per last update from service team, the `COMPLETED` status was added to service models. I also checked AWS SDK for Go v2 [documentation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3@v1.53.0/types#ReplicationStatus), the `ReplicationStatus` enum now also has `COMPLETED` value. Hence, closing this issue. Feel free to reopen in case of any issues.
