### ISSUE TITLE
SQS short polling broken in SDK v2

### ISSUE THREAD

**Issue by jtorkkola** [aws/aws-sdk#261]
### Describe the bug

`ReceiveMessageInput.WaitTimeSeconds` has changed from an [integer pointer](https://github.com/aws/aws-sdk-go/blob/ff01670cf6f7a56927af6c75018c857e580c4ab0/service/sqs/api.go#L4386) in SDK v1 to an [integer](https://github.com/aws/aws-sdk-go-v2/blob/be23823c0958c66c1e41d1b7c2fa9f5014b463e1/service/sqs/api_op_ReceiveMessage.go#L231) in SDK v2. Previously a `nil` value meant that a `ReceiveMessage` call would defer to the queue setting, and a 0 value meant short polling. Now 0 means deferring to the queue setting, and there's no way to short poll if the queue default isn't 0 (see the `ReceiveMessageInput` serialization logic [here](https://github.com/aws/aws-sdk-go-v2/blob/be23823c0958c66c1e41d1b7c2fa9f5014b463e1/service/sqs/serializers.go#L1964)).

`ReceiveMessageInput.VisibilityTimeout` and `SendMessageInput.DelaySeconds` look to have the same issue.

### Expected Behavior

Calling `ReceiveMessage` with `ReceiveMessageInput.WaitTimeSeconds = 0` causes short polling like in SDK v1.

### Current Behavior

Calling `ReceiveMessage` with `ReceiveMessageInput.WaitTimeSeconds = 0` defers to the queue's default receive message wait time, which may not be 0.

### Reproduction Steps

Call `ReceiveMessage` with `ReceiveMessageInput.WaitTimeSeconds = 0` on an empty queue with a default receive message wait time of 10 seconds, and observe the duration of the call.

### AWS Go SDK V2 Module Versions Used

v1.16.0

### Compiler and Version used

1.18

### Operating System and version

macOS 12.3.1

**Comment by calscoo** [comment]
Any updates on this? We're migrating our services to the V2 SDK for the new security features, but can't move forward because our service relies on SQS and this bug is holding us up. It hasn't been touched in almost 9 months. @jasdel @vudh1 @RanVaknin

**Comment by RanVaknin** [comment]
Hi @calscoo, @jtorkkola 

Sorry for the long wait. 

We have tried getting the SQS team to solve this but they are unable to prioritize this fix. 
If you willing, please cut an additional internal ticket to the SQS team via the AWS Console and reference the tracking ticket ID we already have with them `P97774845`, having a customer directly asking for remediation will help prioritization.

Thanks,
Ran~

**Comment by keenangraham** [comment]
Running into this with `VisibilityTimeout` set to `0` in `ChangeMessageVisibilityBatch`.

Version: `github.com/aws/aws-sdk-go-v2/service/sqs v1.31.3`

```
Failed ID: message_0, Code: MissingParameter, Message: The request must contain the parameter ChangeMessageVisibilityBatchRequestEntry.1.VisibilityTimeout.
```

**Comment by RanVaknin** [comment]
This is now fixed.
