### ISSUE TITLE
Set DynamoDB TTL on table creation

### ISSUE THREAD

**Issue by jaredpetersen** [aws/aws-sdk#262]
### Describe the feature

Allow clients to configure the DynamoDB TTL when creating tables as part of [Client.CreateTable](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb#Client.CreateTable).

### Is your Feature Request related to a problem?

As far as I can tell, the only way to set the TTL when creating a DynamoDB table is to run an update function after creation: [Client.UpdateTimeToLive](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb#Client.UpdateTimeToLive)

This is pretty tedious and it would be much easier if you could just set that when defining the create table request.

### Proposed Solution

Add a field to [CreateTableInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb#CreateTableInput):

```go
TimeToLiveSpecification *types.TimeToLiveSpecification
```

This field would be the same as what's defined in [UpdateTimeToLiveInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb#UpdateTimeToLiveInput).

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

v1.15.0

### Go version used

1.17

**Comment by vudh1** [comment]
P70666165

**Comment by RanVaknin** [comment]
Hi @jaredpetersen ,

The dynamo team did not move forward with this feature request. 

Sorry for the inconvenience. 
Ran~

**Comment by klakegg** [comment]
What is the workaround for adding TTL to a DynamoDB table using the SDK?

**Comment by jaredpetersen** [comment]
@klakegg You can still enable TTL with [Client.UpdateTimeToLive](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb#Client.UpdateTimeToLive). It's just not something you can do immediately when you create the table; it's a secondary action.
