### ISSUE TITLE
No "SourceSecurityGroupId" in ec2.AuthorizeSecurityGroupIngressInput

### ISSUE THREAD

**Issue by diwu-db** [aws/aws-sdk#265]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
I am setting up the inbound rule for a security group in nondefault VPC. 

Getting error messages while calling: AuthorizeSecurityGroupIngress
`
The security group 'sourceSgName' does not exist in the default VPC xxx
`
AuthorizeSecurityGroupIngressInput parameters: 
`		
                 FromPort:                util.Int64Ptr(3306),
		GroupId:                 groupId,
		IpProtocol:              util.StrPtr("TCP"),
		SourceSecurityGroupName: sourceSgName,
		ToPort:                  util.Int64Ptr(3306),
`
From the API document, for security groups that are not in the default VPC, we have to use group id instead of name. However, this field is missing in AuthorizeSecurityGroupIngressInput

**Version of AWS SDK for Go?**
 v1.40.56

**Version of Go (`go version`)?**

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

**Expected behavior**
source security group in non-default VPC can be authorized for inbound traffic using GO SDK

**Additional context**

**Comment by vudh1** [comment]
V703665197

**Comment by RanVaknin** [comment]
Response from service team:

>There is intentionally no parameter for SourceSecurityGroupId.

>In the early days of this EC2 API, we supported SourceSecurityGroupName but as more use cases for different type of references came along, the IPPermissions parameter was introduced as a preferred way of adding references in the security group.

>Customer should be able to use the IPPermissions parameter for this: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html . This exists in all SDKs.

Thanks,
Ran~
