### ISSUE TITLE
add support for graviton 3

### ISSUE THREAD

**Issue by ausil** [aws/aws-sdk#266]
**Is your feature request related to a problem? Please describe.**
If I try to use the SDK I can not use c7g instances as the support is missing
**Describe the solution you'd like**
I would like to see the graviton 3 based instances available

**Describe alternatives you've considered**

**Additional context**

**Comment by tim-finnigan** [comment]
It looks like support for these was announced May 23, 2022: https://aws.amazon.com/blogs/aws/new-amazon-ec2-c7g-instances-powered-by-aws-graviton3-processors/

@ausil are you unblocked now or can you let us know where you're still running into issues?

**Comment by ausil** [comment]
Things seem to be working okay now.

**Comment by tim-finnigan** [comment]
Thanks for letting us know, I'll go ahead and close this.
