### ISSUE TITLE
SQS missing "InvalidParameterValue" response error

### ISSUE THREAD

**Issue by montaguethomas** [aws/aws-sdk#267]
**Is your feature request related to a problem? Please describe.**
SQS API can return an `InvalidParameterValue` error, which is [not implemented](https://github.com/aws/aws-sdk-go/blob/3500f2882050c922b818dfebb2e8ec6390f1b63e/service/sqs/errors.go) in the sdk.

**Describe the solution you'd like**
Implement SQS error constant `InvalidParameterValue`.

**Additional context**
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/CommonErrors.html
- https://aws.amazon.com/premiumsupport/knowledge-center/sqs-receipt-handle-error/

**Comment by vudh1** [comment]
P70319691

**Comment by RanVaknin** [comment]
Hi @montaguethomas ,

This was rejected by the service team, `InvalidParameterValue` is a generic error and not specific to that service. You can use string comparison to error handle on this particular error.

I know it's not the answer you were hoping. 

Sorry,
Ran~
