### ISSUE TITLE
Update documentation describing CloudWatch `put_metric_alarm` behavior for create vs update operations

### ISSUE THREAD

**Issue by mullermp** [aws/aws-sdk#27]
`Aws::CloudWatch::Client#put_metric_alarm` supports a `tags` field, but it only works when the alarm does not already exist. The tags field is ignored when updating the alarm.

To update tags on an existing alarm, `Aws::CloudWatch::Client#tag_resource` and `Aws::CloudWatch::Client#untag_resource` are required

The documentation should be updated to reflect that `tags` are not updated when the alarm already exists.

related: https://github.com/aws/aws-sdk-ruby/issues/2408

**Comment by mullermp** [comment]
@kellertk I don't have permission to assign labels, I'm sure that's intended. But please categorize this as documentation improvement.

**Comment by ajredniwja** [comment]
Changes were made, see: https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html

Closing this issue now, please reach out if you have any other questions.
