### ISSUE TITLE
DeleteObjects fails silently if one or some of the objects contain invalid XML characters

### ISSUE THREAD

**Issue by xinmeigui-db** [aws/aws-sdk#271]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
When deleting S3 objects with invalid XML characters using `DeleteObjects`, it fails to delete the object without throwing an error. ([A similar ticket in the java sdk](https://github.com/aws/aws-sdk-java/issues/333))

**Version of AWS SDK for Go?**
1.17.13
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go/aws"`

**Version of Go (`go version`)?**
1.15.2

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```
        req, _ := s.DeleteObjectsRequest(&s3.DeleteObjectsInput{
		Bucket: &s.bucket,
		Delete: &items,
	})
	err := req.Send()
```
where items contain:
```
Objects: [
    {
      Key: "dir1/file3"
    },
    {
      Key: "dir2/dir3/"
    },
    {
      Key: "dir2/dir3/file4"
    },
    {
      Key: "dir4/"
    },
    {
      Key: "dir4/file5"
    },
    {
      Key: "empty_dir/"
    },
    {
      Key: "empty_dir2/"
    },
    {
      Key: "file1"
    },
    {
      Key: "file2"
    },
    {
      Key: "invalidXml/folder1 !#$%&'<>*+,-.=?@[\\^~_\t"
    },
    {
      Key: "invalidXml/invalid\b\v\a"
    },
    {
      Key: "zero"
    }
  ]
```

With `LogDebugWithHTTPBody`, the http request and response are:
```
---[ REQUEST POST-SIGN ]-----------------------------
POST /goofys-test-crj4f6i8wkyqtt4n?delete= HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: aws-sdk-go/1.17.13 (go1.13.4; linux; amd64)
...
Accept-Encoding: gzip

<Delete xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Object><Key>dir1/file3</Key></Object><Object><Key>dir2/dir3/</Key></Object><Object><Key>dir2/dir3/file4</Key></Object><Object><Key>dir4/</Key></Object><Object><Key>dir4/file5</Key></Object><Object><Key>empty_dir/</Key></Object><Object><Key>empty_dir2/</Key></Object><Object><Key>file1</Key></Object><Object><Key>file2</Key></Object><Object><Key>invalidXml/folder1 !#$%&amp;&#39;&lt;&gt;*+,-.=?@[\^~_&#x9;</Key></Object><Object><Key>invalidXml/invalid���</Key></Object><Object><Key>zero</Key></Object></Delete>
-----------------------------------------------------
2020/10/12 19:01:28.841800 s3.DEBUG DEBUG: Response s3/DeleteObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml; charset=UTF-8
Date: Mon, 12 Oct 2020 19:01:28 GMT
...
```
However, bucket with `invalidXml/invalid\b\v\a` was not deleted.

**Expected behavior**
Ideally, bucket with invalid XML characters can be deleted (with configurable URL encoding, similar to `listObjects`).
Alternatively, the request should at least populate the error to user.

**Additional context**

**Comment by vudh1** [comment]
Closing this since it has been fixed.
