### ISSUE TITLE
List all-users from a single group

### ISSUE THREAD

**Issue by mohanvarupula** [aws/aws-sdk#274]
Hello!

Just wondering, is there any way we can list all the users under a single AWS SSO group using AWS-SDK python? I haven't seen any method available to list the users in the group. Furthermore, we are not able to retrieve the groups to which the user belongs to. Please let me know if there is a way to do this.

**Comment by tim-finnigan** [comment]
Hi @mohanvarupula thanks for reaching out. This kind of question would be best suited for a discussion in the boto3 (Python SDK) repository: https://github.com/boto/boto3/discussions/categories/q-a

But this may be the command you are looking for: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/identitystore.html#IdentityStore.Client.list_users
