### ISSUE TITLE
Deserialization fails on emrcontainers.ListVirtualClusters()

### ISSUE THREAD

**Issue by joaoubaldo** [aws/aws-sdk#276]
### Describe the bug

_(Note: As this seems to be related with the API model, I am opening a bug report)_

When calling `emrcontainers` client method `ListVirtualClusters` the following error is returned:
```operation error EMR containers: ListVirtualClusters, https response error StatusCode: 200, RequestID: 749a272c-5455-4497-XXXX-480d407cXXXX, deserialization failed, failed to decode response body with invalid JSON, expected Date to be a JSON Number, got string instead```

The error is being generated in [here](https://github.com/aws/aws-sdk-go-v2/blob/main/service/emrcontainers/deserializers.go#L3686-L3700). 
The `switch` statement is indeed expecting a Number only, whereas the API returns a date string in RFC 3339 format. Looking at other examples, such as [this](https://github.com/aws/aws-sdk-go-v2/blob/main/service/dataexchange/deserializers.go#L288-L299) and based on the [smithy documentation](https://awslabs.github.io/smithy/1.0/spec/core/model.html) about `timestamp` type, it seems the deserializer should be using `smithytime.ParseDateTime()` in this case.

### Expected Behavior

When calling `emrcontainers` client method [ListVirtualClusters](https://github.com/aws/aws-sdk-go-v2/blob/033964b520b943a3b3e15e9c795817900adb4733/codegen/sdk-codegen/aws-models/emr-containers.json#L1589-L1618) it is expected for the API response to be deserialized without errors and `*ListVirtualClustersOutput` object returned, when the HTTP status code is 200.

### Current Behavior

When calling `emrcontainers` client method `ListVirtualClusters` the following error is returned:
```operation error EMR containers: ListVirtualClusters, https response error StatusCode: 200, RequestID: 749a272c-5455-4497-XXXX-480d407cXXXX, deserialization failed, failed to decode response body with invalid JSON, expected Date to be a JSON Number, got string instead```

As such, the method returns a nil value for `*ListVirtualClustersOutput` and the above `err`.

### Reproduction Steps

1. Create `main.go` with:
```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/emrcontainers"
)

func main() {
	ctx := context.TODO()

	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion("eu-west-1"))
	if err != nil {
		os.Exit(1)
	}

	client := emrcontainers.NewFromConfig(cfg)
	out, err := client.ListVirtualClusters(ctx, &emrcontainers.ListVirtualClustersInput{})
	fmt.Printf("%v %v", out, err)
}
```

2. Run with `go run main.go`

### AWS Go SDK V2 Module Versions Used

```
module  mymodule

go 1.16

require (
	github.com/aws/aws-sdk-go-v2/config v1.15.7
	github.com/aws/aws-sdk-go-v2/service/emrcontainers v1.13.5
)
```

### Compiler and Version used

go version go1.17.5 darwin/amd64

### Operating System and version

macOS Monterey 12.2.1

**Comment by vudh1** [comment]
P70318725

**Comment by RanVaknin** [comment]
Issue resolved.

Thank you!
Ran~
