### ISSUE TITLE
Support WebIdentityToken or EksContainer as credential_source for assuming a role

### ISSUE THREAD

**Issue by chrisghill** [aws/aws-sdk#277]
**Is your feature request related to a problem? Please describe.**
I need to use an AWS config file as authentication parameters for an application running on an EKS node. In the AWS config file, I'd like to assume a role, but I want the `credential_source` to come from the `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` environment variables placed there by an IRSA role. Unfortunately, [according to the docs](https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-credential_source.html) the only valid options for `credential_source` are `Environment`, `Ec2InstanceMetadata`, or `EcsContainer`. It would be nice if there was an `EksContainer` or `WebIdentityToken` option as well.

I understand this is more of a request against the whole AWS credential specification, but I don't know where else to put the request. There is a similar request against botocore [here](https://github.com/boto/botocore/issues/2245).

**Describe the solution you'd like**
It would be nice if there was an `EksContainer` or `WebIdentityToken` option for `credential_source` in a `role_arn` credential type.

**Describe alternatives you've considered**
Technically you can get around this issue with a file as such:
```
[profile env]
role_arn=arn:aws:iam:012345678901:role/pod-role
web_identity_token_file=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

[default]
role_arn=arn:aws:iam::012345678901:role/cli-role
source_profile=env
```
But generating `[profile env]` credential block by pulling from the IRSA environment variables is bad experience. It would be preferable to reference them as the `credential_source`.

**Additional context**
Happy to help implement if this would be accepted.

**Comment by vudh1** [comment]
Closing this since team decided that this feature will not be implemented. Please use the above workaround for your solution.

**Comment by gurpalw** [comment]
Sorry, what's the work around?

I have a EKS container which gets `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` from its ServiceAccount.

This role needs has permissions to assume a role in up to 3 other AWS accounts. However currently this is not possible unless the AWS config file supports the EKS service account as a potential `credential_source` in the config profile.

please advise.

**Comment by tavin** [comment]
Hi @gurpalw according to @vudh1 and team, you should use a profile (`my-profile` here) configured along these lines:

    aws configure set role_arn "$AWS_ROLE_ARN"
    aws configure set web_identity_token_file "$AWS_WEB_IDENTITY_TOKEN_FILE"
    aws configure set profile.my-profile.source_profile default
    aws configure set profile.my-profile.role_arn arn:aws:iam::123456789:role/role-to-assume

Of course then your scripts aren't portable -- they're assumed to be running in EKS and won't work in another environment without modifying the above. For this reason I'm puzzled by the decision to close this issue.

Imho the way it should work is that you should be able to omit both `source_profile` and `credential_source` and in that case it should follow the "standard chain" for obtaining the primary credentials (EC2 metadata, all possible AWS_* environment variables, etc.). Short of that, reasonable alternatives might be that `credential_source=Environment` should consider the web identity environment variables, or that `credential_source=Standard` should follow the "standard chain" I just mentioned.

**Comment by gurpalw** [comment]
> Hi @gurpalw according to @vudh1 and team, you should use a profile (`my-profile` here) configured along these lines:
> 
> ```
> aws configure set role_arn "$AWS_ROLE_ARN"
> aws configure set web_identity_token_file "$AWS_WEB_IDENTITY_TOKEN_FILE"
> aws configure set profile.my-profile.source_profile default
> aws configure set profile.my-profile.role_arn arn:aws:iam::123456789:role/role-to-assume
> ```
> 
> Of course then your scripts aren't portable -- they're assumed to be running in EKS and won't work in another environment without modifying the above. For this reason I'm puzzled by the decision to close this issue.
> 
> Imho the way it should work is that you should be able to omit both `source_profile` and `credential_source` and in that case it should follow the "standard chain" for obtaining the primary credentials (EC2 metadata, all possible AWS_* environment variables, etc.). Short of that, reasonable alternatives might be that `credential_source=Environment` should consider the web identity environment variables, or that `credential_source=Standard` should follow the "standard chain" I just mentioned.

thanks for the reply.

https://github.com/aws/aws-sdk/issues/350
