### ISSUE TITLE
Turn off checksum validation for `DynamoDbClient`

### ISSUE THREAD

**Issue by LouieMiddleHawkeye** [aws/aws-sdk#279]
### Describe the feature

Similar to how with the `S3Client` you can pass in a `serviceConfiguration` where you can disable checksum validation it would be useful to be able to turn this off for the DynamoDbClient as well.

### Use Case

I have a test container integration test using LocalStack where occasionally the dynamo query throws a `Crc32MismatchException`. I have submitted and issue for this [here](https://github.com/localstack/localstack/issues/6105) for LocalStack, as I don't get this error when running my service on AWS. 

It would be useful still to be able to disable checksums for cases like this within unit and integration tests.

### Proposed Solution

Something along the lines of:

```
DynamoDbClient.builder()
            .endpointOverride(StringUtils.isNotBlank(endpoint) ? URI.create(endpoint) : null)
            .credentialsProvider(StringUtils.isNotBlank(endpoint) ? LOCAL_STACK_CREDENTIALS : null)
            .region(Region.of(clientConfig.getRegion()))
            .checksumValidationEnabled(false)
            .build();
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.17.190

### JDK version used

11

### Operating System and version

Windows 10 Pro 21H1

**Comment by debora-ito** [comment]
The DynamoDB team responded and said that they'll consider this feature request in future plans.

Since there's nothing more pending from the SDK team, I'll go ahead and close this.
