### ISSUE TITLE
Support waiting form import-snapshot with 'aws ec2 wait...'

### ISSUE THREAD

**Issue by nickbroon** [aws/aws-sdk#282]
### Describe the feature

It would be useful to be able to wait for a snapshot import task to complete.

### Use Case

Importing a snapshot is long a running operation, and currently I have to poll the import task to determine when it complete, with something like the below:

``` shell
import_task_id=$(aws ec2 import-snapshot ... --query 'ImportTaskId' --output text)

# Wait for snapshot completion
while true; do
  import_task_status_command="aws ec2 describe-import-snapshot-tasks --import-task-ids ${import_task_id} --query 'ImportSnapshotTasks[0].SnapshotTaskDetail.Status' --output text"
  echo "Running command: ${import_task_status_command}"
  import_task_status=$(${import_task_status_command})
  echo "Import task [${import_task_id}] status is [${import_task_status}]."

  if [[ "$import_task_status" == "completed" ]]; then
    echo "Completed, exiting..."
    break
  elif [[ "$import_task_status" == "pending" ]]; then
    echo "Waiting 1 minute..."
    sleep 60
  else
    echo "Error, exiting..."
    exit 1
  fi
done
```

Having a wait command for the import would be simpler, and hopefully less error prone.

### Other Information

While there is a [`aws ec2 wait snapshot-completed`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/wait/snapshot-completed.html) command, this requires the snapshotId, which when importing a snapshot is not available until after the import is completed.

So an equivalent command to wait for a snapshot import would be very useful.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.25.6 2.7.7

### Environment details (OS name and version, etc.)

Debian Bullseye

**Comment by tim-finnigan** [comment]
P65768387

**Comment by breisig** [comment]
I have been waiting for the *same* feature for a long time to add a "--wait-until-completed" option to the 'aws ec2 import-snapshot' command. I would rather have the importing 'wait' until its completely done importing before returning back to the command line.

**Comment by tim-finnigan** [comment]
I was informed that the EC2 team has created a `SnapshotImported` waiter that should be released soon.

**Comment by breisig** [comment]
@tim-finnigan Are you saying the feature will be added to AWS Cli 2.9.24? Will it be a parameter feature added?

**Comment by tim-finnigan** [comment]
I would expect it to be added by that version but can't guarantee for sure. You can check for updates to the CLI changelog: https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst. A wait command would get added here: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/wait/index.html
