### ISSUE TITLE
Add service API for retrieving AWS account tax information

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#283]
Original issue: https://github.com/boto/boto3/issues/3296

**Comment by tim-finnigan** [comment]
P65770928

**Comment by tim-finnigan** [comment]
The team that I reached out to said that Public APIs for tax settings are currently under development. The APIs may be available later this year but we can't guarantee any timelines. Please feel free to check in for updates on this in the future.

**Comment by wcoleman** [comment]
I was wondering if there was any update on this issue?
