### ISSUE TITLE
Paginators for Route53 ResourceRecordSets

### ISSUE THREAD

**Issue by felixdesouza** [aws/aws-sdk#285]
**Is your feature request related to a problem? Please describe.**
Iterating through `ResourceRecordSets` via the Route 53 API requires paging. I quite liked the paginators that exist for other resource listing operations and I was surprised when it didn't have one.

**Describe the solution you'd like**
A generated paginator for `ListResourceRecordSets`.

**Describe alternatives you've considered**
To get around it I could have looped and checked for the conditions myself inline, but because I wanted to keep the paginator abstraction, I instead made a handwritten version of the generated paginators. 

**Additional context**
I imagine the difficulty is that there are two components to the token i.e. `StartRecordName` and `StartRecordType`. So it's unclear what would go into the `paginator.json`:

```json
{
  "ListResourceRecordSets": {
    "input_token": "StartRecordIdentifier|StartRecordName|StartRecordType", // how to incorporate these?
    "limit_key": "MaxItems",
    "more_results": "IsTruncated",
    "output_token": "NextRecordIdentifier|NextRecordName|NextRecordType", // how to incorporate these?
    "result_key": "ResourceRecordSets"
  }
}
```

If they all have to be set and that this is the only blocker to having auto generated pagination for this endpoint, I imagine changing the parser for the `paginator.json` to take some field like:

```json
{
  "ListResourceRecordSets": {
    "input_output_tokens": {
      "StartRecordIdentifier": "NextRecordIdentifier",
      "StartRecordName": "NextRecordName",
      "StartRecordType": "NextRecordType"
    }
    ... other fields
  }
}
```

Where we map input tokens to output tokens etc. Everything else from what I've seen can be trivially changed to support this syntax if supporting both is not ideal.

Curious for your thoughts!

**Comment by vudh1** [comment]
P70316690

**Comment by RanVaknin** [comment]
We added a customization for this.
This is now fixed.
