### ISSUE TITLE
Configure environment properties for Addons like VPC-CNI addon > 1.9.0

### ISSUE THREAD

**Issue by Skarlso** [aws/aws-sdk#286]
**Is your feature request related to a problem? Please describe.**

As of 1.9.0 of the VPC-CNI plugin, it's possible to set some environment properties on the daemon-set to allocate more IP addresses described [here](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html).

This is currently not possible with the SDK either post creation by using EKS Endpoint to set environment properties OR while creating the Addon.

The eksctl team would like to add this feature, but we can't until this is possible through the Go SDK.

Tracked here in `eksctl` repo: https://github.com/weaveworks/eksctl/issues/4351

**Comment by vudh1** [comment]
Closing this as service team decided that this feature will require some breaking changes.

**Comment by Skarlso** [comment]
So... release it with a major version update? Just because a feature requires a breaking change, doesn't mean that you will never do it. I'm not following the logic here.
