### ISSUE TITLE
ECR scan shows Status "COMPLETE" when enhanced findings are not there yet

### ISSUE THREAD

**Issue by PB-TW** [aws/aws-sdk#289]
Using this code, we are waiting in our pipeline for the ecr image scan to be completed. The configuration for scanning is ENHANCED and SCAN_ON_PUSH.

```
max_retries=50
retries=0

SCAN=$(aws ecr describe-image-scan-findings --repository-name repo --image-id imageTag=latest)

while [[ -z "$SCAN" ]]; do
  sleep 5
  retries=$((retries+1))
  if [[ $retries == $max_retries ]]; then
    exit 1
  fi
  SCAN=$(aws ecr describe-image-scan-findings --repository-name repo --image-id imageTag=latest)
done

SCAN_FINDINGS=$(echo $SCAN | jq '.imageScanFindings.findingSeverityCounts')
echo $SCAN_FINDINGS

if [ $SCAN_FINDINGS == null ]; then
  echo $SCAN
fi
```

After 4-5 retries, the script terminates, $SCAN_FINDINGS is null. The result of the final echo is the following, with no findings, no enhanced findings, no findingSeverityCounts etc., but with status COMPLETE.

```
{
  "imageScanFindings": {
    "findings": []
  },
  "registryId": "registry",
  "repositoryName": "repo",
  "imageId": {
    "imageDigest": "...",
    "imageTag": "latest"
  },
  "imageScanStatus": {
    "status": "COMPLETE",
    "description": "The scan was completed successfully."
  }
}
```

After waiting for some seconds and running the script again, we have a list of findings, status still being COMPLETE. This status is misleading and should only be COMPLETE if the scan report does not change anymore.

Might be related to https://github.com/aws/aws-sdk/issues/288 and https://github.com/aws/aws-sdk/issues/139

**Comment by tim-finnigan** [comment]
Closing per https://github.com/aws/aws-sdk/issues/288#issuecomment-1215904153.
