### ISSUE TITLE
Ability to create an EMR cluster with gp3 volume type

### ISSUE THREAD

**Issue by dimisjim** [aws/aws-sdk#29]
Yesterday gp3 was made generally available: 

It seems however that it is not yet supported in EMR:

```
$ aws emr create-cluster \
    ...
    --release-label emr-6.1.0 \
    --instance-groups 'InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m5.xlarge,EbsConfiguration={EbsOptimized=true,EbsBlockDeviceConfigs=[{VolumeSpecification={VolumeType=gp3,SizeInGB=10}}]}'

An error occurred (ValidationException) when calling the RunJobFlow operation: Invalid EBS volume type.
```

I understand that this is linked to the RunJobFlow AWS API. Any ETA on when this will be enabled?
Thanks!

**Comment by kdaily** [comment]
P42249993

**Comment by jonjohnston** [comment]
@kdaily any update on the availability of this? this is a critical blocker us

**Comment by barakmalki** [comment]
Hi @kdaily, any update for the availability? this is also a critical blocker for us as well

**Comment by zhongyu211** [comment]
@kdaily any update on the availability of this? this is a critical blocker us

**Comment by kdaily** [comment]
Hi @jonjohnston @barakmalki @zhongyu211 - I requested an update from the EMR team, I have not heard anything back. I appreciate your patience.

**Comment by ibzx** [comment]
Is there any update on this @kdaily ?

**Comment by ryan-25** [comment]
As of 16/06/21 "gp3 support for EMR is in the pipeline, I do not have an ETA for this feature request."
Not too promising being told its in the pipeline with no ETA from that it seems to not be in progress or close to it. Coming up to a year now of this feature being out :/

**Comment by britishbadger** [comment]
Any updates to this one ?

**Comment by kdaily** [comment]
@britishbadger @ibzx, unfortunately no update to report.

**Comment by kdaily** [comment]
Hi all,

The EMR team is in the process of validating the gp3 volume types for use in the service. I've been told that the EMR team is working on this as a priority. The current plan it to be able to offer this in 2021 but don't have an exact launch date to share with you at this time.

While I understand if transitioning is not possible, as a possible workaround, the EMR team let me know that gp3 volumes are currently supported if you are running EMR on EKS. You can read more about that setup here:

https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks.html

**Comment by meetup-sergii-chukhno** [comment]
hi EMR team, 

getting following error "An error occurred (ValidationException) when calling the RunJobFlow operation: Invalid EBS volume type." when trying to configure "VolumeType":"gp3" with 
--release-label emr-6.1.0 and "InstanceType":"r6g.2xlarge"

Thanks in advance for your help!

**Comment by kdaily** [comment]
Hi @meetup-sergii-chukhno,

See my above comment acknowledging that the EMR team is aware of the issue. I don't have any further information at this time!

https://github.com/aws/aws-sdk/issues/29#issuecomment-895563444

**Comment by meetup-sergii-chukhno** [comment]
Thanks @kdaily 
Yeah I saw it. I just thought there are some updates regarding this issue.

**Comment by dstockstad** [comment]
I can confirm that this still doesn't work as of today 4th of November.

**Comment by mtesch-um** [comment]
I can confirm that this still doesn't work as of today 15th of December, 2021.

**Comment by kdaily** [comment]
Hi all, thanks for your patience. I received an update from the EMR team.

> The EMR team is planning to support GP3 with a default throughput of 125MB/s this month, February 2022. Later this year, the throughput will be configurable as a parameter.

**Comment by gordon1992** [comment]
I was able to create a cluster with a GP3 volume! Now that GP3 volumes are supported the main blocker to their use would be the default throughput which is half GP2's maximum. Is there a more concrete ETA for the addition of a parameter to configure the throughput? Would I be correct in assuming that this is likely to be added to [VolumeSpecification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification.html)?

**Comment by dacort** [comment]
EMR team member here. This is now supported in the API with the ability to define throughput as well. The various SDKs and CLIs are still in the process of being updated, but here's an AWS CLI v1 example (various parameters omitted for clarify):

```bash
aws emr emr create-cluster \
    --applications Name=Spark Name=Hadoop Name=Livy Name=JupyterEnterpriseGateway \
    --release-label emr-6.6.0 \
   ...
    --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":50,"VolumeType":"gp3","Throughput": 300},"VolumesPerInstance":2}]},"InstanceGroupType":"MASTER","InstanceType":"m5.xlarge","Name":"master"},{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":50,"VolumeType":"gp3","Throughput": 300},"VolumesPerInstance":2}]},"InstanceGroupType":"CORE","InstanceType":"m5.xlarge","Name":"slave"}]' \
```

```json
[
    {
        "InstanceCount": 1,
        "EbsConfiguration": {
            "EbsBlockDeviceConfigs": [
                {
                    "VolumeSpecification": {
                        "SizeInGB": 50,
                        "VolumeType": "gp3",
                        "Throughput": 300
                    },
                    "VolumesPerInstance": 2
                }
            ]
        },
        "InstanceGroupType": "MASTER",
        "InstanceType": "m5.xlarge",
        "Name": "master"
    },
    {
        "InstanceCount": 1,
        "EbsConfiguration": {
            "EbsBlockDeviceConfigs": [
                {
                    "VolumeSpecification": {
                        "SizeInGB": 50,
                        "VolumeType": "gp3",
                        "Throughput": 300
                    },
                    "VolumesPerInstance": 2
                }
            ]
        },
        "InstanceGroupType": "CORE",
        "InstanceType": "m5.xlarge",
        "Name": "slave"
    }
]
```

CloudFormation and Console support is still pending.

**Comment by shubhamsetia05** [comment]
@dacort Hi, can you please confirm whether gp3 support for EMR is available in Mumbai region (ap-south-1) or not? I tried to clone an EMR cluster but can't see gp3 available for Mumbai region.

**Comment by dacort** [comment]
@shubhamsetia05 If you were trying to clone the cluster in the Console, the ability to add gp3 volumes is not supported there yet. :( You'll have to start the cluster via the API with a configuration similar to the one I posted above.

**Comment by praetp** [comment]
I confirm it works in eu-west-1.

**Comment by dacort** [comment]
I was able to use this command in `ap-south-1`, although it did not accept `Throughput` for some reason and I had to use `Iops` instead.

```bash
aws emr create-cluster --name "gp3" \
    --region ap-south-1 \
    --release-label emr-6.6.0 \
    --applications Name=Spark Name=Livy Name=JupyterEnterpriseGateway \
    --use-default-roles \
    --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":50,"VolumeType":"gp3","Iops": 3000},"VolumesPerInstance":2}]},"InstanceGroupType":"MASTER","InstanceType":"m5.xlarge","Name":"master"},{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":50,"VolumeType":"gp3","Iops": 3000},"VolumesPerInstance":2}]},"InstanceGroupType":"CORE","InstanceType":"m5.xlarge","Name":"slave"}]'
```

**Comment by YevhenKv** [comment]
Is there a way to switch root volume to GP3 too?

**Comment by tim-finnigan** [comment]
Now that gp3 is a supported volume type I think this issue can be closed. Here is the documentation: https://docs.aws.amazon.com/emr/latest/APIReference/API_VolumeSpecification.html

<img width="649" alt="image" src="https://user-images.githubusercontent.com/87778557/219156598-c39e64b6-0aa6-400d-904b-e88a2b9a2544.png">

For additional questions please consider asking through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan or by opening another GitHub issue. Thanks!

**Comment by madhur** [comment]
> Is there a way to switch root volume to GP3 too?

I am having the same issue. How do we switch root volume to gp3?

**Comment by RajasGujarathi** [comment]
We are using AWS CDK, in turn, CLoudformation, and on launching the EMR cluster it launches EC2 instances with `gp2` volume. Is there a way to make the root volume use `gp3` instead of `gp2`

**Comment by dacort** [comment]
Unfortunately, gp3 is not supported for the root volume at launch, but you can do a post-launch update of the root volumes to gp3 using something like:

```
aws ec2 modify-volume --volume-type gp3 --volume-id vol-11111111111111111
```

**Comment by dacort** [comment]
Sorry no ETA.

**Comment by thisiskush** [comment]
Hi @dacort 

Any updates on gp3 support at launch ?

**Comment by dacort** [comment]
This is now supported at launch. For [CloudFormation](https://docs.aws.amazon.com/emr/latest/APIReference/API_Cluster.html) there are the various `EbsRootVolume` properties and the [CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/emr/create-cluster.html) similarly has several `--ebs-root-volume` options. 

This is only supported on EMR 6.15.0 and up.
