### ISSUE TITLE
Incorrectly empty `SecurityGroupRules` array in successful result from `ec2 authorize-security-group-egress`

### ISSUE THREAD

**Issue by danfuzz** [aws/aws-sdk#298]
### Describe the bug

A successful call to `ec2 authorize-security-group-egress` should be expected to return a list of rule descriptions in the result, bound to `SecurityGroupRules`, but it doesn't seem to actually do that.

### Expected Behavior

Each of the rules defined by the arguments gets returned in the results. E.g., here's what should be expected from the repro script:

```
$ ./egress-bug 
Group ID: sg-xxxxxxxx
{
    "Return": true,
    "SecurityGroupRules": [
        {
            "SecurityGroupRuleId": "...",
            ...
        }
    ]
}
```

### Current Behavior

No rules are reported in the results, despite the fact that rules are created. E.g., here's the behavior of the repro script:

```
$ ./egress-bug 
Group ID: sg-xxxxxxxx
{
    "Return": true,
    "SecurityGroupRules": []
}
```

### Reproduction Steps

Here's a script to reproduce the problem. See above sections for expected and actual results.

```bash
#!/bin/bash

# Replace with a valid VPC ID.
vpcId='vpc-xxxxxxxx'

groupId="$(
aws ec2 create-security-group --output json --region us-west-2 \
    --description test --group-name test --vpc-id "${vpcId}" \
| jq --raw-output '.GroupId'
)"

echo "Group ID: ${groupId}"

aws ec2 authorize-security-group-egress --output json --region us-west-2 \
    --group-id "${groupId}" --port 22 --protocol tcp
```

### Possible Solution

I have no idea what's causing this problem; sorry.

### Additional Information/Context

I tried passing arguments both as plain arguments and JSON, and that didn't seem to make a difference.

### CLI version used

aws-cli/2.6.1 Python/3.9.12 Darwin/21.5.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 12.4

**Comment by tim-finnigan** [comment]
P67153136

**Comment by danfuzz** [comment]
Thanks so much!

**Comment by tim-finnigan** [comment]
Hi @danfuzz, wanted to let you know that the documentation has been updated to help clarify this behavior: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupEgress.html. I've created a separate internal ticket for addressing the request to add an error message for this.

**Comment by tim-finnigan** [comment]
P69090743

**Comment by danfuzz** [comment]
Much obliged!

**Comment by tim-finnigan** [comment]
I heard back from the EC2 team and they said that given how long this has been in production, customers may be relying on the current behavior. Returning a client error would break those customers' workflows. Teams managing APIs have to be very careful to maintain strict backwards compatibility for that reason. The documentation update mentioned earlier is the best that can be done at this time. Thanks again for bringing this to our attention.
