### ISSUE TITLE
CreateFlowLogs API missing `Unsuccessful` from response in us-east-1

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#299]
Original issue: https://github.com/boto/boto3/issues/3327

**Comment by tim-finnigan** [comment]
P67379580

**Comment by mokshagna517** [comment]
> P67379580

Hi @tim-finnigan !! Is this an epoch for the deployment of the fix? Or could you let me know please when this will be closed?
Thanks!!

**Comment by tim-finnigan** [comment]
Hi @mokshagna517 thanks for checking in. That is actually a reference to an internal ticket for tracking this issue. The EC2 team has approved a fix for this but it still has to be deployed. The deployment should happen in the near future. I will update this issue when I have more information.

**Comment by mokshagna517** [comment]
Thanks for the info !!

**Comment by ttretau** [comment]
Hi @tim-finnigan , seems that response does behave like before again.
Thanks for opening this one!

**Comment by tim-finnigan** [comment]
Thanks @ttretau for letting me know! I just got confirmation from the team that the fix has been deployed to all regions so I'll go ahead and close this issue.
