### ISSUE TITLE
Cloudformation StackSet Wait steps

### ISSUE THREAD

**Issue by L00162772** [aws/aws-sdk#300]
### Describe the feature

Would it be possible to get wait options in the cloudformation command section for StackSets.
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/wait/index.html#cli-aws-cloudformation-wait

The wait commands are there at the minute for Stacks just

### Use Case

I need to wait until a stackset is created before proceeding - this option is not available currently with stacksets

### Proposed Solution

Implement wait steps for StackSets to match what is in place for stacks

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

V2 latest

### Environment details (OS name and version, etc.)

MAC OS

**Comment by tim-finnigan** [comment]
P67582390

**Comment by tivanov-qb** [comment]
We are also looking for a wait option when creating/updating stack instances. @tim-finnigan is this something you are planning to release ? the current workaround is to use list-stack-instances API and to loop over their statuses. However, I'm worried about reaching max retires, similar to:  An error occurred (ThrottlingException) when calling the DescribeParameters operation (reached max retries: 4): Rate exceeded
Having said the above, having wait on create/update stack instances will be the most suitable one. Thanks!

**Comment by savagete2860** [comment]
Bump. Ironically stilll waiting on a waiter. Any idea what the deal is with this?

**Comment by createchange** [comment]
+1, also needing this.

**Comment by tim-finnigan** [comment]
Thanks all for your patience here. We have heard back from the CloudFormation team and were informed that this feature request is on their roadmap but not currently prioritized. We cannot provide guarantees as to if or when service teams implement feature requests but you can track the [CHANGELOGs](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) and [blogs](https://aws.amazon.com/blogs/aws/category/management-tools/aws-cloudformation/) for updates.

**Comment by createchange** [comment]
FWIW, here is what I implemented in a CI/CD pipeline and it is working well:

```
operation_id=$(aws cloudformation create-stack-instances \
--stack-set-name $STACK_NAME \
--deployment-targets OrganizationalUnitIds=<redacted>,Accounts=<redacted>,AccountFilterType=INTERSECTION \
--regions us-east-1 \
--call-as DELEGATED_ADMIN \
--query "OperationId" \
--output text)

while true; do
  status=$(aws cloudformation describe-stack-set-operation \
    --stack-set-name s3-server-access-log-configurator \
    --call-as DELEGATED_ADMIN \
    --operation-id "$operation_id" \
    --query "StackSetOperation.Status" \
    --output text)

  if [ "$status" = "SUCCEEDED" ]; then
    echo "Stack set operation succeeded."
    break
  elif [ "$status" = "QUEUED" ] || [ "$status" = "RUNNING" ]; then
    echo "Stack set operation is still in progress. Status: $status"
    sleep 10
  else
    echo "Stack set operation failed. Status: $status"
    echo "View status in CloudFormation console."
    exit 1
  fi
```
