### ISSUE TITLE
GetResources API returning previously tagged resources

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#302]
Question raised in this issue: https://github.com/boto/boto3/issues/3341

> What is the purpose of "previously tagged"? How do we turn that off? What is the use case for querying whether a resource ever had a specific tag and would you not want to know when and for how long?

**Comment by tim-finnigan** [comment]
test

**Comment by tim-finnigan** [comment]
I heard back and was given this explanation: The intended use case of the GetResources API is to be able to fetch the tagged resources which are currently active. But due to the inherent design of the API, services with taggable resources should be onboarded to an internal tag mangement service to be able to get the up-to-date resources associated with the tag. As there exists some services which aren't onboarded, sometimes we get stale resources as part of the response. To capture this document has the wording "previously tagged". 

But very few taggable resources are currently not onboarded to that internal tag management service. Hence only in very rare cases customer can see previously tagged resources when a resource is deleted. And if you always perform Create resource -> Tag -> Untag -> Remove resource then you should never see previously tagged resources in the result of GetResources.

**Comment by rbarad** [comment]
Is there any way to filter out the deleted resources from the results
