### ISSUE TITLE
Cognito Migrate User Between Pools

### ISSUE THREAD

**Issue by ahurlburt** [aws/aws-sdk#303]
### Describe the feature

Support a single command / API in cognito-idp to support migrating a user pool from one pool to another (without forcing them to reset their password).

### Use Case

Cognito user pools are great but there are many properties that cannot be changed once the pool is created. Several times now I've found instances where I'd need/like to set a property that cannot be changed and this creates a problem when there are users in the pool (and it's a production app).

The current solutions are 
- export and do an import and reset everyones password (poor user experience)
- create a migration lambda (cumbersome and time consuming)

This exact situation just happened to me when I received a customer support ticket that a custom cannot login and found out the user pool is set to be case-sensitive which is the default for cloudformation but not for the console. This property cannot be changed.

It would be highly beneficial to be able migrate users seamlessly from one pool to another.

### Proposed Solution

It's understandable that cognito would not expose plain text passwords which is why the export / import doesn't work seamlessly but cognito must know the encrypted password so I would expect that can be transferred over aws servers along wtih all user data into a new pool. But I didn't develop cognito so that's just an assumption, seems like something should go in this box.

### Other Information

I'm not sure if this is the best place for this request, I'd prefer it to be part of the API and built in to the appropriate sdk's rather than cli but I couldn't figure out the git repo for cognito itself. It would be nice for it to also be part of cli though.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.2.23

### Environment details (OS name and version, etc.)

Mac OS 11.6

**Comment by tim-finnigan** [comment]
We heard back from a member of the Cognito team. They have noted this feature request but it isn't planned on their roadmap at this time. For future updates we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/), or feel free to check back in here as well.
