### ISSUE TITLE
quiet output eks create-nodegroup

### ISSUE THREAD

**Issue by zencircle** [aws/aws-sdk#304]
### Describe the feature

We would like add quiet option to creating eks nodegroups
https://docs.aws.amazon.com/cli/latest/reference/eks/create-nodegroup.html

### Use Case

We have to  create a lot of nodegroups via  aws cli. Output is always paginated and I have to end (in vi commands). 

### Proposed Solution

```
aws eks create-nodegroup \
--cluster-name test1 \
--nodegroup-name test-nodegroup \
--scaling-config minSize=2,maxSize=2,desiredSize=2 \
--subnets subnet-12345  \
--instance-types m5.2xlarge \
--node-role arn:aws:iam::XXX:role/hmda-eks-role \
--only-show-errors ( or --quiet)
```

### Other Information

aws --version
aws-cli/2.4.20 Python/3.9.10 Darwin/20.6.0 source/x86_64 prompt/off

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.4.20

### Environment details (OS name and version, etc.)

MacOS

**Comment by tim-finnigan** [comment]
P68090726

**Comment by tim-finnigan** [comment]
We just heard back from a member of the team and the recommendation provided was to use the `--no-paginate` parameter. If that does not work for your use case please let us know why and we can revisit this.
