### ISSUE TITLE
AWS Shield API docs for enable-application-layer-automatic-response wrong

### ISSUE THREAD

**Issue by nodomain** [aws/aws-sdk#308]
### Describe the bug

The [docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/shield/enable-application-layer-automatic-response.html) state:

> Note
> This feature is available for Amazon CloudFront distributions only.

However, the respective API call works successfully for an ALB resource and the feature is added to the ALB as expected.

### Expected Behavior

The note is removed or extended to state that also ALBs are supported.

### Current Behavior

ALBs are supported, but the docs state otherwise.

### Reproduction Steps

Execute this command:

```bash	
AWS_PROFILE=myprofile aws shield enable-application-layer-automatic-response --resource-arn arn:aws:elasticloadbalancing:us-east-1:123123123123:loadbalancer/app/name-of-alb/1a2b3c4d --action Block={} --region us-east-1
```

Check the AWS console for a successful mitigation setup.

### Possible Solution

Remove or extend the note.

### CLI version used

aws-cli/2.7.4 Python/3.9.13 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS 12.5

**Comment by tim-finnigan** [comment]
P68496560

**Comment by tim-finnigan** [comment]
I heard back from the team and the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/shield/enable-application-layer-automatic-response.html) has been updated to note support for Application Load Balancers as well as Cloudfront distributions. Thanks again for bringing this to our attention!
