### ISSUE TITLE
AWS Glue: Add support for Python 3.8+

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#313]
Raised by customer here: https://github.com/boto/boto3/discussions/3376

**Comment by tim-finnigan** [comment]
P69075920

**Comment by BasLaanPAM** [comment]
Hi @tim-finnigan, thank you for opening this issue here. Do you have an update on when this issue can be looked into?

**Comment by tim-finnigan** [comment]
Hi @BasLaanPAM thanks for following up. I just pinged the Glue team for an update and they told me that Python 3.9+ is now supported as of just a few days ago per this blog post announcement: https://aws.amazon.com/blogs/big-data/aws-glue-python-shell-now-supports-python-3-9-with-a-flexible-pre-loaded-environment-and-support-to-install-additional-libraries/. Does this address your feature request?

**Comment by BasLaanPAM** [comment]
@tim-finnigan good news, thank you! This will do, we will be upgrading to Python 3.9 then.

**Comment by tim-finnigan** [comment]
Thanks for following up, I'll go ahead and close this issue then. If you run into any more issues related to this then please let us know.
