### ISSUE TITLE
Add Update/Delete API functionlity for kafkaconnect worker configurations

### ISSUE THREAD

**Issue by eliax1996** [aws/aws-sdk#319]
### Describe the bug

I am constructing a CI/CD pipeline that spawns custom connectors (JVM workers) on MSK, they require to be launched with a custom worker configuration.
I tried to search on the source code of `aws-cli` and the [doc](https://docs.aws.amazon.com/cli/latest/reference/kafkaconnect/index.html#cli-aws-kafkaconnect) but seems that isn't possible to delete a worker configuration but only [create a new one](https://docs.aws.amazon.com/cli/latest/reference/kafkaconnect/create-worker-configuration.html#options).
How can I delete/update a custom configuration when I have to update the worker's config? 

There is any solution to this problem? If not, there is the possibility to contact the `kafka connect` team to understand if is possible to implement this feature?

### Expected Behavior

being able to delete and update a worker configuration (at least when there are no connectors that are using a certain configuration)

### Current Behavior

It is possible only to create a new worker configuration

### Reproduction Steps

going to the documentation page available [here](https://docs.aws.amazon.com/cli/latest/reference/kafkaconnect/index.html#cli-aws-kafkaconnect) and view that there is only `create-worker-configuration` command and not the `delete` or `update` one

### Possible Solution

Implement an update/delete api

### CLI version used

aws-cli/2.5.5 Python/3.9.12 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Monterey 12.5

**Comment by tim-finnigan** [comment]
P69222695

**Comment by tim-finnigan** [comment]
I just heard back from a member of the MSK team. They said that the updating/deletion of worker configurations from MSK Connect is not currently supported but that capability is on the roadmap. I can't give a definite timeline but feel free to check back here in the future. If you need to delete resources to avoid service limits (which default to 100 resources per region per [this documentation](https://docs.aws.amazon.com/msk/latest/developerguide/limits.html)), please raise contact [AWS Support](https://aws.amazon.com/contact-us/) to request a limit increase in the meantime.

**Comment by ssakuh** [comment]
Hi @tim-finnigan,
Could you please reach out again to MSK team about this?

**Comment by tim-finnigan** [comment]
Hi @ssakuh - I reached out for an update and can confirm that the MSK team is still tracking this request. We can't share specific timelines but I would expect some traction on this in the coming months.

**Comment by miguelzenteno** [comment]
why is it closed if it hasn't been fixed or released yet? is there an open issue to follow this?

**Comment by tim-finnigan** [comment]
This feature request is still being tracked internally and on the service team's roadmap. It was escalated to the MSK Connect team and closed here because the SDK teams do not directly implement service API requests. You can reach out through [AWS Support](https://aws.amazon.com/contact-us/) for more information, review [blog posts](https://aws.amazon.com/blogs/aws/) for new announcements, or refer to SDK changelogs for updates related to this.

**Comment by michal-kosinski** [comment]
https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-msk-connect-deleting-worker-configurations-tagging-resources/
