### ISSUE TITLE
Redshift Data API Service: Problem with bool and float4 columns

### ISSUE THREAD

**Issue by aBurmeseDev** [aws/aws-sdk#321]
Original Issue: [boto/boto3#3366](https://github.com/boto/boto3/issues/3366/)

**Comment by aBurmeseDev** [comment]
P69276557

**Comment by aBurmeseDev** [comment]
Update from Redshift API team:

> CR is currently in preprod I'll post an update when it reaches the production regions. I believe CX is in us-west-2. I'll post an update when it reaches prod regions and specifically when it reaches us-west-2.

**Comment by dburtsev** [comment]
I am on us-east-1

**Comment by aBurmeseDev** [comment]
Noted, I believe they were referring to another user that's having same issue. I will definitely let them know that we need updates for us-east-1 as well.

**Comment by aBurmeseDev** [comment]
Hi @dburtsev, thank you for your patience.

We have an update from Redshift API team that the fix was released for us-east-1, as of today. Please feel free to reach back out to us if you have any other questions!

> The fix is currently out for roughly half the production regions with the fix being enabled everywhere by September 28th. For specific regions us-east-1 currently has the fix.

**Comment by dburtsev** [comment]
The issue with boolean and float4 is fixed.

**Comment by aBurmeseDev** [comment]
Awesome, thanks for confirming. I'm going to close the issue now.
