### ISSUE TITLE
Redshift Data API Service: Problem with pg_last_copy_count() and pg_last_query_id()

### ISSUE THREAD

**Issue by dburtsev** [aws/aws-sdk#322]
1. pg_last_query_id(). Amazon Redshift maintains insert execution steps for INSERT queries in STL_INSERT system table. We can query this table to get rows inserted in the last insert statement. boto3.client('redshift-data') return None after insert.

CREATE TABLE dev.test10 (id INTEGER IDENTITY, strng VARCHAR(256));

```
import boto3

def ExecuteNonQuery(Boto3Client,ClusterIdentifier,Database,DbUser,Sql):
rows = 0
Response1 = Boto3Client.execute_statement(ClusterIdentifier=ClusterIdentifier,Database=Database,DbUser=DbUser,Sql=Sql)
Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
while Response2['Status'] in ['PICKED', 'STARTED', 'SUBMITTED']:
Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
if Response2['Status'] != 'FINISHED':
print("Expect FINISHED got " + Response2['Status'])
raise ValueError("Expect FINISHED got " + Response2['Status'] + ' ' + Response2['Error'])
Response1 = Boto3Client.execute_statement(ClusterIdentifier=ClusterIdentifier,Database=Database,DbUser=DbUser,Sql='select sum(rows) as inserted_rows from stl_insert where query=pg_last_query_id();')
Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
while Response2['Status'] in ['PICKED', 'STARTED', 'SUBMITTED']:
Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
Response3 = sql_client.get_statement_result(Id=Response1['Id'])
rows = Response3['Records'][0][0].get('longValue')
print(Response3['Records'])
return rows

sql_client = boto3.client('redshift-data', region_name = 'us-east-1')
sql = "INSERT INTO dev.test10 (strng) VALUES ('abc2'),('qwe2');"
ClusterIdentifier = 'abc'
Database = 'xyz'
DbUser = 'qwe'
i = ExecuteNonQuery(sql_client,ClusterIdentifier,Database,DbUser,sql)
print(I)
```
2. pg_last_copy_count() Returns the number of rows that were loaded by the last COPY command run in the current session.
boto3 returns 0

```
import boto3

def ExecuteCopy(Boto3Client,ClusterIdentifier,Database,DbUser,Sql):
    boto3.set_stream_logger('')
    rows = 0
    Response1 = Boto3Client.execute_statement(ClusterIdentifier=ClusterIdentifier,Database=Database,DbUser=DbUser,Sql=Sql)
    Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
    while Response2['Status'] in ['PICKED', 'STARTED', 'SUBMITTED']:
        Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
    if Response2['Status'] != 'FINISHED':
        print("Expect FINISHED got " + Response2['Status'])
        raise ValueError("Expect FINISHED got " + Response2['Status'] + ' ' + Response2['Error'])
    Response1 = Boto3Client.execute_statement(ClusterIdentifier=ClusterIdentifier,Database=Database,DbUser=DbUser,Sql='select pg_last_copy_count();')
    Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
    while Response2['Status'] in ['PICKED', 'STARTED', 'SUBMITTED']:
        Response2 = Boto3Client.describe_statement(Id=Response1['Id'])
    Response3 = sql_client.get_statement_result(Id=Response1['Id'])
    rows = Response3['Records'][0][0].get('longValue')
    print(Response3['Records'])
    return rows

sql_client = boto3.client('redshift-data', region_name = 'us-east-1')
ClusterIdentifier = 'qwe'
Database = 'qwe'
DbUser = 'qwe'
sql = "COPY dev.copy_test FROM 's3://mocsdw01/adhoc/copy_test.csv' FILLRECORD REMOVEQUOTES ESCAPE;"

i = ExecuteCopy(sql_client,ClusterIdentifier,Database,DbUser,sql)
print(i)
```

**Comment by tim-finnigan** [comment]
Adding your debug logs from related issues:
[pg_last_copy_count.txt](https://github.com/aws/aws-sdk/files/9338388/pg_last_copy_count.txt)
[pg_last_query_id.txt](https://github.com/aws/aws-sdk/files/9338389/pg_last_query_id.txt)

**Comment by tim-finnigan** [comment]
@dburtsev can you confirm that the behavior you're seeing is inconsistent with this documentation?

- https://docs.aws.amazon.com/redshift/latest/dg/PG_LAST_COPY_COUNT.html
- https://docs.aws.amazon.com/redshift/latest/dg/PG_LAST_QUERY_ID.html

If so can you please

**Comment by dburtsev** [comment]
Yes, it is inconsistent with AWS documentation.

**Comment by tim-finnigan** [comment]
Thanks for confirming, I just reached out to the Redshift team regarding this and will update this issue when I hear back.

**Comment by tim-finnigan** [comment]
P69992985

**Comment by tim-finnigan** [comment]
I head back from a member of the Redshift Data team. They said this is expected behavior because you are running another query to obtain the query id from the insert/copy but every data API query runs select pg_last_query_id() after the SQL so they can store the query_id in describe-statement. 

To get the query_id from your request you need to check "RedshiftQueryId" in describe-statement. More info can be obtained here: https://docs.aws.amazon.com/redshift-data/latest/APIReference/API_DescribeStatement.html. 

If you're still running into issues related to this then I recommend reaching out to [AWS Support](https://aws.amazon.com/contact-us/) for further assistance.
