### ISSUE TITLE
[Feature Request] Make Console API delete consistent 

### ISSUE THREAD

**Issue by kderck** [aws/aws-sdk#323]
Dear AWS 

I'm not sure if this is the right place but can we look at making delete in the console more consistent?

<img width="590" alt="Screenshot 2022-08-11 at 06 44 17" src="https://user-images.githubusercontent.com/98526301/184239213-05aca8f2-44f2-4328-879c-3d9cac2aaf0a.png">
<img width="509" alt="Screenshot 2022-08-11 at 07 03 49" src="https://user-images.githubusercontent.com/98526301/184239220-42615c44-bb43-46f1-bae1-1562ddcc7218.png">
<img width="586" alt="Screenshot 2022-08-11 at 06 43 13" src="https://user-images.githubusercontent.com/98526301/184239223-57a03ab3-ab6d-466b-9edf-65347e721452.png">

**Comment by tim-finnigan** [comment]
Hi @kderck thanks for the feature request. This repository used is for tracking service API issues and feature requests. For console-related feedback I recommend reaching out to [AWS Support](https://aws.amazon.com/contact-us/) or clicking the Feedback button in the console.
