### ISSUE TITLE
"aws cloudcontrol get-resource" not working for AWS::EC2::PrefixList

### ISSUE THREAD

**Issue by antoninb-ironfort** [aws/aws-sdk#324]
### Describe the bug

The `aws cloudcontrol get-resource` command doesn't work for resources of type `AWS::EC2::PrefixList`, even though it is listed as a supported resource type: https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html.

On the other hand, `aws cloudcontrol list-resources --type-name AWS::EC2::PrefixList` is working just fine.

This is not specific to the CLI, this an API issue as the same issue can be observed with the Go SDK.

### Expected Behavior

`aws cloudcontrol get-resource --type-name AWS::EC2::PrefixList --identifier <identifier>` should succeed when `<identifier>` is a valid  PrefixList identifier.

### Current Behavior

```bash
$ aws cloudcontrol get-resource --type-name AWS::EC2::PrefixList --identifier pl-00a54069

An error occurred (HandlerInternalFailureException) when calling the GetResource operation (reached max retries: 2): AWS::EC2::PrefixList Handler returned status FAILED: null (HandlerErrorCode: InternalFailure, RequestToken: bbd26714-f2c8-4051-a4c6-f4ac9a1d1305)
```

### Reproduction Steps

Run `aws cloudcontrol list-resources --type-name AWS::EC2::PrefixList` first to make sure it works and to obtain a list of PrefixList identifiers. Choose one of these identifiers (referred to as `<identifier>`) and run: `aws cloudcontrol get-resource --type-name AWS::EC2::PrefixList --identifier <identifier>`. It will fail with the above error.

### Possible Solution

Needs to be fixed in the CloudControl API implementation

### Additional Information/Context

This is not specific to the CLI, it's a problem with the CloudControl API. I just didn't know where else to report the bug.

### CLI version used

2.7.21

### Environment details (OS name and version, etc.)

macOS

**Comment by tim-finnigan** [comment]
P69756646

**Comment by tim-finnigan** [comment]
Hi again, thanks for your patience. I've been advised that a fix for this has now been across regions. Please update to the latest version of the CLI/SDK you're using and let us know if you still run into any further issues related to this.
