### ISSUE TITLE
aws backup describe-backup-job BackupSizeInBytes and BytesTransferred are always 0

### ISSUE THREAD

**Issue by orifinkelman** [aws/aws-sdk#325]
I am using aws-cli/2.7.22 
Backup S3 buckets.
All my S3 backup jobs always show BackupSizeInBytes and BytesTransferred always show 0, even the first backup job shows 0.

$ aws backup describe-backup-job --backup-job-id xxxxxxx-xxxx-xxxx-xxxx-a1864bdcde40  --output json
{
    "AccountId": "XXXXXXXXXX",
    "CreationDate": "2022-08-10T12:29:12.700000+03:00",
    "CompletionDate": "2022-08-10T12:45:13.952000+03:00",
    "State": "COMPLETED",
    "PercentDone": "100.0",
    **"BackupSizeInBytes": 0,**
    "ResourceType": "S3",
    **"BytesTransferred": 0,**
    "StartBy": "2022-08-10T13:29:12.700000+03:00"
}

**Comment by tim-finnigan** [comment]
It looks like you also opened an issue for this here in the AWS CLI repository: https://github.com/aws/aws-cli/issues/7192. I think that is the best place for the issue so I'm going to close this one. If it is determined that there is a service API issue, then we can transfer that issue back there to this cross-SDK repository. Thanks!

**Comment by orifinkelman** [comment]
Thanks @tim-finnigan
