### ISSUE TITLE
Websocket APIGateway stage is not deleting using lambda

### ISSUE THREAD

**Issue by mojari** [aws/aws-sdk#329]
Hi Team,

I followed the url https://lukemillerdev.medium.com/cloudformation-does-not-redeploy-your-apig-how-to-fix-that-b0a61aafe220 for deleting the stage with below snippet in lambda but unable to delete the stage of apigateway. Am I missing any thing.

exports.handler = async (event) => {
    
    //const job = event[‘CodePipeline.job’];
    var apigateway;
    try{
       // const parameters = JSON.parse(job.data.actionConfiguration.
      //    configuration.UserParameters);
      //  const {apiId} = parameters;
        let deleteParams = {
          restApiId: 'k67jmvl62d',
          stageName: 'test'
        };
        await apigateway.deleteStage(deleteParams).promise();
        let deploymentParams = { 
          restApiId: 'k67jmvl62d',
          description: `Created via deployment lambda.`
         }
       
    }
    catch(error){
        const failureParams = {
          failureDetails:{
            message: error.message,
            type: 'JobFailed'
          },
        //  jobId: job.id
        };
    //    const failureResult = await codepipeline
     //     .putJobFailureResult(failureParams).promise();
    }
};

**Comment by tim-finnigan** [comment]
Hi @mojari thanks for reaching out. This repository is reserved for issues transferred from SDK repositories after determining that the issue relates to a service API. Please create an issue in the relevant SDK repository as listed here: https://github.com/aws/aws-sdk#aws-sdks-on-github.
