### ISSUE TITLE
Is there way to check whether the cname record for the route53 exist or not?

### ISSUE THREAD

**Issue by akoserwal** [aws/aws-sdk#33]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**
The only way I could find out is to list using: 
* `route53Client.ListResourceRecordSets`
But, It doesn't provide any filtering mechanism with the recordset

Please suggest a better way? or if we can add a feature to add a call like getting resource record set by some attribute?

**Comment by peterwoodworth** [comment]
@akoserwal have you been able to submit a feature request for this anywhere?

**Comment by akoserwal** [comment]
@peterwoodworth No, it requires premium support to raise the request.

**Comment by peterwoodworth** [comment]
I'll create an internal ticket for this today

**Comment by peterwoodworth** [comment]
The team has this feature request in their backlog, but there are no plans to implement it soon. Thank you for submitting this request!
