### ISSUE TITLE
ApiGateway V2 GetDomains deserialisation error

### ISSUE THREAD

**Issue by liamg** [aws/aws-sdk#331]
### Describe the bug

Calling `GetDomains` results in an error.

It seems the timestamp value is not the expected type.

### Expected Behavior

A perfect list of domains to be returned, without error.

### Current Behavior

```
operation error ApiGatewayV2: GetDomainNames, https response error StatusCode: 200, RequestID: 2c0a1998-4ab4-4e90-b816-9f249530abe6, deserialization failed, failed to decode response body with invalid JSON, expected __timestampIso8601 to be of type string, got json.Number instead
```

### Reproduction Steps

Call `GetDomains` and observe - I'm not sure if this requires a certain domain to have a certain value to trigger the error...

### Additional Information/Context

[Usage example](https://github.com/aquasecurity/defsec/blob/master/internal/adapters/cloud/aws/api-gateway/domains_v2.go#L21)

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.16.11
github.com/aws/aws-sdk-go-v2/service/apigateway v1.15.14

### Compiler and Version used

1.19

### Operating System and version

Kernel: 5.18.16-arch1-1

**Comment by RanVaknin** [comment]
Hi @liamg ,

Thanks for bringing this to our attention. This is a APIGateway service modeling issue, and not an SDK specific issue. 
I have cut an internal ticket to API gateway to try and get a fix out soon.

Will keep you updated.
Thanks,
~Ran

`Internal sim ticket P70302809`

**Comment by RanVaknin** [comment]
Hi @liamg ,

Im happy to update you that the service team has pushed a fix for this and this should now be working as expected.

Let us know if you need anything else.

Thanks,
Ran~
