### ISSUE TITLE
`PutBucketIntelligentTieringConfiguration` documentation example results in MalformedXML 

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#336]
Original issue: https://github.com/boto/boto3/issues/3401

Documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=resource#S3.Client.put_bucket_intelligent_tiering_configuration

**Comment by tim-finnigan** [comment]
P70659274

**Comment by tim-finnigan** [comment]
The problem was in the code of the originally reported issues. The `Id` values did not match: one was `intelligent_tiering` and the other was `deep_archive`. After changing both to `deep_archive` the code executed successfully.

**Comment by sam-som** [comment]
> The problem was in the code of the originally reported issues. The `Id` values did not match: one was `intelligent_tiering` and the other was `deep_archive`. After changing both to `deep_archive` the code executed successfully.

Im seeing the same issue and matching the `Id` is not solving the issue
