### ISSUE TITLE
DescribeLoadBalancers API call doesn't return `IpAddressType` value for Gateway Load Balancer

### ISSUE THREAD

**Issue by ParthaI** [aws/aws-sdk#341]
### Describe the bug

The API [DescribeLoadBalancers](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.18.12#Client.DescribeLoadBalancers) doesn't return `IpAddressType` value for Gateway Load Balancer but however we are getting the `IpAddressType` value for Application Load Balancer.

### Expected Behavior

We should get the `IpAddressType` value for Gateway Load Balancer.

### Current Behavior

We are getting an empty string for `IpAddressType` attribute for Gateway Load Balancer though the data is available in AWS console.

### Reproduction Steps

Make the [DescribeLoadBalancers](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.18.12#Client.DescribeLoadBalancers) API call and please verify the `IpAddressType` value in the result.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.16.11

### Compiler and Version used

go version go1.19 darwin/arm64

### Operating System and version

Mac

**Comment by RanVaknin** [comment]
This is now added:

```console
$ aws elbv2 describe-load-balancers --region us-east-1

{
    "LoadBalancers": [
        {
            "LoadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:REDACTED:loadbalancer/gwy/testlb/REDACTED",
            "CreatedTime": "2022-08-31T16:32:31.524000+00:00",
            "LoadBalancerName": "testlb",
            "VpcId": "vpc-REDADTED",
            "State": {
                "Code": "active"
            },
            "Type": "gateway",
            "AvailabilityZones": [
                {
                    "ZoneName": "us-east-1a",
                    "SubnetId": "subnet-REDACTED"
                }
            ],
            "IpAddressType": "ipv4"
        }
    ]
}
```

Thank you for your patience.
All the best,
Ran~
