### ISSUE TITLE
How to list secrets that are mark delete in secretsmanager

### ISSUE THREAD

**Issue by gabsg** [aws/aws-sdk#35]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

I could not find anyway stated in the docs on how to list aws scecrets that are marked deleted?
Someone in stackoverflow had post the same question.
https://stackoverflow.com/questions/65038240/aws-secretsmanager-list-deleted-secrets

**Comment by peterwoodworth** [comment]
Hey @maclarensg have you been able to follow up with premium support or aws forums?
