### ISSUE TITLE
support EKSContainer role as Credential_Source

### ISSUE THREAD

**Issue by gurpalw** [aws/aws-sdk#350]
I have a EKS pod which gets `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables from its associated k8s ServiceAccount.

This role has permissions to assume a role in up to 3 other AWS accounts. However, currently it is not possible to assume those roles unless the AWS config file supports the EKS pod's role as a potential `credential_source` in the config profile.

Currently the below are supported values are supported as `credential_source` arguments in the aws config file.

```
Environment – Retrieves the source credentials from environment variables.

Ec2InstanceMetadata – Uses the IAM role attached to the Amazon EC2 instance profile.

EcsContainer – Uses the IAM role attached to the Amazon ECS container.
```
source: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

Can you add support for using the role derived from the pods service account as a credential source?

**Comment by aBurmeseDev** [comment]
Hi @gurpalw, thanks for opening your first issue in aws-sdk!
 
After investigating, I found out that there's already a feature request under [aws/aws-cli](https://github.com/aws/aws-cli/issues/3875).  Currently, we don't have any update on what we might be able to do about this, though. I would suggest to please :+1: the original post and add any specific use cases there. 

For now, please use these workarounds mentioned by other users [here](https://github.com/aws/aws-sdk/issues/277#issuecomment-1245376729) and [here](https://github.com/aws/aws-cli/issues/3875#issuecomment-1000427941) Thanks!

Best,
John

**Comment by aBurmeseDev** [comment]
I'm closing this in favor of existing FR in [aws/aws-cli](https://github.com/aws/aws-cli/issues/3875). As mentioned above, I'd encourage to 👍 the original post in aws-cli repo and share your specific use cases there. Thanks!
