### ISSUE TITLE
Better apigateway create-usage-plan error message

### ISSUE THREAD

**Issue by jmrah** [aws/aws-sdk#354]
### Describe the bug

Calling the `aws apigateway create-usage-plan` API with _either_ the `stage` parameter or the `apiId` parameter set to NULL/blank/undefined/empty emits an incorrect error message about the problem.

### Expected Behavior

```
aws apigateway create-usage-plan --name test-usage-plan --api-stages='apiId=,stage=dev'

An error occurred (BadRequestException) when calling the CreateUsagePlan operation: Invalid API ID {api: '', stage: dev} specified for usagepla 'test-usage-plan' 
```

### Current Behavior

```
aws apigateway create-usage-plan --name test-usage-plan --api-stages='apiId=,stage=dev'

An error occurred (BadRequestException) when calling the CreateUsagePlan operation: Invalid API Stage {api: %s, stage: %s} specified for usageplan %s
```

### Reproduction Steps

Execute the following command

`aws apigateway create-usage-plan --name test-usage-plan --api-stages='apiId=,stage=dev'`

or 

`aws apigateway create-usage-plan --name test-usage-plan --api-stages='stage=dev'`

or 

`aws apigateway create-usage-plan --name test-usage-plan --api-stages='apiId=foo,stage='`

or 

`aws apigateway create-usage-plan --name test-usage-plan --api-stages='apiId=foo`

### CLI version used

aws-cli/2.6.3 Python/3.9.11 Linux/4.15.0-193-generic exe/x86_64.linuxmint.19 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by tim-finnigan** [comment]
P72133585

**Comment by tim-finnigan** [comment]
I have been advised that an error message has been added for this scenario. It may take something like ~1-2 weeks for the change to get fully propagated. Thanks again for bringing this to our attention, and if you observe any further issues related to this please let us know.
