### ISSUE TITLE
Improve Describe-Users Query Capability for WorkDocs

### ISSUE THREAD

**Issue by ccoffman4477** [aws/aws-sdk#359]
### Describe the feature

provide better ability to filter based on WorkDocs user attributes

### Use Case

need to describe a specific query to overcome RequestedEntityTooLargeException issues associated with AD Connector and large result sets 

An error occurred (RequestedEntityTooLargeException) when calling the DescribeUsers operation: RequestedEntityTooLargeException: The directory has refused the operation because the result set is too large. Please try a more specific query. Request id: cb800d0f-5705-4be5-9d04-46c27143792e

### Proposed Solution

name query alone is not sufficient; develop "filters" option to replace "include" and "user-query" which permits matching based on any combination of user attributes (similar to the capability that currently exists in ec2 describe-instances)  

### Other Information

may be unaware the Administrator function in WorkDocs provided to download a user listing also fails silently; no error message and returns zero byte Users.JSON file when directory refuses the operation

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

PS >aws --version aws-cli/2.5.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

PS >aws --version aws-cli/2.5.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

**Comment by tim-finnigan** [comment]
P72563539

**Comment by tim-finnigan** [comment]
Thanks for your patience - we heard back from a member of the WorkDocs team and they have noted your feature request and added a backlog item for it. I can't guarantee if or when they would implement such a feature but we recommend reaching out to [AWS Support](https://aws.amazon.com/contact-us/) for future updates going forward.
