### ISSUE TITLE
iam list-policies error message is incorrect/incomplete

### ISSUE THREAD

**Issue by chrishodson** [aws/aws-sdk#36]
The error message for the iam list-policies command is incomplete in that the prefic needs to end with a '/' but the error message only talks about it beginning/containing them.

`$ aws iam list-policies --path-prefix '/foo'`

`An error occurred (ValidationError) when calling the ListPolicies operation: The specified value for pathPrefix is invalid. It must begin with the / character and contain only alphanumeric characters and/or / characters.`

`$ aws --version`
`aws-cli/2.1.17 Python/3.7.3 Linux/3.10.0-1062.18.1.el7.x86_64 docker/x86_64.amzn.2 prompt/off`

**Comment by kdaily** [comment]
0543994509

**Comment by kdaily** [comment]
The IAM team is aware of the issue and has put it in their backlog, so it will be updated. No ETA on when it will be fixed. Thanks!

**Comment by viru7683** [comment]
Please continue working on it.
