### ISSUE TITLE
How to fix typo in documentation? ECR

### ISSUE THREAD

**Issue by jmklix** [aws/aws-sdk#366]
Transfered from awslabs/aws-sdk-rust: https://github.com/awslabs/aws-sdk-rust/issues/322

Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution

**Describe the question**
The documentation of [ECR Client](https://docs.rs/aws-sdk-ecr/latest/aws_sdk_ecr/client/struct.Client.html) has typo: "Amazon EC2 Container Registry" should be "Amazon Elastic Container Registry".

How to fix this issue? Does changing ["smithy.api#title"](https://github.com/awslabs/smithy-rs/blob/main/aws/sdk/aws-models/ecr.json#L47) into "Amazon Elastic Container Registry"  solve this?

**Comment by jmklix** [comment]
https://github.com/awslabs/aws-sdk-rust/issues/322#issuecomment-985588988

Hello and thanks for reporting! We consume the models from a central source. `smithy.api#title` is indeed the field that's problematic. I'm following up internally to get this fixed in the API models which will flow back through to the Rust SDK.

https://github.com/awslabs/aws-sdk-rust/issues/322#issuecomment-985949628

I found [ECS Client](https://docs.rs/aws-sdk-ecs/latest/aws_sdk_ecs/client/struct.Client.html) had the same typo: "Amazon EC2 Container Service" should be "Amazon Elastic Container Service".

[This table of contents](https://awslabs.github.io/aws-sdk-rust/) also has the same typo: "Amazon EC2 Container Registry" and "Amazon EC2 Container Service".

**Comment by jmklix** [comment]
P78571596

**Comment by kellertk** [comment]
Hi there. This issue has been acknowledged and is being owned by the ECS team internally. Since there's no other work for us to to here except wait for an update, I'll close this issue now. This portion of our documentation is code generated from service models, so this may take some time to fix in the next available service model update.
