### ISSUE TITLE
Attach custom image to SageMaker domain without update-domain command

### ISSUE THREAD

**Issue by kevinnowland** [aws/aws-sdk#367]
**Is your feature request related to a problem? Please describe.**

It is difficult to attach a custom image to a SageMaker domain via the AWS CLI. The process, [outlined here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-byoi-sdk-attach-current-domain.html), in particular involves using the command `aws sagemaker update-domain` and passing in a JSON file. However, this (a) fails if the domain has an app InService -- which does not happen in the console and (b) can introduce unwanted changes if the JSON file includes other unrelated updates. Generating the JSON config is also burdensome, requiring using `aws sagemaker describe-domain` and extracting the relevant piece of the JSON and generating the new config.

**Describe the solution you'd like**

I would like a command such as `aws sagemaker attach-image` that has parameters domain id, image name, image config name, and optional image version number (default to latest) to handle the attaching process without going through `aws sagemaker update-domain`.

**Describe alternatives you've considered**

The only alternative is going through the console, which is not ideal for CD.

**Additional context**

The image config is hard (impossible?) to find in the AWS console, so adding that would be helpful here as well. That obviously falls outside the purview of this repo.

Thank you!

**Comment by Tanguy-LeFloch** [comment]
Hello @tim-finnigan ,

Thanks for your reactivty.

To be more precise, attaching an image from the console seems to update the domain, but in a different way than updating the domain with the edition of the domain settings.

I'm saying this because I did a test to update the domain from the console, adding a tag. It resulted in an update failure (because I had apps running?), while attaching an image in the console even with apps running did not fail before.

Now I'm stuck with a domain that can't be updated even just to attach images, but I've opened an AWS support ticket for that.

**Comment by tim-finnigan** [comment]
The SageMaker team now has this request in their backlog for further review and prioritization. For updates going forward we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/), or feel free to check back in here as well.

**Comment by dsradecki** [comment]
Was this issue somehow resolve?

@tim-finnigan can you provide us with some issue which was raised to be able to see the progress?

**Comment by tim-finnigan** [comment]
There is no public issue tracking this feature request, I created an internal tracking item for the SageMaker team's consideration. If you want me to pass along any details regarding your use case please let me know. Alternatively you can reach out through [AWS Support](https://aws.amazon.com/contact-us/) for inquiries on this feature request.
