### ISSUE TITLE
Cost Explorer's get_cost_and_usage GroupBy limits

### ISSUE THREAD

**Issue by aBurmeseDev** [aws/aws-sdk#369]
Original Issue: https://github.com/boto/boto3/issues/3443

**Comment by aBurmeseDev** [comment]
P73222159

**Comment by aBurmeseDev** [comment]
Hi @Suzy12 - I wanted to follow up on your request here. I heard back from the CostExplorer team that API only support 2 level GroupBy and this request is not under consideration right now, unfortunately. However, they suggested to check out [AWS CUR](https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html) (Cost and Usage Reports) as an alternative to what you're trying to accomplish. 

Please let us know if you have any other questions!
Best,
John

**Comment by Suzy12** [comment]
Okay, thank you for your time & suggestions! 🙏

**Comment by aBurmeseDev** [comment]
You're very welcome, please feel free to contact us again if you have any other questions! I will go ahead and close this issue now.
