### ISSUE TITLE
add fargateVCPULimit to ecs.PutAccountSettingDefault

### ISSUE THREAD

**Issue by btsuhako** [aws/aws-sdk#374]
### Describe the bug

`fargateVCPULimit` is a current account setting available in AWS. In Oct 2022, there is a migration path to setting this in a region.

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PutAccountSettingDefault.html

https://github.com/aws/aws-sdk-go/blob/main/models/apis/ecs/2014-11-13/api-2.json needs updating to support this new enum, alongside the existing options, such as `containerInsights`, `awsvpcTrunking`, etc

### Expected Behavior

should be able to call the following without error:

```golang
	input := ecs.PutAccountSettingDefaultInput{
		Name:  aws.String("fargateVCPULimit"),
		Value: aws.String("enabled"),
	}
```

### Current Behavior

not currently available

### Reproduction Steps

```golang
	input := ecs.PutAccountSettingDefaultInput{
		Name:  aws.String("fargateVCPULimit"),
		Value: aws.String("enabled"),
	}
```

### SDK version used

v1.44.114

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

go version go1.19.2 darwin/arm64

**Comment by RanVaknin** [comment]
Hi @btsuhako,

A couple of points:
>should be able to call the following without error:

which error are you getting?

Your code has an issue. `name` here is just a string, and shouldn't be wrapped by the aws.String wrapper indicating that it is a pointer to a string.
```go
	out, err := client.PutAccountSettingDefault(context.Background(), &ecs.PutAccountSettingDefaultInput{
		Name:  "fargateVCPULimit",
		Value: aws.String("enabled"),
	})
```

I can run this command without any issues. Here is the output:
```json
{"setting":{"name":"fargateVCPULimit","principalArn":"arn:aws:iam::<redacted>","value":"enabled"}}

```

Let me know if this helps.
Thanks,
Ran~
