### ISSUE TITLE
Very partial list of errors defined in smithy S3 model

### ISSUE THREAD

**Issue by kellertk** [aws/aws-sdk#376]
This issue is to continue the issues in awslabs/smithy#1147 (it's currently not possible to directly transfer issues between GitHub orgs). The original issue text is below:

---

Hi

For context:
- I am working on this project that uses the S3 model to interact with S3 clients and servers - https://github.com/s3d-rs/s3d.
- This is a followup from https://github.com/awslabs/smithy-rs/issues/1150.

When I look at the S3 smithy model, I find that it lacks a lot of error definitions for operations.
Here is a list of all the operations that have errors defined:

```
$ node -e 'm=require("./smithy-rs/aws/sdk/aws-models/s3.json"); Object.entries(m.shapes).forEach(([n,s])=>{ if (s.type==="operation" && s.errors) console.log(n, "---", s.errors.map(x=>x.target).join(",")); })'
com.amazonaws.s3#AbortMultipartUpload --- com.amazonaws.s3#NoSuchUpload
com.amazonaws.s3#CopyObject --- com.amazonaws.s3#ObjectNotInActiveTierError
com.amazonaws.s3#CreateBucket --- com.amazonaws.s3#BucketAlreadyExists,com.amazonaws.s3#BucketAlreadyOwnedByYou
com.amazonaws.s3#GetObject --- com.amazonaws.s3#InvalidObjectState,com.amazonaws.s3#NoSuchKey
com.amazonaws.s3#GetObjectAcl --- com.amazonaws.s3#NoSuchKey
com.amazonaws.s3#HeadBucket --- com.amazonaws.s3#NotFound
com.amazonaws.s3#HeadObject --- com.amazonaws.s3#NotFound
com.amazonaws.s3#ListObjects --- com.amazonaws.s3#NoSuchBucket
com.amazonaws.s3#ListObjectsV2 --- com.amazonaws.s3#NoSuchBucket
com.amazonaws.s3#PutObjectAcl --- com.amazonaws.s3#NoSuchKey
com.amazonaws.s3#RestoreObject --- com.amazonaws.s3#ObjectAlreadyInActiveTierError
```

This is clearly a tiny fraction of the real errors that this API can return.
See https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Is there a way to contribute to the model definition to make it represent the S3 errors correctly?

Thanks!

**Comment by kellertk** [comment]
P62314171

**Comment by kellertk** [comment]
Hi everyone, this will require some changes from the S3 service team in how these errors are modeled. We raised this request up to the team and they've agreed to put it on their feature backlog. We don't have any ETA at this time, but I would expect a timeframe of at least a few months before this will be reviewed further. If there are other updates from the team, we will post them here.

**Comment by ashishdhingra** [comment]
Reached out to service team for an update. Awaiting response.

**Comment by guymguym** [comment]
FYI @Nugine for the https://github.com/Nugine/s3s project

**Comment by ashishdhingra** [comment]
Got update from service team. It's in their prioritized list of feature requests. We can't share specific timelines on when this might be implemented in GitHub; you should monitor the [AWS News Blog](https://aws.amazon.com/blogs/aws/) for updates.

Closing this issue since the feature is prioritized in service team's backlog.
