### ISSUE TITLE
Add RDS DBInstanceStopped waiter

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#379]
Original issue: https://github.com/boto/boto3/issues/3464

Current RDS waiters: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#waiters

**Comment by tim-finnigan** [comment]
P74217938

**Comment by VenkateshMakala** [comment]
Hi @tim-finnigan,

When can we expect the solution.

**Comment by tim-finnigan** [comment]
Hello - we heard back from the RDS team and they said this item is in their backlog. However, they can't provided an estimated completion date for it. If you have a support plan I recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for updates going forward, or feel free to check back in here for updates as well. Thanks!
