### ISSUE TITLE
get-cost-and-usage-with-resources granularity inconsistency

### ISSUE THREAD

**Issue by aBurmeseDev** [aws/aws-sdk#381]
Original Issue: https://github.com/aws/aws-cli/discussions/7382

**Comment by aBurmeseDev** [comment]
P74611727

**Comment by aBurmeseDev** [comment]
Hi @suito-venus, I wanted to share the update here. Upon speaking with Service API team, they suggested to use `get-cost-and-usage` rather than `get-cost-and-usage-with-resources`. The reason behind is that the command `get-cost-and-usage-with-resources` only supports for *hourly* data which requires the date range `time-period` to be within past 14 days.

With `get-cost-and-usage`, you can request *monthly* data. Here's [docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ce/get-cost-and-usage.html) on `get-cost-and-usage` and the command below is what you're looking for.

```
aws ce get-cost-and-usage  \
--granularity MONTHLY \
--time-period Start=2022-06-01,End=2022-09-01 \
--filter '{"Dimensions": { "Key": "INSTANCE_TYPE", "Values": [ "UsageQuantity", "BlendedCosts", "RESOURCE_ID" ] }}' \
--metrics "BlendedCost" "UsageQuantity" \
--group-by Type=DIMENSION,Key=INSTANCE_TYPE
--profile mfa
```

Please let me know if you have further questions or concerns, thank you again for your patience!

**Comment by suito-venus** [comment]
Hi  @aBurmeseDev ,
Thank you for your response. 
I understand use `get-cost-and-usage` rather than `get-cost-and-usage-with-resources` in my use case.
That CLI command works good for me! 
Thanks! 😄:+1:
