### ISSUE TITLE
WaitUntilStackDeleteCompleteWithContext waits on UPDATE_COMPLETE

### ISSUE THREAD

**Issue by DzeryCZ** [aws/aws-sdk#383]
### Describe the bug

I'm using [aws-nuke](https://github.com/rebuy-de/aws-nuke) tool, that deletes CloudFormation stacks. The problem is, when a stack has dependency it hangs on `WaitUntilStackDeleteCompleteWithContext` method.

The time sequence looks like following:

1. `DeleteStack` is called - initialing `DELETE_IN_PROGRESS | User Initiated`
2. `WaitUntilStackDeleteCompleteWithContext` is called - waiting for a success or failure
3. During the wait CloudFormation stack goes to - `UPDATE_COMPLETE | Export xxx cannot be deleted as it is in use by yyy`
4. `WaitUntilStackDeleteCompleteWithContext` does not recognize this as a pre-defined "success or failure" response and continues waiting
5. `WaitUntilStackDeleteCompleteWithContext` timesout after an hour

### Expected Behavior

`WaitUntilStackDeleteCompleteWithContext` recognize `UPDATE_COMPLETE` stack status as `FailureWaiterState`

### Current Behavior

`WaitUntilStackDeleteCompleteWithContext` does not recognize `UPDATE_COMPLETE` stack status at all and waits for a different status, that will never come.

### Reproduction Steps

1. Create CloudFormation stack xxx with output
2. Create CloudFormation stack yyy that uses the output of xxx
3. Initiate deletion via `DeleteStack`
4. Run `WaitUntilStackDeleteCompleteWithContext`

### Possible Solution

Add `UPDATE_COMPLETE` to possible stack status of `WaitUntilStackDeleteCompleteWithContext` method

### SDK version used

v1.44.104

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

Ubuntu 22.04

**Comment by RanVaknin** [comment]
This is now added.

Thanks,
Ran~
