### ISSUE TITLE
DynamoDB support for dynamodb:DescribeReservedCapacity, dynamodb:DescribeReservedCapacityOfferings, and dynamodb:PurchaseReservedCapacityOfferings from CLI

### ISSUE THREAD

**Issue by nikhilkhanna** [aws/aws-sdk#385]
**Is your feature request related to a problem? Please describe.**
Currently DynamoDB does not expose the actions for dynamodb:DescribeReservedCapacity, dynamodb:DescribeReservedCapacityOfferings, and dynamodb:PurchaseReservedCapacityOfferings as cli commands 

**Describe the solution you'd like**
Ideally these actions should be exposed through the cli such as the following
```
aws dynamodb describe-reserved-capacity
aws dynamodb describe-reserved-capacity-offerings
aws dynamodb purchase-reserved-capacity-offerings
```
each with corresponding options as applicable.

**Describe alternatives you've considered**
There is no alternative, this is simply a gap in the dynamodb cli

**Additional context**
I need this (and I assume many other customers do as well), so my company can manage spend for DynamoDB more effectively and handle reserved capacity and purchasing new capacity programmatically as our needs evolve.

**Comment by tim-finnigan** [comment]
The DynamoDB team has this issue in their backlog for further review and prioritization. For updates going forward we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/).
