### ISSUE TITLE
Add --stack-status-filter-ignore option to aws/cloud-formation

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-sdk#386]
Per the description [here](https://stackoverflow.com/questions/43239589/aws-cli-list-only-the-name-of-current-running-cloudformation-stacks), it would be great to be able to list all stacks that are currently running, without the deleted stacks etc.

Expected command:
```
aws cloudformation list-stacks --query 'StackSummaries[].[StackName,TemplateDescription]' --stack-status-ignore-filter DELETE_COMPLETE --output text
```

instead of:
```
aws cloudformation list-stacks --query 'StackSummaries[].[StackName,TemplateDescription]' --stack-status-filter CREATE_IN_PROGRESS CREATE_COMPLETE ROLLBACK_IN_PROGRESS ROLLBACK_FAILED ROLLBACK_COMPLETE DELETE_IN_PROGRESS DELETE_FAILED UPDATE_IN_PROGRESS UPDATE_COMPLETE_CLEANUP_IN_PROGRESS UPDATE_COMPLETE UPDATE_ROLLBACK_IN_PROGRESS UPDATE_ROLLBACK_FAILED UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS UPDATE_ROLLBACK_COMPLETE REVIEW_IN_PROGRESS --output text
```

**Comment by tim-finnigan** [comment]
This request was added to the CloudFormation team's backlog for further review and prioritization. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for updates going forward, or feel free to check back in here as well.
