### ISSUE TITLE
`aws lambda add-permission` seems to have different regex validation from the one intented

### ISSUE THREAD

**Issue by ytoml** [aws/aws-sdk#388]
### Describe the bug

When I tried to add permission for some role, encountered validation error:
```shell
An error occurred (InvalidParameterValueException) when calling the AddPermission operation: The provided input'arn:aws:iam:000000000000:role/xxxx'was invalid. Member must satisfy expression: [\w+=,.@-]* Please check your input and try again.
```
while the [documentation](https://docs.aws.amazon.com/lambda/latest/dg/urls-auth.html) says that this operation can be done with:
```shell
# example on documentation
aws lambda add-permission --function-name my-function \
  --statement-id example0-cross-account-statement \
  --action lambda:InvokeFunctionUrl \
  --principal arn:aws:iam::444455556666:role/example \
  --function-url-auth-type AWS_IAM
```

### Expected Behavior

The `--principal` arcument must accept `arn:aws:iam::000000000000:role/xxxx`. Maybe regex must include `/` as an acceptable character.

### Current Behavior

Validation seems to be done with the regex matcher different from the one intended.

### Reproduction Steps

Run:
```shell
aws lambda add-permission --function-name my-function \
  --statement-id example0-cross-account-statement \
  --action lambda:InvokeFunctionUrl \
  --principal arn:aws:iam::444455556666:role/example \
  --function-url-auth-type AWS_IAM
```
(of course each argument must be replaced with valid one)

### CLI version used

aws-cli/2.8.4 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 12.5

**Comment by tim-finnigan** [comment]
P74832661

**Comment by ytoml** [comment]
Yes, actually I encountered the same problem on AWS console (after opening this PR).

Thanks!

**Comment by nilskk** [comment]
I get the same error when I try to use an STS AssumedRole for Lambda Function URL Permission. Does anybody have an idea how to fix this?

**Comment by tim-finnigan** [comment]
I've been advised the the documentation has been updated. Please note that it does say on https://docs.aws.amazon.com/lambda/latest/dg/urls-auth.html#urls-auth-iam:

>For **Principal**, enter account ID or the Amazon Resource Name (ARN) of the user or role that you want to grant permissions to

For other problems related to this please consider creating a new issue, using the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=Lambda&topic_url=http://docs.aws.amazon.com/en_us/lambda/latest/dg/API_AddPermission.html) link at the bottom of AWS documentation pages, or reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.
