### ISSUE TITLE
S3 GetBucketNotificationConfiguration API returns uppercase FilterRule.Name (Prefix, Suffix)

### ISSUE THREAD

**Issue by HongChenTW** [aws/aws-sdk#389]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

https://github.com/aws/aws-sdk-go-v2/blob/31459368544ba0cafeee5f0f91e957826627e7e1/service/s3/api_op_GetBucketNotificationConfiguration.go#L30

When request `GetBucketNotificationConfiguration` api, `GetBucketNotificationConfigurationOutput` always return uppercase FilterRule.Name (Prefix, Suffix), but `FilterRule` type is also use `FilterRuleName` as type, which cause when we want to compare output with constant variable `FilterRuleNamePrefix`, we need to lowercase the output FilterRule.Name first.

https://github.com/aws/aws-sdk-go-v2/blob/31459368544ba0cafeee5f0f91e957826627e7e1/service/s3/types/enums.go#L336-L352

Is there any suggestions to better handle this comparison?

Thanks.

**Comment by ashishdhingra** [comment]
Reproducible in AWS .NET SDK as well using below code:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.Console;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());

using (AmazonS3Client amazonS3Client = new AmazonS3Client(RegionEndpoint.USEast2))
{
    var bucketConfigResponse = await amazonS3Client.GetBucketNotificationAsync("bucketname");
}
```

This logs the below response in console log output:
```
...
ime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 12 : There is no request_min_compression_size_bytes set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 13 : There is no sdk_ua_app_id set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 0 : Resolved DefaultConfigurationMode for RegionEndpoint [us-east-2] to [Legacy].
Amazon Information: 0 : Starting a process with the following ProcessInfo: UseShellExecute - False RedirectStandardError - True, RedirectStandardOutput - True, CreateNoWindow - True
Amazon Information: 1 : Process started
Amazon Information: 0 : Process ends with exitcode - 0
Amazon Verbose: 0 : Received response (truncated to 1024 bytes): [<?xml version="1.0" encoding="UTF-8"?>
<NotificationConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CloudFunctionConfiguration><Id>testeventnotification</Id><CloudFunction>arn:aws:lambda:us-east-2:139480602983:function:tests3eventnotification</CloudFunction><Event>s3:ObjectCreated:*</Event><Filter><S3Key><FilterRule><Name>Prefix</Name><Value>images/</Value></FilterRule><FilterRule><Name>Suffix</Name><Value>.jpg</Value></FilterRule></S3Key></Filter></CloudFunctionConfiguration></NotificationConfiguration>]
```
If one examines `<FilterRule><Name>Prefix</Name><Value>images/</Value></FilterRule><FilterRule><Name>Suffix</Name><Value>.jpg</Value></FilterRule>`, it appears that filter rule names are returned in sentence case (1st letter in upper case) as reported by customer. 

Similar behavior is observed using AWS CLI `aws s3api get-bucket-notification --bucket "myawsbucket-ashish" --debug`:
```
...

2024-04-04 14:15:03,864 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): myawsbucket-ashish.s3.us-east-2.amazonaws.com:443
2024-04-04 14:15:04,224 - MainThread - urllib3.connectionpool - DEBUG - https://myawsbucket-ashish.s3.us-east-2.amazonaws.com:443 "GET /?notification HTTP/1.1" 200 None
2024-04-04 14:15:04,225 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-id-2': 'kjZ9CgBcdxoMZA3363ss+/CaDFVW6oSQDErFcQUlx+9dtVDHRUaxl3MvI9hqMcnHwFfhZXXOAKk1tAgOhe1/og==', 'x-amz-request-id': 'JFZGR1R7R0CSKPC4', 'Date': 'Thu, 04 Apr 2024 21:15:05 GMT', 'Transfer-Encoding': 'chunked', 'Server': 'AmazonS3'}
2024-04-04 14:15:04,225 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<NotificationConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CloudFunctionConfiguration><Id>testeventnotification</Id><CloudFunction>arn:aws:lambda:us-east-2:139480602983:function:tests3eventnotification</CloudFunction><Event>s3:ObjectCreated:*</Event><Filter><S3Key><FilterRule><Name>Prefix</Name><Value>images/</Value></FilterRule><FilterRule><Name>Suffix</Name><Value>.jpg</Value></FilterRule></S3Key></Filter></CloudFunctionConfiguration></NotificationConfiguration>'
2024-04-04 14:15:04,226 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.GetBucketNotification: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x112e90910>>
2024-04-04 14:15:04,226 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2024-04-04 14:15:04,226 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.GetBucketNotification: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x112e10910>>
...
```
However,
- Service API documentation for [GetBucketNotificationConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketNotificationConfiguration.html#API_GetBucketNotificationConfiguration_ResponseSyntax) > [FilterRule:Name](https://docs.aws.amazon.com/AmazonS3/latest/API/API_FilterRule.html#AmazonS3-Type-FilterRule-Name) specifies `prefix | suffix` as valid values for `Name`.
- Service model (e.g. .NET SDK) for [FilterRuleName](https://github.com/aws/aws-sdk-net/blob/02ec2a6188696a765eebbf50c5fd0bf2f1321b11/generator/ServiceModels/s3/s3-2006-03-01.api.json#L3262) also specifies `prefix` and `suffix` (in lower case) as possible enum values.

So it appears that S3 service API is not returning values in correct case and this is affecting all AWS SDK(s) where values are compares in case sensitive manner.

Appears to be service API issue.

**Comment by ashishdhingra** [comment]
P124952427

**Comment by ashishdhingra** [comment]
@HongChenTW We have opened a ticket with service team. I would post any updates here as these are available. I would close this issue once the service team prioritizes the issue in their backlog.

**Comment by HongChenTW** [comment]
Thanks @ashishdhingra! I feel very flattered that this issue is picked up after 3 years, thanks for let me know!

**Comment by ashishdhingra** [comment]
Service team is evaluating if it would be a breaking change or if some customization could be done.

**Comment by ashishdhingra** [comment]
Followed up with service team again for an update.

**Comment by ashishdhingra** [comment]
Followed up with service team again for an update.

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The S3 team is continuing to track this in their backlog, but as mentioned earlier here there are concerns about introducing a breaking change. I'm going to close this issue as not planned at this time.
