### ISSUE TITLE
Automatically send email verification when running IdentityStore CreateUser API

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#390]
Original issue: https://github.com/boto/boto3/issues/3479

**Comment by tim-finnigan** [comment]
P75055048

**Comment by tim-finnigan** [comment]
We have heard back from the service team that this feature is available as documented here: https://docs.aws.amazon.com/singlesignon/latest/userguide/userswithoutpwd.html

**Comment by fhuebscher** [comment]
@tim-finnigan 
The _client.create_user()_ method from IdentityStore still does not send e-mails automatically after updating the SSO Configuration as follows:

```
"ssoConfiguration": {
            "mfaMode": "CONTEXT_AWARE",
            "noMfaSignInBehavior": "ALLOWED_WITH_ENROLLMENT",
            "noPasswordSignInBehavior": "EMAIL_OTP",
            "allowedMfaTypes": [
                "TOTP",
                "WEBAUTHN"
            ]
        }

```

The terraform community is facing a similar issue that the underlying API operations do not trigger the OTP mail, see
[hashicorp/terraform-provider-aws#28102](https://github.com/hashicorp/terraform-provider-aws/issues/28102)

**Comment by dennisbrouwer91** [comment]
Any update regarding this?
