### ISSUE TITLE
Support --db-instance-class option for restore-db-cluster-to-point-in-time command.

### ISSUE THREAD

**Issue by sonoransun** [aws/aws-sdk#394]
When creating a clone RDS database using the `restore-db-cluster-to-point-in-time` command it would be nice to be able to specify an instance class via `--db-instance-class` option as is used for database creation.

This would greatly speed up creation time (until "available" state) as our default cluster size is much larger than is needed for the clone database.

**Comment by tim-finnigan** [comment]
It looks like a `DBClusterInstanceClass` request parameter is now available for this API: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBClusterToPointInTime.html#API_RestoreDBClusterToPointInTime_RequestParameters

Please update to a recent version of your respective SDK to use this. If you have any other questions or feedback please let us know.
