### ISSUE TITLE
Pagination / MaxResults in ec2 describe-images

### ISSUE THREAD

**Issue by alexandernst** [aws/aws-sdk#397]
**Is your feature request related to a problem? Please describe.**

Using aws ec2 describe-images is extremely slow when searching in the "market-place" (and it's even worse searching "public" images). This happens because that particular endpoint doesn't have any paging  capabilities, nor max-results limiter for that matter.

**Describe the solution you'd like**

I'd like that endpoint to behave like the rest of the endpoints that return lists; I'd like to be able to paginate / limit the number of returned results.

**Describe alternatives you've considered**

N/A

**Additional context**

I'm not sure if this is the right place to ask for this, since this is a bug / missing feature inside AWS's API itself, and this repo is for the AWS CLI.

If this is not the right place to be asking for this, where should I ask?

**Comment by tim-finnigan** [comment]
We recently received an update that the EC2 DescribeImages API now supports pagination: https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ec2-describeimages-supports-pagination/. I'm going to close this issue now, if you have any follow up questions please let us know.
