### ISSUE TITLE
Add Cloud9 CLI support with 'Environment type' to 'Create and run in remote server SSH connection)'

### ISSUE THREAD

**Issue by ed-barberis** [aws/aws-sdk#398]
### Describe the feature

Add support to Cloud9 CLI with 'Environment type' to 'Create and run in remote server (SSH connection)' with an existing EC2 instance.

### Use Case

We use Cloud9 for customer enablement and all of the provisioning is automated to deploy an EC2 instance from a custom AMI w/ pre-installed C9 tooling and the Systems Manager Public Key, except for connecting/creating a Cloud9 environment associated with the running instance.

This is currently a manual step, but our goal is end-to-end automation.

### Proposed Solution

After preparing documentation on how-to prepare the AMI with the required Cloud9 artifacts, it seems that implementation of the CLI would be fairly straight forward.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.7.2

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by tim-finnigan** [comment]
P75222236

**Comment by tim-finnigan** [comment]
Thanks for your patience - we heard back from the service team and were told that there are no plans to prioritize this feature request at this time. There are concerns about the vast number of environment types that would require support. We recommend checking back through [AWS Support](https://aws.amazon.com/contact-us/) for updates in the future and others can continue to reference their use cases, workarounds, etc. here.
