### ISSUE TITLE
Cannot filter by "Charge Type" on "GetCostAndUsageCommand"

### ISSUE THREAD

**Issue by matiasdecarli** [aws/aws-sdk#40]
## Describe the bug
I'm trying to filter by `Charge Type` when calling `GetCostAndUsageCommand` from the SDK, so far with no luck

```
const params = {
    TimePeriod: {
      Start: `${startDate}`,
      End: `${endDate}`
    },
    Metrics: ['UNBLENDED_COST'],
    Filter: {      
      Dimensions: {
        Key: "CHARGE_TYPE",
        Values: [ "USAGE"]
      }
    },
    Granularity: 'DAILY',    
    GroupBy: [{
      Key: 'LINKED_ACCOUNT',
      Type: 'DIMENSION'
    }, {
      Key: 'SERVICE',
      Type: 'DIMENSION'
    }]    
  }
```

#### SDK version number
`@aws-sdk/client-cost-explorer": "3.5.0`

#### Is the issue in the browser/Node.js/ReactNative?
node.js

#### Details of the browser/Node.js/ReactNative version
```
node --version
v14.15.1
```

## Steps to reproduce
```
async function getCostReportForTheDay (startDate, endDate) {
  const client = new CostExplorerClient({})

  const params = {
    TimePeriod: {
      Start: `${startDate}`,
      End: `${endDate}`
    },
    Metrics: ['UNBLENDED_COST'],
    Filter: {      
      Dimensions: {
        Key: "CHARGE_TYPE",
        Values: [ "USAGE"]
      }
    },
    Granularity: 'DAILY',    
    GroupBy: [{
      Key: 'LINKED_ACCOUNT',
      Type: 'DIMENSION'
    }, {
      Key: 'SERVICE',
      Type: 'DIMENSION'
    }]    
  }

  const command = new GetCostAndUsageCommand(params)

  try {
    const data = await client.send(command)

    return data
  } catch (error) {
    throw new Error(error)
  }
}
```

#### Observed behavior
```
{
    "errorMessage": "ValidationException: Dimension CHARGE_TYPE is not allowed. Allowed dimension(s): SAVINGS_PLAN_ARN, RESERVATION_ID, AZ, CACHE_ENGINE, INSTANCE_TYPE_FAMILY, INSTANCE_TYPE, SAVINGS_PLANS_TYPE, PURCHASE_TYPE, LINKED_ACCOUNT, REGION, SERVICE, LEGAL_ENTITY_NAME, USAGE_TYPE, PLATFORM, USAGE_TYPE_GROUP, OPERATION, OPERATING_SYSTEM, DATABASE_ENGINE, TENANCY, BILLING_ENTITY, RECORD_TYPE, DEPLOYMENT_OPTION",
    "errorType": "Error",
    "stackTrace": [
        "Error: ValidationException: Dimension CHARGE_TYPE is not allowed. Allowed dimension(s): SAVINGS_PLAN_ARN, RESERVATION_ID, AZ, CACHE_ENGINE, INSTANCE_TYPE_FAMILY, INSTANCE_TYPE, SAVINGS_PLANS_TYPE, PURCHASE_TYPE, LINKED_ACCOUNT, REGION, SERVICE, LEGAL_ENTITY_NAME, USAGE_TYPE, PLATFORM, USAGE_TYPE_GROUP, OPERATION, OPERATING_SYSTEM, DATABASE_ENGINE, TENANCY, BILLING_ENTITY, RECORD_TYPE, DEPLOYMENT_OPTION",
        "    at getCostReportForTheDay (/Users/matias/Workspace/justos/Aws-Slack-CostReport/report.js:95:11)",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at daily (/Users/matias/Workspace/justos/Aws-Slack-CostReport/report.js:20:16)"
    ]
}
```

#### Expected behavior
I would expect this call to returns the same thing that i'm seeing on the billing dashboard, being able to filter by usage and remove the credits that i have in my account

#### Screenshots
<img width="255" alt="Screen Shot 2021-03-08 at 19 33 07" src="https://user-images.githubusercontent.com/2442390/110390732-30842f00-8045-11eb-928d-fd55185ea31d.png">

**Comment by matiasdecarli** [comment]
@ajredniwja Are you accepting PR's?

**Comment by ajredniwja** [comment]
@matiasdecarli We welcome PRs and that would be in the original repo, I am interested to know what you have in mind as I think for this particular case the change would need to come from the `cost-explorer` team.

**Comment by matiasdecarli** [comment]
Sure, you wanna know about my use case or my proposed implementation?

**Comment by ajredniwja** [comment]
I believe I have some jist of the use case, would like to know more about implementation.

**Comment by matiasdecarli** [comment]
Oh, no idea. I'll figure it out when I look at the actual implementation

**Comment by ajredniwja** [comment]
Yeah the change would have to come from the cost-explorer team as they are not returning the data desired as of now.

**Comment by matiasdecarli** [comment]
Oh alright. I thought it was a `//TO DO` on the SDK, but from what you're saying it's not even implemented on the API?

**Comment by ajredniwja** [comment]
Oh my bad there, thats what I meant when I said the change would need to be implemented by the cost-explorer team dna then it will be implemented by the SDKs.

**Comment by matiasdecarli** [comment]
Oh alright

Any other thing that I can do in order to get the costs without the credits applied? I'm running out of options if I want to use this SDK

**Comment by ocorso** [comment]
Charge type is called "RECORD_TYPE" in the API and "Line item type" in CUR. This is working as intended.

**Comment by matiasdecarli** [comment]
Looks like what I'm looking for is indeed `RECORD_TYPE `

> RECORD_TYPE - The different types of charges such as RI fees, usage costs, tax refunds, and credits.

Would be interesting to understand why on the portal is called "Charge Type", then? 

BTW still not working for me

```
const params = {
    TimePeriod: {
      Start: `${startDate}`,
      End: `${endDate}`
    },
    Metrics: ['UNBLENDED_COST'],
    Filter: {      
      Dimensions: {
        Key: "RECORD_TYPE",
        Values: [ "CUR"]
      }
    },
    Granularity: 'DAILY',    
    GroupBy: [{
      Key: 'LINKED_ACCOUNT',
      Type: 'DIMENSION'
    }, {
      Key: 'SERVICE',
      Type: 'DIMENSION'
    }]    
  }
```

Returns `0.00`, but if I ran this on the portal (with Charge Type on Usage) it returns `> 0`

**Comment by matiasdecarli** [comment]
Any news about this? I'm still not being able to get my daily/monthly costs without credits applied...

**Comment by matiasdecarli** [comment]
Not a lot of customer obsession from Amazon. Finally I fixed this by myself

```
const params = {
    TimePeriod: {
      Start: `${startDate}`,
      End: `${endDate}`
    },
    Metrics: ['UNBLENDED_COST'],
    Filter: {
      Not: {
        Dimensions: {
          Key: "RECORD_TYPE",
          Values: [ "Refund", "Credit" ]
        }
      }
    },
    Granularity: 'DAILY',    
    GroupBy: [{
      Key: 'LINKED_ACCOUNT',
      Type: 'DIMENSION'
    }, {
      Key: 'SERVICE',
      Type: 'DIMENSION'
    }] 
  }
```
