### ISSUE TITLE
The parameter groupName cannot be used with the parameter subnet

### ISSUE THREAD

**Issue by abarke** [aws/aws-sdk#401]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Error when running a combination of commands.

**SDK version number**
aws-cli/1.18.147 Python/2.7.18 Linux/4.14.193-149.317.amzn2.x86_64 botocore/1.18.6

**Platform/OS/Hardware/Device**
EC2 t2.large Linux/4.14.193-149.317.amzn2.x86_64

**To Reproduce (observed behavior)**

Command: 
```
aws ec2 --profile default run-instances --subnet-id subnet-11111111111111111 --image-id ami-1111111111111111 --instance-type m5.xlarge --key-name my-key --security-groups default --count 1
```

Output: 
An error occurred (InvalidParameterCombination) when calling the RunInstances operation: The parameter groupName cannot be used with the parameter subnet

Solution (use --security-group-ids): 
```
aws ec2 --profile default run-instances --subnet-id subnet-11111111111111111 --image-id ami-1111111111111111 --instance-type m5.xlarge --key-name my-key --security-group-ids sg-1111111111111111 --count 1
```

**Expected behavior**
There should not be an error

**Logs/output**
Not putting debug info with security tokens in a public context.

**Additional context**

**Comment by tim-finnigan** [comment]
P75233805

**Comment by tim-finnigan** [comment]
We heard back from the EC2 docs team who removed this from the documentation: 
> For a nondefault VPC, you must use security group IDs instead

For more background on EC2-Classic and security groups you can also refer to this comment: https://github.com/aws/aws-sdk/issues/402#issuecomment-1339824396. For further assistance related to this we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/).
