### ISSUE TITLE
The security group 'XXX' does not exist in default VPC 'YYY'

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws/aws-sdk#402]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

root@Alexey-HP:~# aws --version
aws-cli/2.0.27 Python/3.7.3 Linux/4.4.0-19041-Microsoft botocore/2.0.0dev31

**Describe the question**

I have deleted default VPC (default security group has been deleted automatically) and created new default VPC (default security group has been added automatically).

Unfortunately there is no rule to allow inbound 'ssh' traffic by default, so I have to create one:

root@Alexey-HP:~# aws ec2 authorize-security-group-ingress \
> --group-name sg-040a24e0f8d5aca4c \
> --protocol tcp \
> --port 22 \
> --cidr 0.0.0.0/0

An error occurred (InvalidGroup.NotFound) when calling the AuthorizeSecurityGroupIngress operation: The security group 'sg-040a24e0f8d5aca4c' does not exist in default VPC 'vpc-0965ff934a4aaecaf'

root@Alexey-HP:~# aws ec2 describe-security-groups
SECURITYGROUPS  default VPC security group      sg-040a24e0f8d5aca4c    default 466641473194    vpc-0965ff934a4aaecaf
IPPERMISSIONS   -1
USERIDGROUPPAIRS        sg-040a24e0f8d5aca4c    466641473194
IPPERMISSIONSEGRESS     -1
IPRANGES        0.0.0.0/0

root@Alexey-HP:~# aws ec2 describe-vpcs
VPCS    172.31.0.0/16   dopt-a7e848ce   default True    466641473194    available       vpc-0965ff934a4aaecaf
CIDRBLOCKASSOCIATIONSET vpc-cidr-assoc-03a8f45687c587484        172.31.0.0/16
CIDRBLOCKSTATE  associated
TAGS    Name    pgpro-vpc

What does this error mean? How does default security group not exist in default default VPC ? How to create inbound ssh rule ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by tim-finnigan** [comment]
P75235043

**Comment by tim-finnigan** [comment]
We heard back from the EC2 team who noted that there are two type of security groups. They are either for EC2-Classic or a VPC. The examples with [EC2-Classic] in their example title work only for EC2-Classic. With EC2-Classic, the security group name is the unique identifier. With security groups for a VPC, the ID is the unique identifier. 

There is also a deprecation note in the EC2 [documentation](https://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html) for EC2-Classic:

>We are retiring EC2-Classic. We recommend that you migrate from EC2-Classic to a VPC. For more information, see [Migrate from EC2-Classic to a VPC](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/vpc-migrate.html) in the Amazon Elastic Compute Cloud User Guide .

For further assistance related to this we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/).

**Comment by congbang-le** [comment]
> are two type of security groups. They are either for EC2-Classic or a VPC. The examples with [EC2-Classic] in their example title work only for EC2-Classic. With EC2-Classic, the security group name is the unique identifier. With security groups for a VPC, the ID is the unique identifier.

With your information, I can fix that problem in my Terraform code. At first, I used:
```
resource "aws_security_group" "sg" {
  name        = "allow_access"
  vpc_id      = aws_vpc.vpc.id
  ....
}
resource "aws_spot_instance_request" "vm" {
  ....
  security_groups = ["${aws_security_group.sg.**id**}"]
  ....
```
It got the same error ` InvalidGroup.NotFound: The security group 'sg-XXXXX' does not exist in VPC 'vpc-XXX'`
Then I updated `security_groups = ["${aws_security_group.sg.**id**}"]` to `security_groups = ["${aws_security_group.sg.**name**}"]`. Then it worked!
Thank you~
