### ISSUE TITLE
Estimator.environment not used in SageMaker CreateHyperParameterTuningJob API

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#404]
Original issue: https://github.com/boto/boto3/issues/3488

**Comment by tim-finnigan** [comment]
P75298257

**Comment by lorenzwalthert** [comment]
I think this is resolved with https://aws.amazon.com/about-aws/whats-new/2023/01/amazon-sagemaker-automatic-model-tuning-environment-variables-tuning-jobs/

**Comment by tim-finnigan** [comment]
Thanks for following up here, yes I think this can be closed now. And here is this change was just merged in the SageMaker Python SDK: https://github.com/aws/sagemaker-python-sdk/pull/3614
