### ISSUE TITLE
"ssm start-session": Add convenience helpers (--target-name/--target-tag, port-forward, --command)

### ISSUE THREAD

**Issue by heidemn** [aws/aws-sdk#409]
**Is your feature request related to a problem? Please describe.**
Currently, it's too complicated to 
1\) connect to an instance by "Name" tag, or 
2\) to set up port forwarding, or
3\) to run a custom command.

Also for 2) and 3), a shortcut would improve shell autocompletion.

Current way to do it:

```
# 1)
instance_id="$(aws ec2 describe-instances ....)"
aws ssm start-session \
    --target "$instance_id"

# 2)
aws ssm start-session \
    --target "$instance_id" \
    --document-name AWS-StartPortForwardingSession \
    --parameters '{"portNumber":["80"], "localPortNumber":["56789"]}'

# 3)
aws ssm start-session \
    --target "$instance_id" \
    --document-name AWS-StartInteractiveCommand \
    --parameters 'command=["echo 42"]'
```

**Describe the solution you'd like**

Assuming that the instance has the tag `Name=mongodb`.

```
# 1)
aws ssm start-session \
    --target-name "mongodb"

# Alternative, more flexible:
aws ssm start-session \
    --target-tag "Name=mongodb"

# 2)
aws ssm port-forward \
    --target-name "mongodb" \
    --port 27017 --local-port 27018

# 3)
aws ssm start-session \
    --target "$instance_id" \
    --command "echo 42"
```

**Describe alternatives you've considered**
Writing a custom wrapper, or using 3rd party software, for such simple features should not be required. 

**Additional context**
If the tag specifier is not unique, the tool could print a warning that it will pick `i-12345abcde` of the matching instances.
There could be an additional option to fail with an error instead.

**Comment by tim-finnigan** [comment]
We don't have any updates on this feature request other than that it is still being tracked in the service team's backlog. Because we have already escalated the issue to the appropriate team, we will close this issue for tracking on our end. Please feel free to check back in the future for updates — we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.
