### ISSUE TITLE
Support GPG encrypted credentials

### ISSUE THREAD

**Issue by a-h** [aws/aws-sdk#41]
The `~/.aws/credentials` file is unencrypted by default.

Several mitigations can be put in place, e.g.:

* AWS CLI documentation states to limit access to the file (`chmod 600`) to protect the file from being accessed by other users of the computer
* You can apply full disk encryption to the computer to protect the credentials in the case that an attacker removed the disk from the computer
* Using `sts assume-role` in conjunction with MFA, reducing the impact of losing the credentials, since the IAM user contains no permissions until assuming role, and the MFA device would also need to be lost
* Using 3rd party solutions to encrypt a single set of AWS secret keys and access keys using GPG (so that the keys are decrypted using a security key when needed - e.g. YubiKey or Nitrokey). https://github.com/firstlookmedia/aws-profile-gpg

But it just struck me as odd. I was looking for a way to better secure the credentials file, when I found this issue: https://github.com/naftulikay/aws-env/issues/10

The utility simply looks for `credentials.gpg` file, and if it exists, decrypts it and uses it instead of the `credentials` file. If GPG requires a physical card to decrypt the credentials, then the user would be prompted.

Is that something that the AWS CLI could do?

**Comment by a-h** [comment]
Things have, of course, moved on since I opened this ticket more than 2 years ago.

I think the best way to avoid static creds would be to use AWS SSO for authentication, assuming roles in target accounts. However, although the AWS CLI v2 supports CLI authentication, not all of the client SDKs have been updated, so it's not a straightforward option.

For example, the Go SDK supports it, but the Node.js SDK doesn't: https://github.com/aws/aws-sdk-js/issues/2772 (Some clarity on what's going on with that from the team would be useful.)

This means that tools like Serverless Framework can't support AWS SSO without the help of some other tool to populate the environment.

**Comment by tim-finnigan** [comment]
JavaScript v3 now has documented support for SSO: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso/index.html

Also here is more general documentation on SSO (now IAM Identity Center) support among SDKs: https://docs.aws.amazon.com/sdkref/latest/guide/access-sso.html

I'm not sure if that update is sufficient but please let us know if you had any other feedback related to this.

**Comment by tim-finnigan** [comment]
Given that SSO is available across SDKs as mentioned above I'm going to close this issue. For anything follow up questions please consider creating a new issue.
