### ISSUE TITLE
New instance tags available in metadata service are conflicting with spaced tags

### ISSUE THREAD

**Issue by Darthstevo** [aws/aws-sdk#410]
### Describe the bug

After the change here https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/

I dealt with some issues with instances and tagging. Due to the strict guidelines on "spacing":
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

This of course is a bit a of a conflict when following steps for SSM Patch work:
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-patch-patchgroups.html#how-it-works-patch-groups

The warning is there, but this is a bit conflicting. If you need both:

1. View tags via Instance metadata.
2. Have spacing for custom tagging and other services as mentioned above for SSM patch group solution.

### Expected Behavior

I did not expect any conflicts until this new change.

### Current Behavior

Via AWS CLI, I found there are not options to view if an instance has the "instance metadata tags" option enabled or not.
https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-metadata-options.html

There are only 2 options:

Possible values:

    disabled
    enabled

### Reproduction Steps

aws ec2 modify-instance-metadata-options --instance-id <instance-ID>
and
aws ec2 describe-instances --instance-id <instance-ID>
Can show the IMDS endpoint, etc. But does not show "instance-metadata-tags"
 

### Possible Solution

Any ways to satisfy both; instance metadata and tag spacing would be great.

But, if we can at least have the option to view what is the status for an instance metadata tag via AWS cli, this would go a long way vs searching every instance..

Right now, it is either enable or disable as the documentation [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceMetadataOptions.html#API_ModifyInstanceMetadataOptions_RequestParameters)

Only other option to view the status is via console, AWS docs:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#turn-off-access-to-tags-in-IMDS

### Additional Information/Context

Any pointers to view which instances have the "instance-metadata-tags" enabled or not, is appreciated.

### CLI version used

aws-cli/2.0.30

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by tim-finnigan** [comment]
Checking in - I received an update that this documentation has been updated: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-patch-group-tagging.html#sysman-patch-group-tagging-ec2

Note the warning highlighted in Task 1:
>You can't apply the `Patch Group` tag (with a space) to an Amazon EC2 instance if the Allow tags in instance metadata option is enabled on the instance. Allowing tags in instance metadata prevents tag key names from containing spaces. If you have [allowed tags in EC2 instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#allow-access-to-tags-in-IMDS), you must use the tag key `PatchGroup` (without a space).

Does that help clarify the behavior here? Please let us know if you had any follow up questions regarding this issue.
