### ISSUE TITLE
eks.describe-addon-versions: add --platform-version

### ISSUE THREAD

**Issue by awoimbee** [aws/aws-sdk#411]
**Is your feature request related to a problem? Please describe.**
I manage EKS clusters. To find the latest/appropriate version of eks addons to deploy I use the following command:
```console
$ aws eks describe-addon-versions --kubernetes-version=1.21 --addon-name=aws-ebs-csi-driver --query='addons[0].addonVersions[0].addonVersion'
"v1.5.2-eksbuild.1"
```
Problem: the addon `aws-ebs-csi-driver` `v1.5.2-eksbuild.1` requires platform version "`eks.5+`" and my cluster is "`eks.4`".

**Describe the solution you'd like**
Either AWS gives me the ability to manually upgrade the platform version of my cluster, or the AWS CLI allows me to filter addons by platform version.
I would like a dedicated `--platform-version` arg with version matching (`eks.3` matches `eks.1+`, `eks.3+` but not `eks.4+`).

**Describe alternatives you've considered**
Filter the output of `aws eks describe-addon-versions` with jq -> matching versions (eg `eks.2` matches `eks.1+`) is a pain.

**Comment by tim-finnigan** [comment]
P75461516

**Comment by tim-finnigan** [comment]
Thanks for your patience — the internal ticket we opened seemed to have fallen off of the EKS team's radar but we recently followed up again for an update. They responded and questioned if this feature request was still needed, considering that EKS addons has changed how permissions are handled last year...and ideally you should not have any platform dependency for addons. 

I'm going to close this issue as it is something the EKS team is not considering at this time. But if you would like me to forward any further info to that team (such as more details on use cases) please let me know. If you have a support plan then I recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for more direct correspondence.
