### ISSUE TITLE
SQS add-permission does not support adding a non-account principal

### ISSUE THREAD

**Issue by majsty** [aws/aws-sdk#414]
### Describe the bug

The [docs for add-permission](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/add-permission.html) describe the operation as follows:
>Adds a permission to a queue for a specific [principal](https://docs.aws.amazon.com/general/latest/gr/glos-chap.html#P)

The linked definition of _principal_ describes it as:
>The user, service, or account that receives permissions that are defined in a policy

However, the `add-permission` operation only seems to work with an Account ID.

### Expected Behavior

In addition to accepting an Account ID the operation should accept the Arn for _any_ principal (user, role, etc)

### Current Behavior

When specifying an Arn for a user (or a UserId), the CLI returns the following error:

`An error occurred (InvalidParameterValue) when calling the AddPermission operation: Value [Arn] for parameter PrincipalId is invalid. Reason: Unable to verify principal.`

### Reproduction Steps

1. Create a user in IAM and note the Arn
2. Create a SQS queue and note the URL
3. call `aws sqs add-permission --queue-url [URL from Step 2] --label test --aws-account-ids [Arn from Step 1] --actions SendMessage`

Expected: it works and no error is returns
Actual: `An error occurred (InvalidParameterValue) when calling the AddPermission operation: Value [Arn] for parameter PrincipalId is invalid. Reason: Unable to verify principal.`

### Possible Solution

Perhaps the validation of the `--aws-account-ids` parameter only validates an Account ID, and needs to be expanded to also allow an Arn to be specified?

### Additional Information/Context

If non-account principals are simply not supported by this operation, then the documentation should be updated to emphasise this.

### CLI version used

2.8.2

### Environment details (OS name and version, etc.)

macOS 12.5.1

**Comment by majsty** [comment]
@aBurmeseDev have you received clarification from the SQS team yet?

**Comment by aBurmeseDev** [comment]
@majsty - thanks for following up. I have not received any feedback from the SQS team as of now. But I created an internal ticket and will post an update once I hear back. 

P76622602

**Comment by majsty** [comment]
Happy new year @aBurmeseDev - any updates?

**Comment by aBurmeseDev** [comment]
Happy new year @majsty! Thank you for waiting patiently. I heard back from a SQS team member and here's their response:

> We use the wording principle because the root account needs to make explicit in their principle to make sure the other has access and the `--aws-account-ids` flag only takes AWS Account IDs as parameter. The queue ARN won't work in this case and that it's by design. Supplying account ID would also be less error prone.

Hope that makes sense and please let me know if you have any further questions!

**Comment by CameronMcAuley** [comment]
I'm not 100% satisfied that this has been completely resolved @aBurmeseDev. 
We can manually add role/user ARNs to the SQS role via the console but we can't do it via the CLI without using a 'hacky' method:

1. Get the SQS queue policy with `aws sqs get-queue-attributes`, pass this resulting json in to something like jq for parsing and merge together a new JSON object including the role ARN you want to add:

```
aws sqs get-queue-attributes --region us-east-1 \
  --queue-url https://sqs.us-east-1.amazonaws.com/${account_id}/${sqs_queue_name} \
  --attribute-names Policy \
  | jq --arg account_id "$account_id" \
       --arg my_role_arn "$my_role_arn" \
       --arg region "us-east-1" \
       --arg sqs_queue_name "$sqs_queue_name" \
      '.Attributes.Policy | fromjson | .Statement += [{"Sid": "Allow-EKS","Effect": "Allow", 
      "Principal": { "AWS": "arn:aws:iam::\($account_id):role/\($my_role_arn)" }, 
      "Action": [ "sqs:SendMessage", "sqs:DeleteMessage", "sqs:ReceiveMessage" ], "Resource": "arn:aws:sqs:\($region):\($account_id):\($sqs_queue_name)"}] 
      | tojson | {Policy: .}' > sqs_policy.json
```

2. Update the SQS queue with the new hacked together JSON

```
aws sqs set-queue-attributes --region us-east-1 \
  --queue-url https://sqs.us-east-1.amazonaws.com/${account_id}/${sqs_queue_name} \
  --attributes file://sqs_policy.json
```

This is not user friendly at all and it would be great if there was an easier way to add a role or user ARN to a SQS queue policy.

As @majsty mentioned, can this be re-opened and converted to a feature request?

**Comment by aBurmeseDev** [comment]
Hi @CameronMcAuley - thanks for following up. 

The issue was accidentally closed by github-actions but I've already reopened it as you can see it's currently in open status. Sorry for the confusion. 

I could relay this info back to service team and would be happy to look into it myself. As far as converting this into a FR, we would have to check how other SDK behaves in this matter before making it a FR because this is more of service related concern rather than SDKs and as we'd like to try to keep features consistent between SDKs.

**Comment by majsty** [comment]
Completely agree with @CameronMcAuley. The current state is bad because it is:
* a security risk (encourages breach of least privilege)
* blocking users from doing something that is possible in the console

Could you please confirm that it's not simply caused by overly zealous validation of the `aws-account-ids` parameter? See my suggestion from my original post:
>Perhaps the validation of the --aws-account-ids parameter only validates an Account ID, and needs to be expanded to also allow an Arn to be specified?

**Comment by majsty** [comment]
Hi, any progress on this over the last two months @aBurmeseDev ?

**Comment by aBurmeseDev** [comment]
@majsty - thanks for following up and apologies for the delay. I shared your feedback with service team awhile ago and reached out to them again for their insights on this. Will update once I hear back.

**Comment by majsty** [comment]
Hi @aBurmeseDev, I don't suppose you received any insights from the service team?

**Comment by aBurmeseDev** [comment]
Hi @majsty - I just heard back from a service team member and here's their response.

Thank you for providing the feedback. We can confirm that the SQS `AddPermission` API currently by design does not support non-account principal. See `AddPermission` API reference here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_AddPermission.html. We will look into prioritizing this feature request and expanding the `AddPermission` API to handle other principal types. However, at this moment, we can not provide an estimate. Meanwhile, we recommend you to use [`SetQueueAttributes`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/set-queue-attributes.html) to update your policy for granular customizations of your own SQS resource policies.

I'm going to convert this to feature-request and keep it open. Feel free to check back in for future updates.
Best,
John

**Comment by aBurmeseDev** [comment]
Hi everyone on the thread - thank you for your feedback. I wanted to share that we've let responsible internal team know and they've placed this on their backlog. We can't share specific timelines on when this might be implemented in GitHub; please monitor the [AWS CLI Changelog](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst) for updates.
