### ISSUE TITLE
AWS Batch submit-job should let select the image tag

### ISSUE THREAD

**Issue by IdoPort** [aws/aws-sdk#428]
### Describe the feature

Enable changing the docker image tag defined in the job template when submitting a job.
This can be done by a parameter called --docker-tag which is defaulted to the one from the job definition.

### Use Case

We have a batch process that runs on a bucket in s3 and extracts data from the files in it.
Each developer working on this process is responsible for extracting another piece of data from those files.
When running tests we want developers to check that they were able to extract the new data by running the batch process with their own code prior to completing the task.
Our process is as follows:
Create feature branch -> Make changes -> create docker image with specific tag -> run batch process with created image -> inspect results.

To do that we currently need to create a new job definition for every branch.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.9.1 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 11

**Comment by tim-finnigan** [comment]
P76532268

**Comment by tim-finnigan** [comment]
We heard back from the AWS Batch team who created a backlog item for this feature request. We can't guarantee if or when this would be implemented but feel free to check back here for updates or by reaching out through [AWS Support](https://aws.amazon.com/contact-us/).
