### ISSUE TITLE
Feature request: add waiter for SSM command invocation

### ISSUE THREAD

**Issue by zl4bv** [aws/aws-sdk#43]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

50ba1df

### What issue did you see?

It would be useful to have an `ssm.WaitUntilCommandInvocationCompleted` method or similar so one can send an SSM command and wait before trying to collect the output.

**Comment by tim-finnigan** [comment]
Closing this as I believe what you requested is accomplished by the [WaitUntilCommandExecuted](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.WaitUntilCommandExecuted) waiter. Please let me know if you had any follow up questions or feedback.
