### ISSUE TITLE
AmazonCloudFormationException is listed in Cloudformation.DescribeStacks but does not exist

### ISSUE THREAD

**Issue by kanbara** [aws/aws-sdk#44]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

Any

### Version of Go (`go version`)?

1.13.4

### What issue did you see?

CloudFormation.DescribeStacks says that it will return an `AmazonCloudFormationException` if the stack does not exist, but there is no trace of this exception in the code.

e.g.

```
DescribeStacks API operation for AWS CloudFormation.

Returns the description for the specified stack; if no stack name was specified, then it returns the description for all the stacks created.

If the stack does not exist, an AmazonCloudFormationException is returned.

Returns awserr.Error for service API and SDK errors. Use runtime type assertions with awserr.Error's Code and Message methods to get detailed information about the error.

See the AWS API reference guide for AWS CloudFormation's API operation DescribeStacks for usage and error information. See also, https://docs.aws.amazon.com/goto/WebAPI/cloudformation-2010-05-15/DescribeStacks
```

### Steps to reproduce

Search through AWS documentation as well as the aws-sdk-go, and find no reference to the implementation of this error on the Go side. If it is returned from the API, there is no way to tell that this error is there, and use it in code.

**Comment by stobrien89** [comment]
Hi @suroh1994,

 I actually submitted a ticket for this a few days ago, but forgot to update the thread.  I asked the cloudformation team for more clarity on this and/or to update their documentation.  I'll provide an update here once I've received one!

**Comment by stobrien89** [comment]
P51484521

**Comment by stobrien89** [comment]
The Cloudformation docs writers have removed this exception from the documentation.  Let us know if you have any questions!
