### ISSUE TITLE
Import from S3 to dynamoDB using pre-existing table

### ISSUE THREAD

**Issue by agostain** [aws/aws-sdk#446]
### Describe the feature

Currently bulk import from S3 bucket to dynamoDB table only supports importing to a new DDB table created by the import_table API. 

import_table should allow to provide a pre-existing DDB table instead of creating a new one at each import.

### Use Case

Import multiple files from s3 to ddb table in different point in time. e.g. parallel execution of file processing and once it's done trigger the import. 
Another use case is to provision the DDB table with IaC (cdk, cfn , other) and handle permissions following the least privilege principle. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.26.36

### Environment details (OS name and version, etc.)

macos

**Comment by tim-finnigan** [comment]
Linking my earlier comment on the older issue you opened: https://github.com/boto/boto3/issues/3540#issuecomment-1366185177

I'll reach out to the DynamoDB team and see if they are considering this feature.

**Comment by frediy** [comment]
This would be very useful for moving data from analytical to operational systems. Our current workaround is to provide a cache with the current prod table name and delete the old ones.

In our use case, we'd want to replace the existing table completely and just keep the table name as a reference to the newly created table so we can remove the table name caching service.

There might be use cases for s3 to dynamo imports into existing tables too, overwriting existing unique keys and keeping old records. We don't have a use case for this atm, but felt worth raising as a possible variation of this feature request.

**Comment by tim-finnigan** [comment]
Thanks for following up. We heard back from the DynamoDB team and found they were already tracking this feature request. Please feel free to check back in the future for updates — we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.
