### ISSUE TITLE
EC2: paginator for "describe-vpc-endpoint-services" command

### ISSUE THREAD

**Issue by Obirah** [aws/aws-sdk#447]
### Describe the feature

The `describe-vpc-endpoint-services` operation is paginated (the request and response objects at least contain `maxResults` and `nextToken`), however there is no paginator in the aws-sdk for Java. I would suggest to implement/generate it as it is for other EC2 operations (e.g. the `describeVpcEndpointsPaginator`).

### Use Case

Any API call which requires to query multiple pages of VPC endpoint services requires to be put into a loop right now.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.19.x

### JDK version used

17.0.5

### Operating System and version

macOs 12.x

**Comment by debora-ito** [comment]
The service team acknowledged the request, it was added to their backlog. As usual, we don't comment on release timeline.

Closing this issue, since there's nothing pending on the SDK team.
