### ISSUE TITLE
RequestTooLargeException vs RequestEntityTooLargeException

### ISSUE THREAD

**Issue by erjiang** [aws/aws-sdk#45]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
1.27.4

### Version of Go (`go version`)?
1.13.5

### What issue did you see?
I tried to filter errors coming from Invoke for "RequestTooLargeException" but I actually got the error "RequestEntityTooLarge" exception:

```sh
2020/01/15 14:51:45 Error invoking lambda function
2020/01/15 14:51:45 RequestEntityTooLargeException: Request must be smaller than 6291456 bytes for the InvokeFunction operation
        status code: 413, request id: 4f90b35e-c583-4c6e-bccb-9956291dd896
```

My error handling code looked like:
```go
log.Println("Error invoking lambda function")
log.Println(err)
awsErr, ok := err.(awserr.Error)
if ok && awsErr.Code() == lambda.ErrCodeRequestTooLargeException {
	log.Fatal("Request too large") // never gets called, because the error codes do not match
}
```

The SDK defines lambda.ErrCodeRequestTooLargeException, but not lambda.ErrCodeRequestEntityTooLargeException. So, am I looking in the wrong place for the error code constant? What's the difference between RequestTooLargeException and  RequestEntityTooLargeException? (The descriptions seem to describe the same thing.)

Workaround was just to use a string instead of referencing a constant from the package.

**Comment by vudh1** [comment]
P70312107

**Comment by ashishdhingra** [comment]
Contacted service team for an update. Awaiting response.

**Comment by ashishdhingra** [comment]
Followed with service team again. `RequestEntityTooLargeException` is not modeled per `Invoke` API documentation and AWS [model](https://github.com/aws/aws-models/blob/d8ef92e5bd221e159377c36949ec341b48b82ec4/lambda/2015-03-31/api-2.json#L551).

**Comment by ashishdhingra** [comment]
Contacted service team for an update. Awaiting response.

**Comment by ashishdhingra** [comment]
We have opened product feature request with the service team. As of now, we do not have ETA on when this would be implemented. It should be reviewed by service team along with other priority items. Since no action is required from our side (SDK), closing this issue.
