### ISSUE TITLE
Method initiateAuth does not return updated RefreshToken in response.

### ISSUE THREAD

**Issue by Mifrill** [aws/aws-sdk#454]
### Describe the bug

When `initiateAuth` called the `AuthenticationResult` does not contain `RefreshToken`.

```ts
import { CognitoIdentityProvider } from '@aws-sdk/client-cognito-identity-provider'

const client = new CognitoIdentityProvider({ region: 'eu-west-1' })
const results = await client.initiateAuth({
  AuthFlow: 'REFRESH_TOKEN',
  ClientId: clientId,
  AuthParameters: {
    REFRESH_TOKEN: refreshToken
  }
})
```

According to documentation https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html:
```
Response Syntax
{
   "[AuthenticationResult](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#CognitoUserPools-InitiateAuth-response-AuthenticationResult)": { 
      "[AccessToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html#CognitoUserPools-Type-AuthenticationResultType-AccessToken)": "string",
      "[ExpiresIn](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html#CognitoUserPools-Type-AuthenticationResultType-ExpiresIn)": number,
      "[IdToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html#CognitoUserPools-Type-AuthenticationResultType-IdToken)": "string",
      "[NewDeviceMetadata](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html#CognitoUserPools-Type-AuthenticationResultType-NewDeviceMetadata)": { 
         "[DeviceGroupKey](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_NewDeviceMetadataType.html#CognitoUserPools-Type-NewDeviceMetadataType-DeviceGroupKey)": "string",
         "[DeviceKey](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_NewDeviceMetadataType.html#CognitoUserPools-Type-NewDeviceMetadataType-DeviceKey)": "string"
      },
      "[RefreshToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html#CognitoUserPools-Type-AuthenticationResultType-RefreshToken)": "string",
      "[TokenType](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html#CognitoUserPools-Type-AuthenticationResultType-TokenType)": "string"
   },
   "[ChallengeName](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#CognitoUserPools-InitiateAuth-response-ChallengeName)": "string",
   "[ChallengeParameters](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#CognitoUserPools-InitiateAuth-response-ChallengeParameters)": { 
      "string" : "string" 
   },
   "[Session](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#CognitoUserPools-InitiateAuth-response-Session)": "string"
}
```
It's `Required: No` 
```
RefreshToken
The refresh token.

Type: String

Pattern: [A-Za-z0-9-_=.]+

Required: No
```
As I understand or we should not have `RefreshToken` property in response or we should have it as `string` but not undefined.

### Expected Behavior

Expect a new RefreshToken.

### Current Behavior

```ts
AuthenticationResult.RefreshToken === undefined
```

### Reproduction Steps

https://github.com/Mifrill/bug-reproduce-aws-sdk-js-v3-missing-refresh-token

Follow the steps in README.md

Output:
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'FILTERED_OUT',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  AuthenticationResult: {
    AccessToken: 'FILTERED_OUT',
    ExpiresIn: 3600,
    IdToken: 'FILTERED_OUT',
    NewDeviceMetadata: undefined,
    RefreshToken: undefined,
    TokenType: 'Bearer'
  },
  ChallengeName: undefined,
  ChallengeParameters: {},
  Session: undefined
}
--------------------------------------------------------------
Expect updated RefreshToken that !== process.env.REFRESH_TOKEN
--------------------------------------------------------------

```

### Additional Information/Context

Possible duplicate of https://github.com/aws/aws-sdk-js-v3/issues/3548.

About note:
> The example code you are trying to run looks like the V2 of the of the JS SDK but the package your referring to is V3 so the error might be coming from there.

It's not clear how to send this request for V3 version. I did try this way with no success:
`const client = new CognitoIdentityProvider({ region: 'eu-west-1', apiVersion: '2016-04-18' })`

Note:
> Apparently this is a bug in the AWS Cognito API. The [docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) say that InitiateAuth should return an updated RefreshToken, but it does not.

Source: https://stackoverflow.com/questions/55069851/how-to-get-refresh-token-auth-request-to-return-refreshtoken

### SDK version used

"@aws-sdk/client-cognito-identity-provider": "version": "3.130.0"

### Environment details (OS name and version, etc.)

node -v v16.13.0

**Comment by RanVaknin** [comment]
Hi @Mifrill,

After taking a deeper look into the docs the following statement is correct.

Cognito does not return/rotate a new refresh token for refresh token authentication. User has to re-login after refresh token expires.
The refresh token is used to receive a new Access Token and ID Token. 

Please refer to [this doc](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-refresh-token.html) about using refresh token.

**Comment by Mifrill** [comment]
Hey @RanVaknin thanks for the update. Unfortinutally I don't see how this issue was sorted, if the response is correct then we should update the documentation. The like you provided does not contain Response schema, so as I said before:

> As I understand or we should not have RefreshToken property in response or we should have it as string but not undefined.

So, the [documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) is still incorrect:
![image](https://user-images.githubusercontent.com/23525618/217362641-6c027f8d-6e7a-486c-8533-6196563f64e3.png)

**Comment by guhyeon** [comment]
@Mifrill I agree with you.

Hi @RanVaknin, Is there any way that I get new refresh token without login like below way??

https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation
