### ISSUE TITLE
SpotInstanceState missing `disabled`

### ISSUE THREAD

**Issue by andrewbaxter** [aws/aws-sdk#455]
### Describe the bug

The `SpotInstanceState` enum is missing state `disabled` per https://docs.amazonaws.cn/en_us/AWSEC2/latest/UserGuide/spot-request-status.html

The same issue was reported in https://github.com/aws/aws-sdk-cpp/issues/457 and supposedly it's been updated in the api, but it appears to still be missing in the https://raw.githubusercontent.com/aws/aws-sdk-go/main/models/apis/ec2/2016-11-15/api-2.json document.

### Expected Behavior

`"disabled"` should be a listed value

### Current Behavior

The only values present are `open` `active` `closed` `cancelled` and `failed`.

### Reproduction Steps

Library model issue

### Possible Solution

If the api version can't be updated, this may need manual patching.  I'm not sure how it was handled in cpp.

### AWS Go SDK V2 Module Versions Used

ec2 1.77.0

### Compiler and Version used

18

### Operating System and version

linux

**Comment by RanVaknin** [comment]
This is now resolved, you should be able to pull the latest changes and see the missing disabled type.

Thanks for your patience. 
Ran~

**Comment by andrewbaxter** [comment]
Awesome, thanks! :tada:
