### ISSUE TITLE
macie2 GetMember: No Email returned

### ISSUE THREAD

**Issue by lvthillo** [aws/aws-sdk#456]
See [doc](https://docs.aws.amazon.com/macie/latest/APIReference/members-id.html#members-idget) for GetMemberResponseSchema should return email but it's not returned.

Expected:
Response schema:
```
{
  "accountId": "string",
  "administratorAccountId": "string",
  "arn": "string",
  "email": "string",
  "invitedAt": "string",
  "masterAccountId": "string",
  "relationshipStatus": enum,
  "tags": {
  },
  "updatedAt": "string"
}
```

Current behavior:
Email is not returned.

E.g. using AWS CLI:
```
$ aws macie2 get-member --id yyy
{
    "accountId": "xxx",
    "administratorAccountId": "yyy",
    "arn": "arn:aws:macie2:eu-west-1:yyy:member/xxx",
    "masterAccountId": "xxx",
    "relationshipStatus": "Enabled",
    "tags": {},
    "updatedAt": "2023-01-21T17:56:26.570000+00:00"
}
```

Using `boto3` the same is true, no Email is being returned, same for Go.

**Comment by tim-finnigan** [comment]
Hi @lvthillo thanks for reaching out. Based on the docs I would also expect that an email would be returned. Which version of the CLI/SDKs are you using? Have you tried updating to the latest versions? 

If you're still seeing the issue after updating, could you provide your debug logs (with any sensitive info redacted)? To do this with the AWS CLI you would add `--debug` to the command, or with boto3 you would add `boto3.set_stream_logger('')` to your script.

**Comment by tim-finnigan** [comment]
Closing this issue as we have not heard back, if you're still running into this please let us know.
