### ISSUE TITLE
Ec2Waiters should support vpc endpoint creation

### ISSUE THREAD

**Issue by asanthan-amazon** [aws/aws-sdk#458]
### Describe the feature

Hi,
The current `Ec2Waiters` in java sdk v2 does not support `waitUntil` method for vpc endpoint creation. Can you please add it?

### Use Case

When creating vpc endpoints programmatically, we need polling mechanism to wait for endpoint creation status change to completion.

### Proposed Solution

Add `waitUntilVpcEndpointAvailable` method.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.x

### JDK version used

11

### Operating System and version

Any

**Comment by debora-ito** [comment]
P79747471

**Comment by tim-finnigan** [comment]
Thanks for your patience here — this issue is still being tracked in the EC2 team's backlog. Please refer to the [blog](https://aws.amazon.com/blogs/aws/category/compute/amazon-ec2/) or SDK changelog for updates.
