### ISSUE TITLE
MQ API Model sets validation enum of "ACTIVEMQ". Does not correlate with AWS MQ API behaviour

### ISSUE THREAD

**Issue by Dan-Kitchen** [aws/aws-sdk#46]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

github.com/aws/aws-sdk-go v1.26.8

### Version of Go (`go version`)?

go1.13.6 darwin/amd64

### What issue did you see?

The model for mq is out of line with how the AWS MQ API is setting the field `EngineType` - https://github.com/aws/aws-sdk-go/blob/master/models/apis/mq/2017-11-27/api-2.json#L1679

The validation on this is set to "ACTIVEMQ". This is in line with what all the AWS documentation states for this variable.

https://docs.aws.amazon.com/amazon-mq/latest/api-reference/brokers-broker-id.html#brokers-broker-id-model-enginetype

```
$ aws mq describe-broker-engine-types
{
    "BrokerEngineTypes": [
        {
            "EngineType": "ACTIVEMQ",
            "EngineVersions": [
            ....
}
```

The issue is that AWS MQ API internally sets the configured resource value to be `ActiveMQ`, regardless of input value. This is causing problems with `Terraform` in this case (and also how it interacts with `tflint`).

```
$ aws mq create-broker --broker-name example-mq --engine-version 5.15.9 --host-instance-type mq.t2.micro --security-groups "sg-12345" --users ConsoleAccess=true,Password=admin12233443,Username=admin --engine-type AcTiVeMq --deployment-mode SINGLE_INSTANCE
{
    "BrokerArn": "arn:aws:mq:eu-west-1:XXXXXXXXX:broker:example-mq:b-9b75111e-1b20-4c70-a697-3e031a037f28",
    "BrokerId": "b-9b75111e-1b20-4c70-a697-3e031a037f28"
}

$ aws mq describe-broker --broker-id b-9b75111e-1b20-4c70-a697-3e031a037f28
{
    "AutoMinorVersionUpgrade": false,
    "BrokerArn": "arn:aws:mq:eu-west-1:XXXXXXXXXXX:broker:example-mq:b-9b75111e-1b20-4c70-a697-3e031a037f28",
    "BrokerId": "b-9b75111e-1b20-4c70-a697-3e031a037f28",
    "BrokerInstances": [],
    "BrokerName": "example-mq",
    "BrokerState": "CREATION_IN_PROGRESS",
    "Configurations": {
        "History": [],
        "Pending": {
            "Id": "c-5f6ded1d-8461-46cc-ae88-13ac9c0828af",
            "Revision": 1
        }
    },
    "Created": "2020-01-29T15:51:03.64Z",
    "DeploymentMode": "SINGLE_INSTANCE",
    "EncryptionOptions": {
        "UseAwsOwnedKey": true
    },
    "EngineType": "ActiveMQ",
   .....
}
```

Issue seen initially with [tflint](https://github.com/terraform-linters/tflint) validation on Amazon MQ Broker resource. I don't want to go into loads of detail here about specific issue on Terraform so see this issue for more Terraform specific context:

https://github.com/terraform-linters/tflint/issues/602

Initially thinking the issue was with tflint before fully doing my homework I opened an issue there. I've since realised the problem lays further up the chain.

TL:DR

- Terraform `aws_mq_broker` states `ActiveMQ` is the allowed value - https://www.terraform.io/docs/providers/aws/r/mq_broker.html#engine_type
- `tflint` only allows `ACTIVEMQ` as defined in the linked sdk model for mq
- API is actually case insensitive on input
- Contrary to documentation AWS MQ API seems to be setting the value to `ActiveMQ` regardless of input.
- My symptom seen: this behaviour causes Terraform to constantly try to update the resource if the validated value of `ACTIVEMQ` is used as suggested by tflint/sdk api validation.

### Steps to reproduce

Via CLI:

```
$ aws mq create-broker --broker-name example-mq --engine-type AcTiVeMq --engine-version 5.15.9 --host-instance-type mq.t2.micro --security-groups SG_ID --users ConsoleAccess=true,Password=admin12233443,Username=admin --deployment-mode SINGLE_INSTANCE

$ aws mq describe-broker --broker-id BROKER_ID
```

Via SDK (missing a few env specific inputs)

```go
package main

import (
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/mq"
)

func main() {
	sess := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
		Profile:           "",
	}))

	mqSvc := mq.New(sess)

	create_result, create_err := mqSvc.CreateBroker(&mq.CreateBrokerRequest{
		BrokerName:       aws.String("mq-test-engine-type"),
		DeploymentMode:   aws.String("SINGLE_INSTANCE"),
		EngineType:       aws.String("ACTIVEMQ"),
		EngineVersion:    aws.String("5.15.9"),
		HostInstanceType: aws.String("mq.t2.micro"),
		SecurityGroups: []*string{
			aws.String(""),
		},
		Users: []*mq.User{
			{
				ConsoleAccess: aws.Bool(true),
				Password:      aws.String("admin12233443"),
				Username:      aws.String("admin"),
			},
		},
	})

	if create_err != nil {
		fmt.Println("Error", create_err)
		os.Exit(1)
	}

	brokerId := create_result.BrokerId
	fmt.Printf("Created Broker %s\n", *brokerId)

	describe_result, describe_err := mqSvc.DescribeBroker(&mq.DescribeBrokerInput{
		BrokerId: aws.String(*brokerId),
	})

	if describe_err != nil {
		fmt.Println("Error", describe_err)
		os.Exit(1)
	} else {
		fmt.Printf("Broker %s : MQ Engine Type - %s\n", *brokerId, *describe_result.EngineType)
	}
}
```

**Comment by vudh1** [comment]
P32693531

**Comment by vudh1** [comment]
Closing as service team said this will break some important changes.
