### ISSUE TITLE
Add support of Z2.X worker type for AWS Glue for Ray

### ISSUE THREAD

**Issue by jrichard8** [aws/aws-sdk#460]
### Describe the feature

AWS Glue for Ray support only Z2.X worker type.
See official documentation: https://docs.amazonaws.cn/en_us/glue/latest/dg/ray-using.html
Currently list of worker types are fixed to:
```
WorkerTypeStandard,
WorkerTypeG1x,
WorkerTypeG2x,
WorkerTypeG025x,
```

### Use Case

Deploy job for AWS Glue for Ray through SDK or terraform.

### Proposed Solution

To use Glue for Ray via SDK or Terraform, it would be nice to add support for the Z2.X worker type.

```
....
WorkerTypeZ2X,
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

NA

### Go version used

1.19

**Comment by RanVaknin** [comment]
This is now fixed.

Thanks for your patience. 
Ran~
