### ISSUE TITLE
Amazon Kinesis Video Streams GetClip API: return URL to download file from S3

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#461]
Original issue: https://github.com/boto/boto3/issues/3567

**Comment by tim-finnigan** [comment]
P80591637

**Comment by tim-finnigan** [comment]
The service team has acknowledged this feature request and they are tracking it in their backlog. Please reach out through [AWS Support](https://aws.amazon.com/contact-us/) for questions or updates related to this if you have a support plan.

**Comment by diegocatalao** [comment]
Hello, @tim-finnigan 

I made a [change to the boto3 SDK](https://github.com/boto/botocore/compare/develop...eusouagabriel:botocore:develop). Have you been able to evaluate it? It doesn't seem like a task with such high complexity.
