### ISSUE TITLE
Add description/tag support while creating access key id using aws-cli.

### ISSUE THREAD

**Issue by glg-satish-tripathi** [aws/aws-sdk#464]
### Describe the feature

There is no option in aws cli  to create and access key with description/tag as it's there in the aws web console. 
The same this with aw-sdk and aws terraform provider. 

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/111346255/214309775-dc800cdf-7866-4683-99f4-20f73c292c15.png">

### Use Case

This will be very useful in case of automation where we are creating access key using a lambda function on a certain time interval and updating it in Jenkins/Spacelift for AWS china user as AWS china don't have role based access support.  
So the description is necessary to have in order to  give the Access key id a meaningful description.  

### Proposed Solution

aws iam create-access-key --user-name  xyz --description "Key for China user"
aws iam update-access-key --access-key-id xyztxcdc --user xyz-- description "Key for China user"

 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.8.4 Python/3.10.8 Darwin/22.1.0 source/arm64

### Environment details (OS name and version, etc.)

MacOs

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The IAM team is continuing to track this feature request in their backlog. We cannot provide guarantees as to if or when this would be implemented, but please refer to the [blog](https://aws.amazon.com/blogs/security/tag/iam/) or SDK changelog for updates going forward.
