### ISSUE TITLE
ECS ServicesStable waiter does not respect `CODE_DEPLOY` deployment type

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#465]
Original issue: https://github.com/boto/botocore/issues/2865

**Comment by tim-finnigan** [comment]
P80967581

**Comment by tim-finnigan** [comment]
We heard back from the ECS team and they have created a backlog item for this issue. We can't provide ETAs on if/when something like this would get addressed, but feel free to check back in for updates in the future (either here or through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.)

**Comment by ferschubert-hm** [comment]
hey @tim-finnigan any updates on this from the ECS team? Thanks!
