### ISSUE TITLE
--recursive for `aws s3api restore-object`

### ISSUE THREAD

**Issue by nick-youngblut** [aws/aws-sdk#470]
### Describe the feature

This is a pretty obvious feature: include `--recursive` for `aws s3api restore-object` so one can restore all files in a directory without having to do something like:

```
aws s3api list-objects-v2 \
    --bucket bucketname \
    --query "Contents[?StorageClass=='GLACIER']" \
    --output text \
| awk '{print $2}' > glacier-restore-object list.txt


for x in `glacier-restore-object list.txt`
 do
   echo "Begin restoring $x" 
   aws s3api restore-object \
    --restore-request Days=7 \
    --bucket bucketname \
    --key "$x" \
   echo "Done restoring $x"
 Done
```

### Use Case

I'm frustrated when I have to create a long bash command just to restore all files in a directory, versus just providing a `--recursive` parameter to `aws s3api restore-object`

### Proposed Solution

`aws s3api restore-object --recursive` to restore all files/directories in the specified directory object

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/1.27.20 Python/3.11.0 Darwin/21.6.0 botocore/1.29.20

### Environment details (OS name and version, etc.)

Mac OS

**Comment by RyanFitzSimmonsAK** [comment]
The team replied with a suggestion to use S3 batch operations.  Here is the associated documentation for those.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops.html - Batch Operations
https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-initiate-restore-object.html - Restore Object Batch Operation

Please let me know if this works for you, thanks!

**Comment by nick-youngblut** [comment]
Thanks @RyanFitzSimmonsAK for the links!

According to the batch-ops docs:

> You can use S3 Batch Operations to perform large-scale batch operations on Amazon S3 objects

I generally don't need to perform "large-scale" operations, but it would be very helpful to restore a directory (and all contents with the directory) simply by using a `--recursive` flag.

**Comment by RyanFitzSimmonsAK** [comment]
Unfortunately, this is unlikely to be implemented at the service API level.  Batch operations are the preferred mechanism for these sorts of actions in code.  Closing as "not planned."  

If you feel strongly that this should be at least available from the AWS CLI, I'd encourage you to file a ticket and a pull request implementing the functionality with the AWS CLI: https://github.com/aws/aws-cli/ -- be aware that customizations to the S3 client come with a high level of scrutiny.

**Comment by nick-youngblut** [comment]
Maybe a simple bash script example (and/or example python code) could be added to the docs so that users don't have to keep writing their own versions of the same basic code?
