### ISSUE TITLE
Quicksight: conflicting error message/documentation for `UpdateDataSet`/`CustomSql`/`Columns` 

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#471]
Original issue: https://github.com/boto/boto3/issues/3589

Related discussion: https://community.amazonquicksight.com/t/update-data-set-columns-is-an-required-parameter/9781/2

Documentation:
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateDataSet.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_PhysicalTable.html#QS-Type-PhysicalTable-CustomSql
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CustomSql.html

**Comment by tim-finnigan** [comment]
V830691750

**Comment by RyanFitzSimmonsAK** [comment]
The service team has acknowledged this ticket and has a backlog item to correctly document this field as required.  I do not have a specific timeline for implementation to share.  Please refer to an [SDK or AWS CLI changelog](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst) for updates about this going forward.  Thanks again for submitting this issue.
