### ISSUE TITLE
Route53 updates only one CNAME per batch

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#472]
Original issue: https://github.com/boto/boto3/issues/3579

Related issue: https://github.com/octodns/octodns-route53/issues/45#issuecomment-1345664541

re:Post question: https://repost.aws/questions/QUj9pIHHnyRIGKNJqjqLgaZQ/route-53-batch-of-changes-succeeding-but-only-making-one-of-the-changes

**Comment by tim-finnigan** [comment]
V830722892

**Comment by tim-finnigan** [comment]
Checking in - I escalated this issue internally but the team who looked into the issue was unable to reproduce it. Also it does not look like there was any error in the debug logs. I wonder if this was something transient as we haven't heard any other reports of the issue. If this is still something you're running into and can reproduce consistently please let us know and we can revisit the issue.

**Comment by joshsleeper** [comment]
@tim-finnigan huh, well that's a bummer that they couldn't repro!
my team at $work just had to work around this exact issue in the last couple weeks, so it's very much still present from our perspective.

lemme see if I can work out a simple repro example here soon to demonstrate what we were seeing.

**Comment by anemyte** [comment]
> lemme see if I can work out a simple repro example here soon to demonstrate what we were seeing.

There is a script in the original issue https://github.com/boto/boto3/issues/3579 which I used to reproduce the issue and generate that log above.

**Comment by joshsleeper** [comment]
right you are @anemyte, I hadn't looked at the script from the previous thread that closely, but from your output it clearly results in a "completed" run, without noted errors, while still leaving some records missing the trailing dot.

@tim-finnigan is that not evidence enough to push back on the devs that customers can clearly repro?

**Comment by tim-finnigan** [comment]
Thanks for following up, I've reached out again to the Route 53 team and will share any updates here. If you have an [AWS Support](https://aws.amazon.com/contact-us/) plan you could also create a case for more direct correspondence.

**Comment by tim-finnigan** [comment]
Thanks all for your patience here. The Route 53 team has started investigating this issue. I will close this issue because they are tracking it on their end but please feel free to track back for updates in the future.
