### ISSUE TITLE
Add ability to filter SSO permission sets by name

### ISSUE THREAD

**Issue by stephenmuss** [aws/aws-sdk#473]
### Describe the feature

Currently using the sso-admin APIs it is not possible to find a permission set using its name.

[list-permission-sets](https://docs.aws.amazon.com/cli/latest/reference/sso-admin/list-permission-sets.html) allows listing all permission sets but only returns the permission set ARN. It is then necessary to describe each permission set using the ARN to find one with the matching name.

Even in the case of the official AWS terraform provider, it is limited to this approach when using a data source and only providing the permission set name https://github.com/hashicorp/terraform-provider-aws/blob/b6cdb7681a24a97264aa3b1fb368bf1f37a10650/internal/service/ssoadmin/permission_set_data_source.go#L101-L148

This approach is fine in cases where there is only a handful of permission sets, but with a larger number it is far from ideal and limits effective automation.

### Use case

Providing the ability to filter permission sets by name will make automation much simpler and effective when updating permission sets and assignments. Fetching a list of all permission sets and then describing them one by one is inefficient and slows down automation and increases load on AWS APIs unnecessarily.

### Proposed solution

Ideally the API should provide the ability to filter permission sets based on the name, e.g. `--filters AttributePath=Name,AttributeValue=ABC123`

### CLI version used

aws-cli/2.9.23 Python/3.11.2 Darwin/22.2.0 source/arm64

### Environment details (OS name and version, etc.)

MacOS Darwin Kernel Version 22.2.0

**Comment by yenfryherrerafeliz** [comment]
Hi @stephenmuss, thanks for opening this feature request. I have opened a ticket with the correspondent team with this feature request. I will provide updates regarding as soon as the team provides them.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
V833883120

**Comment by ashishdhingra** [comment]
Checked with service team for an update. Awaiting response.

**Comment by ashishdhingra** [comment]
Reached out to service team requesting for an update.

**Comment by rcrof** [comment]
Hi team, is there any update on this?

**Comment by tim-finnigan** [comment]
Checking in - it looks like this is on the service team's roadmap. We can't provide guarantees as to if or when something like this would be implemented, but please refer to the [blog](https://aws.amazon.com/blogs/security/tag/aws-sso/) and [CHANGELOGs](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for further updates.
