### ISSUE TITLE
Expiration date for bucket lifecycle config not accepting any thing other than midnight

### ISSUE THREAD

**Issue by BhuvanaSaiNatti-Prodly** [aws/aws-sdk#478]
Hello!

I wanted to set the expiration date as (current datetime + 12 hours) for bucket life cycle configuration. But neither aws sdk java nor cli is accepting that. 

Please find the response below when I tried to do that. I don't think it is documented in aws docs such way. So, could you please let me know if this is how it works? If so, could you document it (expiration date must be midnight GMT) ? Ow is this something that could be fixed?

**Response from cli**
aws s3api put-bucket-lifecycle-configuration --bucket testbucket --lifecycle-configuration test.json

An error occurred (InvalidArgument) when calling the PutBucketLifecycleConfiguration operation: 'Date' must be at midnight GMT

test.json
{
    "Rules": [
        {
            "Expiration": {
                "Date": "2023-02-18T01:00:00"
            },
            "Filter": {
                "Prefix": ""
            },
            "Status": "Enabled"
        }
    ]
}

### Links

https://docs.aws.amazon.com/AmazonS3/latest/API/API_LifecycleExpiration.html

**Comment by BhuvanaSaiNatti-Prodly** [comment]
Thank you! Then the date cannot be before midnight for sure? If so, Can you please get documentation updated under rules -> expiration -> date too? 

I see that it is documented as such for transitions -> expiration but not under rules -> expiration.

**Comment by aBurmeseDev** [comment]
>Then the date cannot be before midnight for sure?

The current behavior seems that way as it works fine when I set the format to ` ...00:00:00.000Z` and I will have to confirm with the service team if that's expected behavior and update the docs accordingly. For now, you could set the time to "midnight" as shown above to set the expiration.

**Comment by BhuvanaSaiNatti-Prodly** [comment]
Sure, thanks!

**Comment by BhuvanaSaiNatti-Prodly** [comment]
John, Could you please check with s3 team on this question too?
Can expiration of 12 hours be supported by the put-bucket-lifecycle-configuration api? If not, is there any reason behind that?

**Comment by aBurmeseDev** [comment]
@BhuvanaSaiNatti-Prodly - thanks for the question, I will relay that our service team and share updates once I hear back.

**Comment by aBurmeseDev** [comment]
Hi @BhuvanaSaiNatti-Prodly - thank you for waiting patiently. I wanted to share that the [API doc](https://docs.aws.amazon.com/AmazonS3/latest/API/API_LifecycleExpiration.html#AmazonS3-Type-LifecycleExpiration-Date) for LifecycleExpiration has been updated with following text. 
`The date value must conform to the ISO 8601 format. The time is always midnight UTC.`

I'd also like to follow up regarding your question on the support for 12 hours of expiration. Here's the quick response back from the service team:

>Lifecycle operates on a daily basis, starting at 00UTC every day.
Every day we will evaluate the user objects against their lifecycle policy, this is why we require the lifecycle experation date to be in stated at midnight UTC. Documentation on the UTC time can be found [here](https://aws.amazon.com/de/blogs/aws-cloud-financial-management/discovering-and-deleting-incomplete-multipart-uploads-to-lower-amazon-s3-costs/) and [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html)
_**Important Note: Lifecycle rules run once a day at midnight Universal Coordinated Time (UTC) and new lifecycle rules can take up to 48 hours to complete the first run.**_
_Amazon S3 calculates the time by adding the number of days specified in the rule to the object creation time and rounding the resulting time to the next day midnight UTC. For example, if an object was created at 1/15/2014 10:30 AM UTC and you specify 3 days in a transition rule, then the transition date of the object would be calculated as 1/19/2014 00:00 UTC._ 

Hope that helps answer your question, please let us know if you have any other questions.
Best,
John

**Comment by BhuvanaSaiNatti-Prodly** [comment]
Thanks so much John!!

**Comment by peterwoodworth** [comment]
This seems resolved, closing out.
