### ISSUE TITLE
Bucket lifecycle configuration for localstack doesn’t work

### ISSUE THREAD

**Issue by BhuvanaSaiNatti-Prodly** [aws/aws-sdk#479]
Hello!

I tried to apply bucket life cycle configuration (with expiration 1 day) for s3 buckets when running aws using localstack (awslocal)
But objects in buckets are not being expired even after a few days. 

1. Is it that bucket life cycle configuration doesn’t work in localstack?
2. Also, could you please confirm if bucket life cycle configuration doesn’t delete the buckets? It only deletes the objects inside buckets?

**Steps I followed again today to show you what I did :** 

_**Set life cycle config on bucket :**_ 
awslocal s3api put-bucket-lifecycle-configuration --bucket testbucket --lifecycle-configuration file:///Users/bhuvanasainatti/test.json

_**Get life cycle of bucket :**_
awslocal s3api get-bucket-lifecycle --bucket testbucket
`{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "Status": "Enabled"
        }
    ]
}`

_**Contents of bucket :**_ 
awslocal s3 ls s3://testbucket/                             
2023-02-21 12:38:23        414 testfile.rtf

_**Fetching head-object DOES NOT SHOW EXPIRATION :**_ 
awslocal s3api head-object --bucket testbucket --key testfile.rtf
{
    "LastModified": "2023-02-21T11:38:23+00:00",
    "ContentLength": 414,
    "ETag": "\"e04ad9c72a77cc3eb9d5b8af7141ad0d\"",
    "ContentType": "application/rtf",
    "Metadata": {}
}

**Comment by aBurmeseDev** [comment]
Hi @BhuvanaSaiNatti-Prodly - apology for not getting here sooner.

It seems like you're using awslocal which isn't owned or supported by AWS. This repo might be where you might want to reach out to: https://github.com/localstack/awscli-local

Best,
John
