### ISSUE TITLE
Add waiters methods for servicecatalog 

### ISSUE THREAD

**Issue by gregory-v** [aws/aws-sdk#48]
Add waiters methods for servicecatalog like is done for cloudformation.
aws/aws-sdk-go#3148

**Comment by KaibaLopez** [comment]
P51237744

**Comment by KaibaLopez** [comment]
Update from the service team:
> There is nothing to wait for -- if the SDK method returns (indicating that the HTTP request completed), then the operation is complete. 
> It's not that it isn't feasible, it's that it's not necessary. If we implemented the APIs, they would return true 100% of the time. 
sorry for the time it took, closing this

**Comment by tim-finnigan** [comment]
Closing this based on [comment](https://github.com/aws/aws-sdk/issues/48#issuecomment-1042097658) above. If you have any additional feedback please reopen or create a new issue. Thanks!
