### ISSUE TITLE
InstanceType is missing m7g and r7g instances

### ISSUE THREAD

**Issue by eejbyfeldt** [aws/aws-sdk#483]
### Describe the bug

The enum `software.amazon.awssdk.services.ec2.model.InstanceType` the new instancetypes in m7g and r7g that were recently launched: https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-ec2-m7g-r7g-instances/

### Expected Behavior

I expect instances in the family m7g and r7g to be in the enum.

### Current Behavior

Current versions of the sdk do not recognize these instances.

### Reproduction Steps

N/A.

### Possible Solution

Add the new instance types.

### AWS Java SDK version used

2.20.12

### JDK version used

N/A

### Operating System and version

N/A

**Comment by eejbyfeldt** [comment]
@debora-ito 

The original issue with this ticket is not solved, the instances m7g and r7g are available. But instances added later like `r7gd, m7gd, c7gd`  (https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-ec2-c7gd-m7gd-r7gd-instances/) are not available. Should one expect it to take over a month for new instance types to be added to the sdk?

**Comment by debora-ito** [comment]
@eejbyfeldt good timing, those types were part of yesterday's release - `2.20.141`.

I honestly don't know why it takes so long for the EC2 team to update the list of instance types in their model. I'll see if we can start a conversation with them and speed up that process.
