### ISSUE TITLE
SQS Checksum support with FIPS endpoints

### ISSUE THREAD

**Issue by mullermp** [aws/aws-sdk#499]
FIPS endpoints do not permit MD5 checksums, which SQS only supports as verification. SQS should implement checksum support for CRC32/c, SHA1, or SHA2 etc

See related Ruby SDK issue: https://github.com/aws/aws-sdk-ruby/issues/2645

**Comment by bhoradc** [comment]
V1431918784

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The SQS team is continuing to track this feature request in their backlog. We cannot provide guarantees as to if or when this would be implemented, but please refer to the [blog](https://aws.amazon.com/blogs/compute/tag/amazon-sqs/) or SDK changelog for updates going forward.
