### ISSUE TITLE
Query to listUsers does not return standard attributes

### ISSUE THREAD

**Issue by wolfgangmeyers** [aws/aws-sdk#5]
Hello,

I am posting a new bug because the original one was locked, and I can't comment on it or reopen. The original can be found here:

https://github.com/aws/aws-sdk-js/issues/2570

It should not have been closed, because the solution mentioned in the original bug was a workaround, not a real fix. We should be able to query for a subset of the standard attributes.

**Comment by wolfgangmeyers** [comment]
hi @ajredniwja could you clarify what you mean? Would you like me to do some investigation and comment here about my findings?

**Comment by ajredniwja** [comment]
> hi @ajredniwja could you clarify what you mean? Would you like me to do some investigation and comment here about my findings?

That is what I meant since you mentioned about other combinations.

**Comment by aBurmeseDev** [comment]
Closing since it's working as expected. Please refer to [this comment](https://github.com/aws/aws-sdk-js/issues/2570#issuecomment-471529258) for reference.
