### ISSUE TITLE
s3.ErrCodeAccessDenied is missing

### ISSUE THREAD

**Issue by rittneje** [aws/aws-sdk#50]
The documentation for [s3.HeadObject](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.HeadObject) mentions that there are two possible error codes that can come back if the object doesn't exist.

> * If you have the s3:ListBucket permission on the bucket, Amazon S3 returns
an HTTP status code 404 ("no such key") error.
>
> * If you don’t have the s3:ListBucket permission, Amazon S3 returns
an HTTP status code 403 ("access denied") error.

I can see there is an `s3.ErrCodeNoSuchKey` string constant, but I don't see an equivalent one for the "access denied" error. Am I missing something?

**Comment by jmklix** [comment]
P51417825

**Comment by jmklix** [comment]
Closing issue as the documentation has been updated:
>A HEAD request has the same options as a GET action on an object. The response is identical to the GET response except that there is no response body. Because of this, if the HEAD request generates an error, it returns a generic 404 Not Found or 403 Forbidden code. It is not possible to retrieve the exact exception beyond these error codes.
