### ISSUE TITLE
Paginators for client-cloudwatch-events

### ISSUE THREAD

**Issue by Obirah** [aws/aws-sdk#503]
### Describe the feature

The `client-cloudwatch-events` does not have any paginators while some CloudWatch event operations are paginated (e.g. ListRules) it would be useful to be able to call those paginated operations in the same way as with other services/clients.

### Use Case

Any case in which one has to list a lot or all resources of a CloudWatch events resource type.

### Proposed Solution

Paginators for the paginated CloudWatch events operations should be implemented.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.131.0

### Environment details (OS name and version, etc.)

Any

**Comment by tim-finnigan** [comment]
Checking in. CloudWatch Events is now called EventBridge: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cwe-now-eb.html. The following paginators are available for EventBridge: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/events.html#paginators . Are there any other ones that you wanted to request?
