### ISSUE TITLE
Checkout seller issued licenses in a granted AWS account (AWS License Manager)

### ISSUE THREAD

**Issue by gtsopour** [aws/aws-sdk#506]
### Describe the bug

Regarding the seller issued licenses in AWS License Manager, if we grant access to another AWS account at least two (or more) seller issued licenses with the same ProductSKU, the same KeyFingerprint (as a result from the same issuer name) and the same entitlements, it is not possible to differentiate the license while checking it out.
https://docs.aws.amazon.com/license-manager/latest/APIReference/API_CheckoutLicense.html#licensemanager-CheckoutLicense-request-ProductSKU

### Expected Behavior

More flexibility while checking out a license as the ProductSKU and the issuer's name are not unique while creating a seller issued license in the AWS License Manager.

### Current Behavior

If we grant access to another AWS account two (or more) seller issued licenses with the same ProductSKU, the same KeyFingerprint (as a result from the same issuer name) and the same entitlements, it is not possible to differentiate the license while checking it out. Currently the most recent one is being checked out.
https://docs.aws.amazon.com/license-manager/latest/APIReference/API_CheckoutLicense.html#licensemanager-CheckoutLicense-request-ProductSKU

### Reproduction Steps

If we grant access to another AWS account two (or more) seller issued licenses with the same ProductSKU, the same KeyFingerprint (as a result from the same issuer name) and the same entitlements, it is not possible to differentiate the license while checking it out. Currently the most recent one is being checked out.
https://docs.aws.amazon.com/license-manager/latest/APIReference/API_CheckoutLicense.html#licensemanager-CheckoutLicense-request-ProductSKU

### Additional Information/Context

The sam applies to CLI and all SDKs.

### CLI version used

aws-cli/2.8.3 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS Big Sur 11.6.5 (20G527)

**Comment by tim-finnigan** [comment]
P84789642
