### ISSUE TITLE
Fix for GetProducts() in pricing endpoint

### ISSUE THREAD

**Issue by felix-leber** [aws/aws-sdk#51]
**Describe the issue with documentation**
When calling the GetProducts function from pricing you will run into the issue 
`InvalidParameterException InvalidParameterException: Input Parameters are invalid. serviceCode cannot be null or empty`

**To Reproduce (observed behavior)**
This is the code from the documentation:
``` 
svc := pricing.New(session.New())
input := &pricing.GetProductsInput{
    Filters: []*pricing.Filter{
        {
            Field: aws.String("ServiceCode"),
            Type:  aws.String("TERM_MATCH"),
            Value: aws.String("AmazonEC2"),
        },
        {
            Field: aws.String("volumeType"),
            Type:  aws.String("TERM_MATCH"),
            Value: aws.String("Provisioned IOPS"),
        },
    },
    FormatVersion: aws.String("aws_v1"),
    MaxResults:    aws.Int64(1),
}

result, err := svc.GetProducts(input)
```

**Expected behavior**
I expected the output to be 
```
{
  FormatVersion: "aws_v1",
  NextToken: "OooVlVbZ49QkMIpijFV6yA==:FVAwHedYW0hDyeuAdtqIsXiLAPyW+SF7rZvcoq3ZD88Ybj0fOEsrXuz4YMzSR0zeqAD3IBkmp02s0kT+cVVIUl1bIjWzct/+N/W3howB91Lo8/x67MOZsbpbcfrcQ4M/09bdb/34L3wdXTTI7qORPMbpDJ6STgtXnwiM4yHIjctwENzRlE66M0P+t2aDEfAV",
  PriceList: [{
      product: map[attributes:map[location:Asia Pacific (Singapore)  
...
``` 
‼️ **Solution** ‼️
Add the function call `input.SetServiceCode("AmazonEC2")` and it works without problems.

**Comment by skmcgrail** [comment]
In addition to Alex's statement the service model should be update in addition as to mark the ServiceCode member as required for this operation. https://pkg.go.dev/github.com/aws/aws-sdk-go/service/pricing#GetProductsInput.ServiceCode

**Comment by vudh1** [comment]
The documentation issue has been fixed as part of this ticket: V110259952.
