### ISSUE TITLE
`aws ec2 describe-images --image-ids <image ids...>` should return images in same order they were passed (instead of in a nondeterministic random order)

### ISSUE THREAD

**Issue by ryan-williams** [aws/aws-sdk#514]
### Describe the bug

`aws ec2 describe-images` returns images in a random order, which changes on successive invocations.
```bash
aws ec2 describe-images --image-ids ami-0ac44af394b7d6689 ami-03fce349214ac583f ami-003f25e6e2d2db8f1 ami-00eb0dc604a8124fd ami-05e7fa5a3b6085a75 | jq -r '.Images[].ImageId'
# ami-03fce349214ac583f
# ami-05e7fa5a3b6085a75
# ami-003f25e6e2d2db8f1
# ami-0ac44af394b7d6689
# ami-00eb0dc604a8124fd
aws ec2 describe-images --image-ids ami-0ac44af394b7d6689 ami-03fce349214ac583f ami-003f25e6e2d2db8f1 ami-00eb0dc604a8124fd ami-05e7fa5a3b6085a75 | jq -r '.Images[].ImageId'
# ami-05e7fa5a3b6085a75
# ami-0ac44af394b7d6689
# ami-00eb0dc604a8124fd
# ami-03fce349214ac583f
# ami-003f25e6e2d2db8f1
```

### Expected Behavior

1. Returned `Images` array should be ordered by something sensible and deterministic
2. If specific image-ids are passed, they should appear in the output in the same order in which they were provided.

### Current Behavior

Returned images are randomly shuffled on each invocation.

### Reproduction Steps

As above:

```bash
aws ec2 describe-images --image-ids ami-0ac44af394b7d6689 ami-03fce349214ac583f ami-003f25e6e2d2db8f1 ami-00eb0dc604a8124fd ami-05e7fa5a3b6085a75 | jq -r '.Images[].ImageId'
# ami-03fce349214ac583f
# ami-05e7fa5a3b6085a75
# ami-003f25e6e2d2db8f1
# ami-0ac44af394b7d6689
# ami-00eb0dc604a8124fd
aws ec2 describe-images --image-ids ami-0ac44af394b7d6689 ami-03fce349214ac583f ami-003f25e6e2d2db8f1 ami-00eb0dc604a8124fd ami-05e7fa5a3b6085a75 | jq -r '.Images[].ImageId'
# ami-05e7fa5a3b6085a75
# ami-0ac44af394b7d6689
# ami-00eb0dc604a8124fd
# ami-03fce349214ac583f
# ami-003f25e6e2d2db8f1
```

### Possible Solution

Use the order passed to `--image-ids`, when present.

If absent, pick some other field to order on (e.g. reverse-chron as discussed in https://github.com/aws/aws-cli/issues/6929)

### Additional Information/Context

https://github.com/aws/aws-cli/issues/6928
https://github.com/aws/aws-cli/issues/6929

### CLI version used

1.27.110

### Environment details (OS name and version, etc.)

macOS, Ubuntu 22.04

**Comment by RyanFitzSimmonsAK** [comment]
@ryan-williams, the EC2 service team got back to me, and they said that they do not guarantee a deterministic ordering for scaling reasons, and don't have any plans to do so without a compelling costumer reason.  Could you tell me a bit more about your use case?

**Comment by osatoaigbogun** [comment]
This will check for ECR update and return the tag name in plain text


aws ecr describe-images --repository-name api-prod  --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text

**Comment by osatoaigbogun** [comment]
@ryan-williams ryan-williams 

This will check for ECR update and return the tag name in plain text

aws ecr describe-images --repository-name api-prod --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text

**Comment by Shivam-nagar23** [comment]
@osatoaigbogun the solution you provided will be doing client side quering(filtering) ,which will filter in limited dataset not the actual whole dataset.
