### ISSUE TITLE
Add `StreamExists` and `StreamNotExists` waiters for KinesisVideo

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#517]
Original issue: https://github.com/boto/boto3/issues/3666

Current Kinesis waiters: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesis.html#waiters

Request: Add `StreamExists` and `StreamNotExists` waiters for KinesisVideo: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesisvideo.html

**Comment by tim-finnigan** [comment]
P86229778

**Comment by aBurmeseDev** [comment]
A Product Feature Request has been submitted to the service team regarding the addition of StreamExists and StreamNotExists waiters for KinesisVideo. As this repository is solely dedicated to issues pertaining to SDK, I will close this issue.
