### ISSUE TITLE
CLI V2: aws signer add-profile-permission fails when principal is an IAM role with path

### ISSUE THREAD

**Issue by stefano-m** [aws/aws-sdk#519]
### Describe the bug

Running `aws signer add-profile-permission` with an IAM role with path as principal returns a `ValidationException`, the same command works without problems when using a role with no path.

I am using

```
$ aws --version
aws-cli/2.8.12 Python/3.10.9 Darwin/22.4.0 source/x86_64 prompt/off
```

### Expected Behavior

Given an IAM role with path, e.g. `arn:aws:iam:123456789012:role/teams/my-team/Signer`, the below command succeeds and returns a revision id:

``` shell
aws signer add-profile-permission \
    --action signer:GetSigningProfile \
    --statement-id permission1 \
    --profile-name SomeSignerProfile \
    --principal arn:aws:iam:123456789012:role/teams/my-team/Signer
```

### Current Behavior

Given an IAM role with path, e.g. `arn:aws:iam:123456789012:role/teams/my-team/Signer`, the below command fails with an error

``` shell
aws signer add-profile-permission \
    --action signer:GetSigningProfile \
    --statement-id permission1 \
    --profile-name SomeSignerProfile \
    --principal arn:aws:iam:123456789012:role/teams/my-team/Signer
```

the error returned is

```
An error occurred (ValidationException) when calling AddProfilePermission operation:
Principal is not a valid AWS account id or IAM Role Arn
```

### Reproduction Steps

- create an IAM role with path, e.g.  `arn:aws:iam:123456789012:role/teams/my-team/Signer`
- create an AWS Signer profile, e.g. `SomeSignerProfile`
- run
  ``` shell
  aws signer add-profile-permission \
      --action signer:GetSigningProfile \
      --statement-id permission1 \
      --profile-name SomeSignerProfile \
      --principal arn:aws:iam:123456789012:role/teams/my-team/Signer
  ```

### Possible Solution

Make `AddProfilePermission` validate roles with path the same way roles with no path are validated. Or at least, if this is not supported, make it return a more meaningful error message and document it.

### Additional Information/Context

I appreciate that this might not be a problem with the AWS CLI itself and instead a problem with the `AddProfilePermission` API operation, but I found no other place where to report this bug to AWS.

Thank you

### CLI version used

aws-cli/2.8.12 Python/3.10.9

### Environment details (OS name and version, etc.)

Darwin/22.4.0

**Comment by aBurmeseDev** [comment]
_P86307464_

**Comment by aBurmeseDev** [comment]
Hi @stefano-m - I just heard back from a service team member that using account id as principal is expected and they don't have a plan to support specifying roles with a path, unfortunately. Please let me know if you'd like me to pass anything back to the service team.

**Comment by stefano-m** [comment]
Hi @aBurmeseDev

thanks for getting back to me.

It's a shame that the service team is not planning to support roles with paths. With this, such roles become second-class citizens. But well, I appreciate that you all got back to me with the news.

My suggestions are:

1. return a meaningful validation error when a role with path is passed to the signer. For example ```An error occurred (ValidationException) when calling AddProfilePermission operation:
Principal is not a valid AWS account id or IAM Role Arn (IAM Roles with paths are not supported)```
2. clearly stat the limitation that roles with paths are not supported in the aws signer documentation (both API and CLI)

Hope this helps.

Thank you again.

**Comment by aBurmeseDev** [comment]
Hi @stefano-m - I wanted to share that AWS Signer now supports specifying IAM roles with a path when using the `AddProfilePermission` API. This enables streamlining and managing permissions for IAM entities like roles within an organization.

Hope this helps your workflow!
Best,
John
