### ISSUE TITLE
CloudFront: support reporting API (eg. popular objects)

### ISSUE THREAD

**Issue by arasmussen** [aws/aws-sdk#520]
### Describe the feature

On the [console](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home#/popular_urls), I can hit a [console API endpoint](https://us-east-1.console.aws.amazon.com/cloudfront/v3/api/cloudfrontreporting) to pull reporting on popular objects for a specific distribution and timeframe. It would be very useful to be able to pull this information AWS's CLI and/or SDK. This doesn't currently seem possible.

### Use Case

We're in a situation where we need to monitor popular objects for fraud. Whenever an image goes over a certain number of requests, we'd like to manually review it, and potentially delete it from our underlying S3 bucket and run an invalidation.

### Proposed Solution

Add an SDK endpoint that allows us to pull this data, and then implement that command in the JS SDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

2.1349.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.0

**Comment by ChintanPalan** [comment]
We too have a similar use case. It would make sense to have such a feature in the SDK.

**Comment by RanVaknin** [comment]
Hi all,

Unfortunately the service team has not been able to prioritize this feature request. As it stands it will stay in the backlog waiting to be prioritized. If you need further assistance you can open a support ticket via the AWS console and reference the existing open ticket `P86316444` 

Since this is not actionable by the SDK team I'll close this. 
Thanks again,
Ran~

**Comment by knzcx** [comment]
Is there an update here? After almost a year, I don't see any way to access these metrics via API or SDK. What happens now with this feature request? Can I see the current status somewhere?
