### ISSUE TITLE
aws s3 ls fails when using AWS_USE_FIPS_ENDPOINT

### ISSUE THREAD

**Issue by samholton** [aws/aws-sdk#521]
### Describe the bug

When setting `AWS_USE_FIPS_ENDPOINT=true`, the `aws s3 ls` command does not return the list of buckets. However, setting to `false` returns buckets.

```bash
# working scenario with false
AWS_USE_FIPS_ENDPOINT=false aws s3 ls
<redacted list of S3 buckets>

# failure scenario (run on same instance immediately following above command)
AWS_USE_FIPS_ENDPOINT=true aws s3 ls

Could not connect to the endpoint URL: "https://s3-fips.us-east-1.amazonaws.com/"

# specifying a specific bucket does work with FIPS
AWS_USE_FIPS_ENDPOINT=true aws s3 ls s3://fips-test-123
                                         PRE prefix-xyz/
2023-04-17 19:16:47          6 another.txt
2023-04-17 19:16:42          6 test.txt


# cannot resolve the endpoint on the EC2 instance
nslookup s3-fips.us-east-1.amazonaws.com
Server:		172.16.0.2
Address:	172.16.0.2#53

Non-authoritative answer:
*** Can't find s3-fips.us-east-1.amazonaws.com: No answer
```

### Expected Behavior

List of buckets is returned, as it is with `AWS_USE_FIPS_ENDPOINT=false`

### Current Behavior

```bash
AWS_USE_FIPS_ENDPOINT=true aws s3 ls

Could not connect to the endpoint URL: "https://s3-fips.us-east-1.amazonaws.com/"
```

### Reproduction Steps

`AWS_USE_FIPS_ENDPOINT=true aws s3 ls`

### Additional Information/Context

The same happens on EC2 instance with instance profile as well as locally using temporary credentials from STS.

### CLI version used

aws-cli/2.11.4 Python/3.11.2 Linux/3.10.0-1160.88.1.el7.x86_64 exe/x86_64.centos.7 prompt/off

### Environment details (OS name and version, etc.)

CentOS Linux release 7.9.2009 (Core)

**Comment by tim-finnigan** [comment]
D65626087

**Comment by tim-finnigan** [comment]
Checking in - we heard back from the S3 team and they shared the following:
>Amazon S3 does not support "ListBuckets" or "CreateBucket" API calls on FIPS endpoints in AWS Regions. It is recommended to use the non-FIPS regional endpoint ([s3.region.amazonaws.com](http://s3.region.amazonaws.com/)) for these two APIs. 

They are tracking the feature request to support this in their backlog but it is not planned at this time.
