### ISSUE TITLE
The Wellarchitected GetConsolidatedReport API throwes error when we are passing the `Format` as `JSON` in the input parameter

### ISSUE THREAD

**Issue by ParthaI** [aws/aws-sdk#523]
### Describe the bug

The API [GetConsolidatedReport](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/wellarchitected@v1.19.2#Client.GetConsolidatedReport) throws the following error when we are passing the `Format` value as `JSON` in the input param.

**Input:**
```
	input := &wellarchitected.GetConsolidatedReportInput{
		Format:                 types.ReportFormatJson,
		IncludeSharedResources: true,
		MaxResults:             int32(15),
	}
```

**Error:**
```
Error: operation error WellArchitected: GetConsolidatedReport, https response error StatusCode: 200, RequestID: 6381396e-e959-4678-a352-221a60e99dc9, deserialization failed, failed to decode response body with invalid JSON, expected LensesAppliedCount to be json.Number, got string instead
```

I was having a look at the [AWS API doc](https://docs.aws.amazon.com/wellarchitected/latest/APIReference/API_ConsolidatedReportMetric.html), here it is mentioned that the datatype of the property `LensesAppliedCount` is an integer.

In the Go SDK the property [LensesAppliedCount](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/wellarchitected@v1.19.2/types#ConsolidatedReportMetric)  is also an integer type.

But while I am running the AWS CLI command(`aws wellarchitected get-consolidated-report --format JSON`) I am getting the value as a string.
![Screenshot 2023-04-13 at 6 21 53 PM](https://user-images.githubusercontent.com/47887552/231764151-f9b69798-38f2-4f84-8300-90ecfc50f070.png)

### Expected Behavior

The API [GetConsolidatedReport](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/wellarchitected@v1.19.2#Client.GetConsolidatedReport) should not throw any error.

### Current Behavior

The API [GetConsolidatedReport](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/wellarchitected@v1.19.2#Client.GetConsolidatedReport) throws an error `deserialization failed, failed to decode response body with invalid JSON, expected LensesAppliedCount to be json.Number, got string instead` while typecasting a JSON value to integer type

### Reproduction Steps

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"

	"github.com/aws/aws-sdk-go-v2/service/wellarchitected"
)

func main() {
	listConsolidateReports("us-east-1")
}

func listConsolidateReports(region string) {
	fmt.Println("Region:", region)
	ctx := context.Background()
	configOptions := []func(*config.LoadOptions) error{
		config.WithRegion(region),
	}

	cfg, err := config.LoadDefaultConfig(ctx, configOptions...)
	if err != nil {
		log.Fatalln("load_default_config", err)
	}

	svc := wellarchitected.NewFromConfig(cfg)

	input := &wellarchitected.GetConsolidatedReportInput{
		Format:                 types.ReportFormatJson,
		IncludeSharedResources: true,
		MaxResults:             maxLimit,
	}

	paginator := wellarchitected.NewGetConsolidatedReportPaginator(svc, input, func(o *wellarchitected.GetConsolidatedReportPaginatorOptions) {
		o.Limit = maxLimit
		o.StopOnDuplicateToken = true
	})

	// List call
	for paginator.HasMorePages() {
		output, err := paginator.NextPage(ctx)
		if err != nil {
			log.Fatalln("pagging error", err)
			return nil, err
		}

		for _, items := range output.Metrics {
			fmt.Println("Result :", item)
		}

	}

}

```

### Possible Solution

We need to update the datatype of the property `LensesAppliedCount` to string.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.17.8
github.com/aws/aws-sdk-go-v2/service/wellarchitected v1.19.2

### Compiler and Version used

go version go1.19.2 darwin/arm64

### Operating System and version

MacOS Big Sur - Version 11.4

**Comment by RanVaknin** [comment]
Hi  @ParthaI

This is now fixed.

Thanks again.
Ran~
