### ISSUE TITLE
Parallel Activity Task Poller for Step Functions

### ISSUE THREAD

**Issue by nolotz** [aws/aws-sdk#532]
### Describe the feature

Implement a parallel activity task poller for the Additional Features module that can be scaled across multiple threads to improve throughput and latency. This feature will help in avoiding latency problems when polling for tasks in step functions, as described in the [Amazon Step Functions documentation](https://docs.aws.amazon.com/step-functions/latest/dg/bp-activity-pollers.html).

### Use Case

For production systems using Step Functions with activity workers, it is recommended to have at least 100 open polls per activity ARN at each point in time. This is to ensure that even if a few polls are blocked, there are still many more requests that will receive a taskToken to process work. However, implementing this manually can be cumbersome and prone to errors. By providing a parallel activity task poller in the SDK, users can easily implement and manage their pollers, ensuring high throughput and low latency for their systems.

The proposed solution aims to help users who are leveraging AWS Step Functions in their systems by providing a built-in, easy-to-use, and scalable solution for polling activity tasks. This will enable users to focus on their business logic and not worry about the intricacies of implementing a parallel activity task poller from scratch.

### Proposed Solution

- A configurable number of parallel polls for each activity ARN, with a default of 100 open polls.
- Automatically manage routines and polling for activity tasks, ensuring that the recommended number of open polls is maintained.
- Ability to configure the poller to adjust the polling interval, timeout, and other relevant parameters.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

latest

### Go version used

1.20.3

**Comment by tim-finnigan** [comment]
Just to clarify, is the request here for Step Functions API functionality or SDK functionality? Looking in their documentation on Activities (https://docs.aws.amazon.com/step-functions/latest/dg/concepts-activities.html) It sounds like maybe this relates to [GetActivityTask](https://docs.aws.amazon.com/step-functions/latest/apireference/API_GetActivityTask.html), in which case we would want to reach out to the Step Functions team to review the feature request.
