### ISSUE TITLE
Incorrect serialization for cloudwatch.MetricDatum.Timestamp

### ISSUE THREAD

**Issue by deliahu** [aws/aws-sdk#54]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
I believe the type for [`cloudwatch.MetricDatum.Timestamp`](https://github.com/aws/aws-sdk-go/blob/master/service/cloudwatch/api.go#L7103) should be `*int64`, or the comment should be updated to reflect the fact that the input is of type `*time.Time`.

When I use `*time.Time` (so that it compiles) and I run `PutMetricData()`, I get this error:

`MalformedInput: timestamp must follow ISO8601`

**Version of AWS SDK for Go?**
v1.34.12

**Version of Go (`go version`)?**
1.14

**Additional Context**
This error did not occur with the same code and v1.30.25 of the sdk.

**Comment by vudh1** [comment]
P70318981

**Comment by RanVaknin** [comment]
Since the doc string is defined by the model, it would carry over to other SDKs.  There is currently no consensus on a wording that would work cross SDK so we will close this.

Thanks,
Ran~
