### ISSUE TITLE
Add `ContentType` to S3 `UploadPartRequest`

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#548]
Original issue: https://github.com/boto/boto3/issues/3708

**Comment by lskuper** [comment]
This is a blocker for us.
Our http-request client does by default add a contentType header which leads to SignatureDoesNotMatch errors.

We are using aws-sdk to generate presigned urls for multi-part uploads the following way:
```
      s3.("uploadPart", {
        Bucket: bucket,
        Key: key,
        Expires: expiresInS,
        UploadId: uploadId,
        PartNumber: partNo,
        // "ContentType": contentType, // not allowed by aws-sdk
      })
```
Allowing to specify a contentType for presigned url generation would solve it, is there any reason against it?

"aws-sdk": "2.1406.0",

**Comment by tim-finnigan** [comment]
We heard back from the S3 team and they created a backlog item for this feature request. We can't provide any ETAs or guarantees as to if or when this would be implemented. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for updates in the future if you have a support plan, otherwise feel free to check back in here as well.

**Comment by pjaol** [comment]
Hey what's the deal with this, it's breaking browser uploads to S3
Please escalate it.
