### ISSUE TITLE
Support for Iceberg tables in the create-table command from the aws glue cli

### ISSUE THREAD

**Issue by sfgarcia** [aws/aws-sdk#549]
### Describe the feature

In Athena it is possible to create Iceberg tables through DDLs (explained here https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html). But this same functionality isn't possible to replicate through the aws glue cli in the create-table command (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/glue/create-table.html) , because the TableType option doesn't allow to specify Iceberg.

### Use Case

The main use case is to be able to create Iceberg tables as IaC, instead of just creating them through DDL queries inside Athena. This new feature would open the possibility to Cloudformation team to add the support to create Iceberg tables from the AWS::Glue::Table resource.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

v2

### Environment details (OS name and version, etc.)

MacOS

**Comment by tim-finnigan** [comment]
A backlog item for this feature request has been added for the Glue team's further review and consideration. We can't provide any ETAs or guarantees but please feel free to check back in here for updates in the future. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.
