### ISSUE TITLE
(quicksight): add `paginateListGroups` Async Iterator

### ISSUE THREAD

**Issue by moltar** [aws/aws-sdk#551]
### Describe the feature

Would like to have the `paginateListGroups` Async Iterator function in the QuickSight client.

Other `paginate*` functions already exist, but `paginateListGroups` seems to be missing.

### Use Case

To paginate.

### Proposed Solution

Implement it.

### Other Information

- https://aws.amazon.com/blogs/developer/pagination-using-async-iterators-in-modular-aws-sdk-for-javascript/
- https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-quicksight/src/pagination

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.347.1

### Environment details (OS name and version, etc.)

macOS, Node 16

**Comment by RanVaknin** [comment]
Hi @moltar ,

Changes are now live. 
Thanks for your contribution :slightly_smiling_face: 

All the best,
Ran~

**Comment by moltar** [comment]
@RanVaknin is it released already? which version? Thanks.

**Comment by RanVaknin** [comment]
Hi @moltar ,

Did not see your comment. 

Here is the paginator https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-quicksight/src/pagination/ListGroupsPaginator.ts

This should have been available since 3.376.0

Thanks
Ran~
