### ISSUE TITLE
Unable to sort CloudWatch logs results in descending order by timestamp

### ISSUE THREAD

**Issue by saedyousef** [aws/aws-sdk#554]
### Describe the bug

While using the AWS SDK for PHP to read logs from CloudWatch Logs, I am unable to sort the results in descending order by timestamp.

### Expected Behavior

The SDK should allow me to sort the log results in descending order by timestamp, with the most recent logs appearing first.

### Current Behavior

Despite attempting to sort the results in descending order by timestamp, the logs are still returned in ascending order by default.

### Reproduction Steps

- Use the AWS SDK for PHP to retrieve logs from CloudWatch Logs.
- Attempt to sort the results in descending order by timestamp using the appropriate parameters.
- Observe that the logs are still returned in ascending order by default.

### Possible Solution

One possible solution is to use the 'orderBy' parameter in the query to sort the logs by the timestamp in descending order. For example, the query could be modified to include 'orderBy @timestamp desc' to sort the logs by the '@timestamp' field in descending order.

### SDK version used

3.257.7

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP version: 7.2, OS: Ubuntu 18.04, Webserver: Apache2

**Comment by yenfryherrerafeliz** [comment]
V934942278

**Comment by ashishdhingra** [comment]
Thank you for your feedback. We've let the responsible internal team know and they've placed this on their backlog. We can't share specific timelines on when this might be implemented in GitHub; you should monitor the [AWS News Blog](https://aws.amazon.com/blogs/aws/) for updates.
