### ISSUE TITLE
TypeScript types for SQS client could be improved

### ISSUE THREAD

**Issue by kibertoad** [aws/aws-sdk#557]
### Describe the feature

See https://github.com/aws/aws-sdk-js-v3/blob/6c8730a9646e324cc2c01b6e86df974a9f39fc64/clients/client-sqs/src/models/models_0.ts#L719

Attributes are defined simply as `Attributes?: Record<string, string>;`, without any type-safety. Supported options are only listed in documentation.

### Use Case

When project that relies on SQS client is using TypeScript, it is very helpful to have compilation time type-safety, so that compilation will fail, if unsupported parameter is passed. Otherwise this error will only be caught in the runtime, which may be too late.

### Proposed Solution

Provide stronger types in `/clients/client-sqs/src/models/models_0.ts`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.357.0

### Environment details (OS name and version, etc.)

Windows 11

**Comment by yenfryherrerafeliz** [comment]
V944691875

**Comment by yenfryherrerafeliz** [comment]
Hi @kibertoad, this feature has been implemented by the service now. You can confirm it [here](https://github.com/aws/aws-sdk-js-v3/blob/ba83d46690522a0a18094d7cd72d95724c95177b/clients/client-sqs/src/models/models_0.ts#L743) where attributes expect that the key for the record type provide to be one of the following options defined for QueueAttributeName type [here](https://github.com/aws/aws-sdk-js-v3/blob/ba83d46690522a0a18094d7cd72d95724c95177b/clients/client-sqs/src/models/models_0.ts#L414).

Thanks!

**Comment by kibertoad** [comment]
@yenfryherrerafeliz Thanks a lot for addressing this! I've also opened a symmetric entry for SNS, as it has the same problem now (even in the latest version) - https://github.com/aws/aws-sdk/issues/626
