### ISSUE TITLE
SQS.ReceiveMessage has the wrong list of valid values for AttributeName request parameter

### ISSUE THREAD

**Issue by luislew** [aws/aws-sdk#56]
Original issue: https://github.com/aws/aws-sdk-go-v2/pull/1194
Comment redirecting to open an issue here: https://github.com/aws/aws-sdk-go-v2/pull/1194#issuecomment-809590534

**Summary**: The [API documentation for `SQS.ReceiveMessage`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) has the wrong set of valid values for the  `AttributeName`. This is propagated through to the various SDKs as well, so it appears to be misconfigured in the underlying API model.

**Details**: The detailed list of supported `AttributeName` values is **correct**:

> AttributeName.N
> A list of attributes that need to be returned along with each message. These attributes include:
> 
> All – Returns all values.
> 
> ApproximateFirstReceiveTimestamp – Returns the time the message was first received from the queue (epoch time in milliseconds).
> 
> ApproximateReceiveCount – Returns the number of times a message has been received across all queues but not deleted.
> 
> AWSTraceHeader – Returns the AWS X-Ray trace header string.
> 
> SenderId
> 
> For an IAM user, returns the IAM user ID, for example ABCDEFGHI1JKLMNOPQ23R.
> 
> For an IAM role, returns the IAM role ID, for example ABCDE1F2GH3I4JK5LMNOP:i-a123b456.
> 
> SentTimestamp – Returns the time the message was sent to the queue (epoch time in milliseconds).
> 
> MessageDeduplicationId – Returns the value provided by the producer that calls the SendMessage action.
> 
> MessageGroupId – Returns the value provided by the producer that calls the SendMessage action. Messages with the same MessageGroupId are returned in sequence.
> 
> SequenceNumber – Returns the value provided by Amazon SQS.

Unfortunately, the "Valid Values" list is **wrong** - it points at the set of valid values for [`SQS.GetQueueAttributes`'s `AttributeName` request parameter](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html#API_GetQueueAttributes_RequestParameters):

> Type: Array of strings
> 
> Valid Values: All | Policy | VisibilityTimeout | MaximumMessageSize | MessageRetentionPeriod | ApproximateNumberOfMessages | ApproximateNumberOfMessagesNotVisible | CreatedTimestamp | LastModifiedTimestamp | QueueArn | ApproximateNumberOfMessagesDelayed | DelaySeconds | ReceiveMessageWaitTimeSeconds | RedrivePolicy | FifoQueue | ContentBasedDeduplication | KmsMasterKeyId | KmsDataKeyReusePeriodSeconds | DeduplicationScope | FifoThroughputLimit

**Comment by KaibaLopez** [comment]
P48664419

**Comment by stobrien89** [comment]
Followed up on this again today.  Will update once I've heard back.

**Comment by RanVaknin** [comment]
This is now fixed.
