### ISSUE TITLE
KinesisAnalyticsV2Client pagination functions

### ISSUE THREAD

**Issue by pmckl** [aws/aws-sdk#567]
### Describe the feature

The KinesisAnalyticsV2Client lack the paginator functions, thats available in many other clients like KinesisClient.

### Use Case

We're building an application which collect many of our AWS resources from multiple accounts, and it would be great if we could use the SDK provided pagination for all the resource types.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

@aws-sdk/client-kinesis-analytics-v2:^3.300.0

### Environment details (OS name and version, etc.)

general

**Comment by bhoradc** [comment]
Hi @pmckl,
 
The service team has acknowledged this issue and they have a backlog item created for tracking it. 

There is no ETA on the fix for now. Therefore, I will go ahead and close this issue. 

Regards, 
Chaitanya
