### ISSUE TITLE
Incorrect types for ApplicationVersionStatus for elastic-beanstalk

### ISSUE THREAD

**Issue by poph2** [aws/aws-sdk#569]
### Describe the feature

Update the [ApplicationVersionStatus](https://github.com/aws/aws-sdk-js-v3/blob/1b1fd2608691661a65258b6ec718135990855397/clients/client-elastic-beanstalk/src/models/models_0.ts#L498-L504)'s statuses to match what is returned by AWS APIs

### Use Case

When Elastic beanstalk application versions are queries using a command such as [DescribeApplicationVersionsCommand](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-elastic-beanstalk/src/commands/DescribeApplicationVersionsCommand.ts), the response looks like the below:

```
{
  "$metadata": {...},
  "ApplicationVersions": [
    {
      "ApplicationVersionArn": "...",
      "ApplicationName": "...",
      "Description": "",
      "VersionLabel": "...",
      "SourceBundle": {
        "S3Bucket": "...",
        "S3Key": "..."
      },
      "DateCreated": "...",
      "DateUpdated": "...",
      "Status": "PROCESSED"
    }
  ]
}
```

The `Status` attribute is supposed to be any one [ApplicationVersionStatus](https://github.com/aws/aws-sdk-js-v3/blob/1b1fd2608691661a65258b6ec718135990855397/clients/client-elastic-beanstalk/src/models/models_0.ts#L498-L504) which are all in Title case while the api responses are in upper case.

In this case, we cannot simply verify the application version's status with the expression `appVersion.Status === ApplicationVersionStatus.Processed`, this is resolved to `PROCESSED === Processed`, which was quite frustrating to debug in the context of my project.

### Proposed Solution

This should work

```
export const ApplicationVersionStatus = {
  BUILDING: "BUILDING",
  FAILED: "FAILED",
  PROCESSED: "PROCESSED",
  PROCESSING: "PROCESSING",
  UNPROCESSED: "UNPROCESSED",
} as const;
```

### Other Information

Although the [aws-cli documentation](https://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/describe-application-versions.html) described the ApplicationVersion statuses are in title case, this is not the what is returned by the cli. The statuses are in upper case.

The command below provides a response identical to the one returned by the SDK. So we can safely conclude the upper case statuses are to be expected.
```
aws elasticbeanstalk describe-application-versions --application-name <APP_NAME> --version-label "<APP_VERSION>"
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

@aws-sdk/client-elastic-beanstalk:3.379.1

### Environment details (OS name and version, etc.)

Mac OS

**Comment by RanVaknin** [comment]
The service team has closed this issue.
If you wish to re-engage with them, please open a support ticket via the AWS console and mention the ticket ID `V975621920`.

Apologies for the inconvenience.

Thanks,
Ran~
