### ISSUE TITLE
API support for modifying ALB Capacity Configuration

### ISSUE THREAD

**Issue by ahujarajesh** [aws/aws-sdk#57]
**Is your feature request related to a problem? Please describe.**
We can modify ALB LCU Capacity only from AWS Console.

**Describe the solution you'd like**
There should be AWS CLI / API Support for modifying ALB Capacity.

**Describe alternatives you've considered**
I don't think there is any alternative approach except AWS Console.

**Additional context**
We want to automate the LCU Units on ALB as per our requirement at specific times. however we cannot achieve it because there are no APIs/CLI Command to do so.

**Comment by kdaily** [comment]
V345362358

**Comment by ahujarajesh** [comment]
Thank you @kdaily

**Comment by kdaily** [comment]
Hi @ahujarajesh,

Thank you again for your request. The ELB team is aware of this, but this feature is not currently available. I cannot provide you a timeline on when it could be made available.
