### ISSUE TITLE
C# and .NET version of MediaConvert, GetJobAsync method - documentation issue

### ISSUE THREAD

**Issue by Bellarmine-Head** [aws/aws-sdk#571]
### Describe the issue

The C# `Amazon.MediaConvert.AmazonMediaConvertClient.GetJobAsync` method says in its comments:-

```
        //
        // Summary:
        //     Retrieve the JSON for a specific completed transcoding job.
        //
```

I would like to emphasize the word "completed" here.

I was worried about this, because I wanted to call `GetJobAsync` every 2 or 3 seconds to get an updated status... but the summary suggests that the method will only work for _completed_ jobs.

I tried it anyway, and got "PROGRESSING" a few times before I got "COMPLETED".

So method works for completed and also ongoing transcoding jobs!  Perhaps the documentation could be updated to reflect that.

### Links

Can't find a link to a .NET page, but here's one that's very similar and illustrates the problem....

https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs-id.html#jobs-idget

**Comment by ashishdhingra** [comment]
@Bellarmine-Head This appears to have been fixed at https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs-id.html.
