### ISSUE TITLE
Include tags in Cognito Identity ListUserPools/ListIdentityPools API responses

### ISSUE THREAD

**Issue by zpbonjour** [aws/aws-sdk#573]
### Describe the feature

Currently list-user-pools outputs the following info:
```
{
      "Id": "<Pool_Id>",
      "Name": "<Pool_Name>",
      "LambdaConfig": { <Lambda_Triggers> },
      "LastModifiedDate": "<Date_Modified>",
      "CreationDate": "<Data_Created>"
 }
```

 and list-identity-pools:

```
{
  "IdentityPoolId":"<Pool_Name>"
  "IdentityPoolName": "<Pool_Name>"
 }
```

I would like to see more descriptive information that will help narrow down the search for a specific pool.  Tags would be super helpful for my use case.
 
```
 {
      "Id": "<Pool_Id>",
      "Name": "<Pool_Name>",
      "LambdaConfig": { <Lambda_Triggers> },
      "LastModifiedDate": "<Date_Modified>",
      "CreationDate": "<Data_Created>",
      "UserPoolTags": {
           "TagKey1": "TagValue1",
           "TagKey2": "TagValue2"
      }
 }
```
```
{
  "IdentityPoolId": "<Pool_Name>"
  "IdentityPoolName": "<Pool_Name>",
  "IdentityPoolTags": {
           "TagKey1": "TagValue1",
           "TagKey2": "TagValue2"
      }
}
```
### Use Case

I am working on some workflow automation that needs to fetch a user and identity pool's id.  Unfortunately, the name of the pool is not always uniform or known.  However, there are some tags that I could use to find the intended pool.  Right now, I am unable to search the tags unless I know the pool id as list-tags-for-resource requires an ARN and describe-identity/user-pool requires a pool id.

### Proposed Solution

output the pool resource tags when listing pools with list-identity/user-pools so they can be used to locate a pool.

### Other Information

All of my testing has been done in Cloud Shell but I intend to use this feature with Github Actions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.13.4 Python/3.11.4 Linux/4.14.255-314-253.539.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

Cloud Shell

**Comment by jmklix** [comment]
You might be able to use [AWS Resource Explorer](https://aws.amazon.com/resourceexplorer/) as a possible workaround.

After Resource Explorer is [setup](https://docs.aws.amazon.com/resource-explorer/latest/userguide/getting-started-setting-up.html), you could use the [Search API](https://docs.aws.amazon.com/resource-explorer/latest/apireference/API_Search.html) and query for the tags you use.

For example, if you had several Cognito user pools tagged with a key value of "sanboxCognitoUserPools", you could use a query similar to `"tag.key: sanboxCognitoUserPools"` with the Resource Explorer Search API and you would get back a response similar to this:

```
{
    "Resources": [
        {
            "Arn": "arn:aws:cognito-idp:<REGION>:<ACCOUNT-ID>:userpool/<REGION>_123abc",
            "LastReportedAt": "2024-02-27T17:43:39+00:00",
            "OwningAccountId": "<ACCOUNT-ID>",
            "Properties": [
                {
                    "Data": [
                        {
                            "Key": "sanboxCognitoUserPools",
                            "Value": ""
                        }
                    ],
                    "LastReportedAt": "2024-02-27T17:43:39+00:00",
                    "Name": "tags"
                }
            ],
            "Region": "<REGION>",
            "ResourceType": "cognito-idp:userpool",
            "Service": "cognito-idp"
        }
    ],
}
```

From there you would get the ARN and could extract the user pool id (or identity pool id) and then call ListUserPools/ListIdentityPools API.

**Comment by jmklix** [comment]
I reached out to the cognito team and shared your use case to gather more insights on your behalf. Since this issue isn’t directly actionable by the SDK team, and this repository is dedicated to SDK-related issues, I'll go ahead and close this ticket. If you have access to AWS support through the Developer Console, please consider creating a support ticket and referencing the ticket ID I shared above to receive updates directly from the service team. Otherwise, you can keep an eye on our release notes for news on when this is resolved.
