### ISSUE TITLE
Opensearch update-domain-config (instance count)

### ISSUE THREAD

**Issue by Tjkent88** [aws/aws-sdk#575]
### Describe the issue

![image](https://github.com/aws/aws-cli/assets/40183177/1b822ef0-4d51-4fb9-be97-472ff4397146)
It seems like this value controls data nodes rather than master nodes since the following controls that, can someone confirm?

![image](https://github.com/aws/aws-cli/assets/40183177/1dce948c-f7f6-4f2d-9f9e-4d6be44139a5)

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/opensearch/update-domain-config.html

**Comment by tim-finnigan** [comment]
The documentation has now been updated in the API documentation but not the CLI documentation:

<img width="1969" alt="image" src="https://github.com/aws/aws-sdk/assets/87778557/ef783f13-ed8a-4d9f-bebd-abb49b92ac89">

Sometimes there is a delay in the rollout of documentation updates — I can try checking in with the team.

**Comment by tim-finnigan** [comment]
The CLI documentation has now been updated as well so I'll go ahead and close this. Thanks again for bringing this to our attention!
