### ISSUE TITLE
An `S3Exception` caused by an S3 301 HTTP status doesn't actually contain the redirect URL

### ISSUE THREAD

**Issue by changlinli** [aws/aws-sdk#578]
### Describe the feature

For a 301 HTTP response, actually capture the redirect URL somewhere in an `S3Exception` to make debugging considerably easier. It's especially annoying with when the following error message is returned
```
Please send all future requests to this endpoint.
```
but "this endpoint" is never specified anywhere and can't be found anywhere in the `S3Exception` instance.

### Is your Feature Request related to a problem?

If a 301 status code is returned from S3 we get an `S3Exception`, but the exception is not very helpful. In particular, while the 301 status indicates that a URL has moved permanently and should specify where the URL has moved to, the corresponding `S3Exception` does not describe where the URL has moved to anywhere that I could find, which makes both automated error reporting and manual debugging very frustrating.

This is the default `toString`:

```
software.amazon.awssdk.services.s3.model.S3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: S3, Status Code: 301, Request ID: SOME_REQUEST_ID, Extended Request ID: SOME_LONG_EXTENDED_REQUEST_ID)
```

If I look at `S3Exception.awsErrorDetails()` there are two promising methods `rawResponse` and `sdkHttpResponse`. Unfortunately `rawResponse` is `null` and while `sdkHttpResponse` does return a `SdkHttpFullResponse` (after downcasting from `SdkHttpResponse`), the underlying `InputStream` of its `content` is already closed by the time the `S3Exception` gets thrown and can't be read.

So effectively, AFAICT, nowhere in an `S3Exception` is the actual redirect URL captured.

Compare this with the raw XML returned by an endpoint, which actually tells us what "this endpoint" is:

```xml
<Error>
  <Code>PermanentRedirect</Code>
  <Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
  <!-- I want this data below somewhere in an S3Exception! -->
  <Endpoint>$SOME_BUCKET.s3-us-east-1.amazonaws.com</Endpoint>
  <Bucket>$SOME_BUCKET</Bucket>
  <RequestId>$SOME_REQUEST_ID</RequestId>
  <HostId>$SOME_HOST_ID</HostId>
</Error>
```

### Proposed Solution

One way to implement this without changing any of the public API surface to actually pass in non-null `documentBytes` to `software.amazon.awssdk.protocols.query.internal.unmarshall.AwsXmlErrorUnmarshaller.unmarshall`, which at least will get us the raw bytes of the HTTP response.

Right now when the XML is being unmarshalled it just gets saddled with an `Optional.empty()` which eventually turns into a `null` (see here: https://github.com/aws/aws-sdk-java-v2/blob/5d39aa01fc69269a316cce10667af2564fb42848/core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/AwsXmlErrorTransformer.java#L51).

We could instead do a similar thing with what is done here https://github.com/aws/aws-sdk-java-v2/blob/5d39aa01fc69269a316cce10667af2564fb42848/core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/unmarshall/AwsXmlErrorProtocolUnmarshaller.java#L99 that actually gives us a non-null `documentBody`.

### Describe alternatives you've considered

Could have an actual change to an `S3Exception`'s surface API, but that seems much more invasive.

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Java SDK version used

2.17.133

### JDK version used

openjdk version "16" 2021-03-16

### Operating System and version

NixOS 21.05

**Comment by vgjenks** [comment]
I thought I'd throw my $0.02 in here. I'm having the same problem w/ the JS SDK. An exception never actually gets thrown when doing an HTTP PUT on a bucket with a signed URL, but when I test in Postman, outside of the code, I see this:

`
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>PermanentRedirect</Code>
    <Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
    <Endpoint>s3.amazonaws.com</Endpoint>
    <Bucket>my-bucket-name</Bucket>
    <RequestId>XXXXXXXXXXXXXXXX</RequestId>
    <HostId>MY-HOSTID-VALUE</HostId>
</Error>
`
It's not very helpful and I have no idea why this is happening.

**Comment by kellertk** [comment]
P126359672

**Comment by steveloughran** [comment]
@vgjenks 
> It's not very helpful and I have no idea why this is happening.
newer regions (milan) are changing how requests against s3 central are redirected. instead of a 301/302 you now have to parse the response

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The request to support this is continuing to be tracked in the S3 team's backlog. Please refer to the [blog](https://aws.amazon.com/blogs/aws/category/storage/amazon-simple-storage-services-s3/) or SDK changelog for updates.
