### ISSUE TITLE
BUG with UpdateContactCommand @aws-sdk/client-sesv2

### ISSUE THREAD

**Issue by Meags27** [aws/aws-sdk#579]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

If I create a new contact with some attributes in the SES Contact List and then later run UpdateContactCommand to update the Topic Preferences for the contact and don't pass in "AttributesData" (which says in the docs is not required), the UpdateContactCommand will then ultimately override/wipe/delete the AttributesData. 

I wanted to be able to update a contact's topic preferences without having to pass in the AttributesData again (like name, location etc.)

  ```
//not passing in AttributesData
      const input = {
            ContactListName: ContactListNameHere,
            EmailAddress: email,
            TopicPreferences: [{
            TopicName: "Marketing",
            SubscriptionStatus: "OPT_IN",
        }]

const response = await sesClient.send(new UpdateContactCommand(input));   
        };
```

### SDK version number

@aws-sdk/client-sesv2@3.387.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.14.2

### Reproduction Steps

Some CLI commands to run (same issue happens with SDK) - you'l just have to add your credentials at the end to run them. Feel free to change the region too

//create contact list

aws sesv2  create-contact-list --contact-list-name testContactListName --topics "[{\"TopicName\":\"Marketing\",\"DisplayName\":\"Marketing\",\"Description\":\"MarketingTopic\",\"DefaultSubscriptionStatus\":\"OPT_OUT\"},{\"TopicName\":\"News\",\"DisplayName\":\"News\",\"Description\":\"NewsTopic\",\"DefaultSubscriptionStatus\":\"OPT_OUT\"}]" --region us-west-2

//create contact

aws sesv2 create-contact --contact-list-name playersEmailList --email-address example@gmail.com --region us-west-2 --attributes-data {\"Name\":\"TestName\"} --topic-preferences "[{\"TopicName\":\"Marketing\",\"SubscriptionStatus\":\"OPT_OUT\"},{\"TopicName\":\"News\",\"SubscriptionStatus\":\"OPT_IN\"}]"

//get contact

aws sesv2 get-contact --contact-list-name playersEmailList --email-address example@gmail.com --region us-west-2

//update contact

aws sesv2 update-contact --contact-list-name playersEmailList --email-address example@gmail.com --region us-west-2 --topic-preferences "[{\"TopicName\":\"Marketing\",\"SubscriptionStatus\":\"OPT_OUT\"},{\"TopicName\":\"News\",\"SubscriptionStatus\":\"OPT_OUT\"}]"

//get contact

aws sesv2 get-contact --contact-list-name playersEmailList --email-address example@gmail.com --region us-west-2

### Observed Behavior

With get contact, the first time is shows the AttributeData, the second time it doesn't. I assume it's overiding the AttributeData?

### Expected Behavior

I expected the AttributeData to still be there when only updating the Topic Preferences.

**Comment by RanVaknin** [comment]
Hi,

I heard back from the service team. This is the intentional behavior. They have updated their API docs to reflect this:

>[UpdateContactCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sesv2/command/UpdateContactCommand)	
>
>Updates a contact's preferences for a list.
>
>You must specify all existing topic preferences in the TopicPreferences object, not just the ones that need updating; otherwise, all your existing preferences will be removed.

Thanks,
Ran~
