### ISSUE TITLE
Lack of space between `attributes` and `defined`  

### ISSUE THREAD

**Issue by okarmusk** [aws/aws-sdk#58]
After calling create table operation on localhost DynamoDB, aws cli returns error code with lack of space between words `attributes` and `defined`.

Output:
```
An error occurred (ValidationException) when calling the CreateTable operation: The number of attributes in key schema must match the number of attributesdefined in attribute definitions.
```

I mean word **attributesdefined** in error log.

AWS cli version:
`aws-cli/2.1.36 Python/3.8.8 Linux/5.4.0-70-generic exe/x86_64.ubuntu.20 prompt/off`

**Comment by kdaily** [comment]
V347268349
