### ISSUE TITLE
Missing option to enable DNSSEC for registered domains

### ISSUE THREAD

**Issue by TCY16** [aws/aws-sdk#587]
### Describe the feature

Currently enabling DNSSEC on a registered domain is not possible via the CLI, but is possible via the management console. I would love a command option that makes it possible to register a DS record public key generated by the `create-key-signing-key` command.

### Use Case

This a missing feature in the chain of automating DNSSEC on anyones full domain currently

### Proposed Solution

Please add this command option

### Other Information

-removed incorrect reference-

### Acknowledgements

- [X] I may be able to implement this feature request

### CLI version used

2.13.1

### Environment details (OS name and version, etc.)

macOS Ventura 13.4

**Comment by RyanFitzSimmonsAK** [comment]
@Hi @TCY16; I spoke with the service team and they pointed me towards [this](https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_AssociateDelegationSignerToDomain.html) operation in the Route53 API.  Does this fulfill your use case?

**Comment by TCY16** [comment]
Hi @RyanFitzSimmonsAK, thanks for getting back to me, it seems like it does! 

From the documentation you linked to I'm still a little unclear if this is specific for the route53, but I'm guessing it is. If so, this would allow me to publish my DS record with the Route53 registrar (like the steps from the first bubble in [this guide](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring-dnssec-enable-signing.html#dns-configuring-dnssec-chain-of-trust)), could you confirm that?

Thanks again!

**Comment by RyanFitzSimmonsAK** [comment]
Yes, that operation should fulfill that step in the guide you linked.

**Comment by TCY16** [comment]
That's great to hear! I would still love an implementation in the `aws-cli` tool, do you think that's possible?

Thanks!

**Comment by RyanFitzSimmonsAK** [comment]
Could you clarify what you mean by an implementation in the CLI?  The operation I linked earlier is available through the CLI (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/route53domains/associate-delegation-signer-to-domain.html).

**Comment by TCY16** [comment]
Ah great! I never found that in the documentation (while the name is correct of course, it's not exactly intuitive to me). Thanks, that's exactly what I was looking for 👍
