### ISSUE TITLE
AWS Batch SDK. Not returning job definition for job

### ISSUE THREAD

**Issue by jsarrelli** [aws/aws-sdk#588]
### Describe the bug

The Batch SDK is returning null as job definition. 

![Screenshot 2023-08-11 at 15 09 19](https://github.com/aws/aws-sdk-java-v2/assets/18368538/61be7c9f-d788-4c2a-ac3e-55ba83dd7aed)
![Screenshot 2023-08-11 at 15 09 54](https://github.com/aws/aws-sdk-java-v2/assets/18368538/51ad9105-0d3d-4a93-852b-b522d2239945)
![Screenshot 2023-08-11 at 15 10 07](https://github.com/aws/aws-sdk-java-v2/assets/18368538/28aabcf6-404e-48f7-98c9-540bd1ace487)
![Screenshot 2023-08-11 at 15 10 17](https://github.com/aws/aws-sdk-java-v2/assets/18368538/d7a1d9b0-8f62-4d05-9bae-d1ae486dd890)
a 

### Expected Behavior

Returns the job definition for a job correctly

### Current Behavior

Returning null as job definitions

### Reproduction Steps

1) Create a job associated with a job definition on AWS Console
2) Consume the job using the Batch SDK
3) Check result

### AWS Java SDK version used

"software.amazon.awssdk" % "batch" % "2.20.69"

### JDK version used

openjdk 11.0.16.1 2022-08-12

### Operating System and version

.

**Comment by debora-ito** [comment]
P97260321

**Comment by debora-ito** [comment]
@jsarrelli The Batch team acknowledged the issue, they are aware that JobDefinition should be returned in the ListJobs response. They added the task to their backlog, with no timeline for the fix to share right now.

On the investigation, they noticed that the JobDefinition is returned when a filter is provided:
```java
    ListJobsRequest request = ListJobsRequest.builder()
        .filters(f->f.name("JOB_NAME").values("MyJobTest"))
        .build();
```

so this can be used as a workaround.

I'll go ahead and mark this to auto close soon, as there's no action pending on the SDK team. Let us know if you have any other question.
