### ISSUE TITLE
`resourcegroupstaggingapi get-resources --resource-arn-list` does not accept valid ARNs

### ISSUE THREAD

**Issue by kota65535** [aws/aws-sdk#589]
### Describe the bug

`aws securityhub get-findings` returns findings with corresponding resources, whose ID is ARN.

```
{
    "Findings": [
        {
            "Resources": [
                {
                    "Type": "AwsEc2Instance",
                    "Id": "arn:aws:ec2:ap-northeast-1:433616233360:instance/i-0e41903cb3601a109",
        ...
```

I've noticed that some findings have resources with ID in different ARN formats. This is not surprising since there are 3 ARN formats according to [the document](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html).

1. `arn:aws:service:region:account-id:resource-type/resource-id`
    - Almost this
    - For example: `arn:aws:ec2:ap-northeast-1:433616233360:instance/i-0e41903cb3601a109`
2. `arn:aws:service:region:account-id:resource-id`
    - Sometimes
    - For example: `arn:aws:ec2:ap-northeast-1:433616233360:i-0825a83d29e870145`
3. `arn:aws:service:region:account-id:resource-type:resource-id`
    - I've never seen yet

The problem is that the 2nd format ARN cannot be used for `aws resourcegroupstaggingapi get-resources --resource-arn-list`.

```sh
$ aws resourcegroupstaggingapi get-resources --resource-arn-list "arn:aws:ec2:ap-northeast-1:433616233360:i-0825a83d29e870145"

An error occurred (InvalidParameterException) when calling the GetResources operation: arn:aws:ec2:ap-northeast-1:433616233360:i-0825a83d29e870145 is not a valid AmazonResourceName (ARN)
```

The documentation does not specify the format of ARNs that will be accepted. Is this an expected behavior?

Or, is it actually due to `aws securityhub get-findings` not returning resource IDs with the 1st ARN format?

### Expected Behavior

`resourcegroupstaggingapi get-resources --resource-arn-list` succeeds with the 2nd ARN format.

### Current Behavior

```sh
$ aws resourcegroupstaggingapi get-resources --resource-arn-list "arn:aws:ec2:ap-northeast-1:433616233360:i-0825a83d29e870145"

An error occurred (InvalidParameterException) when calling the GetResources operation: arn:aws:ec2:ap-northeast-1:433616233360:i-0825a83d29e870145 is not a valid AmazonResourceName (ARN)
```

### Reproduction Steps

See Describe the bug

### CLI version used

aws-cli/2.13.9 Python/3.11.4 Darwin/21.4.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Darwin/21.4.0

**Comment by RyanFitzSimmonsAK** [comment]
Hi @kota65535, thanks for your patience.  This behavior was actually fixed before the creation of this issue.  Triggering a new scan of your resources should result in ARNs that are correctly formed.  You can do that by changing some settings in Security Hub about your EC2 findings.  Hope that helps, please let me know if you have any follow-up questions.
