### ISSUE TITLE
dynamodb.ErrCodeConditionalCheckFailedException should indicate which condition failed

### ISSUE THREAD

**Issue by timthejiang** [aws/aws-sdk#59]
**Is your feature request related to a problem? Please describe.**
When an UpdateItem request has a failed condition, `dynamodb.ErrCodeConditionalCheckFailedException` does not indicate which condition failed.

**Describe the solution you'd like**
When a condition fails, the error should indicate which condition failed. Similar to `dynamodb.TransactionCanceledException.CancellationReasons`.

**Describe alternatives you've considered**
Retrieving the item before UpdateItem to check the conditions in calling code, but that seems hacky.

**Additional context**
N/A

**Comment by stobrien89** [comment]
Hi @timthejiang,

My sincere apologies for the delayed response on this.  I've created an internal ticket to request this functionality from the DynamoDB team.  I'll reach out as soon as I have an update!

**Comment by stobrien89** [comment]
P51608561

**Comment by tim-finnigan** [comment]
We were informed that the DynamoDB team added this feature request to their backlog. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for updates going forward, but feel free to check back in here as well.
