### ISSUE TITLE
Support Application assignments in AWS IAM Identity Center (successor to AWS Single Sign-On)

### ISSUE THREAD

**Issue by lvthillo** [aws/aws-sdk#593]
There is no API to automate application assignments in AWS IAM Identity Center. We add and remove new AWS accounts on a daily base (with new SSO groups). We should configure this manually each time.

**Comment by jmklix** [comment]
P100882565

**Comment by jmklix** [comment]
Support for application assignments was added last year. Please let us know if you have any questions/problems with this.
