### ISSUE TITLE
NextToken field is not populated in DescribeScalableTargetsResult

### ISSUE THREAD

**Issue by emilsedai** [aws/aws-sdk#595]
### Describe the bug

The result of the function `describeScalableTargets` of the class `AWSApplicationAutoscaling` does not have the field `nextToken` populated.

Pagination doesn't work for this request because `nextToken` will always be null.

### Expected Behavior

The `nextToken` field would have the token for requesting the next page of the API response.

### Current Behavior

The `nextToken` field in the `DescribeScalableTargetsResult` is always null.

### Reproduction Steps

```java
DescribeScalableTargetsResult result = awsApplicationAutoScalingClient.describeScalableTargets(
        new DescribeScalableTargetsRequest.withMaxResults(2).withServiceNamespace("ecs"));
System.out.println(result.getNextToken()); // this will be null
```

### Additional Information/Context

The problem was reproduced in accounts with multiple autoscalers.

### AWS Java SDK version used

1.12.400

### JDK version used

17.0.8

### Operating System and version

Ubuntu 22.04.1 LTS

**Comment by debora-ito** [comment]
P98567392

**Comment by ashishdhingra** [comment]
Reached out to service team for the backlog item in their feature list. As of now, no ETA is available for prioritization and fix. Closing this issue since it is already tracked in service team backlog.
