### ISSUE TITLE
Pinpoint update journey with ACTIVE state cannot accept a timezone

### ISSUE THREAD

**Issue by bahaa-mp** [aws/aws-sdk#597]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When I try to update a journey in pinpoint in sdk v3 to active state. like this 

```
import { PinpointClient,  UpdateJourneyCommand  } from "@aws-sdk/client-pinpoint"; 
const ppclient = new PinpointClient({ region: "us-west-2" }); 
const input = { // Update Journey Command 
   // ... all required parameters 
    Schedule: { // JourneySchedule
       EndTime: new Date("2023-09-10 11:00 AM"),
       StartTime: new Date("2023-09-3 12:15 PM"),
        Timezone: "UTC+09"
     },
     State: "ACTIVE",
},
const command = new UpdateJourneyCommand(input);
await ppclient.send(command );
```

I always get an error like this 

```
Journey validation failed, Start time 2023-09-03T12:15:00Z doesn't have the same offset as the journey's schedule offset: UTC+09
```

It is clear that whatever we set as a value to StartTime or EndTime would not  solve the issue as the _.toISOString() is executed internally and always would result in an ISO string without time offset. 

### SDK version number

@aws-sdk/client-pinpoint 

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

lambda environment node Node.js 18.x

### Reproduction Steps

Use the code mentioned in the description 

### Observed Behavior

I could not set a journey as an active with a timezone 

### Expected Behavior

I should be able to set a journey as an active with a timezone

**Comment by bahaa-mp** [comment]
Hi Ran, 

Thank you for the follow-up and the detailed investigation. Please keep us posted with the result of your ticket. 

Unfortunately, there are other issues I face sometimes like when the Journey created in the console has open hours in the schedule for some days and the other days are empty (default no open hours). Then, the getJourneyCommand does not work and returns an error that cannot format dates.  But the REST API / or the SDK v2 work.

Also, I could not set the estimation of the timezone per endpoint phone number. I double-checked to use a local time = true. 
The request returns success but that has no effect in the console. In SDK v2, I get the error TimezoneEstimationMethods is not an expected key!

Thank you again

**Comment by ashishdhingra** [comment]
@bahaa-mp Good afternoon. We have an update from the service team that the fix is already deployed for this issue. Could you please verify the same at your end and confirm if this issue is good to be closed.

Thanks,
Ashish
