### ISSUE TITLE
Inconsistent Outputs with AppRunner list-services

### ISSUE THREAD

**Issue by aBurmeseDev** [aws/aws-sdk#599]
Original Issue: https://github.com/aws/aws-cli/issues/8124

**Comment by aBurmeseDev** [comment]
P98343488

**Comment by tim-finnigan** [comment]
The service team has acknowledged this issue but is not able to prioritize it at this time.

**Comment by MarcoGlauser** [comment]
@tim-finnigan Thank you for the update. We have since completely moved away from apprunner because of issues like this that were and will probably never be addressed and make the dev experience unnecessarily complicated.
