### ISSUE TITLE
Request with "Communications link failure" from the RDS Data Service should be retried

### ISSUE THREAD

**Issue by advanderveer** [aws/aws-sdk#60]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
Accessing an Aurora servless database through the Data API (rdsdataapiservice) when the database is asleep returns a BadRequestException that is not retried by default. The error looks like this:
```
BadRequestException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

**Version of AWS SDK for Go?**
1.35.22

**Version of Go (`go version`)?**
go1.15.3 darwin/amd64

**To Reproduce (observed behavior)**
When the database is asleep (capacity is 0), run the following:
```
package db

import (
	"context"
	"testing"

	awss "github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/rdsdataservice"
)

func TestDataAPIRetry(t *testing.T) {
	sess := session.Must(session.NewSession())

	var in rdsdataservice.ExecuteStatementInput
	in.SetResourceArn("arn:aws:rds:eu-west-1:...")
	in.SetSecretArn("arn:aws:secretsmanager:eu-west-1:...")
	in.SetSql(`SELECT table_schema FROM information_schema.columns`)

	_, err := rdsdataservice.New(sess).ExecuteStatementWithContext(context.Background(), &in)
	if err != nil {
		t.Fatal(err)
	}
}
```

it will output
```
--- FAIL: TestDataAPIRetry (3.86s)
    data_api_test.go:27: BadRequestException: Communications link failure
        
        The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

**Expected behavior**
The expected behaviour is that the default retryer should retry this error until the database becomes available. My guess is that the "BadRequestException" part causes the SDK to think the error is not retryable (Status code 400). But the "Communications link failure" part shows that it should be (could be a temporary network error after all).

**Additional context**
As a test to prove that it was the retry logic I created a custom retryer that always retries. And it caused the correct behaviour. 

Also, it seems the JS SDK ran into the same issue and there it was as mall fix to a "retry matcher": https://github.com/aws/aws-sdk-js/issues/2914. But arguably the response shouldn't have been a BadRequestException to begin with...

**Comment by KaibaLopez** [comment]
So the error is defined by the service models and it defines what kind of errors are retry-able by default, you could define your own retry strategy to retry this kind of errors but if your expectation is that the error is retry-able then it becomes a feature request for the service model.

**Comment by peterwoodworth** [comment]
Created ticket: P52850852

**Comment by peterwoodworth** [comment]
The team is aware of this and has this item in their backlog, thank you for reporting this issue 😄
