### ISSUE TITLE
aws docdb describe-db-instances | missing "PerformanceInsightsEnabled" in output

### ISSUE THREAD

**Issue by mt-spe** [aws/aws-sdk#607]
### Describe the bug

Output for -

`aws docdb describe-db-instances --filters Name=db-cluster-id,Values=adocdb-cluster-cl1 --query 'DBInstances[].PerformanceInsightsEnabled'`

is not returning any data for a DocumentDB cluster.

However, results are returned for 

`aws rds describe-db-instances --filters Name=db-cluster-id,Values=adocdb-cluster-cl1 --query 'DBInstances[].PerformanceInsightsEnabled'`

$ aws --version
aws-cli/2.8.9 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Expected Behavior

Output should show value of PerformanceInsightsEnabled - either true or false. For example, this below for a 3 instance cluster.

[
    true,
    true,
    true
]

### Current Behavior

No values are returned.
[]

### Reproduction Steps

`aws docdb describe-db-instances --filters Name=db-cluster-id,Values=adocdb-cluster-cl1 --query 'DBInstances[].PerformanceInsightsEnabled'`

### Possible Solution

aws docdb describe-db-instances output should include the status of PerformanceInsightsEnabled - either true or false.

### CLI version used

aws-cli/2.8.9

### Environment details (OS name and version, etc.)

Windows/10 exe/AMD64

**Comment by RyanFitzSimmonsAK** [comment]
`PerformanceInsightsEnabled` and `PerformanceInsightsKMSKeyId` have been added to the `DescribeDBInstances` response.  Thank you for your patience.
