### ISSUE TITLE
Add Waiter for NAT Gateway Deletion.

### ISSUE THREAD

**Issue by allir** [aws/aws-sdk#61]
**Is your feature request related to a problem? Please describe.**
Since deleting a NAT gateway takes a little while it's useful to have a waiter since it can otherwise lead to dependency failures to delete other resources like VPC.

**Describe the solution you'd like**
Add a waiter for NatGatewayDeleted.

**Describe alternatives you've considered**
Writing a loop to manually check for the state and continue once deleted.

**Additional context**

**Comment by nnsense** [comment]
It would be useful, I'm trying to delete a whole terraform deplyoment and those NGWs are taking ages.
I've found somewhere the following snippet, but it doesn't work
```
waiter = client_ec2.get_waiter('nat_gateway_available')
waiter.wait(Filters=[{'Name': 'state','Values': ['deleted']},{'Name': 'nat-gateway-id','Values': [ <my_ngw_id> ]}])
```

It gives this error:
```
botocore.exceptions.WaiterError: Waiter NatGatewayAvailable failed: Waiter encountered a terminal failure state: For expression "NatGateways[].State" we matched expected path: "deleted" at least once
```

Adding this feature would be awesome, or at least a workaround (like the one above, but working).

Thanks

**Comment by tim-finnigan** [comment]
Just reached out to the EC2 team for feedback on this request and will post an update here when I hear back!

**Comment by tim-finnigan** [comment]
P62157317

**Comment by tim-finnigan** [comment]
The EC2 team recently added a waiter model for NatGatewayDeleted. If you update to the latest version of your SDK then you should be able to use it. Please reach out if you have any other questions!
