### ISSUE TITLE
Add `--engine-arn` to `update-canary`

### ISSUE THREAD

**Issue by socketbox** [aws/aws-sdk#613]
### Describe the feature

I'd like to see `update-canary` be capable of taking an `--engine--arn` argument that does what the Java and Go SDK are capable of with [setEngineArn](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/synthetics/model/Canary.html#setEngineArn-java.lang.String-) and [SetEngineArn](https://github.com/aws/aws-sdk-go/blob/8f1d676824ca07db1386cbaced6e855e9236a333/service/synthetics/api.go#L2783).

### Use Case

When instantiating canaries outside of the AWS Console, either via IaC-related approaches or some other means, it's possible for the canary to become out-of-sync with its attendant Lambda function's latest version.

If there was a different use case that was behind the creation of the `setEngineArn`/`SetEngineArn` methods of the SDKs, then I'd think that same use case would apply here as well.

### Proposed Solution

As mentioned, I think this could be as simple as adding an `--engine-arn` option to `aws synthetics update-canary`.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.11.16 Python/3.11.3 Linux/6.2.0-33-generic

### Environment details (OS name and version, etc.)

Linux/6.2.0-33-generic  x86-64 Linux Mint 21.2

**Comment by tim-finnigan** [comment]
We heard back from a member of the service team and they have added this feature request to their backlog. We cannot guarantee if or when the service team would implement this feature, but feel free to check back in the future for updates. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.
