### ISSUE TITLE
log file size is different when downloaded using console and cli

### ISSUE THREAD

**Issue by YashCharpe** [aws/aws-sdk#615]
### Describe the issue

I am trying to download log file of writer instance using aws cli. So for that I am using 'download-db-log-file-portion' command like this:
```
aws rds download-db-log-file-portion \
--db-instance-identifier instance_name \
--log-file-name error/postgresql.log.2023-09-26-0300.gz \
--starting-token 0 \
--output text >> directory_path
```
This rds instance has .gz extension log files. On console, I can see the log file size as 25mb but when I download it via the above command, the downloaded file size is of 223mb. Does anyone know what could be the reason behind this and how do I download the log file of 25mb?

### CLI version used

1.22.34

### Environment details (OS name and version, etc.)

WSL2

**Comment by tim-finnigan** [comment]
Thanks for your patience — we heard back from someone on the RDS team who said that you could use the DownloadCompleteDBLogFile API for this use case: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/DownloadCompleteDBLogFile.html. (Note that this is only available via REST API and not in the SDKs.) Please let us know if you have any follow up questions.
