### ISSUE TITLE
SDK doesn't offer a way to remove canary VPC Config

### ISSUE THREAD

**Issue by carcher5432** [aws/aws-sdk#617]
### Describe the bug

There is no way in the SDK to send the correct request that AWS expects in order to remove VPC Config from an existing canary.

### Expected Behavior

VPC Config can be removed from canary.

### Current Behavior

AWS API request that successfully removes the vpc configuration:
```
{ # Other parameters removed because they are not relevant
   "requestParameters": {
        "VpcConfig": {
            "SubnetIds": "***",
            "SecurityGroupIds": "***"
        },
        "name": "canary-name"
    }
}
```
*output comes from CloudTrail

With this structure for the VPC Config Input and no additional logic to set the "***" that the AWS API expects, it doesn't seem possible to remove an existing VPC Config.
```go
type VpcConfigInput struct {
	_ struct{} `type:"structure"`

	// The IDs of the security groups for this canary.
	SecurityGroupIds []*string `type:"list"`

	// The IDs of the subnets where this canary is to run.
	SubnetIds []*string `type:"list"`
}
```

### Reproduction Steps

N/A

### Possible Solution

I don't know what the best solution would be, given the current type constraints. It might require an additional field on the VpcConfigInput type and custom logic where the json body for the API request is created.

### SDK version used

latest

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

N/A, core feature

**Comment by tim-finnigan** [comment]
Were there any updates on the internal ticket opened for this? I couldn't find anything referencing this issue. If in involves Terraform then this may something that would need to be handled on their end.
