### ISSUE TITLE
Kinesis SerializationError masking ServiceUnavailableException

### ISSUE THREAD

**Issue by palmerlao** [aws/aws-sdk#62]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**

When making Kinesis `PutRecord` calls, occasionally the SDK reports that it has a `SerializationError`, but the body of the payload it's attempted to deserialize seems to indicate that it's actually a `ServiceUnavailableException` that isn't being handled correctly.

```
SerializationError: failed to unmarshal response error
status code: 503, request id: d16bcad1-3fe9-a741-895a-307fea237b3c
caused by: UnmarshalError: failed decoding error message
00000000  3c 53 65 72 76 69 63 65  55 6e 61 76 61 69 6c 61  |<ServiceUnavaila|
00000010  62 6c 65 45 78 63 65 70  74 69 6f 6e 2f 3e 0a     |bleException/>.|
caused by: invalid character '<' looking for beginning of value
```

**Version of AWS SDK for Go?**

`v1.35.8`

**Version of Go (`go version`)?**

`1.14`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

This is a transient error that happens very rarely (approximately 1/30000 over the last day), so I don't have a useful reproduction to share.

**Expected behavior**

The SDK returns an error that is easy to match on using `errors.Is` or `errors.As` and a library-defined error value or type. The error value or type indicates that it is a transient server failure, not a client parsing error. The error value or type does not contradict the error code.

**Additional context**

I mostly see this error in an application that is doing cross-account Kinesis calls.

**Comment by KaibaLopez** [comment]
ticket created P51610272
