### ISSUE TITLE
TypeScript types for SNS client could be improved

### ISSUE THREAD

**Issue by kibertoad** [aws/aws-sdk#626]
This is the equivalent of https://github.com/aws/aws-sdk/issues/557 for the SNS

### Describe the feature

See https://github.com/aws/aws-sdk-js-v3/blob/6c8730a9646e324cc2c01b6e86df974a9f39fc64/clients/client-sns/src/models/models_0.ts#L548

Attributes are defined simply as `Attributes?: Record<string, string>` without any type-safety. Supported options are only listed in documentation.

### Use Case

When project that relies on SNS client is using TypeScript, it is very helpful to have compilation time type-safety, so that compilation will fail, if unsupported parameter is passed. Otherwise this error will only be caught in the runtime, which may be too late.

### Proposed Solution

Provide stronger types in /clients/client-sns/src/models/models_0.ts

Likely same solution that was used for SQS could be reused here (I assume these are autogenerated types as well).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.433.0

### Environment details (OS name and version, etc.)

Windows 11

**Comment by tim-finnigan** [comment]
Thanks for creating this feature request, we'll try reaching out to the SNS team to see if they would consider these changes like the SQS team did. (ref: P138972038)

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The SNS team is continuing to track this in their backlog. We cannot guarantee when service API requests like this would be implemented, but please refer to the [blog](https://aws.amazon.com/blogs/compute/category/messaging/amazon-simple-notification-service-sns/) or SDK changelog for updates going forward.
