### ISSUE TITLE
How to get untagged resources using resourcegrouptagging api?

### ISSUE THREAD

**Issue by PraveenR-r** [aws/aws-sdk#627]
Hi everyone, Is this issue been looked upon? Wondering if the SDK could list down untagged resources from the AWS account. Because using the same resourcegrouptagging sdk, it still returns tagged resources and the resources that has been tagged before. Is there any filter that could be set to get the untagged resources as well?

_Originally posted by @PraveenR-r in https://github.com/aws/aws-sdk/issues/12#issuecomment-1776911709_

**Comment by tim-finnigan** [comment]
The request for API/SDK support is still being tracked but not prioritized. In the meantime please refer to https://docs.aws.amazon.com/resource-explorer/latest/userguide/using-search-query-examples.html#example-1.
