### ISSUE TITLE
identitystore describe-user: get enabled/disabled status

### ISSUE THREAD

**Issue by jk2l** [aws/aws-sdk#628]
More or less follow up on https://github.com/aws/aws-sdk/issues/477, as that ticket is closed and AWS team may not see it. I am trying to start a new conversation here.

as AWS console's API provide the Active field information but not accessible via official AWS API. what is aws-sdk stand on integrate with that side of API by pulling in the information from that? there are example codes on how to achieve it, but it will be great to be built in officially into AWS sdk

**Comment by tim-finnigan** [comment]
I provide an updated here on the issue you linked: https://github.com/aws/aws-sdk/issues/477#issuecomment-1785761496. Going to close this one as a duplicate.
