### ISSUE TITLE
Paginators for Lightsail `GetInstances` and `GetStaticIps` calls

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk#631]
### Describe the feature

The Lightsail APIs `GetInstances` and `GetStaticIps` support pagination, but don't have generated Paginators

### Use Case

We currently have to manually paginate calls to the APIs instead of using a Paginator

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/lightsail v1.27.1

### Go version used

go version go1.20.3 darwin/arm64

**Comment by jmklix** [comment]
Thank you for your feedback. We've let the responsible internal team know and they've placed this on their backlog. We can't share specific timelines on when this might be implemented in GitHub. You should monitor the [AWS News Blog](https://aws.amazon.com/blogs/aws/) for updates.
