### ISSUE TITLE
EXTERNAL_PROVIDER missing from UserStatusType

### ISSUE THREAD

**Issue by walterholohan** [aws/aws-sdk#635]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

EXTERNAL_PROVIDER is missing from the UserStatusType enum. Not sure if this is on purpose or a mistake. it is mentioned in the [docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserType.html) but is not in the list of valid values. We use EXTERNAL_PROVIDER within our code so do not want to upgrade SDK until I know if its a missing type issue or not

### SDK version number

@aws-sdk/client-cognito-identity-provider@3.438.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.x

### Reproduction Steps

Upgrade @aws-sdk/client-cognito-identity-provider to latest version and you will get a type error for `EXTERNAL_PROVIDER` in UserStatusType @

### Observed Behavior

UserStatusType should have a value for EXTERNAL_PROVIDER

### Expected Behavior

UserStatusType should have a value for EXTERNAL_PROVIDER

**Comment by pajohns** [comment]
I noticed this omission of EXTERNAL_PROVIDER too. @RanVaknin this is certainly a workaround that you've suggested, but it was confusing for me as I would like to be able to map all available responses from AWS and this one was missing hence was throwing an exception when trying to map it to a matching domain model on my end.

**Comment by flamewow** [comment]
EXTERNAL_PROVIDER is missing in UserStatusType, but the JSDoc still contains it
<img width="1366" alt="image" src="https://github.com/aws/aws-sdk/assets/7524697/bb1e5e14-fb20-41d6-a9fb-52f929d74245">

**Comment by RanVaknin** [comment]
I have checked back with the service team and asked them to properly release the model change. 
Since this is not actionable by the SDK team, Im going to go ahead and close this ticket.

Please keep an eye on our release note to see when this has been updated.

Thanks again!
Ran~

**Comment by RanVaknin** [comment]
This has now been released.
