### ISSUE TITLE
Add `--filters` for iam list-roles

### ISSUE THREAD

**Issue by LozanoMatheus** [aws/aws-sdk#636]
### Describe the feature

Currently, the [iam list-roles](https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html) doesn't have the option `--filters`, only the query.

### Use Case

This would be quite handy when using the AWS CLI for scripting. For example, if I want to get certain roles:

```bash
aws iam list-roles --query "Roles[*].RoleName" --filters "Name=role-name,Values=*my-role*"

## or using the tagging

aws iam list-roles --query "Roles[*].RoleName" --filters "Name=tag:Name,Values=*my-role*"
```

### Other Information

Similar to [ec2 describe-instances](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#options)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.13.28 Python/3.11.6 Darwin/22.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS Ventura 13.6

**Comment by michaelajr** [comment]
This is definitely needed. Especially to list all roles based on a tag.

**Comment by RyanFitzSimmonsAK** [comment]
The IAM team replied to me with the following information.

- Implementing filtering is not currently feasible for this API.  They do have a relevant backlog item.
- They mentioned GetRole if you want the details of a specific role.
- Consider using utilities such as `grep` if that works for your use case.

Obviously you are aware of the CLI's client-side filtering capabilities as well.

I'm going to close this issue for now, but I'll reopen it if anything changes regarding this.
