### ISSUE TITLE
waitUntilLoadBalancersDeleted never resolves

### ISSUE THREAD

**Issue by cpyle0819** [aws/aws-sdk#639]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The waiter, `waitUntilLoadBalancersDeleted`, returns a promise that never resolves.

### SDK version number

 "@aws-sdk/client-elastic-load-balancing-v2": "^3.441.0"

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.9.0

### Reproduction Steps

```
import {
  ElasticLoadBalancingV2Client,
  waitUntilLoadBalancersDeleted,
} from "@aws-sdk/client-elastic-load-balancing-v2";

await waitUntilLoadBalancersDeleted(
  {
    client: new ElasticLoadBalancingV2Client({}),
  },
  { Names: ["some-fake-name"] }
);
```

### Observed Behavior

The promise from the waiter never resolves.

### Expected Behavior

The promise should resolve immediately for non-existent load balancers.

**Comment by kuhe** [comment]
fixed in the AWS SDK JSv3 with https://github.com/aws/aws-sdk-js-v3/pull/6501
