### ISSUE TITLE
Return full JSON vs. Hive data structures from the AWS Glue GetTables method

### ISSUE THREAD

**Issue by jaysonhurd** [aws/aws-sdk#64]
**Is your feature request related to a problem? Please describe.**
When I use the AWS Glue GetTables method it returns JSON with some kind of Hive structures nested within for the individual objects (i.e. tables, complex data structures etc.).  This makes the results very difficult to work with because it's not a structure that we frequently use with Go such as JSON or XML.

**Describe the solution you'd like**
I would like the option in the GetTables method for AWS Glue to be able to return full JSON such that the data leaves are returned also as JSON within the full JSON payload.  This would make it much easier to work with.

**Describe alternatives you've considered**
I have already written a couple of functions in a small package to do this.  It's basically a parser that takes any Hive data structure and converts it to JSON.  I had to do this in order to be able to effectively work with these while analyzing databases.

**Additional context**
I did not wish to create a fork and add this (which would require further rework to integrate into the existing AWS package) without first checking if something like this might already exist or be planned.

**Comment by KaibaLopez** [comment]
P51610624 created

**Comment by RanVaknin** [comment]
Hi @jaysonhurd ,

This was never get addressed by the service team. If this is still relevant you might want to open a feature request through the AWS console. Tickets filed by customers tend to get more leverage when asking for new features. 

Thanks,
Ran~
