### ISSUE TITLE
S3 Strong consistency mention

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk#65]
**Describe the issue with documentation**
No mention of S3 consistency upon https://pkg.go.dev/github.com/aws/aws-sdk-go/service/s3

https://aws.amazon.com/s3/consistency/

**To Reproduce (observed behavior)**
Find on documentation page

**Expected behavior**
Keywords like "consistency" match and an example can be found

**Comment by NGL321** [comment]
Hey @kaihendry,

Thank you for reporting this! It appears to be a gap in documentation spanning across SDKs, so we are going to track it here as a bug. You can watch this issue for further updates as a fix gets implemented.

😸 😷

**Comment by jmklix** [comment]
P51418559

**Comment by jmklix** [comment]
All s3 operations are strongly consistent, as noted [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel):
>Strong consistency
Amazon S3 provides strong read-after-write consistency for PUT and DELETE requests of objects in your Amazon S3 bucket in all AWS Regions. This behavior applies to both writes of new objects as well as PUT requests that overwrite existing objects and DELETE requests. In addition, read operations on Amazon S3 Select, Amazon S3 access control lists (ACLs), Amazon S3 Object Tags, and object metadata (for example, the HEAD object) are strongly consistent. For more information, see [Amazon S3 data consistency model](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel).

This being details about the s3 service means that it doesn't need to be documented in each of the sdk's. So I will be closing this issue. If you disagree or have any other suggestions for documentation improvements please let us know.

**Comment by joeatnetgear** [comment]
I am trying to implement a goloang program and can not find the strong consistency attribute in the put object.   Can somebody provide an example of how to use it from golang
