### ISSUE TITLE
EnableSnapshotBlockPublicAccess API does not accept `unblocked` for `State`

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#651]
Original issue: https://github.com/boto/boto3/issues/3942

API: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EnableSnapshotBlockPublicAccess.html

Ref: P106671727

**Comment by tim-finnigan** [comment]
> There are a few issues with your `RoundTrip` implementation:
> 
> 1. You're consuming the body without resetting it. This combined with my next point is almost certainly why you're seeing that failure of "content length x with body length 0" - you're using up the entire body, so when the underlying transport goes to actually send the request, it tries to read the body and gets nothing. As an aside I wouldn't recommend discarding the error on `ReadAll` but that's up to your discretion.
> 2. You're mutating the request which directly violates the semantic restrictions on [`http.RoundTripper`](https://pkg.go.dev/net/http#RoundTripper) - see the API doc there, but more specifically, implementations SHOULD NOT modify the request (which you are doing when you set `ContentLength`).
> 
> * specifically in the SDK you will run into various issues (i.e. with signing and content hash calculations) if you do this. The correct way to modify the behavior of SDK requests is via [middleware](https://aws.github.io/aws-sdk-go-v2/docs/middleware/).
> 
> Beyond that I'm not sure how implementing the requested change would solve the problem here. Let's address the above issues in advance of any discussion.

Thank you for your help.
It is indeed caused by the "io. ReadAll" method, and I have fixed this error
```
data, _ := io.ReadAll(req.Body)
if len(data) > 0 {
attrs = append(attrs, attribute.String("http.request.body", string(data)))
}
req.Body = io.NopCloser(bytes.NewBuffer(data))
```
Although creating a custom client in this way can enable recording of request data during requests, I would like to use the default client with options http.RoundTripper. *http. Transport is an implementation of http. RoundTripper

**Comment by tim-finnigan** [comment]
test123

**Comment by tim-finnigan** [comment]
> testing

**Comment by tim-finnigan** [comment]
>testing 3
23

**Comment by tim-finnigan** [comment]
>testing

waefwef

**Comment by TimFinnigan** [comment]
test words
>quote1
> quote 2

test 3

**Comment by TimFinnigan** [comment]
> Original issue: [boto/boto3#3942](https://github.com/boto/boto3/issues/3942)
> 
> API: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EnableSnapshotBlockPublicAccess.html
> 
> Ref: P106671727

quote reply

**Comment by tim-finnigan** [comment]
The API documentation has been updated to note:
>`unblocked` is not a valid value for **EnableSnapshotBlockPublicAccess**.

(It still shows in the `Valid Values` list due to the modeling traits, I followed up with the service team to see if that's something they can address.)
