### ISSUE TITLE
ACM DomainStatus documentation has incomplete <code> blocks

### ISSUE THREAD

**Issue by jcardali** [aws/aws-sdk#656]
https://github.com/boto/botocore/blob/develop/botocore/data/acm/2015-12-08/service-2.json#L617

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm/client/describe_certificate.html

**Comment by jmklix** [comment]
![code_block](https://github.com/aws/aws-sdk/assets/5644066/e927ac70-9ced-4d52-9c80-ceea7cebc942)

Thanks for pointing this out. I'm reaching out to the ACM team to get this documentation updated.

**Comment by jmklix** [comment]
P107746227
