### ISSUE TITLE
SQS sendMessageBatch is missing `Failed` array in the response (v2.1500)

### ISSUE THREAD

**Issue by gersmann** [aws/aws-sdk#657]
### Describe the bug

SendMessageBatch does not contain `Failed: []` anymore in case of successful sends:

```
sqs.sendMessageBatch(params, function (err, result) {
    if (err) return cb(err);

    failedMessages = failedMessages.concat(result.Failed.map(entryId));

    if (endIndex < messages.length) {
      return producer._sendBatch(failedMessages, messages, endIndex, cb);
    }

    cb(createError(failedMessages));
```

Gives us:
```
TypeError: Cannot read properties of undefined (reading 'map')
```

### Expected Behavior

According to the SendMessageBatch docs and the AWS SDK documentation, `Failed` is a required property:

[SendMessageBatch API Docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html#API_SendMessageBatch_ResponseElements)

Example:
```
HTTP/1.1 200 OK
x-amzn-RequestId: <requestId>
Content-Length: <PayloadSizeBytes>
Date: <Date>
Content-Type: application/x-amz-json-1.0
{
   "Failed": [],
    "Successful": [
        {
            "Id": "test_msg_001",
            "MD5OfMessageBody": "0e024d309850c78cba5eabbeff7cae71",
            "MessageId": "f4eb349f-cd33-4bc4-bdc2-e557c900d41d"
        },
        {
            "Id": "test_msg_002",
            "MD5OfMessageAttributes": "8ef4d60dbc8efda9f260e1dfd09d29f3",
            "MD5OfMessageBody": "27118326006d3829667a400ad23d5d98",
            "MessageId": "1dcfcd50-5a67-45ae-ae4c-1c152b5effb9"
        }
    ]
}
```

### Current Behavior

`Failed` is missing from the response object (in eu-central-1 as of 7am UTC)

### Reproduction Steps

Perform `sendMessageBatch` using the `aws-js-sdk` in `eu-central-1`.

### Possible Solution

Apparently this is handled at the SDK level now in for instance the Ruby SDK:
https://github.com/aws/aws-sdk-ruby/issues/2957

### SDK version used

2.1500

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by gersmann** [comment]
@RanVaknin thank youf or the follow up. What's interesting in this case, this has been working fine on the updated versions of the SDK, but stopped working around 23rd 6pm UTC (for us). Others have made the same observation, see : https://github.com/ssut/nestjs-sqs/issues/72 + the TS types / AWS docs also currently contain 'Failed'. 

@Noezor thanks for raising a support case. Can you keep us posted if you get a response or post the Case ID so that we can refer to it?

**Comment by Noezor** [comment]
+1 on the issue starting to appear at this time for us too. This created quite a lot of headaches to find the root cause.

CASE 14379988591 is where we filled it. I'll let support know that the issue has been rerouted to the SQS team so that they can investigate.

**Comment by RanVaknin** [comment]
Hi there, 

Thank you all for your patience. After some more investigation, we have found out that the behavior of adding `Failed: []` explicitly when there are no failed messages in the response was a behavior unique to JS SDK v2. 

I have created [a fix](https://github.com/aws/aws-sdk-js/pull/4542) for v2 to continue (mis)behaving the way it did before the migration to JSON. But just a heads up, this behavior is not going to be the same in v3. In v3 we rely on the service to send back data, and the SDK does not model data that is not returned. 

Thanks again for your cooperation.
All the best,
Ran~

**Comment by Noezor** [comment]
Thanks a lot Ran! Just tested and it works. Super speedy fix considering you had to ping an external team.

By the way, I used latest version (`2.1512`), but did not manage to find on the MR from which version onwards this was fixed. Do you know where to find on which release the MR was included?
