### ISSUE TITLE
Aws::Pinpoint::Client create_import_job fails

### ISSUE THREAD

**Issue by yeldah3** [aws/aws-sdk#660]
### Describe the bug

The `create_import_job` method on the Aws::Pinpoint::Client fails with the Aws::Pinpoint::Errors::BadRequestException 
```
Unexpected character ('I' (code 73)): was expecting double-quote to start field name
 at [Source: (String)"{ Id: "9GSh1dnhtfjUTh8J9Yj9N33LBe4f9gn2x1zks" }"; line: 1, column: 4].
```
The stack trace points to `lib/seahorse/client/plugins/raise_response_errors.rb:17`

As far as I'm aware, this `Id` is part of the response payload from this request (looking at the docs [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Pinpoint/Types/ImportJobResponse.html)), and it's causing the sdk to fail in sending the response back to us. 

### Expected Behavior

A successful response

### Current Behavior

The Aws::Pinpoint::Errors::BadRequestException is raised

### Reproduction Steps

```
credentials = Aws::Credentials.new(<access_key_id>, <secret_key>)
client = Aws::Pinpoint::Client.new(region: <region>, credentials: credentials)
import_job_request = {
  define_segment: true,
  format: "JSON",
  register_endpoints: true,
  role_arn: <role_arn>,
  s3_url: <s3_url>,
  segment_name: <segment_name>
}

client.create_import_job(
  {
    application_id: <application_id>,
    import_job_request: import_job_request
  }
)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-pinpoint 1.68.0, with aws-sdk-core 3.127.0 (although I tried upgrading to aws-sdk-pinpoint 1.84.0/aws-sdk-core 3.188.0 and saw the same error). 

### Environment details (Version of Ruby, OS environment)

ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin22]

**Comment by RanVaknin** [comment]
Hi @yeldah3,

I heard back from the Pinpoint service team. My problem was that the input I provided was a json object that was new line formatted. 
When I change the json file to a single line input:
```
{"Address":"example@email.com","ChannelType":"EMAIL","Attributes":{"CustomAttribute1":["value1","value2"],"CustomAttribute2":["value3","value4"]},"Demographic":{"AppVersion":"1.0","Locale":"en_US","Make":"Apple","Model":"iPhone","ModelVersion":"X","Platform":"ios"},"Location":{"Country":"US","Latitude":47.615556,"Longitude":-122.334444,"PostalCode":"98101","City":"Seattle"},"Metrics":{"CustomMetric1":1.0,"CustomMetric2":2.0},"User":{"UserId":"user123","UserAttributes":{"Interests":["sports","music"],"Age":["30"]}}}
```

This fixed the issue for me. 

Can you check the JSON file you uploaded to S3 to make sure it conforms to format highlighted above? 

Additionally, please check this documentation https://docs.aws.amazon.com/pinpoint/latest/userguide/segments-importing.html

Thanks,
Ran~

**Comment by yeldah3** [comment]
Hey Ran! Good catch, the issue was in fact that our json object was not properly formatted. We've fixed it on our end and not get 200s back from the API. Thanks for your help!
