### ISSUE TITLE
S3 getObject cors support

### ISSUE THREAD

**Issue by roeycohen** [aws/aws-sdk#662]
### Describe the feature

getObject parameters would support "Access-Control-Allow-Origin" (cors) header same way other headers are supported using
ResponseCacheControl, ResponseContentDisposition, ResponseContentEncoding, ResponseContentLanguage, ResponseContentType, ResponseExpires
see: https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#getobject

### Use Case

this mostly should be used with createPresignedRequest, avoiding the broader usage of policies.

### Proposed Solution

the second argument "parameters" will accept a new option such as ResponseAccessControlAllowOrigin... of course S3 backend should also support this feature :)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 7.4

**Comment by bhoradc** [comment]
V1349634501

**Comment by tim-finnigan** [comment]
Thanks for your patience here. The S3 team is continuing to track this feature request in their backlog. We cannot provide guarantees as to if or when this would be implemented, but please refer to the [blog](https://aws.amazon.com/blogs/aws/category/storage/amazon-simple-storage-services-s3/) or SDK changelog for updates going forward.
