### ISSUE TITLE
S3 EventBridgeConfiguration shape missing members

### ISSUE THREAD

**Issue by jcardali** [aws/aws-sdk#663]
https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json#L3832
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_bucket_notification_configuration.html

**Comment by jmklix** [comment]
P123898435

**Comment by kellertk** [comment]
Filtering EventBridge notifications are done with [this](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html), rather then EventBridgeConfiguration. But EventBridgeConfiguration is still a valid destination, so it remains modeled but empty.
