### ISSUE TITLE
describe_cluster method of EMR client not returning field 'Code'

### ISSUE THREAD

**Issue by RyanFitzSimmonsAK** [aws/aws-sdk#664]
Original issue : https://github.com/boto/boto3/issues/3964

Ticket # for internal reference : V1151986688

**Comment by RyanFitzSimmonsAK** [comment]
Hi @albertoCCz, thanks for your patience.  This behavior is intended.  All of the possible codes are for terminal states, and so the `Code` field will only appear if the cluster is terminating or terminated.  For responses that contain objects ([StateChangeReason ](https://docs.aws.amazon.com/emr/latest/APIReference/API_ClusterStateChangeReason.html)in this case), the documentation shows all possible fields for those objects, but not all parameters will necessarily exist for every operation.  Hope that helps!

**Comment by albertoCCz** [comment]
Okey, got it. Thanks @RyanFitzSimmonsAK!
