### ISSUE TITLE
DescribeLogGroupsResponse missing some field (logGroupArn)

### ISSUE THREAD

**Issue by thangdoominh** [aws/aws-sdk#669]
### Describe the issue

I use [DescribeLogGroupsCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudwatch-logs/command/DescribeLogGroupsCommand/) with [@aws-sdk/client-cloudwatch-logs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-cloudwatch-logs) for discover the list of Log Groups in AWS Cloudwatch. I saw some differences with a document in the response.

This is the example in the AWS Document:
```
{ // DescribeLogGroupsResponse
  logGroups: [ // LogGroups
    { // LogGroup
      logGroupName: "STRING_VALUE",
      creationTime: Number("long"),
      retentionInDays: Number("int"),
      metricFilterCount: Number("int"),
      arn: "STRING_VALUE",
      storedBytes: Number("long"),
      kmsKeyId: "STRING_VALUE",
      dataProtectionStatus: "ACTIVATED" || "DELETED" || "ARCHIVED" || "DISABLED",
      inheritedProperties: [ // InheritedProperties
        "ACCOUNT_DATA_PROTECTION",
      ],
      logGroupClass: "STANDARD" || "INFREQUENT_ACCESS",
    },
  ],
  nextToken: "STRING_VALUE",
};
```

My response:
```
{
  "arn": "arn:aws:logs:ap-southeast-1:*****:log-group:/aws/amazonmq/broker/b-***-***-***-***-***/general:*",
  "region": "ap-southeast-1",
  "logGroupArn": "arn:aws:logs:ap-southeast-1::*****::log-group:/aws/amazonmq/broker/b-***-***-***-***-***/general",
  "storedBytes": 26279***,
  "creationTime": 1670257385***,
  "logGroupName": "/aws/amazonmq/broker/b-***-***-***-***-***/general",
  "logGroupClass": "STANDARD",
  "retentionInDays": 180,
  "metricFilterCount": 0
}

```

- I saw the `logGroupArn` in the response. Its difference with arn field is the arn has `:*` and the `logGroupArn` doesn't has. I don't why it has 2 arn.
- When I use arn for the Tagging Resource (ResourceGroupsTaggingAPI -  "@aws-sdk/client-resource-groups-tagging-api": "^3.474.0") I use arn field in the response, which will raise the wrong arn. I use the logGroupArn, and it will be successful.

Package version:
`"@aws-sdk/client-cloudwatch-logs": "^3.478.0"`

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudwatch-logs/command/DescribeLogGroupsCommand/

**Comment by thangdoominh** [comment]
I use Typescript for my project. So the `interface LogGroup` doesn't have the `logGroupArn`, so I cannot use like 
![image](https://github.com/aws/aws-sdk/assets/44288750/99c93ee6-6dd9-465c-87fb-a3199f6f0358).
By your confirmation I already work around it. I will follow up on this issue,  thank you

**Comment by RanVaknin** [comment]
Documentation is now [updated](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html) 👍 
Thanks again!
Ran~
