### ISSUE TITLE
Golang version of AmazonSQSBufferedAsyncClient

### ISSUE THREAD

**Issue by wedneyyuri** [aws/aws-sdk#67]
### Is this related to a problem?
The AWS SDK for Java includes `AmazonSQSBufferedAsyncClient` which accesses Amazon SQS. It allows up to 10 requests to be buffered and sent as a batch request, decreasing the cost of using Amazon SQS and reducing the number of sent requests.

### Feature description
A solution that allows for simple request batching using client-side buffering. Where calls made from the client are first buffered and then sent as a batch request to Amazon SQS.

### Describe alternatives you've considered
I'm currently using go-cloud SDK, under the hood it's batching every call.
https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L107

### Additional context
AWS Docs: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-client-side-buffering-request-batching.html

**Comment by prashanthpai** [comment]
I've implemented a wrapper around aws-go-sdk-v2 which achieves this. Check it out: https://github.com/prashanthpai/asyncsqs

**Comment by wedneyyuri** [comment]
Good to see @prashanthpai ! I was wondering how to achieve at least once delivery from a publisher point of view.

For example, let's assume we have a http server route publishing messages. How to ensure every message was placed successfully?

**Comment by prashanthpai** [comment]
@wedneyyuri 

> For example, let's assume we have a http server route publishing messages. How to ensure every message was placed successfully?

You could configure SQS client to have the desirable number of implicit retries. Specifically about the async library linked above, you can register callback functions for send message in batch operation. The callback function can track which ones passed or failed and handle failures as per your business logic.

Please beware that regardless of which implementation you use, messages sent via any async buffered client are susceptible to be lost during ungraceful termination of your application.

**Comment by jmklix** [comment]
P78573348

**Comment by jmklix** [comment]
Closing this as it is now on the service teams roadmap. I don't have a specific timeline for when this will get added.
