### ISSUE TITLE
The parameter DBInstanceIdentifier is not a valid identifier because it is longer than 63 characters.

### ISSUE THREAD

**Issue by chidifrank** [aws/aws-sdk#673]
### Describe the bug

Hi,

We are not able to modify our db-cluster because the cluster identifier that was generated (because it is an optional field and we did not specify it) says it is longer than 63 characters while it is 57 characters.

### Expected Behavior

input: `
aws rds modify-db-cluster --db-cluster-identifier <our_57_character_cluster_identifier> --engine-mode provisioned --allow-engine-mode-change --db-cluster-instance-class db.r5.xlarge`

output: `
--> json output with corresponding values
`

### Current Behavior

input: `
aws rds modify-db-cluster --db-cluster-identifier <our_57_character_cluster_identifier> --engine-mode provisioned --allow-engine-mode-change --db-cluster-instance-class db.r5.xlarge`

output: `
--> An error occurred (InvalidParameterValue) when calling the ModifyDBCluster operation: The parameter DBInstanceIdentifier is not a valid identifier because it is longer than 63 characters.
`

### Reproduction Steps

`
aws rds modify-db-cluster --db-cluster-identifier <a_57_character_cluster_identifier> --engine-mode provisioned --allow-engine-mode-change --db-cluster-instance-class db.r5.xlarge`

### Possible Solution

- Refactor aws rds modify-db-cluster, commands validator

### CLI version used

2.13.8

### Environment details (OS name and version, etc.)

Amazon Linux, Version 2

**Comment by gopal-tanwar** [comment]
Hi @RyanFitzSimmonsAK 
We also getting same error.

`**An error occurred (InvalidParameterValue) when calling the CreateBlueGreenDeployment operation: The parameter Filter: db-cluster-id is not a valid identifier because it is longer than 63 characters.**`

**Comment by RyanFitzSimmonsAK** [comment]
The service team has pushed a fix for this issue.  Please update to the most recent version of the SDK you're using, and let me know if this behavior still occurs.
