### ISSUE TITLE
 create-instance-export-task expired and automatically canceled

### ISSUE THREAD

**Issue by prnr** [aws/aws-sdk#674]
### Describe the bug

I used the ec2 create-instance-export-task command to export one instance with a single 8GB volume, and waited for over 100 hours. And today, I checked the progress with the describe-export-task command and found the following results.
The other instance I have has been exported normally, and only one is not being exported.

This instance is an instance where CentOS volume is connected to Amazon Linux 2023, so I'm wondering if CentOS is a problem. However, if that's a problem, I don't understand issuing an export command and displaying the state as active for 100 hours.
I registered this question on Discussion, but I haven't answered in more than 2 weeks, so I re-register on Bugs.

Is there any way to check why it's not progressing?

### Expected Behavior

Expect export to be completed within 3-10 hours

### Current Behavior

aws ec2 describe-export-tasks --export-task-ids export-i-095dc8b13d450a9c0
{
    "ExportTasks": [
        {
            "ExportTaskId": "export-i-095dc8b13d450a9c0",
            "ExportToS3Task": {
                "ContainerFormat": "ova",
                "DiskImageFormat": "vmdk",
                "S3Bucket": "backup-greon",
                "S3Key": "vms/export-i-095dc8b13d450a9c0.ova"
            },
            "InstanceExportDetails": {},
            "State": "cancelled",
            "StatusMessage": "Task expired and automatically canceled"
        }
    ]
}

### Reproduction Steps

aws ec2 create-instance-export-task --instance-id i-0ef25ad9e25c7e932 --target-environment vmware --export-to-s3-task file://config.json

in config.json

{
    "ContainerFormat": "ova",
    "DiskImageFormat": "VMDK",
    "S3Bucket": "backup-greon",
    "S3Prefix": "vms/"
}

### CLI version used

aws-cli/2.15.2

### Environment details (OS name and version, etc.)

 Python/3.11.6 Windows/11 22h2 23606.1000 exe/AMD64 prompt/off

**Comment by prnr** [comment]
How can I check the progress related to this? Due to the maintenance cost issue, we have to delete the instance as soon as possible (originally, January 10 was the deadline for deletion).

**Comment by prnr** [comment]
> Thanks for following up. As far as I can tell, the debug logs don't indicate any issue with the CLI, leading me to believe this is a service team issue. I've reached out to the EC2 team about what could be the issue here. In the meantime, as this is a service team issue, I'm going to transfer this to our cross-SDK repository (https://github.com/aws/aws-sdk/). I'll leave any updates in this issue. Thanks!
> 
> Ticket # for internal use : P112677642

How can I check the progress related to this? Due to the maintenance cost issue, we have to delete the instance as soon as possible (originally, January 10 was the deadline for deletion). And can I ask the customer center with this ticket using the basic plan? If possible, how can I proceed with the inquiry?

**Comment by RyanFitzSimmonsAK** [comment]
The export task failed because the volume was originally created from an AMI which contains a Marketplace Code.  From the [EC2 documentation](https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html),

> You can't export an instance if it contains third-party software provided by AWS. For example, VM Export cannot export Windows or SQL Server instances, or any instance created from an image in the AWS Marketplace.

You can use the DescribeImages to determine if an image is from the AWS Marketplace.  Please let me know if you have any other questions.
