### ISSUE TITLE
aws resourcegroupstaggingapi get-resources returns deleted resources

### ISSUE THREAD

**Issue by j-land** [aws/aws-sdk#676]
### Describe the bug

I see discrepancies between the reported resources from the `resourcegroupstaggingapi get-resources` API and resources that actually exist either from individual service APIs or the console. The following resources seem to be impacted (though not sure if this is an exhaustive list):

- EC2 fleet
- EC2 volumes
- Route53 hosted zones
- Elastic Load Balancing listeners
- Elastic Load Balancing listener rules

I see these discrepancies when invoking the `resourcegroupstaggingapi` from both the AWS CLI and the boto3 library. Through manual inspection, I have found that the  `resourcegroupstaggingapi` returns information for deleted resources.

I have found a number of related issues/forums/posts that describe the same issue but have largely been ignored or dismissed:
- https://github.com/aws/aws-cli/issues/4173
- https://repost.aws/questions/QUcinjyU36SBSmcYA8eYJf0Q/only-get-existing-resources-with-resourcegrouptaggingapi
- https://stackoverflow.com/questions/63876995/aws-resourcegroupstaggingapi-retrieving-resource-that-doesnt-exist
- https://stackoverflow.com/questions/71035336/only-get-existing-resources-with-resourcegrouptaggingapi

### Expected Behavior

The  `resourcegroupstaggingapi` returns information only for active resources OR provides an argument to filter deleted resources.

### Current Behavior

The  `resourcegroupstaggingapi` returns information for active and deleted resources.

### Reproduction Steps

**Route53**
```
aws resourcegroupstaggingapi get-resources --resource-type-filters route53 | jq '.ResourceTagMappingList | map(.ResourceARN) | length'
70

aws route53 get-hosted-zone-count | jq '.HostedZoneCount'
21
```

**EC2 Fleets**
```
aws resourcegroupstaggingapi get-resources --resource-type-filters ec2:fleet | jq '.ResourceTagMappingList | map(.ResourceARN) | length'
4884

aws ec2 describe-fleets | jq '.Fleets | map(.FleetId) | length'
0
```

**EC2 Volumes**
```
aws resourcegroupstaggingapi get-resources --resource-type-filters ec2:volume | jq '.ResourceTagMappingList | map(.ResourceARN) | length'
15

aws ec2 describe-volumes | jq '.Volumes | length'
9
```

### CLI version used

aws-cli/2.11.23

### Environment details (OS name and version, etc.)

Darwin/22.6.0

**Comment by RyanFitzSimmonsAK** [comment]
For EC2 resources, tags on deleted resources can take several hours before being properly deleted and removed from GetResources responses.  The team is aware of this behavior, and is working on a solution, but I can't promise any specific timeline.  In the meantime, if you need stale tags removed at any point, you can reach out, as the service team is able to manually remove stale tags on their end.
