### ISSUE TITLE
DescribeClientVpnTargetNetworks doesn't respect AssociationIds

### ISSUE THREAD

**Issue by nijave** [aws/aws-sdk#68]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
The `AssociationIds` parameter isn't respected. A work-around is to use filters. This appears to be an API bug but posting here for continuity since it's existed unfixed for >9 months

**Version of AWS SDK for Go?**
N/A appears to be an API bug

**Version of Go (`go version`)?**
N/A

**To Reproduce (observed behavior)**
https://github.com/hashicorp/terraform-provider-aws/pull/14380/files#diff-2f8dd56b8c463c6b45b0d84b914f0a200ae8cadf1b1a6c6f1b8a48b77457cc4eL123
It doesn't filter

**Expected behavior**
It works the same as using the `Filter` with `association-id`

**Additional context**

**Comment by NGL321** [comment]
Hey @nijave,

Thank you for reporting this! We are sorry for the long delays on response. It seems this is an issue that has impact across the SDKs, so we are going to track it in this repo. You can continue to follow this issue for updates on fix.

In the interim, if you are willing to share your personal workaround, the information could be very useful for other users in your position and we would appreciate anything you are willing to share!

😸 😷

**Comment by KaibaLopez** [comment]
P51609782 created.

**Comment by tim-finnigan** [comment]
Closing per [comment](https://github.com/aws/aws-sdk/issues/68#issuecomment-906718551) above.
