### ISSUE TITLE
s3.ErrCodeNotModified does not exist - but should

### ISSUE THREAD

**Issue by rayjlinden** [aws/aws-sdk#69]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
This bug was reported before but closed with I think the developer not understanding the issue:
https://github.com/aws/aws-sdk-go/issues/1507

The s3 service may return a code of NotModified (http status code 304).
This is not mentioned in the docs:
https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

What is missing is a definition for the code.
s3.ErrCodeNotModified = "NotModified"

**Version of AWS SDK for Go?**
1.35.29

**Version of Go (`go version`)?**
1.14.9

**To Reproduce (observed behavior)**
See referenced bug.

**Expected behavior**
I expect the constant "s3.ErrCodeNotModified" to exist and be set to "NotModifed"

**Additional context**

**Comment by KaibaLopez** [comment]
ticket has been opened for the service team, will update with more info when I have it: P48407576

**Comment by peterwoodworth** [comment]
The S3 API team returns enough data here for the SDKs to be able to handle this properly. If this issue still persists; raise the issue in the SDK repo you're using so that the team can implement a solution.
