### ISSUE TITLE
Bedrock InvokeModel lacking documentation and clarity around StopSequences parameter

### ISSUE THREAD

**Issue by RyanFitzSimmonsAK** [aws/aws-sdk#692]
Original issue : https://github.com/boto/boto3/issues/3993

Ticket # for internal reference : P116361553

**Comment by RyanFitzSimmonsAK** [comment]
The service team added some documentation to the User Guide that clarifies some ambiguity.



> Stop sequences (stopSequences) – Specify a character sequence to indicate where the model should stop. Currently, you can only specify one of the following options:
> 
>     |
> 
>     User:

**Comment by adinathtw** [comment]
Are there any further updates / work around on this issue?

**Comment by manwithaplandy** [comment]
Nothing that I've seen. Just a clarification in the docs.

**Comment by RyanFitzSimmonsAK** [comment]
The Bedrock documentation around `stopSequences` was updated again.  If there are still issues surrounding this, please feel free to open a new issue.

**Comment by manwithaplandy** [comment]
The real issue here was never that the documentation was wrong, it was that the user is unable to specify any stop sequences because the regex check was too restrictive. Was that issue resolved?
