### ISSUE TITLE
AWS Cognito UserMFASettingList field of AdminGetUserResponse is empty

### ISSUE THREAD

**Issue by lgolubenkobit** [aws/aws-sdk#693]
### Describe the bug

I have the same problem described here, not only with MFASettingList, also with mfaOptions and preferredMfaSetting
[StackOverflow](https://stackoverflow.com/questions/77289014/usermfasettinglist-field-of-admingetuserresponse-is-empty)

After login on hosted UI, i've configured TOTP App as 2FA, but when invoke, by sdk, adminGetUser or getUser, 
attributes are null or empty

### Expected Behavior

Return preferred MFA and available options

### Current Behavior

Attributes are null or empty
	MFASettingList: []
	mfaOptions: []
	preferredMfaSetting: null

### Reproduction Steps

Login on hosted UI and configure 2FA,
Invoke adminUserInfo vía SDK.

### AWS Java SDK version used

2.21.12

### JDK version used

Java 8

### Operating System and version

KDE Plasma

**Comment by debora-ito** [comment]
@lgolubenkobit The Cognito team confirmed the behavior is expected. 

As for my ask to clarify in the documentation, they said they don't see the confusion. But I'll push back on that. 

I'll go ahead and close this, as there's nothing else pending from the SDK team. Feel free to reach out if you have any other question.
