### ISSUE TITLE
Rust: Example of puting lifecycle  / creating aws_sdk_s3::types::LifecycleRuleFilter?

### ISSUE THREAD

**Issue by DimanNe** [aws/aws-sdk#699]
It seems `aws_sdk_s3::types::LifecycleRuleFilter` does not have `::builder()` method. **If this is true, how can I create it?**

Alternatively, can anyone give an example of adding a lifecycle to a bucket?

```
      let abort_incomplete_rule = aws_sdk_s3::types::LifecycleRule::builder()
         .status(aws_sdk_s3::types::ExpirationStatus::Enabled)
         .filter(????)
```

[Here are docs](https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/types/enum.LifecycleRuleFilter.html).

**Comment by jmklix** [comment]
Thanks for opening this issue. This repo is for issues that affect multiple sdk's. I've opened a copy of this issue in the correct repo here: https://github.com/awslabs/aws-sdk-rust/discussions/1084
