### ISSUE TITLE
Pinpoint email friendly sender name support

### ISSUE THREAD

**Issue by mbelang** [aws/aws-sdk#70]
**Is your feature request related to a problem? Please describe.**
I want to control Pinpoint email channel friendly sender name via [terraform](https://github.com/hashicorp/terraform-provider-aws/issues/18050) but the SDK doesns't support the parameter in the API.

**Describe the solution you'd like**
Add the support of email friendly sender name in the PinPoint API.

**Describe alternatives you've considered**
Configure the parameter manually in the AWS console but it is agains the principle of infrastructure as code.

**Comment by NGL321** [comment]
Hi @mbelang,

Thank you for submitting this! This feature-request will require some design consideration between the SDKs so we will track its progress here.

😸 😷

**Comment by mbelang** [comment]
Hello,

I do not see my comment but it works in fact if you set the email that way `Freindly Sender Name <my@email.com>`

It is a lack of documentation rather than a missing feature.

**Comment by NGL321** [comment]
Huh, not sure what happened to the comment, but thank you for the clarification. I have updated the issue to reflect this.

**Comment by mbelang** [comment]
There is my comment :) https://github.com/hashicorp/terraform-provider-aws/issues/18050#issuecomment-800530666

So I honestly think there is nothing to do except documentation I guess.

**Comment by tim-finnigan** [comment]
It looks like Terraform added this based on [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/18050#issuecomment-881078099) and in the Pinpoint User Guide [here](https://docs.aws.amazon.com/pinpoint/latest/userguide/settings-email.html#settings-email-verify-identity) it notes how you can "You can optionally enter a Friendly sender name identifying this address." Closing this but please let us know if you had any other questions or feedback.
