### ISSUE TITLE
AWS CLI Cost Manager doesn't accept RESOURCE_ID in filters

### ISSUE THREAD

**Issue by hakimoa** [aws/aws-sdk#700]
### The issue

when called with RESOURCE_ID filter `aws ce get-cost-and-usage` responds 

` An error occurred (ValidationException) when calling the GetCostAndUsage operation: Dimension RESOURCE_ID is not allowed. ` 

### Expected behaviour

- The RESOURCE_ID is accepted as a dimension in filters as described in this documentation page [here](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_DimensionValues.html)

- Returns cost information of the filtered resource 

### Command line to reproduce 

```
 aws ce get-cost-and-usage \
  --time-period Start="2023-12-01",End="2024-02-01" \
  --granularity DAILY \
  --metrics "BlendedCost" \
  --filter '{"And":[{"Dimensions":{"Key":"SERVICE","Values":["DynamoDB"]}},{"Dimensions":{"Key":"RESOURCE_ID","Values":["my-dynamodb-table-name"]}}]}' \
  --output json

```

### AWS CLI version 
`aws-cli/2.15.19 Python/3.11.6 Darwin/23.2.0 exe/x86_64 prompt/off`

**Comment by RyanFitzSimmonsAK** [comment]
It looks like resource-level data is an opt-in feature.  You can enable it in the Billing and Cost Management preferences page.  [This documentation](https://docs.aws.amazon.com/cost-management/latest/userguide/ce-resource-daily.html) might help.  Could you verify if you've opted in?
