### ISSUE TITLE
Kinesis Video Streaming: Parsing GetMedia Output Payload

### ISSUE THREAD

**Issue by Last650Wizard** [aws/aws-sdk#71]
Hi,

I have configured the GStreamer plugin as a producer sending streaming from an IP camera to Kinesis.

Now, I want to consume the video and get each frame as image to do some real time video analytics, to do that I used [GetMedia](https://docs.aws.amazon.com/sdk-for-go/api/service/kinesisvideomedia/#KinesisVideoMedia.GetMedia) which returned [GetMediaOutput](https://docs.aws.amazon.com/sdk-for-go/api/service/kinesisvideomedia/#GetMediaOutput) object that contained `Payload` as a [ReadCloser](https://golang.org/pkg/io/#ReadCloser)

For example when I ran the following code:

```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/kinesisvideo"
	"github.com/aws/aws-sdk-go/service/kinesisvideomedia"
)

func main() {
	mySession := session.Must(session.NewSession())
	svc := kinesisvideo.New(mySession, aws.NewConfig().WithRegion("us-west-2"))
	params := kinesisvideo.GetDataEndpointInput{
		APIName:    aws.String("GET_MEDIA"),
		StreamName: aws.String("TestStream"),
	}
	dataEndpointOutput, err := svc.GetDataEndpoint(&params)
	if err != nil {
		panic(err)
	}
	svmc := kinesisvideomedia.New(mySession, aws.NewConfig().
		WithRegion("us-west-2").
		WithEndpoint(*dataEndpointOutput.DataEndpoint))
	input := kinesisvideomedia.GetMediaInput{
		StartSelector: &kinesisvideomedia.StartSelector{
			StartSelectorType: aws.String("EARLIEST"),
		},
		StreamName: aws.String("TestStream"),
	}
	getMediaOutput, err := svmc.GetMedia(&input)
	if err != nil {
		panic(err)
	}
	fmt.Println(getMediaOutput.GoString())
}

```
The output is:
```
{
  ContentType: "video/webm",
  Payload: buffer(0xc000548300)
}
```
When I tried to Read the payload, it read only a small slice of bytes (like 40 bytes):
```
b := make([]byte, 10000)
n, err := getMediaOutput.Payload.Read(b)
if err != nil {
	panic(err)
}
fmt.Println(n)
```
output:
```
40
```
but when I tried to read more than one time, it continued to read, so I make for loop and reading until there's no data:
```
for {
	b := make([]byte, 10000)
	n, err := getMediaOutput.Payload.Read(b)
	fmt.Println(n)
	if err == io.EOF {
		fmt.Println(err)
		break
	}
	if err != nil {
		panic(err)
	}
}
```
output:
```
40
12
6
31
46
26
13
14
19
17
.
.
.
13
1316
1335
1187
1423
1412
13
1385
1555
1456
173
.
.
.
```
It continued to read while the producer is running and streaming the video.

According to [aws docs](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_GetMedia.html#API_dataplane_GetMedia_ResponseSyntax) the `GetMedia` returns chunks in `mkv` format but there is no more information, and when I tried to write chunks into a file with `.mkv` or `.webm` extension, the operating system couldn't recognize it.

My question is how to deal with those chunks in order to get the frames/fragments to do a real time analytics?

Note: I know there's a parser library in [Java](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/parser-library.html) but I have to do things in golang.

**Comment by vudh1** [comment]
V694665981

**Comment by RanVaknin** [comment]
Hi @Last650Wizard ,

Sorry for the very long response time. The service team responded with "Customer is asking to extract frames from stream to support ML. Please inform them of KVS Images feature, which should be a better solution: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/images.html"

I hope this helps.
Thanks!
Ran~
