### ISSUE TITLE
An option to accept email attachments as a CDN in the AWS's Simple Email Service

### ISSUE THREAD

**Issue by CW-AnandRamesh** [aws/aws-sdk#711]
### Describe the feature

As of now, files have to be received within services as a stream or a byte array before passing the same to AWS SES for sending emails. A better approach would be to receive this file as a CDN Url directly in SES.

### Use Case

Problem with current approach is to maintain scalability of our services with increasing requests and their corresponding memory profile management. By utilizing a CDN to share the attachment, memory resources of the service responsible for sharing this to AWS SES will be improved significantly.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleEmail 3.7.300.54

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
P122374479

**Comment by ashishdhingra** [comment]
@CW-AnandRamesh Based on response from service team, SES does not currently support specifying attachments via URL. They will consider this request for a future product release. As of now we cannot provide ETA for the same. The feature, once supported, should be propagated to all the AWS SDK(s) via model and feature update.

Thanks,
Ashish
