### ISSUE TITLE
Usage of Tier in `S3.ClientRestoreObject`

### ISSUE THREAD

**Issue by wunderbarb** [aws/aws-sdk#713]
### Describe the issue

In the structure `s3.RestoreObjectInput.RequestRestore`, there are two times the `types.Tier`.  The first one within `RestoreRequest.GlacierJobParameters` and the one as `RestoreRequest.Tier`.  
1- What is the difference?  What would happen if they differ?
2- `GlacierJobParameteters` is not valid when using `OutputLocation`.  Thus, I guess that we should use the second one to define the retrieval speed.  Unfortunately when using something like 
```roIN := &awsS3.RestoreObjectInput{
		Bucket: aws.String(b),
		Key:    aws.String(p),
		RestoreRequest: &types.RestoreRequest{
				Tier: types.TierExpedited,
	
		},
	}
	if oo.restoreLocation != "" {
		br, kr := parse1(oo.restoreLocation)
		roIN.RestoreRequest.OutputLocation = &types.OutputLocation{
			S3: &types.S3Location{
				BucketName: br,
				Prefix:     kr,
			},
		}
	} else {
		roIN.RestoreRequest.Days = aws.Int32(days)
	}
``` creates an XML misformation whereas ```
roIN := &awsS3.RestoreObjectInput{
		Bucket: aws.String(b),
		Key:    aws.String(p),
		RestoreRequest: &types.RestoreRequest{
			GlacierJobParameters: &types.GlacierJobParameters{
				Tier: types.TierExpedited,
			},
		},
	}
	if oo.restoreLocation != "" {
		br, kr := parse1(oo.restoreLocation)
		roIN.RestoreRequest.OutputLocation = &types.OutputLocation{
			S3: &types.S3Location{
				BucketName: br,
				Prefix:     kr,
			},
		}
	} else {
		roIN.RestoreRequest.Days = aws.Int32(days)
	}``` works.  
	THus, how can I define the "speed": bulk, standard or expedited when using `OutputLocation`?

### Links

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3@v1.53.0/types#RestoreRequest

### AWS Go SDK V2 Module Versions Used

```
	github.com/aws/aws-sdk-go-v2 v1.26.0
	github.com/aws/aws-sdk-go-v2/config v1.26.6
	github.com/aws/aws-sdk-go-v2/credentials v1.16.16
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.12.15
	github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.15.13
	github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.31.0
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.26.9
	github.com/aws/aws-sdk-go-v2/service/eventbridge v1.28.0
	github.com/aws/aws-sdk-go-v2/service/lambda v1.49.7
	github.com/aws/aws-sdk-go-v2/service/s3 v1.53.0
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.26.2
	github.com/aws/aws-sdk-go-v2/service/sesv2 v1.24.6
	github.com/aws/aws-sdk-go-v2/service/sns v1.26.7
	github.com/aws/aws-sdk-go-v2/service/sqs v1.31.3
	github.com/aws/aws-sdk-go-v2/service/ssm v1.49.1
	github.com/aws/aws-sdk-go-v2/service/textract v1.28.6
```

**Comment by RanVaknin** [comment]
Hi @wunderbarb 

I heard back from the S3 service team. The following  inputs are only for glacier select jobs:
- OutputLocation
- SelectParameters
- Tier
- Type

Thanks,
Ran~
