### ISSUE TITLE
[AWS Batch] Ability to specify a working directory for a container in ECS TaskContainerProperties

### ISSUE THREAD

**Issue by brian-mulier-p** [aws/aws-sdk#716]
### Describe the feature

Ability to specify for a container the working directory to use

### Use Case

I have a usecase where I need to bootstrap multiple containers where one will eventually fetch from S3 to some job-wide volume and the main container will need to have access to these files.

However both containers are not necessarily using the same image so I'm unable to know where to mount files if I can't specify an arbitrary working directory.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.25.14

### JDK version used

17

### Operating System and version

Ubuntu

**Comment by debora-ito** [comment]
@brian-mulier-p the Batch team replied and said it's a feature they are interested in implementing. They've added a feature task to their backlog but don't have a timeline to share for the fix.

Closing this, as there's nothing pending on the SDK team.

**Comment by brian-mulier-p** [comment]
@debora-ito is there a link, an issue, something to track this ?

**Comment by debora-ito** [comment]
Unfortunately no, there's no mechanisms to track Batch service-side feature requests that are open to the public. I recommend keeping an eye on the [changelog](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md) but it's not super practical.
