### ISSUE TITLE
Errors/failure clearing workspaces CustomSecurityGroupID and DefaultOu

### ISSUE THREAD

**Issue by ablackrw** [aws/aws-sdk#72]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
When invoking workspaces.ModifyWorkspaceCreationProperties, it appears impossible to unset either the CustomSecurityGroupId or the DefaultOu property. This stands in contrast to the web console, where both properties can be cleared.

**Version of AWS SDK for Go?**
> 1.33.10

**Version of Go (`go version`)?**
`go version go1.14.2 darwin/amd64`

**To Reproduce (observed behavior)**
The following is a test program that aims to demonstrate the problem. Attempts are made to unset the CustomSecurityGroupId and DefaultOu properties via 3 different ways. The first is by passing a nil value for the property, the second is by passing an empty string, and the third is by omitting the properties. To invoke the test program, set the AWS_PROFILE and AWS_REGION environment variables as appropriate, and pass the ID of a workspaces directory in the specified profile and region that has both properties set.
```go
package main

import (
	"flag"
	"fmt"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/workspaces"
	"os"
)

func main() {
	var directoryid string
	flag.StringVar(&directoryid, "d", "", "Directory ID.")
	flag.Parse()

	sess := session.Must(session.NewSession())
	svc := workspaces.New(sess)
	query := &workspaces.DescribeWorkspaceDirectoriesInput{
		DirectoryIds: []*string{aws.String(directoryid)},
	}

	fmt.Printf("AWS SDK version: %q\n", aws.SDKVersion)
	test(svc, "Clearing via nil data", &workspaces.ModifyWorkspaceCreationPropertiesInput{
		ResourceId: aws.String(directoryid),
		WorkspaceCreationProperties: &workspaces.WorkspaceCreationProperties{
			CustomSecurityGroupId: nil,
			DefaultOu:             nil,
		},
	}, query)
	test(svc, "Clearing CustomSecurityGroupId via empty string", &workspaces.ModifyWorkspaceCreationPropertiesInput{
		ResourceId: aws.String(directoryid),
		WorkspaceCreationProperties: &workspaces.WorkspaceCreationProperties{
			CustomSecurityGroupId: aws.String(""),
		},
	}, query)
	test(svc, "Clearing DefaultOu via empty string", &workspaces.ModifyWorkspaceCreationPropertiesInput{
		ResourceId: aws.String(directoryid),
		WorkspaceCreationProperties: &workspaces.WorkspaceCreationProperties{
			DefaultOu: aws.String(""),
		},
	}, query)
	test(svc, "Clearing via empty struct", &workspaces.ModifyWorkspaceCreationPropertiesInput{
		ResourceId:                  aws.String(directoryid),
		WorkspaceCreationProperties: &workspaces.WorkspaceCreationProperties{},
	}, query)
}

func test(svc *workspaces.WorkSpaces, step string, input *workspaces.ModifyWorkspaceCreationPropertiesInput, query *workspaces.DescribeWorkspaceDirectoriesInput) {
	fmt.Println(step)
	_, err := svc.ModifyWorkspaceCreationProperties(input)
	if err != nil {
		fmt.Println(err)
	}

	resp, err := svc.DescribeWorkspaceDirectories(query)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	p := resp.Directories[0].WorkspaceCreationProperties
	if nil != p {
		if nil != p.CustomSecurityGroupId {
			fmt.Println("SecurityGroupId not cleared")
		}
		if nil != p.DefaultOu {
			fmt.Println("DefaultOu not cleared")
		}
	} else {
		fmt.Println("Workspace Creation properties cleared.")
	}
}
```
When invoked, this products the following output:

> AWS SDK version: "1.33.10"
> Clearing via nil data
> SecurityGroupId not cleared
> DefaultOu not cleared
> Clearing CustomSecurityGroupId via empty string
> InvalidParameter: 1 validation error(s) found.
> - minimum field size of 11, ModifyWorkspaceCreationPropertiesInput.WorkspaceCreationProperties.CustomSecurityGroupId.
> 
> SecurityGroupId not cleared
> DefaultOu not cleared
> Clearing DefaultOu via empty string
> InvalidParameterValuesException: An invalid or out-of-range value was supplied for the input parameter.
> SecurityGroupId not cleared
> DefaultOu not cleared
> Clearing via empty struct
> SecurityGroupId not cleared
> DefaultOu not cleared

**Expected behavior**
It is expected that one of the mechanisms identified above (nil value, empty string, missing property), when passed to ModifyWorkspaceCreationProperties would clear the property in question on the directory.

**Additional context**
This was discovered while attempting to implement https://github.com/terraform-providers/terraform-provider-aws/issues/12737 and reproduced with the AWS CLI client before a native (Go SDK-native) test case was drafted.

**Comment by jmklix** [comment]
P51613002

**Comment by jmklix** [comment]
This should now be fixed. Please let me know if you are still running into this error
