### ISSUE TITLE
Add S3 Inventory Configuration Results API

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#720]
Original issue: https://github.com/boto/boto3/issues/4082

Related [gist](https://gist.github.com/corey-cole/d537b08e3a426f7884f305f845737514) shared.

**Comment by tim-finnigan** [comment]
V1354825925

**Comment by tim-finnigan** [comment]
The S3 service team has added this feature request to their backlog for tracking. We cannot provide any guarantees as to if or a when a request like this may get implemented, but feel free to check back in the future for updates or to share any additional details regarding your use case. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan.

**Comment by iainelder** [comment]
From the console.

> **Access denied**
>
> Inventory export for 2024-05-10 failed because S3 doesn’t have access to the destination bucket or KMS key. Ask the owner of the destination bucket or KMS key to grant the necessary access and then try again.

@tim-finnigan , thanks for filing the feature request. I'll follow up with support.
