### ISSUE TITLE
DMS resource identifier (friendly name)

### ISSUE THREAD

**Issue by RobbertDM** [aws/aws-sdk#723]
### Describe the issue

For some DMS resources, you can pass `--resource-identifier (string)`, so that the ARN gets a friendly name instead of a randomly generated string.
The description for each of these is:
```
A friendly name for the resource identifier at the end of the EndpointArn response parameter that is returned in the created Endpoint object. The value for this parameter can have up to 31 characters. It can contain only ASCII letters, digits, and hyphen (‘-‘). Also, it can’t end with a hyphen or contain two consecutive hyphens, and can only begin with a letter, such as Example-App-ARN1 . For example, this value might result in the EndpointArn value arn:aws:dms:eu-west-1:012345678901:rep:Example-App-ARN1 . If you don’t specify a ResourceIdentifier value, DMS generates a default identifier value for the end of EndpointArn .
```

Which seems to be written for `create-endpoint`, but that's not even correct since the ARN mentioned is `arn:aws:dms:eu-west-1:012345678901:rep:Example-App-ARN1`, which is a `ReplicationInstance`'s ARN. 
Endpoints have `endpoint` in the ARN, replication instances have `rep` and tasks have `task`.

BTW, I have spent some time trying to find where I could contribute to the docs myself, but I cannot find where the docs are generated from. I guess the docs at the URLs referenced below are not open to contributions?

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/create-replication-task.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/create-replication-instance.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/create-endpoint.html

**Comment by tim-finnigan** [comment]
I confirmed that the DMS documentation team is tracking this, no other updates for now. Feel free to check back in the future for updates.
