### ISSUE TITLE
Add OS Operation code for the RDS instances

### ISSUE THREAD

**Issue by daeho-ro** [aws/aws-sdk#724]
### Describe the feature

When you call the DescribeInstances API, there exists `UsageOperation` key and the example values are `RunInstances`, `RunInstances:0002` and so on. It can be used to mapping the exact operating system with a license model, so I want to see the similar data from DescribeDBInstances API for RDS. It could have the values for example, `CreateDBInstances:0002, CreateDBInstances:0016` and so on.

### Use Case

The Usage Operation key is used to map the resources and operating systems to get the billing I guess. Without this and API only, it is really hard to get the exact pricing sku.

### Proposed Solution

Add the UsageOperation key for the DescribeDBInstances API.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.21.5

### JDK version used

17

### Operating System and version

M3 14.3.1

**Comment by debora-ito** [comment]
@daeho-ro The RDS team acknowledged the feature request, it was added to their backlog. We don't have a timeline for the change to share right now.

Will go ahead and close this, as there's no action pending from the SDK team. Let us know if you have any other question or request.
