### ISSUE TITLE
boto3.client("s3").head_bucket does not throw NoSuchBucket as per documentation

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#726]
Original issue here: https://github.com/boto/boto3/issues/4092

ref: P127336178

**Comment by tim-finnigan** [comment]
Thanks for sharing those, here's another related issue: https://github.com/aws/aws-sdk/issues/255. We heard back from an S3 documentation writer who updated this page: https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html

This is now highlighted in a Note for better visibility:

![image](https://github.com/aws/aws-sdk/assets/87778557/58cdd31e-22e5-457f-b9b4-f6aec8a7a327)

So while the error below is documented:

![image](https://github.com/aws/aws-sdk/assets/87778557/51fa4f72-ae24-4506-b629-6e2440d19900)

It cannot be handled client-side due to the limitations described in the Note. Please use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=S3&topic_url=https://docs.aws.amazon.com/en_us/AmazonS3/latest/API/API_HeadBucket.html) to send any additional feedback directly to the S3 team regarding this.

**Comment by anentropic** [comment]
So... this will never get fixed?

The documentation change in API_HeadBucket does nothing to clarify the situation for Boto3 users who find a `NoSuchBucket` exception class on the S3 client instance that never gets raised.  To all intents and purposes it still looks like the thing you should catch for the 404 case.

Is it all so auto-generated that it's impossible to put a specific note in the Boto3 docs?
