### ISSUE TITLE
dynamodb: If the value of the hash key is nil, this will cause an infinite loop

### ISSUE THREAD

**Issue by d-tsuji** [aws/aws-sdk#73]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
Infinite loop if the value of Key in [dynamodb.GetItemInput](https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#GetItemInput) is nil.

**Version of AWS SDK for Go?**
v1.34.0

**Version of Go (`go version`)?**
go version go1.14 windows/amd64

**To Reproduce (observed behavior)**

DynamoDB uses DynamoDB local. And use [AWSCLI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html).

```
docker run -p 8000:8000 amazon/dynamodb-local
```

- directory structure

```
.
├── data_input_user.json
├── go.mod
├── go.sum
├── main.go
└── table_local_users.json
```

- table_local_users.json

```json
{
  "TableName": "local_users",
  "KeySchema": [
    {
      "AttributeName": "user_id",
      "KeyType": "HASH"
    }
  ],
  "AttributeDefinitions": [
    {
      "AttributeName": "user_id",
      "AttributeType": "S"
    }
  ],
  "ProvisionedThroughput": {
    "ReadCapacityUnits": 1,
    "WriteCapacityUnits": 1
  }
}
```

- data_input_user.json

```json
{
  "user_id": {
    "S": "0001"
  },
  "comment": {
    "S": "test comment"
  }
}
```

- main.go

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os/exec"
	"strings"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
)

func cmdExec(cmd string) {
	args := strings.Split(cmd, " ")
	if err := exec.Command(args[0], args[1:]...).Run(); err != nil {
		log.Printf("cmd failed, %v %s", err, cmd)
	}
}

func main() {
	dynamoDbRegion := "ap-northeast-1"
	dynamoDbEndpoint := "http://localhost:8000"

	sess := session.Must(session.NewSession(&aws.Config{
		Region:     aws.String(dynamoDbRegion),
		Endpoint:   aws.String(dynamoDbEndpoint),
		DisableSSL: aws.Bool(false),
	}))
	db := dynamodb.New(sess)

	cmdExec(`aws dynamodb --endpoint-url http://localhost:8000 create-table --cli-input-json file://./table_local_users.json`)
	cmdExec(`aws dynamodb put-item --endpoint-url http://localhost:8000 --table-name local_users --item file://./data_input_user.json`)
	defer cmdExec(`aws dynamodb --endpoint-url http://localhost:8000 delete-table --table local_users`)

	input := &dynamodb.GetItemInput{
		TableName: aws.String("local_users"),
		Key: map[string]*dynamodb.AttributeValue{
			// The hash key that is nil is, of course, invalid.
			"user_id": nil,
		},
	}
	res, err := db.GetItemWithContext(context.TODO(), input)
	if err != nil {
		panic(err)
	}

	var resp User
	if err := dynamodbattribute.UnmarshalMap(res.Item, &resp); err != nil {
		panic(err)
	}

	fmt.Println(resp)

}

type User struct {
	UserID  string `dynamodbav:"user_id"`
	Comment string `dynamodbav:"comment"`
}
```
**Expected behavior**
An error is returned to the caller.

**Additional context**
Nothing.

**Comment by KaibaLopez** [comment]
P51607846 created.

**Comment by RanVaknin** [comment]
Hi @d-tsuji 

After speaking with the service team, they have pushed a fix for this issue.

If this issue persists please feel free to re-open.

Thank you for your patience 🙏 
Ran~
