### ISSUE TITLE
Add support for CloudWatch Logs Infrequent Access to RDS 

### ISSUE THREAD

**Issue by vchernov-avenga** [aws/aws-sdk#732]
### Describe the feature
- Make it possible to set a custom Cloudwatch log group when enabling log exports
- Or make it possible to set the CloudWatch Log class when enabling log exports

### Use Case
To reduce costs we would like to change the log class from `Standard` to `Infrequent Access`.

As of now, there is no way to set the [CloudWatch Log class](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch_Logs_Log_Classes.html) or custom [log group](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#Create-Log-Group) when you enable [CloudWatch log export for RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.MySQLDB.PublishtoCloudWatchLogs.html):
```
aws rds modify-db-instance \
    --db-instance-identifier mydbinstance \
    --cloudwatch-logs-export-configuration '{"EnableLogTypes":["audit","error","general","slowquery"]}'
```  
The Cloudwatch log group for RDS is created with the `Standard` log class by default.

- We can't change the CloudWatch log class because of RDS limitations. 
- Also, we can't create our log group for RDS because RDS doesn't support that 
 ![Screenshot 2024-01-19 at 10 49 47](https://github.com/aws/aws-cli/assets/142888669/0b105f74-f694-4491-81ac-1f680750af82).
- Also, We are not able to set a custom log group for RDS

### Proposed Solution

- Make it possible to set a custom Cloudwatch log group when enabling log exports:
```
aws rds modify-db-instance \
    --db-instance-identifier mydbinstance \
    --cloudwatch-logs-export-configuration '{"EnableLogTypes":["audit","error","general","slowquery"],"LogGroup":"MyCustomLogGroupARN"}'
```  
- Or make it possible to set the CloudWatch Log class when enabling log exports:
```
aws rds modify-db-instance \
    --db-instance-identifier mydbinstance \
    --cloudwatch-logs-export-configuration '{"EnableLogTypes":["audit","error","general","slowquery"],"LogClass":"InfrequentAccess"}'
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.15.6

### Environment details (OS name and version, etc.)

Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000

**Comment by tim-finnigan** [comment]
Upon searching internally, I found that there is an existing backlog item for the RDS team tracking this feature request. We cannot guarantee if or when a feature request like this will be implemented, but I'll record the feedback you provided here, and you can track the [CHANGELOGs](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) and [blogs](https://aws.amazon.com/blogs/database/) for updates going forward. Thanks again.
