### ISSUE TITLE
Waiter for EMR on EKS job completion

### ISSUE THREAD

**Issue by RyanFitzSimmonsAK** [aws/aws-sdk#734]
Original issue : https://github.com/boto/boto3/issues/4063

Ticket # for internal reference : P128479461

**Comment by paul-civitas** [comment]
Thanks Ryan for filing this and the internal ticket as well!

**Comment by RyanFitzSimmonsAK** [comment]
The service team acknowledged the ticket and asked me to cut an internal feature request, which I've done.  Thank you again for this issue.
