### ISSUE TITLE
Have a command to generate a Redis Auth token just like RDS

### ISSUE THREAD

**Issue by romelBen** [aws/aws-sdk#737]
### Describe the feature

`aws-cli` does not support generating a Redis AUTH token like what RDS does with command `aws generate-db-auth-token`.

### Use Case

Currently we have to create a token through code which is used for applications. This is understandable and is notated here in this [AWS blog post](https://aws.amazon.com/blogs/database/simplify-managing-access-to-amazon-elasticache-for-redis-clusters-with-iam/); however, there is no documentation for developers to access the Redis clusters using `aws-cli` only RDS.

### Proposed Solution

Add another command with name `generate-redis-auth-token` for `aws-cli`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.13.36

### Environment details (OS name and version, etc.)

MacOS M2 Macbook

**Comment by tim-finnigan** [comment]
Thanks for catching that, you're right - this does appear to be a duplicate. Closing in favor of https://github.com/aws/aws-sdk/issues/580 to continue tracking there.
