### ISSUE TITLE
MIGRATION ISSUE: No programatic access to region descriptions used in pricing API

### ISSUE THREAD

**Issue by rifelpet** [aws/aws-sdk#739]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for similar migration issues.

### Go Version Used

Go 1.22

### Describe the Migration Issue

The [pricing.GetProducts API Action](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_pricing_GetProducts.html) supports filtering on arbitrary product metadata. The [example output](https://docs.aws.amazon.com/cli/latest/reference/pricing/get-products.html#examples) in the AWS CLI docs shows a response with fields:

```
"locationType":"AWS Region","location":"Asia Pacific (Singapore)"
```

Note that the `location` value is not the region name `ap-southeast-1` but a region description `Asia Pacific (Singapore)` that correspond to the values in [this](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html#Concepts.RegionsAndAvailabilityZones.Availability) table in the AWS docs.

In the v1 SDK this field was available through exported methods:

https://github.com/aws/aws-sdk-go/blob/417f8a94adeed59918cfef686dcb3e438b77735b/aws/endpoints/defaults.go#L179-L181

In the v2 SDK there is no such way to map a region name to a region description, including with `ec2.DescribeRegions`. 

### Code Comparison

This repo in the AWS github org demonstrates the SDK v1 usage with `pricing.GetProductsInput{}`:

https://github.com/aws/amazon-ec2-instance-selector/blob/14d4dfcbaadfe9a1c389c823df8eb7b142f2c997/pkg/ec2pricing/odpricing.go#L275-L297

There is no such solution for SDK v2.

### Observed Differences/Errors

I would expect the SDK v2 to offer a mapping between region names and these region descriptions like `Asia Pacific (Singapore)` so I can filter pricing products by location. Each region's pricing API returns results for all regions, so initializing the pricing API client with a specific region is insufficient.

### Additional Context

I'm aware of the desire to [treat region identifiers as opaque strings](https://github.com/aws/aws-sdk-go-v2/issues/2584#issuecomment-2025920433), however this makes the pricing.GetProducts API very difficult to filter by region.

As mentioned in https://github.com/aws/amazon-ec2-instance-selector/pull/158, this prevents the project from fully migrating off of the v1 SDK.

**Comment by RanVaknin** [comment]
Hi @rifelpet ,

I understand where you are coming from, and sympathetic to the need. I have created an internal feature request with the pricing service team `V1378823017`. I don't have visibility to when / if this would be implemented, but I will check with them periodically at least to make sure this has made it to their queue. 

You can safely mix imports between v2 and v1, so if the only implementation detail holding you back from upgrading to v2 is this, you can simply import alias the package from v1 that has the region info until this is implemented.

If you have access to AWS support through the AWS developer console my advice would be to open a support ticket yourself and reference the ticket ID I shared above, that might help drive this feature forward. 

All the best,
Ran~

**Comment by amberkushwaha** [comment]
location name is also changed in the most changed regime for the particular paste drop or click to add files inot it for the section values in it.

**Comment by RanVaknin** [comment]
We were not able to get an acknowledgement from the service about this feature. I have created an additional ticket in a different FR pipeline internally. Please refer to the ec2 blog and check for new announcement to see if this was implemented in the future. Since it's not actionable by the SDK team Im going to go ahead an close this.

Thanks,
Ran~
