### ISSUE TITLE
MIGRATION ISSUE: DAX not supported

### ISSUE THREAD

**Issue by miparnisari** [aws/aws-sdk#743]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for similar migration issues.

### Go Version Used

Go 1.22

### Describe the Migration Issue

My team can't upgrade to v2 unless the DAX SDK (https://github.com/aws/aws-dax-go) upgrades to v2 too. 

However, that repository looks abandoned:
- https://github.com/aws/aws-dax-go/issues/2
- https://github.com/aws/aws-dax-go/issues/54
- https://github.com/aws/aws-dax-go/issues/52

and PRs don't get attention: https://github.com/aws/aws-dax-go/pull/43

See also
- https://github.com/aws/aws-sdk-go-v2/issues/2539
- https://github.com/aws/aws-sdk-go-v2/issues/1955
- https://github.com/aws/aws-sdk-go-v2/issues/1763

I understand that the maintainers of `aws-sdk-go-v2` (this repo) don't want to own the burden of supporting DAX. However, this looks like an organizational problem; please don't put the burden on customers.

**Why does this SDK not support DAX? Why is DAX a second-class citizen? It's a service offered by AWS, is it not? And this is the AWS SDK, is it not? Then it should support it.** 

### Observed Differences/Errors

n/a

**Comment by RanVaknin** [comment]
Hi there,

I have reached out to the DAX team, they have confirmed that they do have plans for supporting newer SDK versions, but I'm not able to share an ETA.

If you have any additional questions / concerns please reach out to the DAX team directly either by opening new issues on their [github repo](https://github.com/aws/aws-dax-go), or by creating an internal support ticket via the AWS developer console.

Thanks again,
Ran~
