### ISSUE TITLE
Unable to save athena query results in parquet using unload statement

### ISSUE THREAD

**Issue by sunnydahit** [aws/aws-sdk#745]
I want to store the athena query results in parquet file and for which i've used the unload command but unfortunately im unsuccessful in doing so as the unload statement get executed but in the target location i get an extensionless file. Same thing happens when i use the CTAS as well. Can you please tell me the potential cause of it? I dont have nay encryption enabled on my athena workspace. 
![extensionless_file](https://github.com/aws/aws-sdk/assets/48004274/c1277ff9-6784-4a34-8db8-966fe24e206c)

**Comment by sunnydahit** [comment]
This is the reference issue https://github.com/aws/aws-sdk/issues/185 , i came across while looking for solution i did not get a confirmation if UNLOAD method worked.

**Comment by tim-finnigan** [comment]
As mentioned in https://github.com/aws/aws-sdk/issues/185, the Athena team said:
>...since their mechanism for exporting to a chosen format is via the UNLOAD operator, they didn't have plans to expose a format option directly in the StartQueryExecution API. Using UNLOAD via the API should still work for customers.

If you are having issues with the current functionality, please provide the steps to reproduce as well as debug logs.
