### ISSUE TITLE
With MultiValueAnswer: aws.Bool(false), SetIdentifier is required to call ChangeResourceRecordSet

### ISSUE THREAD

**Issue by vroad** [aws/aws-sdk#75]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
I expect the SDK to treat it as the same as setting null if I set MultiValueAnswer to aws.Bool(false), but actually the SDK acts as if I set aws.Bool(true) to the value. I get following error without any SetIdentifier:

```
InvalidInput: Invalid request: Missing field 'SetIdentifier' in Change with [Action=UPSERT, Name=foo.example.com, Type=TXT, SetIdentifier=null]
	status code: 400, request id: [REQUEST-ID]: requestError
```

**Version of AWS SDK for Go?**
Example: v1.34.32
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go/aws"`

**Version of Go (`go version`)?**
1.15.2

**To Reproduce (observed behavior)**

```go
func test(route53Client *route53.Route53) error {
	txtRoute53Changes := []*route53.Change{
		{
			Action: aws.String("UPSERT"),
			ResourceRecordSet: &route53.ResourceRecordSet{
				Name: aws.String("foo.example.com"),
				Type: aws.String("TXT"),
				ResourceRecords: []*route53.ResourceRecord{
					{
						Value: aws.String("\"someValue\""),
					},
				},
				TTL:              aws.Int64(10),
				SetIdentifier:    nil,
				// Works if set to MultiValueAnswer: nil
				MultiValueAnswer: aws.Bool(false),
			},
		},
	}

	_, err := route53Client.ChangeResourceRecordSets(&route53.ChangeResourceRecordSetsInput{
		ChangeBatch: &route53.ChangeBatch{
			Changes: txtRoute53Changes,
		},
		HostedZoneId: aws.String("HOSTED-ZONE-ID"),
	})

	return err
}
```

**Expected behavior**
SetIdentifier can be null in this case

**Additional context**

**Comment by KaibaLopez** [comment]
ticket opened: P48408185

**Comment by ashishdhingra** [comment]
Thank you for your feedback. We've let the responsible internal team know and they've placed this on their backlog. We can't share specific timelines on when this might be implemented in GitHub; you should monitor the [AWS News Blog](https://aws.amazon.com/blogs/aws/) for updates.
