### ISSUE TITLE
Push fails when image already exists on repository with tag and is immutable

### ISSUE THREAD

**Issue by daveisfera** [aws/aws-sdk#750]
### Describe the bug

Pushing an image to a tag where it already exists reports an error

### Expected Behavior

If the image is identical, then it should report that it already exists without an error

### Current Behavior

An error is reported with return code `254`

### Reproduction Steps

1. Put an image with a tag
2. Put the the same image with the same tag

### Possible Solution

Report that it already exists and return success

### CLI version used

aws-cli/2.15.17 Python/3.11.7 Darwin/23.4.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS 14.4.1

**Comment by tim-finnigan** [comment]
We heard back from the ECR team and they recommended creating an issue in this repository where they publicly tracks customer feature requests: https://github.com/aws/containers-roadmap

You can can see if a similar feature request already exists, or create one if not. Those issues are reviewed by the ECR service team.

As far as workarounds on the client-side, you can either treating `ImageAlreadyExistsException` as a non-exception or check if an image exists before calling `put-image`.

**Comment by gsf** [comment]
Here is a tested workaround for the `aws ecr batch-get-image` and `aws ecr put-image` commands (adapted from https://stackoverflow.com/a/38362476/589391):

```
TOKEN=$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken')
CONTENT_TYPE="application/vnd.docker.distribution.manifest.v2+json"
EXISTING_TAG="example"
NEW_TAG="example-new"

echo "Getting the manifest of the image tagged $EXISTING_TAG"
MANIFEST=$(curl -sS -H "Authorization: Basic $TOKEN" -H "Accept: $CONTENT_TYPE" "https://$ECR_REPO_DOMAIN/v2/$ECR_REPO/manifests/$EXISTING_TAG")

echo "Adding the $NEW_TAG tag to $EXISTING_TAG image"
curl -sS -X PUT -H "Authorization: Basic $TOKEN" -H "Content-Type: $CONTENT_TYPE" -d "$MANIFEST" "https://$ECR_REPO_DOMAIN/v2/$ECR_REPO/manifests/$NEW_TAG"
```
