### ISSUE TITLE
would like to see Add GetNamedQuery By QueryName

### ISSUE THREAD

**Issue by Diwamoto** [aws/aws-sdk#753]
### Describe the feature

hello.
It is an automatic translation and may result in strange English. Sorry.

I would like to be able to search an Athena NamedQuery by the Name of the Query.
The current implementation of GetNamedQuery() is only from the auto-generated query_id, and it is difficult to keep track of this id from the program.

ref: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/athena/get-named-query.html
```
aws athena get-named-query --named-query-id <auto-generated-id>
```

Also, ListNamedQueries() must be implemented to retrieve this ID programmatically, but the response from this API is only a list of IDs, and we do not know which ID is the desired query.

ref: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/athena/list-named-queries.html
```
aws athena list-named-queries
--> 
{
    "NamedQueryIds": [
        "a1b2c3d4-5678-90ab-cdef-EXAMPLE11111",
        "a1b2c3d4-5678-90ab-cdef-EXAMPLE22222",
        "a1b2c3d4-5678-90ab-cdef-EXAMPLE33333"
    ]
}
```

(For example, if the name of the query as well as the ID is recorded here, you can use the query option of the AWS CLI to filter the results.)

### Use Case

Looking at the implementation of getting NamedQuery in AWS Athena Console from Chrome Dev tools, it executes all ListNamedQueries and then GetNamedQuery one by one, which becomes more inefficient as the number of NamedQueries increases.

### Proposed Solution

I would like to see GetNamedQueryByName added or name added to the ListNamedQueries response.

```
aws athena get-named-query --named-query-name <query_name>
```
```
aws athena list-named-queries
--> 
{
    "NamedQueries": [
        {
            "Id": "a1b2c3d4-5678-90ab-cdef-EXAMPLE11111",
            "Name": "named_query_example_1"
        },
        {
            "Id": "a1b2c3d4-5678-90ab-cdef-EXAMPLE22222",
            "Name": "named_query_example_2"
        },
        {
            "Id": "a1b2c3d4-5678-90ab-cdef-EXAMPLE33333",
            "Name": "named_query_example_3"
        }
    ]
}
```

Changing the response of ListNamedQueries would lose backward compatibility, so if anything we should add GetNamedQueryByName or another solution.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CLI version used

aws-cli/2.15.36 Python/3.11.9 Darwin/23.4.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

Mac OS Sonoma 14.4.1

**Comment by tim-finnigan** [comment]
Thanks for your patience. The Athena team has added this feature request to their backlog for further review and consideration. We can't provide any guarantees on if or when this would be added, but please refer to the [Athena Blog](https://aws.amazon.com/blogs/big-data/tag/amazon-athena/) and [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for related updates.
