### ISSUE TITLE
Feature request: add paginator to SSM list_inventory_entries

### ISSUE THREAD

**Issue by stepcz** [aws/aws-sdk#756]
SSM list_inventory_entries does not have a paginator even though the underlying API ListInventoryEntries does support pagination. It would be a usefull addition as some of the inventory types (like AWS:Application) return large sets.

**Comment by ashishdhingra** [comment]
Followed up with service team for update. Awaiting response.

**Comment by ashishdhingra** [comment]
Followed up with service team for update. Awaiting response.

**Comment by ashishdhingra** [comment]
We have created product feature request with service team that would be reviewed based on other priorities. As of now, we cannot provide ETA for the same.
