### ISSUE TITLE
Extend InvokeModelCommand to specify knowledge base

### ISSUE THREAD

**Issue by jogep** [aws/aws-sdk#757]
As a user I want to use the `InvokeModelCommand` with a specified knowledge base to have better matching results.

```JavaScript
  const bedrockInput = {
    "modelId": "anthropic.claude-3-sonnet-20240229-v1:0",
    "contentType": "application/json",
    "accept": "application/json",
    "body": JSON.stringify({
      "anthropic_version": "bedrock-2023-05-31",
      "max_tokens": 4096,
      "system": "Take on the role of a ...",
     "knowledgeBaseId": "<ID OF KNOWLEDGEBASE>",
      "messages": [{
        "role": "user",
        "content": [{
          "type": "text",
          "text": promt
        }]
      }]
    })
  };
  const bedrockData = await bedrockClient.send(new InvokeModelCommand(bedrockInput));
```

**Comment by tim-finnigan** [comment]
Have you tried using the [RetrieveAndGenerate API](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerate.html)? Per the Bedrock documentation on knowledge bases, that is the recommended approach: https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base.html.

**Comment by jogep** [comment]
> Yes I tried but hit some other limitations. Why the InvokeCommand can not work the same way?

**Comment by tim-finnigan** [comment]
What other limitations did you hit? Different APIs serve different use cases, if you'd like us reach out the Bedrock team with a specific request here let us know, but if you're asking why one API doesn't do what another API does they will probably say that is intended by design.
