### ISSUE TITLE
Allow to delete Amazon MQ broker configuration

### ISSUE THREAD

**Issue by mkhodave** [aws/aws-sdk#758]
### Describe the feature

Allow to delete Amazon MQ broker configuration

### Use Case

As many of us using IaC code like pulumi to provision aws MQ rabbitmq service, but here broker configuration always creates for every spin of broker, as list of broker configuration increasing its really annoying to see many broker configuration & easy to get lost which one exact that I am using, so please allow to delete broker configuration

### Proposed Solution

As there is already bunch of configuration paramter like delete broker , delete tags. similar way please provide to delete broker configuration

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CLI version used

aws-cli/2.15.49 Python/3.11.8

### Environment details (OS name and version, etc.)

Ubuntu 22.04.4 LTS

**Comment by tim-finnigan** [comment]
Upon searching internally I found that the MQ team does have an existing backlog item for this feature request. It is on their roadmap, but we cannot provide any guarantees as far as if or when a feature gets implemented. Please use the announcements page (https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/amazon-mq-release-notes.html) and respective [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) to track release updates.
