### ISSUE TITLE
Missing `Throttling` error code

### ISSUE THREAD

**Issue by gudgl** [aws/aws-sdk#76]
**Describe the issue with documentation**
There is an error code missing in the documentation of [SendEmail](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/ses-example-send-email.html). To be precise the code is `Throttling`.

**To Reproduce (observed behavior)**
I have a RabbitMQ consumer that sends emails. When the consumer had to send a huge amount of emails I received `Throttling: Maximum sending rate exceeded.\n\tstatus code: 400`, but there is no code `Throttling` in the sea package.

**Expected behavior**
I expected to find the code in the package error codes.

**Comment by vudh1** [comment]
This has been updated and closed.
