### ISSUE TITLE
Managed Grafana programmatically assign user to workspace

### ISSUE THREAD

**Issue by robert-siewert** [aws/aws-sdk#760]
As discussed here,

[https://github.com/boto/boto3/issues/3212#issuecomment-1097226363](url)

I would like the AWS Managed Grafana boto3 Python sdk to add the "assign user" function to programatically assign and remove users to and from workspaces.

Request to place this issue in aws-sdk instead of boto3 is here [https://github.com/boto/boto3/issues/3212#issuecomment-1098259494](url)

**Comment by tim-finnigan** [comment]
Hi @robert-siewert thanks for reaching out. It looks like you can use [update_permissions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/grafana/client/update_permissions.html) you can assign the role of `Admin`, `Editor`, or `Viewer`, which is what https://github.com/boto/boto3/issues/3212 originally was about. If that does not quite accomplish your use case though then we can reach out to the Grafana team with your request, please confirm.
