### ISSUE TITLE
`put-bucket-acl` : JSON file causing MalformedACLError for XML in AWS S3 Bucket ACL Operation

### ISSUE THREAD

**Issue by maheshrijal** [aws/aws-sdk#765]
### Describe the bug

I'm calling `aws s3api put-bucket-acl` and passing a JSON file for the acl policy. However, error message indicates an issue with XML formatting. 

### Expected Behavior

An error pointing to the json schema or at the very least highlighting that the json policy is invalid would be helpful. 

### Current Behavior

An error occurred (MalformedACLError) when calling the PutBucketAcl operation: The XML you provided was not well-formed or did not validate against our published schema

### Reproduction Steps

1. Create a json acl policy that is invalid
2. Run `aws s3api put-bucket-acl --bucket bucketname --access-control-policy file://policy.json`
3. Observe Error: `An error occurred (MalformedACLError) when calling the PutBucketAcl operation: The XML you provided was not well-formed or did not validate against our published schema`

### CLI version used

2.15.36

### Environment details (OS name and version, etc.)

Linux/5.15.146.1-microsoft-standard-WSL2

**Comment by tim-finnigan** [comment]
The request to improve the error message is now being tracked internally. I will close this as there is no further action on our side, please refer to the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) or [S3 blog](https://aws.amazon.com/blogs/aws/category/storage/amazon-simple-storage-services-s3/) for updates.
