### ISSUE TITLE
inspector2 list_findings: cannot apply sort for updatedAt

### ISSUE THREAD

**Issue by rkumarkhaniya-crest** [aws/aws-sdk#772]
We are using InspectorV2 list_findings API to fetch the findings. Following are the parameters we are passing to fetch the findings.

params = {
            "filterCriteria": {
                "lastObservedAt": [{"startInclusive": begin, "endInclusive": end}]
            },
            "sortCriteria": {"field": "LAST_OBSERVED_AT", "sortOrder": "ASC"},
        }

Here, we are using lastObservedAt to pass the data parameters to get the findings for a specific date period and then we store the lastObservedAt of the last findings from the API response as per the sortCriteria so that in the subsequent scheduling of the API call, we can avoid the findings duplication. Unfortunately, this filter parameters does not return the updated findings in the future API calls.

After this issue is closed https://github.com/aws/aws-sdk/issues/416, we can use the updatedAt filterCriteria to get the updated findings also. But, updatedAt is missing from the sortCriteria and we can not use this filter to get the updated findings as it will lead to duplication or missing findings in the next API invocation in case the API call was interrupted previously.

While using 
{
        "filterCriteria": {
            "updatedAt": [{"startInclusive": begin, "endInclusive": end}]
        },
        "sortCriteria": {"field": "UPDATED_AT", "sortOrder": "ASC"},
    }

Throws the following error:
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ListFindings operation: 1 validation error detected: Value at 'sortCriteria.field' failed to satisfy constraint: Member must satisfy enum value set: [LAST_OBSERVED_AT, FINDING_STATUS, NETWORK_PROTOCOL, INSPECTOR_SCORE, ECR_IMAGE_PUSHED_AT, RESOURCE_TYPE, ECR_IMAGE_REGISTRY, AWS_ACCOUNT_ID, FINDING_TYPE, ECR_IMAGE_REPOSITORY_NAME, VENDOR_SEVERITY, FIRST_OBSERVED_AT, COMPONENT_TYPE, SEVERITY, EPSS_SCORE, VULNERABILITY_SOURCE, VULNERABILITY_ID]

API Reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/inspector2/client/list_findings.html

list_findings also requires sortCriteria for updatedAt and in memory sorting is not feasible.

Thanks!

**Comment by bhoradc** [comment]
V1445474986

**Comment by rkumarkhaniya-crest** [comment]
@bhoradc Thank you for looking into this. I can see that the feature request label has been assigned. Can you please let us know ETA for this?

**Comment by bhoradc** [comment]
Hello @rkumarkhaniya-crest, 

Thank you for following up. 

I am awaiting response from Inspector team to acknowledge this feature request. I will update here once I hear back from them. Also, I won't be able to provide an ETA on if and when the service team would prioritize this request. 

Regards, 
Chaitanya

**Comment by tim-finnigan** [comment]
Checking in — we heard back from the service team who acknowledged this feature request and added it to their backlog. We cannot guarantee if or when a service API feature request would be implemented but please refer to the [blog](https://aws.amazon.com/blogs/security/tag/amazon-inspector/) or SDK changelog for updates.
