### ISSUE TITLE
Add waiters for AWS Workspaces

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#79]
Originally requested at: [boto3/#2527](https://github.com/boto/boto3/issues/2527) and [botocore PR #2115](https://github.com/boto/botocore/pull/2115)

**Comment by stobrien89** [comment]
P47954750

**Comment by stobrien89** [comment]
Hi @littlejo, 

Just wanted to reach out to get more clarification on your use case— Could you describe your use cases?  The Workspaces team is trying to understand the impact of this request.  Thanks!

**Comment by terminator9999** [comment]
@stobrien89 the case that I would have is eg.
1. Start X amount of AWS Workspaces (start_workspaces api call)
2. Wait till the Workspace starts (the workspace is in the AVAILABLE state)
3. Modify the state to ADMIN_MAINTENANCE 

Does it make sense?

**Comment by s3638844** [comment]
I would also like to see this, we need to implement exactly this pattern as well
1. Start AUTO_STOP workspaces
2. Wait till state AVAILABLE
3. set ADMIN_MAINTENANCE
4. do actions
5. unset ADMIN_MAINTENANCE

**Comment by jmklix** [comment]
This has been added to the backlog for the internal team. I don't have a timeline for when this will be added. Closing this issue
