### ISSUE TITLE
There should be a region endpoint that allows all regions to be retrieved without an SDK update.

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk#792]
We have code that iterates all regions and (for example) calls describe instance on each for a given credential. The SDK should provide region enums as a convenience, not a necessity.  All clients should work with new regions that show up. Partition files should be pulled from an URL instead of json baked into the SDK build. Then `RegionUtils.getRegions()` would return all current regions (or at least as current as the last time that process started). If the regions URL is not available then it could fall back onto the baked-in JSON partition files.

**Comment by tim-finnigan** [comment]
Does the SSM [GetParametersByPath API](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html) accomplish this use case for you? Here is documentation with examples: https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters-global-infrastructure.html
