### ISSUE TITLE
Glue - Add ability to enable Auto Scaling for ETL jobs

### ISSUE THREAD

**Issue by Rizxcviii** [aws/aws-sdk#794]
Within the AWS Console, you are able to choose a checkbox to specify auto scaling for ETL jobs.
![image](https://github.com/user-attachments/assets/67db87df-3bdd-4891-907d-d96c306b631f)
However, there is no functionality within the SDK to allow for this change.

**Comment by tim-finnigan** [comment]
Hi @Rizxcviii - have you tried using `NumberOfWorkers` in the Glue [CreateJob API](https://docs.aws.amazon.com/glue/latest/webapi/API_CreateJob.html#Glue-CreateJob-request-NumberOfWorkers)?

**Comment by Rizxcviii** [comment]
Hi @tim-finnigan, yes I have tried that, but it does not seem to work. It sets the number of workers, but does not set the checkbox

**Comment by tim-finnigan** [comment]
It looks like this what you want to use: https://docs.aws.amazon.com/glue/latest/dg/auto-scaling.html. Does that meet your use case?

* https://docs.aws.amazon.com/glue/latest/webapi/API_StartJobRun.html
* https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html

**Comment by Rizxcviii** [comment]
Hey @tim-finnigan, yes this is what I want. That will solve my use case. However I'm not sure if this will select the checkbox to be active for job creation. For other developers, they may still ask for this.

**Comment by Rizxcviii** [comment]
Hi @tim-finnigan, I apologies, but you could set this when creating a job as well. The checkbox is enabled when that parameter is parsed. Therefore, I will close this
