### ISSUE TITLE
PutMedia support for aws-sdk-js-v3

### ISSUE THREAD

**Issue by uxtx** [aws/aws-sdk#798]
### Describe the feature

Implementing the PutMedia api as described [here](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html)

### Use Case

Suppose a user is trying to send streaming video data up to a kinesis video stream. There appears to be no viable way to easily pass the stream data other than spinning up a Java lambda function, pass in the video data and utilize the `PutMedia` command that way. 

### Proposed Solution

support for a `client-kinesis-video-media` `putMediaCommand` that would decorate the request with the necessary amz headers and allow an argument with a video fragment in the payload.

### Other Information

I am alternately going to try PUTing directly to the kinesis stream api and pass in the payload this way.

### Acknowledgements

- [X] I may be able to implement this feature request
- [x] This feature might incur a breaking change

### SDK version used

3.410.0

### Environment details (OS name and version, etc.)

Mac OS M2, Chrome Browser

**Comment by RanVaknin** [comment]
Closing because Kinesis team could not commit to publishing a producer client for additional languages. 


Thanks,
Ran~
