### ISSUE TITLE
EC2 describeInstanceTypes and describeInstanceTypeOfferings missing pagination config

### ISSUE THREAD

**Issue by sheldonkwok** [aws/aws-sdk#8]
`describeInstanceTypes` and `describeInstanceTypeOfferings` are missing pagination features. The ec2 paginators json does not have them referenced. 

https://github.com/aws/aws-sdk-js/blob/master/apis/ec2-2016-11-15.paginators.json#L165

**SDK version number**
v2.584.0

**Comment by tim-finnigan** [comment]
The paginators have since been added, closing as resolved.
