### ISSUE TITLE
start-live-tail on GovCloud: Could not connect to the endpoint URL: "https://streaming-logs.us-gov-west-1.amazonaws.com/"

### ISSUE THREAD

**Issue by NeckBeardPrince** [aws/aws-sdk#809]
### Describe the bug

When using `aws logs start-live-tail` on GovCloud gives an error in output.

### Expected Behavior

![image](https://github.com/user-attachments/assets/3fd4aa6c-9f48-44d7-9712-d14a0abf9cfd)

### Current Behavior

```console
❯ aws logs start-live-tail  --log-group-identifiers arn:aws-us-gov:logs::us-gov-west-1:<account-id>:log-group/aws/aes/domains/<redacted>/application-logs

Could not connect to the endpoint URL: "https://streaming-logs.us-gov-west-1.amazonaws.com/"
```

### Reproduction Steps

Run command in CLI

### Additional Information/Context

I even tried setting `--endpoint-url https://logs.us-gov-west-1.amazonaws.com` but even I get the same output `Could not connect to the endpoint URL: "https://streaming-logs.us-gov-west-1.amazonaws.com/"`

I don't think that streaming-logs.us-gov-west-1.amazonaws.com is even a valid domain.

```console
❯ dig streaming-logs.us-gov-west-1.amazonaws.com

; <<>> DiG 9.10.6 <<>> streaming-logs.us-gov-west-1.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11851
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;streaming-logs.us-gov-west-1.amazonaws.com. IN A

;; AUTHORITY SECTION:
us-gov-west-1.amazonaws.com. 5	IN	SOA	dns-external-master.amazon.com. hostmaster.amazon.com. 2012084890 180 60 2592000 5

;; Query time: 40 msec
;; SERVER: 192.168.1.2#53(192.168.1.2)
;; WHEN: Wed Aug 07 09:01:47 CDT 2024
;; MSG SIZE  rcvd: 145
```

Where as a non-govcloud endpoint has DNS records.

```console
❯ dig logs.us-gov-east-1.amazonaws.com

; <<>> DiG 9.10.6 <<>> logs.us-gov-east-1.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54376
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;logs.us-gov-east-1.amazonaws.com. IN	A

;; ANSWER SECTION:
logs.us-gov-east-1.amazonaws.com. 60 IN	A	18.252.59.222
logs.us-gov-east-1.amazonaws.com. 60 IN	A	18.252.58.4
logs.us-gov-east-1.amazonaws.com. 60 IN	A	18.252.59.246

;; Query time: 57 msec
;; SERVER: 192.168.1.2#53(192.168.1.2)
;; WHEN: Wed Aug 07 09:03:00 CDT 2024
;; MSG SIZE  rcvd: 109
```

### CLI version used

aws-cli/2.17.24 Python/3.11.9 Darwin/23.5.0 source/arm64

### Environment details (OS name and version, etc.)

macOS 14.5 (23F79)

**Comment by jsicheng** [comment]
The documentation [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatchLogs_LiveTail.html) and [here](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-cwl.html) have been updated. Updating the error code might not be possible at this time. Let me know if you need anything else.

**Comment by tim-finnigan** [comment]
> The documentation [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatchLogs_LiveTail.html) and [here](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-cwl.html) have been updated. Updating the error code might not be possible at this time. Let me know if you need anything else.

Thanks for sharing the update. I'm going to close this for tracking from our end then, since documentation updates were made and there are not plans to update the error code as this time.
