### ISSUE TITLE
Add waiter for Cloudformation DescribeStackDriftDetectionStatus

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#81]
Originated from boto/boto3#1771 and [this PR](https://github.com/boto/botocore/pull/1860)

**Comment by stobrien89** [comment]
P47958387

**Comment by mazerty** [comment]
hi :)
any news about this feature ?

**Comment by tim-finnigan** [comment]
Thanks for your patience — we heard back from the CloudFormation team regarding this request and they have added a backlog item for tracking it. We can't provide any guarantees on if or when this would be implemented but feel free to check back in for any updates in the future. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan for updates or to share your use case for this feature.
