### ISSUE TITLE
Bedrock Rag is missing ppt, pptx text splitting support with knowledgebase queries

### ISSUE THREAD

**Issue by converseKarl** [aws/aws-sdk#819]
### Describe the feature

Current support but is behind other systems at moment,

format: "pdf" || "csv" || "doc" || "docx" || "xls" || "xlsx" || "html" || "txt" || "md", // required

but in rag you need ppt, pptx,   (powerpoint splitting)

to 100% complete you need 
mp4, mp3, youtube URL, youtube channel and JSON (someone implied its in there but i've not seen it)

### Use Case

You have everything else except powerpoint, you have word, excel, txt, csv, html but no powerpoint.

A lot of information is in powerpoints, company info, results, and numerous presentations for training so ragifying them and using the information is quite a substantial set of user cases. 

### Proposed Solution

implement the embedding extraction from powerpoints (like you do with PDF's). If your using langchain in the background, its  5 minute job to add the PPT/PPTX conversion as a loader type but I don't know your underlying implementation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.651.1

### Environment details (OS name and version, etc.)

Linux Debian, Nodejs / EC2 or even using Lamba AWS direct

**Comment by zshzbh** [comment]
Added Product Feature Request, title - "Add ppt, pptx text splitting support in Bedrock Rag knowledge base query"

**Comment by zshzbh** [comment]
Thanks again for the feature request.The Bedrock team is continuing to track this in their backlog for consideration. We're going to close this on our end as the service team would need to take the next steps here. Please refer to the [blog](https://aws.amazon.com/blogs/devops/category/developer-tools/aws-code-artifact/) or [CHANGELOG](https://github.com/aws/aws-sdk-js-v3/blob/b92df2038b84f36ab60139f03ccb626ef29f2163/clients/client-bedrock-runtime/CHANGELOG.md#L4) for updates, or feel free to reach out through support if you have a support plan.


Thanks!
Maggie
