### ISSUE TITLE
[Bedrock] Is there any way to programmatically acquire the schema of api request body for each foundation model by model id?

### ISSUE THREAD

**Issue by cooco119** [aws/aws-sdk#823]
For bedrock, 

It seems that the schemas for api request body for foundation models vary not just by the providers, but also the model itself within a same provider. 

I want to programmatically get the schema for each model by model id or any identifiers. 

Is that possible, or should I hard-code all the schemas for every model type?

Thank you in advance and sorry if I'm posting on the wrong channel.

**Comment by aBurmeseDev** [comment]
Hi @cooco119 - thanks for your inquiry. 

After consulting with our Bedrock team, I regret to inform you that the functionality you requested is not currently supported or recommended. Specifically, hard-coding schema is not advisable.

Instead, the team recommends utilizing the [Converse](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html) API as an alternative solution to address your needs. I've forwarded your ask to the team as feature request. Feel free to share your use case to better understand the request. 

If you have any further questions or concerns, please don't hesitate to reach out.
