### ISSUE TITLE
Add waiter support for Batch DescribeJobs

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#84]
Specifically, JobExists and JobExecutionComplete waiters.

Originated from https://github.com/boto/botocore/pull/1307

**Comment by hugoprudente** [comment]
Any news? Or it will take more 2 years like the other PR that was closed?

**Comment by stobrien89** [comment]
Hi @hugoprudente,

Thanks for your patience.  I wanted to wait until I had a more substantial update to respond, but I'm still working to get this prioritized by the Batch team.

The reason there isn't any code attached to this request is that I've submitted your implementation and context to the Batch team via an internal ticket.  One of the reasons the responsibilities for waiters and paginators were shifted to the service teams is that they have better tools to determine what the appropriate number of timeouts/retries, etc. should be— essentially, they know their service best.  Another reason was the inconsistency of the implementation across AWS SDKs.  We have an automated release system for updates from service teams to be distributed to the SDK service models, so now when a service team approves a new waiter or paginator, it can simply be made available across every AWS SDK.  

I'm hoping this won't take much longer, but service teams often have a large number of feature requests in their backlog, but I'll keep requesting updates and will definitely let you know as soon as I have an update.

**Comment by hugoprudente** [comment]
So the point of having it opensource and offload the work from the AWS Service team is null. If they have backlog a large backlog this will ended in the lowest possible priority as no one have merged this in the botocore for over 2 years who will ensure that this will get ever merged. 

The only thing that this did was not being delivered and the transparency is like a black hole, it means that maybe in 20 years time or more this feature can get released. 

Till there we can just patch our codes and move on with our life as all the tools that SUPPORTS BATCH in HPC did dues to the time that this feature took to get merged.

Not even the opensources developers that were in the other thread believe that this feature will ever get released the 2 biggests schedulers opensource patch their code based on a draft, as AWS didn't clicked 1 button and backported to the other SDKS.

I think it will be more realistic if you close this feature with "there's no interest of AWS on support this" as a SIMPLE waiter and paginator didn't got delivered as basic feature and the service was launch in 1 Dec 2016, who will believe that it will add 5 years later?

**Comment by stobrien89** [comment]
Hi @hugoprudente,

I definitely understand the frustration.  The reason the initial request sat for so long without a response is because the team, at the time, did not have the capacity to respond to most feature requests, which we take full responsibility for, but we've been improving our response times and have been trying to bubble up some of the older requests that haven't received attention.

It's unfortunately not as simple as clicking a button and backporting to other SDKs— Service teams push their models, which now include waiters and paginators, to the SDKs through an automated process, so if we were take any external contributions in that area now, it would create conflicts and break our release process.  

That said, this is obviously a valid request and I see the number or customers who would find this useful, so this is something I'll continue to work with the Batch team on.

**Comment by hugoprudente** [comment]
Any news on this matter?

**Comment by cariaso** [comment]
![0B2C47D2-C65D-494D-9D40-82F703042196](https://user-images.githubusercontent.com/125330/171753666-b6f01cae-e673-43b1-a800-2baa4260c4f4.jpeg)

**Comment by hugoprudente** [comment]
Just to flag that this waiter is waiting 4 years, 2 years on this PR and 2 years on the other PR...

**Comment by tim-finnigan** [comment]
Thanks again for your patience here...we understand your frustrations and are also frustrated that the Batch team has not provided an update on this. As mentioned here previously the waiters are implemented and maintained by service teams like Batch so that they can be used consistently across SDKs (which is why a waiter PR for a specific SDK cannot get merged.) For anyone who has a support account, we recommend reaching out through [AWS support](https://aws.amazon.com/contact-us/) to escalate this and help the service team understand why this feature is important to help address your use case.

**Comment by bounlu** [comment]
> Thanks again for your patience here...we understand your frustrations and are also frustrated that the Batch team has not provided an update on this. As mentioned here previously the waiters are implemented and maintained by service teams like Batch so that they can be used consistently across SDKs (which is why a waiter PR for a specific SDK cannot get merged.) For anyone who has a support account, we recommend reaching out through [AWS support](https://aws.amazon.com/contact-us/) to escalate this and help the service team understand why this feature is important to help address your use case.

AWS Support is not free.

**Comment by cariaso** [comment]
@jmklix Can you please indicate what commit completes this work? My scan of your recent commits doesn't find a sufficiently obvious connection
https://github.com/aws/aws-sdk-cpp/commits?author=jmklix&since=2024-03-01&until=2024-03-28
