### ISSUE TITLE
Add retry state to SSM GetCommandInvocation CommandExecuted waiter

### ISSUE THREAD

**Issue by stobrien89** [aws/aws-sdk#86]
Originated from: https://github.com/boto/boto3/issues/2701
Related PR: https://github.com/boto/botocore/pull/2266

**Comment by stobrien89** [comment]
P47990948

**Comment by buttnomaan9** [comment]
@stobrien89 any idea when it will be fixed?
It is such a core feature, so it is practically making waiter useless for ssm send command.
`Waiter CommandExecuted failed: An error occurred (InvocationDoesNotExist): 
`

**Comment by stobrien89** [comment]
Hi @buttnomaan9,

This request is still under consideration from the SSM team, but I haven't received any updates beyond their initial acceptance of the request.  I've asked for an update and will let you know as soon as I hear back from them!

**Comment by buttnomaan9** [comment]
@stobrien89 can you provide any udpate on this issue? Today again I ran into same problem.

**Comment by gs-scooter** [comment]
Looking for an update to this issue as well.

**Comment by rmbhatt** [comment]
hi any update on this issue?

**Comment by tim-finnigan** [comment]
Thanks for your patience. We don't have any updates at this time - the SSM team is continuing to track this feature request in their backlog but it is not currently prioritized. Please feel free to check back in the future for updates.
