### ISSUE TITLE
create-replace-root-volume-task changes volume type to standard

### ISSUE THREAD

**Issue by shaicoleman** [aws/aws-sdk#87]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws ec2 create-replace-root-volume-task` changes the EBS type to `standard` instead of maintaining the original volume type

**SDK version number**
`aws-cli/2.1.39 Python/3.8.8 Linux/5.12.2-051202-generic exe/x86_64.linuxmint.20 prompt/off`

**To Reproduce (observed behavior)**
1. Launch an EC2 instance with a `gp3` EBS volume.
2. `aws ec2 create-replace-root-volume-task --instance-id i-xxxxxx`

**Expected behavior**
The replaced volume should be the same as original, e.g. `gp3` and not `standard`.

**Additional context**
API documentation:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-replace-root-volume-task.html

Also it might make sense to offer more control over the replacement as command line options (e.g. volume type/size/iops)

**Comment by kdaily** [comment]
In regards to offering the ability to provide specific command line arguments, this command uses the API model, so changing that would require a change to the API by the EC2 team, not the CLI specifically. However, the documentation for this is the following, I'm not sure I understand why you would specify a specific volume type - you need to select a specific snapshot or restore it:

> The root volume can either be restored to its initial launch state, or it can be restored using a specific snapshot.

**Comment by deric4** [comment]
Agree with @shaicoleman as its not obvious why a larger subset of the `create_volume` API options aren't supported:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_volume

**Comment by kdaily** [comment]
@shaicoleman and others, this issue should be resolved now. Your volume should remain the same type after replacing.

@deric4, if you describe your use case more completely, I'm happy to take that feedback to the EC2 team as well.

**Comment by kdaily** [comment]
Closing this as it has been resolved. Thanks!
