### ISSUE TITLE
Add support for lambda listRelations to aws cli/sdk

### ISSUE THREAD

**Issue by gtmtech** [aws/aws-sdk#92]
In the AWS Management Console (Web), when viewing a Lambda Function, it is possible to see a nice view of what triggers the lambda function - e.g. an s3 bucket notification or cloudwatch event. This is visualised in a nice display. 

Looking at the raw requests into how this information is gotten, I see a call to operation=listRelations of the function, which returns in my case an S3 bucket notification object. 

I want to get the same information from the AWS Cli - i.e. - show me using the cli how a function is triggered. 

None of the lambda:get-function, lambda:get-function-configuration, lambda-list-function-event-invoke-configs, list-event-source-mappings etc. return this information. So is it possible to get this back from the CLI (have I missed something?)

If not, can we have an equivalent SDK/API call listRelations() showing the same information that we can get back from the Management Console

**Comment by stobrien89** [comment]
P48551054

**Comment by andrew-barnett** [comment]
Any update on this? Looking for a clean way to list triggers when given a Lambda.

**Comment by tim-finnigan** [comment]
This feature request is currently being tracked in the Lambda team's backlog, but we can't provide any guarantees on if or when this would be considered. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan to get any updates going forward. 

In the meantime you could try workarounds such as using the [GetPolicy API](https://docs.aws.amazon.com/lambda/latest/dg/API_GetPolicy.html), for example with the AWS CLI:
`aws lambda get-policy --function-name <function-name> --query 'Policy' --output text | jq '.'`
