### ISSUE TITLE
Add support for aws cli v2 - secretsmanager SecretTargetAttachment

### ISSUE THREAD

**Issue by ovi-hutu-aws** [aws/aws-sdk#93]
When working with SecretsManager there is no support to add SecretTargetAttachment when creating/modifying secrets. This is supported in CDK and CloudFormation, as described here: 
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html 
* https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_secretsmanager/SecretTargetAttachment.html

**Comment by kdaily** [comment]
D24823662
