### ISSUE TITLE
InvalidAMIID.NotFound error message shows AMI ID as a list

### ISSUE THREAD

**Issue by kdaily** [aws/aws-sdk#97]
Filed at https://github.com/boto/boto3/issues/2927

The brackets are being added in the error message provided by EC2:

```
2021-07-14 01:42:06,837 botocore.parsers [DEBUG] Response headers: {'x-amzn-RequestId': '4e759009-7884-46eb-bcf9-0a238087d593', 'Cache-Control': 'no-cache, no-store', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Type': 'text/xml;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'vary': 'accept-encoding', 'Date': 'Wed, 14 Jul 2021 08:42:05 GMT', 'Connection': 'close', 'Server': 'AmazonEC2'}
2021-07-14 01:42:06,837 botocore.parsers [DEBUG] Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Response><Errors><Error><Code>InvalidAMIID.NotFound</Code><Message>The image id \'[ami-fake123]\' does not exist</Message></Error></Errors><RequestID>4e759009-7884-46eb-bcf9-0a238087d593</RequestID></Response>'
```

Requested that this error message be changed to not show the AMI ID as a list with a single element.

**Comment by kdaily** [comment]
P49965957

**Comment by kdaily** [comment]
@markrogersjr,

Unfortunately since the error messaging is a cosmetic issue, it won't be changed now. Customers may be using the existing formatting on their own and would risk breaking if it's changed now. We appreciate you bringing it up, though!

**Comment by markrogersjr** [comment]
Hi @kdaily, I think I did already make the case that it's not solely cosmetic, but it makes sense to not touch it since it would risk breaking/affecting the api of other stuff. at least the issue is documented in case others are trying to debug and come across the same issue.

**Comment by kdaily** [comment]
@markrogersjr - I don't disagree that it caused confusion! I'm glad we agree that it may be a breaking change, and yes having these issues could aid in the future. Thanks again for raising and your understanding.
